src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Buying_Entity__c</fullName>
        <inlineHelpText>Whether, in our judgment, this entity makes independent decisions about system purchases (as opposed to a subsidiary that has no operational distinction from its parent).</inlineHelpText>
        <label>Buying Entity</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t Know</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Accelerator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Best Practise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Database</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Platform Compatibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Policy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal/Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tools</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Customer Account)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_Summary_Next_Steps__c</fullName>
        <label>Status Summary/Next Steps</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Alliances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Announcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Meeting Agenda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Meeting Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Best Practices/Methodology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change order and Addendums</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confluence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corp Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Profile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deal Sheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director&apos;s Meeting Agenda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director&apos;s Meeting Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EchoSign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDADMIN/Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Empire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expense Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Force</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Mobility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gov.Agreements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Handbook Updates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CaseEscalatorHandlerTest.cls
@istest(seeAllData =true)
public class CaseEscalatorHandlerTest
{
    static testmethod void Escalator()
    {
        account acc= new account();
        acc.Name = 'Test';
        acc.Type = 'Analyst';
        acc.Buying_Entity__c = 'No';
        acc.CurrencyIsoCode = 'USD';
        acc.Industry='Analyst';
        acc.BillingCountry = 'India';
        
        insert acc;   
        
        String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Guidewire Live'].Id;
        
        Case cse = new Case();
        cse.Subject = 'guideLive';
        cse.Description='test guidewire';
        cse.Category__c ='Application Issue';
        cse.Sub_Category__c='All';
        cse.RecordTypeId = strRecordTypeId;
        cse.Status_Summary_Next_Steps__c ='Guidewire live cases org';
        cse.Customer_Account__c =acc.Id;
        cse.IsEscalated = false;
        
        insert cse;
        
        cse.IsEscalated = true;
        update cse;
        
    }

}