src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LatAm</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Customer_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>IF(INCLUDES( Customer_Account__r.Region__c , &quot;APAC&quot;), &quot;APAC&quot;, NULL)  + BR() + 
IF(INCLUDES( Customer_Account__r.Region__c , &quot;EMEA&quot;), &quot;EMEA&quot;, NULL)  + BR() + 
IF(INCLUDES( Customer_Account__r.Region__c , &quot;NAM&quot;), &quot;NAM&quot;, NULL) + BR() +
IF(INCLUDES( Customer_Account__r.Region__c , &quot;LatAm&quot;), &quot;LatAm&quot;, NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Fiscal_Period__c</fullName>
        <description>Fiscal Period based on Closed Date of Oppty</description>
        <formula>CASE(MONTH(CloseDate),
1, &quot;Q2&quot; ,
2, &quot;Q3&quot;,
3, &quot;Q3&quot;,
4, &quot;Q3&quot;,
5, &quot;Q4&quot;,
6, &quot;Q4&quot;,
7, &quot;Q4&quot;,
8, &quot;Q1&quot;,
9, &quot;Q1&quot;,
10, &quot;Q1&quot;,
11, &quot;Q2&quot;,
12, &quot;Q2&quot;,
&quot;None&quot;)

&amp; &quot;-&quot;

&amp; IF((MONTH(CloseDate) &gt;= 8 &amp;&amp; MONTH(CloseDate) &lt;= 12),
TEXT (YEAR(CloseDate)+1) ,
TEXT (YEAR(CloseDate))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fiscal Period</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Add on- select below</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ClaimCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PolicyCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BillingCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DataHub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InfoCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Predictive Analytics for Claims</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Predictive Analytics for Profitability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Predictive Analytics Model Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Predictive Analytics Scoring Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underwriting Management</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>AMER</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Preparation__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Event__c</fullName>
        <label>Sales Event</label>
        <referenceTo>Sales_Event__c</referenceTo>
        <relationshipLabel>Preparations</relationshipLabel>
        <relationshipName>Preparations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start</label>
        <type>Date</type>
    </fields>
    <label>Preparation</label>
    <nameField>
        <label>Preparation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preparations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Event__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_End_Date__c</fullName>
        <label>Confirmed End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Demonstration</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Sale Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proof of Concept</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI / RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Consulting Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Workshop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Workshop Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Alignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Tracking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Consultation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HQ Visit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>List_Of_People__c</fullName>
        <description>Calculated list of people based on who participated</description>
        <label>People</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Events</relationshipLabel>
        <relationshipName>Sales_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage when the event is originally created.</description>
        <label>Stage</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Tentative</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VC_Dash1Controller.cls
public with sharing class VC_Dash1Controller {

    public String MyRequestRangeAsString;
    public Integer MyRequestRangeAsInteger;
    
    public VC_Dash1Controller()
    {
       setMyRequestRange('2014');
    }

    public String  getMyRequestRange()
    {
        return MyRequestRangeAsString;
    }

    public void setMyRequestRange(String newValue)
    {
       MyRequestRangeAsString = newValue;
       MyRequestRangeAsInteger = Integer.valueOf(MyRequestRangeAsString);
    }

    public void reloadPage()
    {
        

    }  


    public List< EventWrapper > getTheFilteredList() {
        
        
        
        Date startDate = date.newinstance(MyRequestRangeAsInteger-1, 8, 1 );
        Date endDate = date.newinstance(MyRequestRangeAsInteger, 7, 31 );
        
        
        String[] vcEventTypes = new String[]{'Value Consulting Assessment','Value Consulting Business Case','Value Alignment','Value Consulting Proof of Value','Value Consultation'};
        
        List<Sales_event__c> eventList = [SELECT Id, Name, Stage__c,Event_Type__c,Confirmed_End_Date__c, List_Of_People__c, Status__c, 
                                              Opportunity__r.Name, Opportunity__c, Opportunity__r.Owner.Name, Opportunity__r.Region__c, Opportunity__r.Product_Type__c,
                                                 Opportunity__r.Fiscal_Period__c, Opportunity__r.FISCALYEAR, Opportunity__r.FISCALQUARTER, Opportunity__r.StageName,
                                              Opportunity__r.Account.Name , Opportunity__r.Account.BillingCountry
                                              //, Opportunity__r.OpportunityHistories
                                              //, (SELECT Histories.LastModifiedDate FROM Opportunity__r ORDER By Histories.LastModifiedDate DESC LIMIT 1 )
                                       FROM Sales_Event__c 
                                       //WHERE Opportunity__r.FISCALYEAR = :MyRequestRangeAsInteger AND
                                       WHERE (Confirmed_End_Date__c >= :startDate AND Confirmed_End_Date__c <= :endDate) AND 
                                             (Status__c = 'Completed' or Status__c = 'Confirmed') AND
                                             Event_Type__c in :vcEventTypes
                                       ORDER BY Confirmed_End_Date__c];
                                             
        
        Set<Id> oppIds = new Set<Id>();
        List<EventWrapper> retval = new List<EventWrapper>();
        Map<Id,Set<EventWrapper>> theMap = new Map<Id, Set<EventWrapper>>();
        for(Sales_Event__c thisEvent : eventList)
        {
            EventWrapper theWrapper = new EventWrapper(thisEvent);
            retval.add(theWrapper);
            oppIds.add(thisEvent.Opportunity__c);
            if(theMap.get(thisEvent.Opportunity__c) == null) theMap.put(thisEvent.Opportunity__c, new Set<EventWrapper>());
            theMap.get(thisEvent.Opportunity__c).add(theWrapper);
//            theMap.put(thisEvent.Opportunity__c, theWrapper);
        }
        System.Debug('**** Ids size  ' + oppIds.size());
        
        List<OpportunityHistory> theHistories = [SELECT StageName, OpportunityId, SystemModstamp From OpportunityHistory where OpportunityId in :oppIds];
        System.Debug('**** ' + theHistories.size());
        for(OpportunityHistory thisOne : theHistories)
        {
            Set<EventWrapper> thisSet = theMap.get(thisOne.OpportunityId);
            for(EventWrapper ew : thisSet)
            {
                
//                System.Debug('**** SysModStamp' + thisOne.SystemModstamp);
                if(thisOne.SystemModstamp != null)             
                //Preparation__c holder = new Preparation__c(Start__c = date.newinstance(thisOne.SystemModstamp.year(), thisOne.SystemModstamp.month(), thisOne.SystemModstamp.day() ));
//                holder.Start__c = );
//                    ew.setResultDate(holder.Start__c);
//  MATT
                    ew.setResultDate(date.newinstance(thisOne.SystemModstamp.year(), thisOne.SystemModstamp.month(), thisOne.SystemModstamp.day() ));
//                theMap.put(thisOne.OpportunityId, ew);
            }
        }
                
        
        return retval;
    }
    
    
 
    public class EventWrapper
    {
        Set<Integer> currentFiscalMonths = new Set<Integer> { 1, 2, 3, 4, 5, 6, 7 };
    
        public EventWrapper(Sales_Event__c inputEvent)
        {
            theEvent = inputEvent;
            if(theEvent.Confirmed_End_Date__c != null)
            {              
                EventDate = theEvent.Confirmed_End_Date__c;
                EventYear = getFiscalYear(EventDate);
                EventQuarter = getFiscalQuarter(EventDate);
            }
            
        }
    
        public Sales_Event__c theEvent {get; set;} 
        public Date EventDate {get; set;} 
        public String EventQuarter {get; set;} 
        public String EventYear {get; set;} 
        public Date ResultDateInternal;
        public String getResultDate()
        {
            if(ResultDateInternal == null) return '';
            return ResultDateInternal.format();
        }
        public void setResultDate (Date newDate)
        {
            if(ResultDateInternal == null || newDate > ResultDateInternal)
            {
                ResultDateInternal = newDate;
                ResultYear = getFiscalYear(ResultDateInternal);
                ResultQuarter = getFiscalQuarter(ResultDateInternal);                                
            }
        
        }        
        public String ResultQuarter {get; set;} 
        public String ResultYear {get; set;} 
        
        public String getFiscalYear(Date inputDate)
        {
                String retval = String.valueOf(inputDate.year());
                Integer month = inputDate.month();
                if(!currentFiscalMonths.contains(month))
                {
                    retval = String.valueOf(inputDate.year()+1);
                }
                return retval;
        
        }
        
        public String getFiscalQuarter(Date inputDate)
        {
                Integer month = inputDate.month();
                String retval = 'Q4';
                //now determine quarter
                if(month == 8 || month == 9 || month == 10) retval = 'Q1';                 
                else if(month == 11 || month == 12 || month == 1) retval = 'Q2';                 
                else if(month == 2 || month == 3 || month == 4) retval = 'Q3';         
                
                return retval;                
        }
    
    }
   
}