src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Record type used for all Partner records.</description>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PRM_Referring_Partner2__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Referring Partner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Referring Partner)</relationshipLabel>
        <relationshipName>Opportunities6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Premium_In_Scope__c</fullName>
        <inlineHelpText>This should be the deal premium in scope or the incremental DWP Adjustment. Used in conjunction with Price Rules to calculate the price for certain Products.</inlineHelpText>
        <label>Premium In Scope</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SWOT_Opportunities__c</fullName>
        <description>The Opportunities aspect of the SWOT</description>
        <inlineHelpText>Opportunities EXTERNAL to Guidewire</inlineHelpText>
        <label>Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_SO__c</fullName>
        <inlineHelpText>Strategy for addressing the Opportunities in the context of our Strengths</inlineHelpText>
        <label>Strengths/Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_ST__c</fullName>
        <inlineHelpText>Strategy for addressing the Threats in the context of our Strengths</inlineHelpText>
        <label>Strengths/Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_WO__c</fullName>
        <inlineHelpText>Strategy for addressing Opportunities in the context of our Weaknesses</inlineHelpText>
        <label>Weaknesses/Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_WT__c</fullName>
        <inlineHelpText>Strategy for addressing the Threats in the context of our Weaknesses</inlineHelpText>
        <label>Weaknesses/Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strengths__c</fullName>
        <inlineHelpText>Guidewire Strengths</inlineHelpText>
        <label>Strengths</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Threats__c</fullName>
        <inlineHelpText>Threats external to Guidewire</inlineHelpText>
        <label>Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Weaknesses__c</fullName>
        <inlineHelpText>Guidewire Weaknesses</inlineHelpText>
        <label>Weaknesses</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PRMPartnerOpportunitySharingTest.cls
@isTest(seealldata=true)
class PRMPartnerOpportunitySharingTest
{
    static testMethod void testPRMPartnerOppty()
    {
        List<Profile> lstProfile =[Select Id from Profile
                                    where profile.userlicense.name = 'Partner Community'];
       
          
        list<user> ulst = [select id,name,contact.Account.id from user where profile.userlicense.name = 'Partner Community' and user.contact.Account.name != null and isactive=true ];
       
       
       
        List<RecordType> lstRecordType = [Select Id from RecordType where Name ='Partner'];
        List<RecordType> lstPartnerOpptyRT = [Select Id from RecordType where Name ='Partner Opportunity'];
         id accid=ulst[0].contact.Account.id;
         id recid=lstPartnerOpptyRT[0].id;
       
       
        
       
       Opportunity oppty = new Opportunity(SWOT_Strengths__c='S Value',
                                            SWOT_Weaknesses__c='W Value',
                                            SWOT_Opportunities__c = 'O Value',
                                            SWOT_Threats__c = 'T Value',
                                            SWOT_Strategy_SO__c = 'SO Value',
                                            SWOT_Strategy_ST__c = 'ST Value',
                                            SWOT_Strategy_WO__c = 'WO Value',
                                            SWOT_Strategy_WT__c = 'WT Value',
                                            Name = 'Test SWOT Opportunity',
                                            StageName = 'Qualified',
                                            CloseDate = Date.today(),
                                            Premium_In_Scope__c = 1000,
                                            PRM_Referring_Partner2__c =accid,
                                            RecordTypeId =recid,
                                            Amount=100);
       
            Database.saveResult saveResult = Database.insert(oppty, false);
            //Opportunity opp =[Select RecordType.Name from Opportunity];
           // system.debug('****'+opp.RecordType.Name);
          // system.assert(saveResult.isSuccess());
        
       
    }
}