src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <picklist>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Integrated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Participant_id__c</fullName>
        <externalId>true</externalId>
        <label>Participant ID</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Contact__c.object
<CustomObject>
    <description>This object allows tracking of multiple addresses/sites and Contact types.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill To \ Ship To</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Key__c</fullName>
        <externalId>true</externalId>
        <label>Contact Key</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bill To\ Ship To</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Integrated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Participant_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Participant Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Site</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill To \ Ship To - All</relationshipLabel>
        <relationshipName>Account_Contacts1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <label>Account Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Five_Digit_Id__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Current_Value__c</fullName>
        <label>Current Value</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Five Digit Id</label>
</CustomObject>

src/classes/trac_AccountContactHandlerTest.cls
/**
 * @description Testing trac_AccountContactHandler Generates auto number for the Contact_Key__c field
 *
 * @author Tanminder Rai, Traction On Demand
 * @date May 25/2015
 */
@isTest
private class trac_AccountContactHandlerTest {

  //************************ Test Utils *************************

  private static List<Contact> createContact(Integer howMany){
    List<Contact> contList = new List<Contact>();
    for (Integer i = 0; i < howMany; i++){
      contList.add( new Contact(LastName='Test'+i, Email='test@test.com') );
    }
    insert contList;
    return contList;    
  }

	//************************ Unit Tests **************************

  //Test that the auto number is incremented when new Account_Contact__c records are created
   @isTest
    static void accountGenerateAutoNumTest(){
      insert new Five_Digit_Id__c(Current_Value__c = 10002);

      List<Contact> contList = createContact(2);
      Account acc = new Account(Name = 'Test', Participant_Id__c = '0');
      insert acc;
      Account_Contact__c accountContact = new Account_Contact__c(Contact__c = contList[0].Id, Account__c=acc.Id, Integration_Status__c = 'Pending Integration', Participant_Account__c=acc.Id); 
    	insert accountContact;

      for (Account_Contact__c accRetrieve :[SELECT Id, Contact_Key__c
                                 			  FROM Account_Contact__c 
                                 			  WHERE Id=:accountContact.Id]){
          System.assertEquals(String.ValueOf(10002), accRetrieve.Contact_Key__c);
      }

        //The next account contact should get the next consecutive number
      Account_Contact__c accountContact2 = new Account_Contact__c(Contact__c = contList[0].Id, Account__c=acc.Id, Integration_Status__c = 'Pending Integration', Participant_Account__c=acc.Id); 
      insert accountContact2;  
      for (Account_Contact__c accRetrieve :[SELECT Id, Contact_Key__c
                                        FROM Account_Contact__c 
                                        WHERE Id=:accountContact2.Id]){
          System.assertEquals(String.ValueOf(10003), accRetrieve.Contact_Key__c);
      }

    }       

    //Test that the auto number is incremented when record is updated to match trigger condition
    @isTest
    static void accountGenerateAutoNumUpdateTest(){

      insert new Five_Digit_Id__c(Current_Value__c = 1002);

      List<Contact> contList = createContact(2);
      Account acc = new Account(Name = 'Test', Participant_Id__c = '0');
      insert acc;
      Account_Contact__c accountContact = new Account_Contact__c(Contact__c = contList[0].Id, Account__c=acc.Id, Participant_Account__c=acc.Id); 
      insert accountContact;

      accountContact.Integration_Status__c = 'Pending Integration';
      update accountContact;

      for (Account_Contact__c accRetrieve :[SELECT Id, Contact_Key__c
                                        FROM Account_Contact__c 
                                        WHERE Id=:accountContact.Id]){
          System.assertEquals(String.ValueOf(1002), accRetrieve.Contact_Key__c);
      }
    }

    // Test for query failure
    @isTest
    static void generateAutoNumberFailure(){
        List<Contact> contList = createContact(2);
        Account acc = new Account(Name = 'Test', Participant_Id__c = '0');
        insert acc;
        Account_Contact__c accountContact = new Account_Contact__c(Contact__c = contList[0].Id, Account__c=acc.Id, Participant_Account__c=acc.Id); 
        insert accountContact;

        accountContact.Integration_Status__c = 'Pending Integration';
        trac_GenerateAutoNumber.TEST_EXCEPTION = true;

        // Attempt an update
        try {
            update accountContact;
            System.assert(False, 'Expected exception not thrown');
        } catch (DmlException exp) {
            // Success because the account was not updated
        }
    }
}