src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MPL_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MPL Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MPL_SalesReps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Services_Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Services Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ServicesAccountManager</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Contact__c.object
<CustomObject>
    <description>This object allows tracking of multiple addresses/sites and Contact types.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bill To\ Ship To</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Participant_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Participant Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Site</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill To \ Ship To - All</relationshipLabel>
        <relationshipName>Account_Contacts1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Account_Address__c</fullName>
        <formula>(Account__r.BillingStreet)+ &quot;, &quot; +(Account__r.BillingCity)+ &quot;, &quot;+(Account__r.BillingState)+ &quot;, &quot; +(Account__r.BillingCountry)+ &quot;, &quot;+( Account__r.BillingPostalCode)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site Account Address</label>
        <type>Text</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <label>Account Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Premium_In_Scope__c</fullName>
        <inlineHelpText>This should be the deal premium in scope or the incremental DWP Adjustment. Used in conjunction with Price Rules to calculate the price for certain Products.</inlineHelpText>
        <label>Premium In Scope</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Term_Annual_License_Fee__c</fullName>
        <label>Term - Annual Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Term_Length_Years__c</fullName>
        <label>Term - Length (Years)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Software_Access_Request__c.object
<CustomObject>
    <description>Stores information for the Software Access Request.</description>
    <fields>
        <fullName>Content_items__c</fullName>
        <label>Content items</label>
        <picklist>
            <picklistValues>
                <fullName>CA Standards Based Template</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP Standards Based Template</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CR Standards Based Template</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GL Standards Based Template</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WC Standards Based Template</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Services_account_manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Services account manager</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Software_Access_RequestsAM</relationshipLabel>
        <relationshipName>Software_Access_RequestsAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Software Access Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Software Access Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Software Access Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SoftwareAccessRequestHelper.cls
//--------------------
// Helper for Software Access Request Form Controller.
// Date: 1/23/2016
// Author: Rohit Koul
//--------------------

public class SoftwareAccessRequestHelper { 

    public static Account_Contact__c getContactDetails(Id acrId){
      List<Account_Contact__c> acrList = [Select Contact__r.Title,Participant_Account__r.MPL_Sales_Rep__c,Participant_Account__r.OwnerId,Participant_Account__r.Services_Account_Manager__c,Contact__r.Email,Contact__r.Name,Contact__r.Phone,Site_Account_Address__c from Account_Contact__c where id =: acrId]; 
            if (acrList.size()>0)
            {
                return acrList[0];
            }else 
            return new Account_Contact__c();
    }
    
    public static Opportunity getOpportunityInfoDetails(Id oppId){
      List<Opportunity> oppList = [Select id,Name,currencyISOcode,Term_Annual_License_Fee__c,Term_Length_Years__c,Premium_In_Scope__c from Opportunity where id =: oppId]; 
            if (oppList.size()>0)
            {
                return oppList[0];
            }else 
            return new Opportunity();
    }
    
	public static List<String> getstandardsBasedTemplates(){
	       List<String> sbtList = new List<String>();
	       Schema.DescribeFieldResult fieldResult = Software_Access_Request__c.Content_items__c.getDescribe();
           List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
           for(Schema.PicklistEntry f : ple)
		   {
			  sbtList.add(f.getValue());
		   }
		   return sbtList; 
	 }
}