src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Participant_id__c</fullName>
        <externalId>true</externalId>
        <label>Participant ID</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>pse__Practice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Practice</label>
        <referenceTo>pse__Practice__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>pse__Region__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PSA_Project_Forecast__c.object
<CustomObject>
    <description>The central repository for calculated billing forecast information. Each record contains a summary of scheduled and forecast billings for a project and month, without regard to forecast category.</description>
    <fields>
        <fullName>PSA_Include_in_Forecast__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies whether the record should be included in forecast reporting</description>
        <inlineHelpText>Automatically maintained by the calculation, specifies whether the record should be included in forecast reporting.  Turned off for past periods on active projects.</inlineHelpText>
        <label>Include in Forecast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSA_Project__c</fullName>
        <description>Project for the forecast record</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>PSA Project Forecasts</relationshipLabel>
        <relationshipName>PSA_Project_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PSA_Scheduled_Cost__c</fullName>
        <description>Sum of Scheduled Cost from Project Forecast Detail records with source of assignment or resource request</description>
        <inlineHelpText>Sum of Scheduled Cost from related Project Forecast Detail records with source of Assignment or Resource Request</inlineHelpText>
        <label>Scheduled Cost</label>
        <summarizedField>PSA_Project_Forecast_Detail__c.PSA_Scheduled_Cost__c</summarizedField>
        <summaryFilterItems>
            <field>PSA_Project_Forecast_Detail__c.PSA_Include_in_Forecast__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>PSA_Project_Forecast_Detail__c.PSA_Project_Forecast__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PSA_Scheduled_Time_Billings__c</fullName>
        <description>Roll-Up Summary of Scheduled Time Billings from related detail items with source of Assignment or Resource Request</description>
        <inlineHelpText>Sum of Scheduled Time Billings from related detail items with source of Assignment or Resource Request</inlineHelpText>
        <label>Scheduled Time Billings</label>
        <summarizedField>PSA_Project_Forecast_Detail__c.PSA_Scheduled_Time_Billings__c</summarizedField>
        <summaryFilterItems>
            <field>PSA_Project_Forecast_Detail__c.PSA_Include_in_Forecast__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>PSA_Project_Forecast_Detail__c.PSA_Project_Forecast__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PSA_Time_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the month-type time period to which the project forecast relates</description>
        <label>Time Period</label>
        <referenceTo>pse__Time_Period__c</referenceTo>
        <relationshipLabel>PSA Project Forecasts</relationshipLabel>
        <relationshipName>PSA_Project_Forecasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PSA Project Forecast</label>
    <nameField>
        <displayFormat>PF-{0000000}</displayFormat>
        <label>Project Forecast Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSA Project Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PSA_Project_Forecast_Detail__c.object
<CustomObject>
    <description>Provides detail level for rollup to monthly PSA Project Forecast records, with each record referencing an assigment, resource request, or sum of scheduled expense or fixed fee services billings or billing rule adjustments</description>
    <fields>
        <fullName>PSA_Include_in_Forecast__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies whether the record should be included in forecast reporting</description>
        <inlineHelpText>Automatically set by the Billing Forecast calculation, specifies whether the record should be included in forecast reporting</inlineHelpText>
        <label>Include in Forecast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSA_Project_Forecast__c</fullName>
        <label>PSA Project Forecast</label>
        <referenceTo>PSA_Project_Forecast__c</referenceTo>
        <relationshipLabel>PSA Project Forecast Details</relationshipLabel>
        <relationshipName>PSA_Project_Forecast_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PSA_Scheduled_Cost__c</fullName>
        <description>Scheduled hours times cost rate for a related resource request or assignment (if applicable), and month</description>
        <inlineHelpText>Scheduled hours times cost rate for a related resource request or assignment (if applicable), and month</inlineHelpText>
        <label>Scheduled Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSA_Scheduled_Time_Billings__c</fullName>
        <description>Sum of expected Billings from scheduled Assignments and Resource Requests</description>
        <inlineHelpText>Sum of scheduled billings for the period from a scheduled Assignment or Resource Request</inlineHelpText>
        <label>Scheduled Time Billings</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>PSA Project Forecast Detail</label>
    <nameField>
        <displayFormat>PFD-{0000000}</displayFormat>
        <label>PSA Project Forecast Detail Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSA Project Forecast Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestGenerateBillingsForecastDetails.cls
@isTest
public with sharing class TestGenerateBillingsForecastDetails {
	
	private static void setupdata(){
      
     // create Project Forecast Detail
       
      //Create RPG
        pse__Region__c testR = psaTestUtils.createTestRegion('Corporate');
        pse__Practice__c testP = psaTestUtils.createTestPractice('Corporate');
        pse__Grp__c testG = psaTestUtils.createTestGroup('Corporate');

        Account a = psaTestUtils.createTestAccount('Test Account', '12345');
        a.Participant_id__c = '1234';
        update a;
        //Create 2 contacts, one to submit and one as the manager
        User u = psaTestUtils.createTestUser('tuser121', 'tuser121@tuser.com', 'tser121', 'test', 'tuser121@tuser.com', 'ttser123');
        Contact c = psaTestUtils.createTestResource(u, testR, testP, testG);
        
        Date startDate = system.today().adddays(-61);
        Date endDate = system.today().adddays(-30);
        Double seasonalityFactor = 0.90;
        pse__Time_Period__c timePeriod = psaTestUtils.createTestTimePeriod('Test Period', seasonalityFactor, startDate, endDate, 'Month', true);

        pse__Proj__c testProject = psaTestUtils.createTestProjectInProgress('Test Project', a, testR, testP, testG, null, c, u);
        PSA_Project_Forecast__c prjForecast = new PSA_Project_Forecast__c(PSA_Project__c = testProject.Id, PSA_Include_in_Forecast__c = true,PSA_Time_Period__c =  timePeriod.ID);
        insert prjForecast;
        PSA_Project_Forecast_Detail__c forecastDetails = new PSA_Project_Forecast_Detail__c(PSA_Project_Forecast__c = prjForecast.Id,CurrencyIsoCode ='USD',PSA_Scheduled_Cost__c= 1,PSA_Scheduled_Time_Billings__c =1); 
        insert forecastDetails;

	}

	@isTest
	private static void TestForecastDetails() {
	    setupdata(); 
	    Test.startTest();
        String sDate = String.valueOf(system.today().addDays(-365));
        String eDate = String.valueOf(system.today());
        // validate if data is returned for the Forecast Detail report.
		System.assert(GenerateBillingsForecastDetails.getForecastDetails(sDate,eDate).size()>0);
		Test.stopTest();
	}

}