src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Record type used for all Customer records.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Record type used for all Partner records.</description>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>CS_Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>***** Asset  active Status ******</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Parent_Product__c</fullName>
        <description>Fetches Product Name from Standard product</description>
        <formula>BLANKVALUE(Product2.Product__r.Name, Product2.Name)</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Product_Family__c</fullName>
        <formula>HYPERLINK(
CASE($User.ProfileId, $Setup.CS_Profile_Id__c.CS_Customer_Profile__c ,&quot;/customer/&quot;,  $Setup.CS_Profile_Id__c.CS_Partner_Profile__c ,&quot;/GWPartners/&quot;,&quot;/&quot;)&amp;Id,
IMAGE(
CASE(  BLANKVALUE(Product2.Product__r.Name, Product2.Name) ,
&quot;BillingCenter&quot;,Image_Url__c&amp;&quot;/producticons/BillingCenter.png&quot;, 
&quot;ClaimCenter&quot;,Image_Url__c&amp;&quot;producticons/ClaimCenter.png&quot;, 
&quot;PolicyCenter&quot;,Image_Url__c&amp;&quot;producticons/PolicyCenter.png&quot;,
&quot;DataHub&quot;,Image_Url__c&amp;&quot;producticons/DataHub.png&quot;, 
&quot;InfoCenter&quot;,Image_Url__c&amp;&quot;producticons/InfoCenter.png&quot;,
Image_Url__c&amp;&quot;NoImages&quot;),Product2.Product__r.Name,20,20)
,&apos;_self&apos;)</formula>
        <inlineHelpText>Product Family</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Product_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Version</label>
        <referenceTo>CS_Release__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CS_Product__c</fullName>
        <formula>Product2.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Record_Type_Name__c</fullName>
        <description>Asset Record Type Name</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Version__c</fullName>
        <formula>CS_Product_Version__r.CS_Version__c+&apos; &apos;+BLANKVALUE(TEXT(CS_Product_Version__r.CS_Patch_Version__c),&apos;&apos;)</formula>
        <inlineHelpText>Product Version</inlineHelpText>
        <label>Version</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CS_Access_Type__c</fullName>
        <label>Access Type</label>
        <picklist>
            <picklistValues>
                <fullName>General Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support (View Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Is_Disabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Disabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>- Will bring in the related Contat and Partner User Information from the triggre on the User.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <description>Support Contact</description>
        <label>Support</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Asset_Contact_Permissions__c.object
<CustomObject>
    <fields>
        <fullName>CS_Access_Type__c</fullName>
        <label>Access Type</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support (View Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Asset_Name__c</fullName>
        <formula>CS_Asset__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Asset Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Asset_Status__c</fullName>
        <formula>TEXT(CS_Asset__r.Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Asset Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipName>Asset_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CS_Contact_Type__c</fullName>
        <formula>CS_Contact__r.Account.RecordType.DeveloperName</formula>
        <label>Contact Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Asset_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CS_Email__c</fullName>
        <formula>CS_Contact__r.Email</formula>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_First_Name__c</fullName>
        <formula>CS_Contact__r.FirstName</formula>
        <inlineHelpText>First Name</inlineHelpText>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Last_Name__c</fullName>
        <formula>CS_Contact__r.LastName</formula>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Office_Phone__c</fullName>
        <formula>CS_Contact__r.Phone</formula>
        <label>Office Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Product__c</fullName>
        <formula>BLANKVALUE(CS_Asset__r.Product2.Product__r.Name,CS_Asset__r.Product2.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Product_version__c</fullName>
        <formula>CS_Asset__r.CS_Product_Version__r.Name</formula>
        <label>Product Version</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Release_Version__c</fullName>
        <formula>CS_Asset__r.CS_Product_Version__r.CS_Version__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Version</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Title__c</fullName>
        <formula>CS_Contact__r.Title</formula>
        <label>Title</label>
        <type>Text</type>
    </fields>
    <label>Asset Contact Permission</label>
    <nameField>
        <label>Product Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Contact Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Release__c.object
<CustomObject>
    <description>***Service Cloud **** This Object  maintains the Installable Product versions</description>
    <fields>
        <fullName>CS_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Product_Version__c</fullName>
        <formula>Text(CS_Major_Release_version__c)&amp; Text(CS_Minor_Release_Version__c)  &amp;  Text(CS_Maintenance_Release_Version__c) &amp;  CS_Additional_Version_Code__c</formula>
        <label>Release Version</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordType.Name</field>
                <operation>contains</operation>
                <value>Standard Products,Entitled Product</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Product_Version</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CS_Version__c</fullName>
        <formula>TEXT(CS_Major_Release_version__c) + &apos;.&apos; +  IF(NOT(ISPICKVAL(CS_Minor_Release_Version__c, &apos;&apos;)), TEXT(CS_Minor_Release_Version__c), &apos;0&apos;) +  IF(NOT(ISPICKVAL(CS_Maintenance_Release_Version__c, &apos;&apos;)), &apos;.&apos; + TEXT(CS_Maintenance_Release_Version__c), &apos;&apos;)</formula>
        <label>Version</label>
        <type>Text</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Product Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>CS_Profile_Name__c</fullName>
        <formula>$Profile.Name</formula>
        <label>Profile Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CS_ViewContactsController.cls
/*
*****************************************************************************************************************************
Class Name - CS_ViewContactsController
Class Type -  Controller
Test Class-
Purpose- View Contacts Lightning Component Controller


*****************************************************************************************************************************

Name        Email              Date             Notes 
Shan xu                                            Initial Creation
Mani G                        09/06/2016           Fixed the Query to add   CS_Access_Type__c for Defect DE591
Suchitra p                    11/02/2016           Added additional check to not display disabled contacts/users. INC0063480
*****************************************************************************************************************************
*/
public with sharing class CS_ViewContactsController {
    /*
     @AuraEnabled
    public static List<CS_Asset_Contact_Permissions__c> getcontactlist() {
    List<CS_Asset_Contact_Permissions__c> toReturn =  New List<CS_Asset_Contact_Permissions__c>([select  CS_Asset__r.Account.name,CS_Product__c,CS_Asset_Status__c, 
                        CS_Contact_Type__c, CS_Email__c, CS_First_Name__c, CS_Last_Name__c,CS_Full_Name__c, CS_Office_Phone__c,
                         CS_Product_version__c, CS_Title__c from CS_Asset_Contact_Permissions__c]);
      System.debug('QUERY Result===========' +toReturn);
    return toReturn;
  }
  */
    
    static User user {
        get {
            return [Select Id, AccountId, ContactId from User where Id = :UserInfo.getUserId()];
        }
    }
    @AuraEnabled
    public static User getCurrentUser() {
      User toReturn = [SELECT Id, CS_Profile_Name__c,FirstName, LastName FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
      system.debug('+++++++toReturn'+toReturn);
        return toReturn;
  }
    
    @AuraEnabled
    public static List<CS_Asset_Contact_Permissions__c> getcontactlist() {
        List<CS_Asset_Contact_Permissions__c> acpList;
        if (user != null) {
            acpList =  [select  Name, CS_Email__c, CS_Asset__r.Account.name,CS_Asset_Name__c,CS_Product__c, 
                                                            CS_Contact_Type__c, CS_First_Name__c, CS_Last_Name__c, CS_Contact__r.Name, CS_Office_Phone__c,
                                                            CS_Product_version__c, CS_Title__c, CS_Access_Type__c, CS_Asset_Status__c from CS_Asset_Contact_Permissions__c
                                                           where CS_Asset__r.cs_record_type_name__c='Parent Asset' and CS_IsActive__c=true 
                                                           and CS_Asset__r.AccountId = :user.AccountId and 
                                                           CS_Asset__r.cs_record_type_name__c='Parent Asset' and CS_IsActive__c=true AND CS_Contact__r.CS_Is_Disabled__c=:false AND CS_Contact__r.User__r.IsActive=: true]; //INC0063480 Additional filter condition to exclude disabled contact and inactive user 
        }
        
        system.debug('contact list on initial load ' +acpList.size() );
        return acpList;
    }

    @AuraEnabled
    public static List<String> getParentAssets(String organization) {
        List<String> parentAssetNames = new List<String>();

        //Id ContactId=[select contactid from user where id =:userinfo.getUserId() limit 1];

        List<CS_Asset_Contact_Permissions__c> acpList;
        if (user != null ) {
            acpList = [Select Id, CS_Asset__c, CS_Release_Version__c, CS_Asset_Name__c, CS_Asset_Status__c, CS_Product__c,
                              CS_Contact_Type__c,CS_Access_Type__c, CS_Asset__r.CS_Product_Version__r.CS_Version__c,
                              CS_Asset__r.CS_Product_Family__c, CS_Asset__r.CS_Parent_Product__c, CS_Asset__r.Status 
                              from CS_Asset_Contact_Permissions__c 
                              where CS_Asset__r.AccountId = :user.AccountId
                              and CS_Asset__r.CS_Is_Active__c = true  
                              AND CS_Contact__r.CS_Is_Disabled__c=:false AND CS_Contact__r.User__r.IsActive=: true and
                               CS_Contact__c in
                               (select contactid from user where id =:userinfo.getUserId())];//INC0063480 Additional filter condition to exclude disabled contact and inactive user 
            for (CS_Asset_Contact_Permissions__c acp : acpList) {
                if (acp.CS_Access_Type__c == 'Customer Support' || acp.CS_Access_Type__c=='Customer Support (View Only)' || acp.CS_Access_Type__c == 'Partner' || acp.CS_Access_Type__c == 'General Customer' || acp.CS_Access_Type__c == 'Certified') {
                    parentAssetNames.add(acp.CS_Asset_Name__c);
                }
            }
        }
        return parentAssetNames;
    }
    @AuraEnabled
    public static List<CS_Asset_Contact_Permissions__c> getParentAssetswithId(String organization) {
        List<CS_Asset_Contact_Permissions__c> parentAssetNames = new List<CS_Asset_Contact_Permissions__c>();

        //Id ContactId=[select contactid from user where id =:userinfo.getUserId() limit 1];

        List<CS_Asset_Contact_Permissions__c> acpList;
        if (user != null ) {
            acpList = [Select Id, CS_Asset__c, CS_Release_Version__c, CS_Asset_Name__c, CS_Asset_Status__c, CS_Product__c,
                              CS_Contact_Type__c, CS_Access_Type__c, CS_Asset__r.CS_Product_Version__r.CS_Version__c,
                              CS_Asset__r.CS_Product_Family__c, CS_Asset__r.CS_Parent_Product__c, CS_Asset__r.Status 
                              from CS_Asset_Contact_Permissions__c 
                              where //CS_Asset__r.AccountId = :user.AccountId and 
                              CS_Asset__r.CS_Is_Active__c = true AND CS_Contact__r.CS_Is_Disabled__c=:false AND CS_Contact__r.User__r.IsActive=: true and  CS_Contact__c in
                               (select contactid from user where id =:userinfo.getUserId())];//INC0063480 Additional filter condition to exclude disabled contact and inactive user 
            for (CS_Asset_Contact_Permissions__c acp : acpList) {
                if (acp.CS_Access_Type__c == 'Customer Support' || acp.CS_Access_Type__c=='Customer Support (View Only)' || acp.CS_Access_Type__c == 'Partner' || acp.CS_Access_Type__c == 'General Customer' || acp.CS_Access_Type__c == 'Certified') {
                    parentAssetNames.add(acp);       
                }
            }
        }
        return parentAssetNames;
    }
    @AuraEnabled
    public static List<String> getProducts() {
        Set<String> productSet = new Set<String>();
        List<CS_Asset_Contact_Permissions__c> acpList;
        if (user != null) {
            acpList =  [select  CS_Asset__r.Account.name,CS_Asset_Name__c,CS_Product__c,CS_Asset_Status__c, 
                        CS_Contact_Type__c, CS_Access_Type__c, CS_Email__c, CS_First_Name__c, CS_Last_Name__c, CS_Contact__r.Name, CS_Office_Phone__c,
                        CS_Product_version__c, CS_Title__c from CS_Asset_Contact_Permissions__c
                        where CS_Asset__r.AccountId = :user.AccountId and CS_Asset__r.CS_Is_Active__c = true 
                        AND CS_Contact__r.CS_Is_Disabled__c=:false AND CS_Contact__r.User__r.IsActive=: true
                        and CS_Asset__r.cs_record_type_name__c='Parent Asset' ];//INC0063480 Additional filter condition to exclude disabled contact and inactive user 
            for (CS_Asset_Contact_Permissions__c acp : acpList) {
                productSet.add(acp.CS_Asset_Name__c);
            }
        }
        system.debug('productSet=='+productSet);
        return new List<String>(productSet);
    }
    
    /*
    @AuraEnabled 
    public static List<CS_Asset_Contact_Permissions__c> getContactsByProduct(String product) {
        System.debug('Input Product==='+product);
        List<CS_Asset_Contact_Permissions__c> acpList;
        if (user != null && product != 'All Products') {
            acpList =  [select  CS_Asset__r.Account.name,CS_Product__c,CS_Asset_Status__c, 
                        CS_Contact_Type__c, CS_Access_Type__c, CS_Email__c, CS_First_Name__c, CS_Last_Name__c, CS_Contact__r.Name, CS_Office_Phone__c,
                        CS_Product_version__c, CS_Title__c from CS_Asset_Contact_Permissions__c
                        where CS_Asset__r.AccountId = :user.AccountId
                        and CS_Product__c = :product];
        } else if (user != null && product == 'All Products') {
            acpList =  [select  CS_Asset__r.Account.name,CS_Product__c,CS_Asset_Status__c, 
                        CS_Contact_Type__c, CS_Email__c, CS_First_Name__c, CS_Last_Name__c, CS_Contact__r.Name, CS_Office_Phone__c,
                        CS_Product_version__c, CS_Title__c from CS_Asset_Contact_Permissions__c
                        where CS_Asset__r.AccountId = :user.AccountId];
        }
        return acpList;
    }
    */
    
    @AuraEnabled
    public static List<String> getChildAssetProducts(String organization) {
        system.debug('organization==='+organization);
        List<String> childAssetProducts = new List<String>();
        List<Asset> childAssets;
        if (user != null && organization == 'All') {
            childAssets = [Select Id, Product2.Name, ParentId 
                          from Asset
                          where AccountId = :user.AccountId and cs_record_type_name__c='Child Asset'];
        } else if (user != null && organization != 'All') {
            childAssets = [Select Id, Product2.Name, ParentId 
                          from Asset
                          where Parent.Name = :organization
                          
                          and AccountId = :user.AccountId
                          and cs_record_type_name__c='Child Asset'];
        }
        system.debug('MMG Child Assets ===='+ childAssets);
        for (Asset child : childAssets) {
            childAssetProducts.add(child.Product2.Name);
        }
        return childAssetProducts;
    }
    
    @AuraEnabled
    public static List<CS_Asset_Contact_Permissions__c> getContactsByAsset(String assetId) {
        System.Debug('user' + user);
        System.Debug('assetId' + assetId);

        List<Profile> PROFILE = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];
        String loggedInProfile = PROFILE[0].Name;
        String filterContactType = '';
        String queryString = '';
        if(loggedInProfile.toUpperCase() == 'GW PARTNER COMMUNITY')
        {
                 filterContactType = ' AND CS_Contact_Type__c!=\'Customer\'';
        }

        List<CS_Asset_Contact_Permissions__c> acpList;
        if (user != null && assetId!='All') {

            //INC0063480 Additional filter condition to exclude disabled contact and inactive user 
            queryString =  'select  Name, CS_Email__c, CS_Asset__r.name,CS_Asset_Name__c,CS_Asset__r.Account.name,CS_Product__c, CS_Contact_Type__c, CS_First_Name__c, CS_Last_Name__c, CS_Contact__r.Name, CS_Office_Phone__c,CS_Product_version__c, CS_Title__c, CS_Access_Type__c, CS_Asset_Status__c from CS_Asset_Contact_Permissions__c where CS_Asset__r.cs_record_type_name__c=\'Parent Asset\' and CS_IsActive__c=true  and (CS_Asset__r.name = \'' + assetId + '\' or CS_Asset__r.Id=\'' + assetId + '\') AND CS_Contact__r.CS_Is_Disabled__c=false AND CS_Contact__r.User__r.IsActive=true' + filterContactType  ;
                          
            acpList =  Database.query(queryString);
        }
        else{
            //INC0063480 Additional filter condition to exclude disabled contact and inactive user 
            queryString =  'select  Name, CS_Email__c, CS_Asset__r.name,CS_Asset_Name__c,CS_Asset__r.Account.name,CS_Product__c, CS_Contact_Type__c, CS_First_Name__c, CS_Last_Name__c, CS_Contact__r.Name, CS_Office_Phone__c, CS_Product_version__c, CS_Title__c, CS_Access_Type__c, CS_Asset_Status__c from CS_Asset_Contact_Permissions__c where CS_Asset__r.cs_record_type_name__c=\'Parent Asset\' and CS_IsActive__c=true AND CS_Contact__r.CS_Is_Disabled__c=false AND CS_Contact__r.User__r.IsActive=true' + filterContactType ;
                          
                        //and CS_Asset__r.AccountId = :user.AccountId ];
            acpList =  Database.query(queryString);         

        }
      
        return acpList;
    }
    
    /*
    @AuraEnabled
    public static String getAssetProduct(String assetId) {
        Asset a = [Select CS_Parent_Product__c from Asset where Id = :assetId];
        return a.CS_Parent_Product__c;
    }
    */
}