src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resubmit Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Participant_id__c</fullName>
        <externalId>true</externalId>
        <label>Participant ID</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Requested_Approval__c</fullName>
        <label>Requested Approval</label>
        <picklist>
            <picklistValues>
                <fullName>New Customer - Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer – Indirect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer - Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer – Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer - Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid POC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PartnerConnect - Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PartnerConnect - Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner - Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site</fullName>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Record type used for all Customer records.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Record type used for all Partner records.</description>
        <label>Partner</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Record type used for all Prospect records.</description>
        <label>Prospect</label>
    </recordTypes>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <description>Record Type used for all Site Records</description>
        <label>Site</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Record Type used for all Vendor Records</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Contact__c.object
<CustomObject>
    <description>This object allows tracking of multiple addresses/sites and Contact types.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill To \ Ship To</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bill To\ Ship To</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RecordStatus__c</fullName>
        <label>Record Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <label>Account Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/trac_AccountHandler.cls
/**
 * @description Generate auto number for the Participant_id__c field
 *              Automatically submit record for approval
 * @author Tanminder Rai, Traction On Demand
 * @date May 25/2015
 */

public with sharing class trac_AccountHandler {

    public static Id PROS_RT = Schema.SObjectType.Account.RecordTypeInfosByName.get('Prospect').RecordTypeId;
    public static Id PART_RT = Schema.SObjectType.Account.RecordTypeInfosByName.get('Partner').RecordTypeId;
    public static Id VEND_RT = Schema.SObjectType.Account.RecordTypeInfosByName.get('Vendor').RecordTypeId;
    public static Id CUST_RT = Schema.SObjectType.Account.RecordTypeInfosByName.get('Customer').RecordTypeId;
    public static Boolean disableTrigger = false;

    //Automatically submit the account for approval when status is changed to 'Resubmit Required'
    public static void autoSubmitApproval(Account[] acc){
        if(!disableTrigger){
            for (Account a :acc) {
                if(a.Participant_id__c != null 
                    && a.Approval_Status__c == 'Resubmit Required' 
                    && ( a.RecordTypeId == PROS_RT || a.RecordTypeId == PART_RT || a.RecordTypeId == VEND_RT || a.RecordTypeId == CUST_RT) 
                    && a.Requested_Approval__c !=NULL ){
                    try{
                        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                        req1.setComments('Submitting request for approval.');
                        req1.setObjectId(a.id);
                        Approval.ProcessResult result = Approval.process(req1);
                        System.debug('Approval Process Result:' + result);
                        disableTrigger = true;
                    }catch(Exception e){
                        throw new CustomException('***ERROR: Matching approval process not found.***');
                    }
                }
            }
        }
    }

    public static void validateAccountContactDeletion(List<SObject> oldObjList, String sObjType){
       
       List<Account_Contact__c>  acrList = new List<Account_Contact__c>();
       List<Account> accLst = new List<Account>();
       if(sObjType =='Contact'){
         acrList = [select Id,Account__c,Contact__c  from Account_Contact__c where Contact__c  in: oldObjList and RecordStatus__c = 'Active'];
       }else if(sObjType =='Account'){
         acrList = [select Id,Account__c,Contact__c,Account__r.RecordTypeId  from Account_Contact__c where Account__c in: oldObjList and RecordStatus__c = 'Active'];
         Acclst = [select id,name, Participant_id__c from account where id IN: oldObjList];         
       }
     
       for(SObject  sobj : oldObjList)
       {
          if(acrList.size()>0){
             for(Account_Contact__c acrVar : acrList){
                 if(sObjType =='Contact'){
                     if(acrVar.Contact__c == sobj.Id){
                          sobj.addError('Contact can not be deleted as it has associated Bill To/Ship To.');
                     }
                 } else if(sObjType =='Account'){
                     if(acrVar.Account__c == sobj.Id && acrVar.Account__r.RecordTypeId  == Schema.SObjectType.Account.RecordTypeInfosByName.get('Site').RecordTypeId){
                          sobj.addError('Account can not be deleted as it has associated Bill To/Ship To.');
                     }   
                 }
             }
          } 
          
          // Added to check Participant id - Hari
          
          for(Account acc : Acclst)
          {
            if(acc.id == sobj.id && acc.Participant_id__c != Null)
            {
              sobj.addError('Account can not be deleted as it has Participant Id');
            }
          } 
       }
    }

    public class CustomException extends Exception {}
}