src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LatAm</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>RFI_Approval_SC__c</fullName>
        <label>RFI Approval - SC</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFI_Approval_SD__c</fullName>
        <label>RFI Approval - SD</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFI_Approved_Denied_SC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFI Approved/Denied by SC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunitiesuzvy</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RFI_Approved_Denied_SD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFI Approved/Denied by SD</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesuzwD</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RFP_Approval_SC__c</fullName>
        <label>RFP Approval - SC</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFP_Approval_SD__c</fullName>
        <label>RFP Approval - SD</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFP_Approved_Denied_SC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFP Approved/Denied by SC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesuzwS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RFP_Approved_Denied_SD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFP Approved/Denied by SD</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunitiesuzwc</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>AMER</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Services_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Services Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesTaDV</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RFI_RFP_Emails__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RFI/RFP-Opportunity-Emails</label>
</CustomObject>

src/classes/RFIRFPApprovalHandler.cls
public class RFIRFPApprovalHandler
{
    public static boolean flag = true;
    
    public void SCSDRequested(set<id> Oppids, Map<id,Opportunity> OldMap) 
    {
        Boolean updateflag = false;
         
        List<Opportunity> OppLst = [select id,name,region__c, Services_Director__c,Services_Director__r.email,OwnerId,Owner.email,owner.name,Account.name, RFI_Approval_SC__c,RFI_Approval_SD__c,RFP_Approval_SC__c,RFP_Approval_SD__c
                                from Opportunity where Id IN: Oppids];
        
        List<opportunity> newoppLst = new list<Opportunity>();
        List<opportunity> oldOppLst = new list<Opportunity>();
      
        for(Opportunity opp : OppLst)
        {     
                
            if(opp.RFI_Approval_SC__c != OldMap.get(opp.Id).RFI_Approval_SC__c && (opp.RFI_Approval_SC__c =='Approved' || opp.RFI_Approval_SC__c =='Denied'))
             {     
                opp.RFI_Approved_Denied_SC__c = userinfo.getUserId();
                updateflag = true;
             }
            
            
            if(opp.RFI_Approval_SD__c != OldMap.get(opp.Id).RFI_Approval_SD__c && (opp.RFI_Approval_SD__c =='Approved' || opp.RFI_Approval_SD__c =='Denied'))
              {
                 opp.RFI_Approved_Denied_SD__c = userinfo.getUserId();
                   updateflag = true;
              }
            
          
             if(opp.RFP_Approval_SC__c != OldMap.get(opp.Id).RFP_Approval_SC__c && (opp.RFP_Approval_SC__c =='Approved' || opp.RFP_Approval_SC__c =='Denied'))
              {
                  opp.RFP_Approved_Denied_SC__c = userinfo.getUserId();
                    updateflag = true;
              }
            
           
             if(opp.RFP_Approval_SD__c != OldMap.get(opp.Id).RFP_Approval_SD__c && (opp.RFP_Approval_SD__c =='Approved' || opp.RFP_Approval_SD__c =='Denied'))
              {
                  opp.RFP_Approved_Denied_SD__c = userinfo.getUserId();
                    updateflag = true;
              }            
           
          newoppLst.add(opp);
            
        }
        
        if(updateFlag)
        {
          flag = false;
          update newOppLst;
          SendEmail(newoppLst, OldMap);
        }    
    }
    
     public void SendEmail(List<Opportunity> NewOpps, Map<id,Opportunity> OldOppMap)
     {
         Map<string,RFI_RFP_Emails__c> customMap = RFI_RFP_Emails__c.getAll();
         system.debug('map values :'+ customMap);
         Messaging.SingleEmailMessage[] emailMessageList = new Messaging.SingleEmailMessage[]{};
             
         for(Opportunity Opp: NewOpps)
         {
            Opportunity oldOpp = OldOppMap.get(opp.id);
             
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
             
             String[] toAdd = new String[]{};
                 
             if(opp.Services_Director__c != Null)
              {
                 string sdEmail = opp.Services_Director__r.email; 
                 system.debug('service Direc'+sdEmail);
                 toAdd.add(sdemail);                  
              }
                       
             toAdd.add(opp.Owner.email); 
             
             if(opp.Region__c =='EMEA')
             {             
             string DirectorofSC = customMap.get('EMEA - Director of SC').email__c;
             string EmeaSalesOps = customMap.get('EMEA - Sales Ops').email__c;
             toAdd.add(DirectorofSC);
             toAdd.add(EmeaSalesOps); 
             
             if(opp.RFI_Approval_SC__c == 'Approved' || opp.RFI_Approval_SD__c == 'Approved' || opp.RFP_Approval_SC__c == 'Approved' || opp.RFP_Approval_SD__c == 'Approved'
                || opp.RFI_Approval_SC__c == 'Denied' || opp.RFI_Approval_SD__c == 'Denied' || opp.RFP_Approval_SC__c == 'Denied' || opp.RFP_Approval_SD__c == 'Denied')
             {
                 string VP = customMap.get('EMEA - VP').email__c;
                 toAdd.add(VP);
             } 
             } 
             
             if(opp.Region__c =='AMER')
             {             
             string DirectorofSC = customMap.get('AMER - Director of SC').email__c;
             string EmeaSalesOps = customMap.get('AMER - Sales Ops').email__c;
             toAdd.add(DirectorofSC);
             toAdd.add(EmeaSalesOps); 
             
             if(opp.RFI_Approval_SC__c == 'Approved' || opp.RFI_Approval_SD__c == 'Approved' || opp.RFP_Approval_SC__c == 'Approved' || opp.RFP_Approval_SD__c == 'Approved'
                || opp.RFI_Approval_SC__c == 'Denied' || opp.RFI_Approval_SD__c == 'Denied' || opp.RFP_Approval_SC__c == 'Denied' || opp.RFP_Approval_SD__c == 'Denied')
             {
                 string VP = customMap.get('AMER - VP').email__c;
                 toAdd.add(VP);
             } 
             }   
             
             if(opp.Region__c =='APAC')
             {             
             string DirectorofSC = customMap.get('APAC - Director of SC').email__c;
             string EmeaSalesOps = customMap.get('APAC - Sales Ops').email__c;
             toAdd.add(DirectorofSC);
             toAdd.add(EmeaSalesOps); 
             
             if(opp.RFI_Approval_SC__c == 'Approved' || opp.RFI_Approval_SD__c == 'Approved' || opp.RFP_Approval_SC__c == 'Approved' || opp.RFP_Approval_SD__c == 'Approved'
                || opp.RFI_Approval_SC__c == 'Denied' || opp.RFI_Approval_SD__c == 'Denied' || opp.RFP_Approval_SC__c == 'Denied' || opp.RFP_Approval_SD__c == 'Denied')
             {
                 string VP = customMap.get('APAC - VP').email__c;
                 toAdd.add(VP);
             } 
             } 
             
             if((oldOpp.RFI_Approval_SC__c !=opp.RFI_Approval_SC__c) && opp.RFI_Approval_SC__c == 'Approved')
             {
             
               mail.setToAddresses(toAdd);                      
               mail.setSubject(opp.name +', RFI Approval');             
               mail.setHtmlBody('The Opportunity titled <b>'+ Opp.name +'</b> owned by <b>' +Opp.Owner.Name+'</b> from Account <b>'+opp.Account.name+'</b> has been approved by Sales Consulting. <br> <br> Please click on the link below to view the opportunity <a href="'+URL.getSalesforceBaseUrl().toExternalForm()+'/'+Opp.id+'">'+opp.Name+'</a> <br> <br> Thank You.' );
               
             emailMessageList.add(mail); 
             }
             
             if((oldOpp.RFI_Approval_SC__c !=opp.RFI_Approval_SC__c) && opp.RFI_Approval_SC__c == 'Denied')
             {
             
               mail.setToAddresses(toAdd);                      
               mail.setSubject(opp.name +', RFI Denial');             
               mail.setHtmlBody('The Opportunity titled <b>'+ Opp.name +'</b> owned by <b>' +Opp.Owner.Name+'</b> from Account <b>'+opp.Account.name+'</b> has been declined by Sales Consulting. <br> <br> Please click on the link below to view the opportunity <a href="'+URL.getSalesforceBaseUrl().toExternalForm()+'/'+Opp.id+'">'+opp.Name+'</a> <br> <br> Thank You.' );
               
             emailMessageList.add(mail); 
             }
             
             if((oldOpp.RFI_Approval_SD__c != opp.RFI_Approval_SD__c) && opp.RFI_Approval_SD__c == 'Approved')
             {
             
               mail.setToAddresses(toAdd);                      
               mail.setSubject(opp.name +', RFI Approval');             
               mail.setHtmlBody('The Opportunity titled <b>'+ Opp.name +'</b> owned by <b>' +Opp.Owner.Name+'</b> from Account <b>'+opp.Account.name+'</b> has been approved by Sales Management. <br> <br> Please click on the link below to view the opportunity <a href="'+URL.getSalesforceBaseUrl().toExternalForm()+'/'+Opp.id+'">'+opp.Name+'</a> <br> <br> Thank You.' );
               
             emailMessageList.add(mail); 
             }
             
             if((oldOpp.RFI_Approval_SD__c != opp.RFI_Approval_SD__c) &&  opp.RFI_Approval_SD__c == 'Denied')
             {
             
               mail.setToAddresses(toAdd);                      
               mail.setSubject(opp.name +', RFI Denial');             
               mail.setHtmlBody('The Opportunity titled <b>'+ Opp.name +'</b> owned by <b>' +Opp.Owner.Name+'</b> from Account <b>'+opp.Account.name+'</b> has been declined by Sales Management. <br> <br> Please click on the link below to view the opportunity <a href="'+URL.getSalesforceBaseUrl().toExternalForm()+'/'+Opp.id+'">'+opp.Name+'</a> <br> <br> Thank You.' );
               
             emailMessageList.add(mail); 
             }
             
             if((oldOpp.RFP_Approval_SC__c != opp.RFP_Approval_SC__c) && opp.RFP_Approval_SC__c == 'Approved' )
             {
             
               mail.setToAddresses(toAdd);                      
               mail.setSubject(opp.name +', RFP Approval');             
               mail.setHtmlBody('The Opportunity titled <b>'+ Opp.name +'</b> owned by <b>' +Opp.Owner.Name+'</b> from Account <b>'+opp.Account.name+'</b> has been approved by Sales Consulting. <br> <br> Please click on the link below to view the opportunity <a href="'+URL.getSalesforceBaseUrl().toExternalForm()+'/'+Opp.id+'">'+opp.Name+'</a> <br> <br> Thank You.' );
               
             emailMessageList.add(mail); 
             }
             
             if((oldOpp.RFP_Approval_SC__c != opp.RFP_Approval_SC__c) &&  opp.RFP_Approval_SC__c == 'Denied')
             {
             
               mail.setToAddresses(toAdd);                      
               mail.setSubject(opp.name +', RFP Denial');             
               mail.setHtmlBody('The Opportunity titled <b>'+ Opp.name +'</b> owned by <b>' +Opp.Owner.Name+'</b> from Account <b>'+opp.Account.name+'</b> has been declined by Sales Consulting. <br> <br> Please click on the link below to view the opportunity <a href="'+URL.getSalesforceBaseUrl().toExternalForm()+'/'+Opp.id+'">'+opp.Name+'</a> <br> <br> Thank You.' );
               
             emailMessageList.add(mail); 
             }
             
             if((oldOpp.RFP_Approval_SD__c != opp.RFP_Approval_SD__c) && opp.RFP_Approval_SD__c == 'Approved' )
             {
             
               mail.setToAddresses(toAdd);                      
               mail.setSubject(opp.name +', RFP Approval');             
               mail.setHtmlBody('The Opportunity titled <b>'+ Opp.name +'</b> owned by <b>' +Opp.Owner.Name+'</b> from Account <b>'+opp.Account.name+'</b> has been approved by Sales Management. <br> <br> Please click on the link below to view the opportunity <a href="'+URL.getSalesforceBaseUrl().toExternalForm()+'/'+Opp.id+'">'+opp.Name+'</a> <br> <br> Thank You.' );
               
             emailMessageList.add(mail); 
             }
             
             if((oldOpp.RFP_Approval_SD__c != opp.RFP_Approval_SD__c) && opp.RFP_Approval_SD__c == 'Denied')
             {
             
               mail.setToAddresses(toAdd);                      
               mail.setSubject(opp.name +', RFP Denial');             
               mail.setHtmlBody('The Opportunity titled <b>'+ Opp.name +'</b> owned by <b>' +Opp.Owner.Name+'</b> from Account <b>'+opp.Account.name+'</b> has been declined by Sales Management. <br> <br> Please click on the link below to view the opportunity <a href="'+URL.getSalesforceBaseUrl().toExternalForm()+'/'+Opp.id+'">'+opp.Name+'</a> <br> <br> Thank You.' );
               
             emailMessageList.add(mail); 
             }
         }
         
         Messaging.sendEmail(emailMessageList);
     }
}