src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Record type used for all Customer records.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Record type used for all Prospect records.</description>
        <label>Prospect</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>CS_Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>***** Asset  active Status ******</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Record_Type_Name__c</fullName>
        <description>Asset Record Type Name</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CS_Urgency__c</fullName>
        <description>Specify how urgently this particular Issue needs a solution</description>
        <inlineHelpText>Specify how urgently this particular Issue needs a solution</inlineHelpText>
        <label>Urgency</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immediate</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <picklist>
            <controllingField>Asset_Type__c</controllingField>
            <picklistValues>
                <fullName>1-Blocker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2-Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3-Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4-Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1–Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2–Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3–Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4–Cosmetic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <description>Support Contact</description>
        <label>Support</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Asset_Contact_Permissions__c.object
<CustomObject>
    <label>Asset Contact Permission</label>
    <nameField>
        <label>Product Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Contact Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Milestone_Business_Hours__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>**** Service Cloud  Milestone Business Hours ******</description>
    <label>GW Milestone Business Hours</label>
</CustomObject>

src/objects/CS_Request__c.object
<CustomObject>
    <fields>
        <fullName>CS_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CS_is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dev_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dev Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>Req-{00000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GW_Common_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>GW Common Settings</label>
</CustomObject>

src/classes/TestCS_RequestTriggerHandler.cls
@isTest
public class TestCS_RequestTriggerHandler {
    static Account customerAcc;
    static Contact customerContact;
    static User currentUsr;
    static User customerCommunityTestUser;
    static Product2 prod;
    static User testUser;
    static CS_Asset_Contact_Permissions__c acp;
    static ContentVersion contentVersion;
    static ContentDocumentLink cdl;
    static List<GW_Common_Settings__c> commonSettings;
    static Entitlement ent;
    static CS_Milestone_Business_Hours__c mbh;
    static CaseTeamRole ctr;
    static CaseTeamMember ctm;
    static  Case insertedCase;
    
    static void setupTestData() { 
        
        testUser = CS_TestDataUtility.createServiceTestUser();
        
        prod = CS_TestDataUtility.createProductRecord();
        customerAcc = CS_TestDataUtility.createCustomerAccount();
        customerContact = CS_TestDataUtility.createContact(customerAcc, 'Customer Support');
        // insert parent asset for customer account
        List<Asset> parentAssetsCustomer = CS_TestDataUtility.createParentAssetRecord(customerAcc, true);
            
        // insert child assets
        
        for (Integer i=0; i < parentAssetsCustomer.size(); i++) {
            if (i < parentAssetsCustomer.size() - 1) {
                CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Prospect');
            } else {
                CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Implementation');
            }
        }
        
     
    }
    
    static testMethod void testRequstInsert() {
        setupTestData();

        //query asset
        Asset childAsset = [Select Id, CS_Is_Active__c from Asset where CS_Record_Type_Name__c = 'Child Asset' and ParentId != null limit 1];
        // query case record type
        RecordType rt = [Select Name, developername from RecordType where sobjecttype = 'Case' and Name = 'Customer Support'];
       
        Case c = new Case();
        c.AssetId = childAsset.Id;
        
        c.AccountId = customerAcc.Id;
        c.RecordTypeId = rt.Id;
        c.ContactId = customerContact.Id;
        c.Severity__c = '3-Major';
        c.CS_Urgency__c = 'High';
        insert c;
        
        // query case team role       
        ctr = [Select Id, Name from CaseTeamRole where Name = 'Customer Support' and AccessLevel = 'Edit' limit 1];
        
        ctm = CS_TestDataUtility.createCaseTeamMember(c.Id, testUser.Id, ctr.Id);
       
        Test.startTest();
        // insert Request
        CS_Request__c request = new CS_Request__c();
        request.CS_Case__c = c.Id;
        request.Dev_Assignee__c = testUser.Id;
        request.CS_is_Active__c = true;
        insert request;
        Test.stopTest();        
    }
}