src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Record type used for all Customer records.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Record type used for all Prospect records.</description>
        <label>Prospect</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>CS_Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>***** Asset  active Status ******</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Record_Type_Name__c</fullName>
        <description>Asset Record Type Name</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CS_Contact_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Licensed Product</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>CS_Asset_Contact_Permissions__c.CS_Contact__c</field>
                <operation>equals</operation>
                <valueField>$User.ContactId</valueField>
            </filterItems>
            <filterItems>
                <field>CS_Asset_Contact_Permissions__c.CS_IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>CS_Asset_Contact_Permissions__c.CS_Access_Type__c</field>
                <operation>equals</operation>
                <value>Customer Support, Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CS_Asset_Contact_Permissions__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CS_Restoration_Milestone_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Mark Restoration Complete</inlineHelpText>
        <label>Restoration Milestone Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Urgency__c</fullName>
        <description>Specify how urgently this particular Issue needs a solution</description>
        <inlineHelpText>Specify how urgently this particular Issue needs a solution</inlineHelpText>
        <label>Urgency</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immediate</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <picklist>
            <controllingField>Asset_Type__c</controllingField>
            <picklistValues>
                <fullName>1-Blocker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2-Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3-Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4-Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1–Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2–Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3–Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4–Cosmetic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <description>Support Contact</description>
        <label>Support</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Asset_Contact_Permissions__c.object
<CustomObject>
    <label>Asset Contact Permission</label>
    <nameField>
        <label>Product Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Contact Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_ByPass__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>ByPass from Triggers,WF Rules and Validation Rules</description>
    <fields>
        <fullName>CS_Disable_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>ByPass from Trigger</inlineHelpText>
        <label>Disable Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Disable_ValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ByPass from Validation Rules</description>
        <label>Disable ValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <label>GW ByPass</label>
</CustomObject>

src/objects/CS_Milestone_Business_Hours__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>**** Service Cloud  Milestone Business Hours ******</description>
    <fields>
        <fullName>CS_Business_Days__c</fullName>
        <label>Business Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CS_Entitlement_Process_Name__c</fullName>
        <description>Entitlement Process Name</description>
        <label>Entitlement Process Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Milestone_Name__c</fullName>
        <description>Milestone Name</description>
        <label>Milestone Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Severity__c</fullName>
        <label>Severity</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>GW Milestone Business Hours</label>
</CustomObject>

src/objects/Support_Business_Hours__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Business_Hours_End__c</fullName>
        <label>Business Hours End(hh)</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Hours_End_mm__c</fullName>
        <label>Business Hours End (mm)</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Hours_Start__c</fullName>
        <label>Business Hours Start (hh)</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Hours_Start_mm__c</fullName>
        <label>Business Hours Start (mm)</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_of_support__c</fullName>
        <label>Type of support</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Support Business Hours</label>
</CustomObject>

src/classes/Test_CaseMilestoneCalculationHostedAsset.cls
@isTest(SeeAllData=false)
public class Test_CaseMilestoneCalculationHostedAsset {
    static Account customerAcc;
    static Contact customerContact;
    static User currentUsr;
    static Product2 prod;
    static User testUser;
    static CS_Asset_Contact_Permissions__c acp;
    static Entitlement ent;
    static CS_Milestone_Business_Hours__c mbh;
    
    static void setupTestData() {
        // query current test user
        currentUsr = [select Id, UserRole.Name from User where Id = :UserInfo.getUserId()];       
        
        prod = CS_TestDataUtility.createProductRecord();
        customerAcc = CS_TestDataUtility.createCustomerAccount();
        customerContact = CS_TestDataUtility.createContact(customerAcc, 'Customer Support');
        // insert parent asset for customer account
        List<Asset> parentAssetsCustomer = CS_TestDataUtility.createParentAssetRecordHosted(customerAcc, true);
            
        // insert child assets
        for (Integer i=0; i < parentAssetsCustomer.size(); i++) {
            if (i < parentAssetsCustomer.size() - 1) {
                CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Prospect');
            } else {
                CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Implementation');
            }
        }
        
         // if (parentAssetsCustomer != null && parentAssetsCustomer.size() > 0) {
             // create acp
            // acp = CS_TestDataUtility.createACP(parentAssetsCustomer[0], customerContact, 'Customer Support', true);
         // }
        
         mbh = CS_TestDataUtility.createMileStoneBusinessHours('3sh','Initial Response (3S)','Hosted Standard', 1, '3–Minor');
         mbh = CS_TestDataUtility.createMileStoneBusinessHours('4s','Initial Response (4S)','Hosted Standard', 1, '3-Major');
         mbh = CS_TestDataUtility.createMileStoneBusinessHours('3sd','Initial Response (3S)','Default', 1, '3-Major');
         mbh = CS_TestDataUtility.createMileStoneBusinessHours('4sd','Initial Response (4S)','Default', 1, '4-Minor');
         
         //query MileStone
        // CaseMileStone cms = [Select Id, MilestoneType.Name from CaseMileStone limit 1];
        
        //query entitlement
        // Entitlement insertedEnt = [Select Id, Name from Entitlement limit 1];
        
        List<CS_Milestone_Business_Hours__c> mbhListToInsert = new List<CS_Milestone_Business_Hours__c>();
        CS_Milestone_Business_Hours__c mbh1 = new CS_Milestone_Business_Hours__c();
        mbh1.Name = 'TestMBH1';
        mbh1.CS_Business_Days__c = 5;
        mbh1.CS_Entitlement_Process_Name__c = 'Hosted Standard';
        mbh1.CS_Severity__c = '3-Major';
        mbh1.CS_Milestone_Name__c = 'Initial Response (3S)';
        mbhListToInsert.add(mbh1);
        
        // List<CS_Milestone_Business_Hours__c> mbhListToInsert = new List<CS_Milestone_Business_Hours__c>();
        // CS_Milestone_Business_Hours__c mbh3 = new CS_Milestone_Business_Hours__c();
        // mbh3.Name = 'TestMBH3';
        // mbh3.CS_Entitlement_Process_Name__c = 'Default';
        // mbh3.CS_Business_Days__c = 5;
        // mbh3.CS_Severity__c = '3-Major';
        // mbh3.CS_Milestone_Name__c = 'Initial Response (3S)';
        // mbhListToInsert.add(mbh3);
        
        CS_Milestone_Business_Hours__c mbh2 = new CS_Milestone_Business_Hours__c();
        mbh2.Name = 'TestMBH2';
        mbh2.CS_Entitlement_Process_Name__c = 'Hosted Standard';
        mbh2.CS_Business_Days__c = 10;
        mbhListToInsert.add(mbh2);
        
         
        
        insert mbhListToInsert;
        
        // Support_Business_Hours__c bizHrs = [SELECT Business_Hours_End_mm__c,Business_Hours_End__c,Business_Hours_Start_mm__c,Business_Hours_Start__c,Type_of_support__c FROM Support_Business_Hours__c where Type_of_support__c = 'Hosted Asset' ];
        
        Support_Business_Hours__c sbh = new Support_Business_Hours__c();
        sbh.Business_Hours_End_mm__c = 0;
        sbh.Business_Hours_End__c = 17;
        sbh.Business_Hours_Start_mm__c = 0;
        sbh.Business_Hours_Start__c = 8;
        sbh.Type_of_support__c = 'Hosted Asset';
        sbh.Name = 'Hosted Asset';
        
        insert sbh;
        
        //query asset
        Asset childAsset = [Select Id, CS_Is_Active__c from Asset where CS_Record_Type_Name__c = 'Child Asset' and ParentId != null limit 1];
        
        acp = [Select Id from CS_Asset_Contact_Permissions__c limit 1];
        // query case record type
        RecordType rt = [Select Name, developername from RecordType where sobjecttype = 'Case' and Name = 'Customer Support'];
        
        // create entitlement
        ent = CS_TestDataUtility.createEntitlement(childAsset, customerAcc,'Hosted Standard');
        system.debug('%%%%%%%% Entitlement Business Hours Id:  ' + ent.BusinessHoursId);
        CS_ByPass__c byPass = new CS_ByPass__c();
                byPass.Name = 'CS_Disable_ValidationRule__c';
                byPass.SetupOwnerId = Userinfo.getUserId();
                byPass.CS_Disable_ValidationRule__c = true;
                byPass.CS_Disable_Trigger__c = true;
                insert byPass;
        
        List<Case> caseList = new List<Case>();
        
        ent = [SELECT Id,BusinessHoursId,SlaProcessId from Entitlement LIMIT 1 ];
        
        for(Integer i = 0; i < 1 ; i ++){
            Case c = new Case();
            c.AssetId = childAsset.Id;
        c.Subject = 'This is a test for ' + i;
        c.AccountId = customerAcc.Id;
        c.RecordTypeId = rt.Id;
        c.ContactId = customerContact.Id;
        c.Severity__c = '3-Major';
        c.CS_Urgency__c = 'High';
        c.CS_Contact_Asset__c = acp.Id;
        c.EntitlementId = ent.Id;
        c.Entitlement = ent;
        // c.Entitlement.BusinessHoursId = ent.BusinessHoursId;
        // c.Entitlement.SlaProcess = ent.SlaProcess;
        c.BusinessHoursId = ent.BusinessHoursId;
        caseList.add(c);
        
        }
        
        // Integer duration = getDuration(c.Entitlement.SlaProcess.Name, 
                                            // mt.Name, c.Severity__c);
        
        insert caseList;
        
        for(case ca : caseList){
                system.debug('############### Entitlement is  : ' + ca.EntitlementId + '   ::  ' + ca.Entitlement.BusinessHoursId);
        }
        
        Integer i = 0;
        Integer j = 0;
        
        
        for(case ca : caseList){
                system.debug('###### Current created Date : ' + ca.createdDate);
                Test.setCreatedDate(ca.Id, system.Now().addHours(i).addDays(j - 1));
                
                
                i = i - 6;
                j = j - 1;
        }
        
        caseList = [SELECT Subject,AccountId,RecordTypeId,ContactId,Severity__c,CS_Urgency__c,CS_Contact_Asset__c,EntitlementId,BusinessHoursId,CreatedDate from Case];
        
        for(case ca : caseList){
                system.debug('###### Changed created Date : ' + ca.createdDate + '      ######system.Now().addHours(i) ' + system.Now().addHours(i));
        }
        
        
        
        
    }
    
    static testMethod void testcalculateMilestoneTriggerTime() {
         setupTestData();
         Test.startTest();
        
       
        
        List<Case> caseList = [Select Id, AssetId, EntitlementId, BusinessHoursId, CS_Restoration_Milestone_Completed__c from Case];
        // Case c = [Select Id, AssetId, EntitlementId, BusinessHoursId, CS_Restoration_Milestone_Completed__c from Case limit 1];
        
        for(Case c : caseList){
            // CaseMileStone cms = [Select MileStoneTypeId from CaseMileStone where CaseId=: c.Id limit 1];
        string myMilestoneTypeId = '';
        
        system.debug('############### Entitlement is  : ' + c.EntitlementId );
        // if(cms == null)
            myMilestoneTypeId = '55734000000PDVvAAO';
        // else
            // myMilestoneTypeId = cms.MileStoneTypeId;
        
            CS_CaseMilestoneCalculationHostedAsset cmsCalculation = new CS_CaseMilestoneCalculationHostedAsset();
            cmsCalculation.calculateMilestoneTriggerTime(c.Id, myMilestoneTypeId);
        }
        
        Test.stopTest();
    }
    
    static testMethod void testCustomMilestoneCalculation() {
       setupTestData();
        
       Test.startTest();
       
        
        
        Case c = [Select Id, AssetId, EntitlementId, BusinessHoursId, CS_Restoration_Milestone_Completed__c from Case limit 1];
        List<CaseMileStone> cms = [Select MileStoneTypeId from CaseMileStone where CaseId=: c.Id];
        
        system.debug('############## RP Start Debug' + cms);
        
        // CaseMileStone cms = [Select MileStoneTypeId from CaseMileStone where CaseId=: c.Id limit 1];
        string myMilestoneTypeId = '';
        
        // if(cms != null || cms.size() > 0)
            // myMilestoneTypeId = cms.get(0).MileStoneTypeId;
        // else
            myMilestoneTypeId = '55734000000PDVvAAO';
            
        
        
        CS_CaseMilestoneCalculationHostedAsset cmsCalculation = new CS_CaseMilestoneCalculationHostedAsset();
        cmsCalculation.customMilestoneCalculation(c.Id, myMilestoneTypeId, true);
        Test.stopTest();
    }
}