src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Record type used for all Customer records.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <description>Support Contact</description>
        <label>Support</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Community_Content__c.object
<CustomObject>
    <fields>
        <fullName>CS_Community__c</fullName>
        <label>Community</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Place</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Content__c</fullName>
        <label>Content</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>CS_Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>R1C1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R1C2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R1C3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R2C1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R2C2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R2C3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R3C1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R3C2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R3C3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R3C3A</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Popup__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Popup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CS_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>URL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Community Content</label>
    <nameField>
        <displayFormat>Content-{00000}</displayFormat>
        <label>Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CommunityContent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CS_Content_Access__c.object
<CustomObject>
    <fields>
        <fullName>CS_Content__c</fullName>
        <label>Content</label>
        <referenceTo>CS_Community_Content__c</referenceTo>
        <relationshipLabel>Content Access</relationshipLabel>
        <relationshipName>Content_Access</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CS_Profile__c</fullName>
        <label>Profile</label>
        <picklist>
            <picklistValues>
                <fullName>GW Partner Community</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GW Customer Community Profile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GW Customer Community</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GW Support/Enablement – Operations/ Lead/Manager</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Content_Access</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Content Access</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Content Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestCS_CommunityContentController.cls
@isTest
public class TestCS_CommunityContentController {
    static User testUser;
    static void setupTestData() {
        testUser = CS_TestDataUtility.createTestUser();
        
        CS_Community_Content__c content= new CS_Community_Content__c();
        content.CS_Community__c = 'Customer';
        content.CS_Content__c = 'Test Community Content';
        content.CS_Location__c = 'R1C3';
        content.CS_Popup__c = true;
        content.CS_Sort_Order__c = 1;
        content.CS_Type__c = 'Text';
        content.CS_Status__c = 'Active';
        insert content;
        
        // query just inserted content
        CS_Community_Content__c insertedContent = [Select Id, Name from CS_Community_Content__c limit 1];
        CS_Content_Access__c access = new CS_Content_Access__c();
        access.CS_Content__c = insertedContent.Id;
        access.CS_User__c = testUser.id;
        access.CS_Profile__c = 'System Administrator';
        
        insert access;
        
    }
    
    static testMethod void testCommunityContent() {
        setupTestData();
        Account acc = CS_TestDataUtility.createCustomerAccount();
        Contact cont = CS_TestDataUtility.createContact(acc, 'Customer Support');
        User currentUsr = [select Id, UserRole.Name from User where Id = :UserInfo.getUserId()];

        System.runAs(testUser) {
        	Test.startTest();
            List<CS_Content_Access__c> contentAccess = CS_CommunityContentController.getContentAccess('R1C3', 'Customer');
            Id currentUser = CS_CommunityContentController.getCurrentUser();
            CS_Community_Content__c content = CS_CommunityContentController.getCommunityContent('R1C3', 'Customer');
            User user = CS_CommunityContentController.getCurrentUserforContent();
            Boolean displaySabaRedirect = CS_CommunityContentController.displaySabaRedirectLink();
            
            User customerCommunityTestUser = CS_TestDataUtility.createCustomerCommunityTestUser(cont);
            System.runAs(customerCommunityTestUser) {
            	String reidrectToSabaUrl = CS_CommunityContentController.redirecttoSabaURL();
            }
            Test.stopTest();
        }
    }
}