src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Products_Purchased__c</fullName>
        <label>Products Purchased</label>
        <picklist>
            <picklistValues>
                <fullName>BillingCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ClaimCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Data Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DataHub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InfoCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MiAgents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Millbrook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile &amp; Portals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PolicyCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rating Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reinsurance Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standards-based Templates</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LatAm</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Record type used for all Partner records.</description>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Forecast_Trending__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount_Converted__c</fullName>
        <label>Amount Converted</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <label>Deal Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Period__c</fullName>
        <label>Fiscal Period</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Forecast_Bucket__c</fullName>
        <label>Forecast Bucket</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Forecast_Category__c</fullName>
        <label>Forecast Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Forecast_Date__c</fullName>
        <label>Forecast Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <label>Opportunity ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Forecast Trending</label>
    <nameField>
        <label>Forecast Trending Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecast Trending</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <label>Deal Type</label>
        <picklist>
            <picklistValues>
                <fullName>Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term with ramp up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term with ramp up and PBO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term with PBO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perpetual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subscription</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fiscal_Period__c</fullName>
        <description>Fiscal Period based on Closed Date of Oppty</description>
        <formula>CASE(MONTH(CloseDate),
1, &quot;Q2&quot; ,
2, &quot;Q3&quot;,
3, &quot;Q3&quot;,
4, &quot;Q3&quot;,
5, &quot;Q4&quot;,
6, &quot;Q4&quot;,
7, &quot;Q4&quot;,
8, &quot;Q1&quot;,
9, &quot;Q1&quot;,
10, &quot;Q1&quot;,
11, &quot;Q2&quot;,
12, &quot;Q2&quot;,
&quot;None&quot;)

&amp; &quot;-&quot;

&amp; IF((MONTH(CloseDate) &gt;= 8 &amp;&amp; MONTH(CloseDate) &lt;= 12),
TEXT (YEAR(CloseDate)+1) ,
TEXT (YEAR(CloseDate))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fiscal Period</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PRM_Referring_Partner2__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Referring Partner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Referring Partner)</relationshipLabel>
        <relationshipName>Opportunities6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Premium_In_Scope__c</fullName>
        <inlineHelpText>This should be the deal premium in scope or the incremental DWP Adjustment. Used in conjunction with Price Rules to calculate the price for certain Products.</inlineHelpText>
        <label>Premium In Scope</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>AMER</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SWOT_Opportunities__c</fullName>
        <description>The Opportunities aspect of the SWOT</description>
        <inlineHelpText>Opportunities EXTERNAL to Guidewire</inlineHelpText>
        <label>Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_SO__c</fullName>
        <inlineHelpText>Strategy for addressing the Opportunities in the context of our Strengths</inlineHelpText>
        <label>Strengths/Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_ST__c</fullName>
        <inlineHelpText>Strategy for addressing the Threats in the context of our Strengths</inlineHelpText>
        <label>Strengths/Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_WO__c</fullName>
        <inlineHelpText>Strategy for addressing Opportunities in the context of our Weaknesses</inlineHelpText>
        <label>Weaknesses/Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_WT__c</fullName>
        <inlineHelpText>Strategy for addressing the Threats in the context of our Weaknesses</inlineHelpText>
        <label>Weaknesses/Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strengths__c</fullName>
        <inlineHelpText>Guidewire Strengths</inlineHelpText>
        <label>Strengths</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Threats__c</fullName>
        <inlineHelpText>Threats external to Guidewire</inlineHelpText>
        <label>Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Weaknesses__c</fullName>
        <inlineHelpText>Guidewire Weaknesses</inlineHelpText>
        <label>Weaknesses</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WhatChangedReportTest.cls
@isTest
class WhatChangedReportTest
{
    static testMethod void testReport()
    {
        List<Profile> lstProfile =[Select Id from Profile 
                                    where profile.userlicense.name = 'Partner Community'];
        
        List<RecordType> lstRecordType = [Select Id from RecordType where Name ='Partner'];
        List<RecordType> lstPartnerOpptyRT = [Select Id from RecordType where Name ='Partner Opportunity'];
        
        Account objAccount = New Account(name='TestProduct',Products_Purchased__c= 'BillingCenter');
        objAccount.RecordTypeId =lstRecordType[0].Id;
        insert objAccount;
        
        Opportunity oppty = new Opportunity(SWOT_Strengths__c='S Value',
                                            SWOT_Weaknesses__c='W Value',
                                            SWOT_Opportunities__c = 'O Value',
                                            SWOT_Threats__c = 'T Value',
                                            SWOT_Strategy_SO__c = 'SO Value',
                                            SWOT_Strategy_ST__c = 'ST Value',
                                            SWOT_Strategy_WO__c = 'WO Value',
                                            SWOT_Strategy_WT__c = 'WT Value',
                                            Name = 'Test SWOT Opportunity',
                                            StageName = 'Qualified',
                                            CloseDate = Date.today(),
                                            Premium_In_Scope__c = 1000,
                                            PRM_Referring_Partner2__c =objAccount.Id,
                                            RecordTypeId =lstPartnerOpptyRT[0].Id,
                                            Amount=100);
        
            Database.saveResult saveResult = Database.insert(oppty, false);
        
        Forecast_Trending__c forecastTestObject = new Forecast_Trending__c();
        forecastTestObject.Name ='testForeCast';
        forecastTestObject.Amount_Converted__c =12345;
        forecastTestObject.Account_Name__c ='tetAccForeCast';
        forecastTestObject.Amount__c =12345;
        forecastTestObject.Billing_Country__c ='testInd';
        forecastTestObject.Deal_Type__c ='ttForeCast';
        forecastTestObject.Fiscal_Period__c ='ttForeCast';
        forecastTestObject.Forecast_Bucket__c ='teForeCast';
        forecastTestObject.Forecast_Category__c ='testForeCast';
        forecastTestObject.Forecast_Date__c =Date.today();
        forecastTestObject.Opportunity_ID__c = oppty.Id;
        forecastTestObject.Opportunity_Name__c = 'testOppty';
        forecastTestObject.Region__c = 'testOppty';
        //insert forecastTestObject;
        
        Forecast_Trending__c forecastTestObjectNew = new Forecast_Trending__c();
        forecastTestObjectNew.Name ='testForeCast';
        forecastTestObjectNew.Amount_Converted__c =12345;
        forecastTestObjectNew.Account_Name__c ='tetAccForeCast';
        forecastTestObjectNew.Amount__c =12345;
        forecastTestObjectNew.Billing_Country__c ='testInd';
        forecastTestObjectNew.Deal_Type__c ='ttForeCast';
        forecastTestObjectNew.Fiscal_Period__c ='ttForeCast';
        forecastTestObjectNew.Forecast_Bucket__c ='teForeCast';
        forecastTestObjectNew.Forecast_Category__c ='Pipeline';
        forecastTestObjectNew.Forecast_Date__c =Date.today() + 1;
        forecastTestObjectNew.Opportunity_ID__c = oppty.Id;
        forecastTestObjectNew.Opportunity_Name__c = 'testOppty';
        forecastTestObjectNew.Region__c = 'EMEA';
        //insert forecastTestObjectNew;
        
        Forecast_Trending__c forecastTestObjectSec = new Forecast_Trending__c();
        forecastTestObjectSec.Name ='testForeCaest';
        forecastTestObjectSec.Amount_Converted__c =123456;
        forecastTestObjectSec.Account_Name__c ='tetAccForeCast';
        forecastTestObjectSec.Amount__c =123456;
        forecastTestObjectSec.Billing_Country__c ='tesetInd';
        forecastTestObjectSec.Deal_Type__c ='ttForeeCast';
        forecastTestObjectSec.Fiscal_Period__c ='tteForeCast';
        forecastTestObjectSec.Forecast_Bucket__c ='ForeCast';
        forecastTestObjectSec.Forecast_Category__c ='Pipeline';
        forecastTestObjectSec.Forecast_Date__c =Date.today() + 2;
        forecastTestObjectSec.Opportunity_ID__c = oppty.Id;
        forecastTestObjectSec.Opportunity_Name__c = 'testOppty';
        forecastTestObjectSec.Region__c = 'APAC';
        //insert forecastTestObjectSec;
        
        Forecast_Trending__c forecastTestObjectApac = new Forecast_Trending__c();
        forecastTestObjectApac.Name ='testForeCast';
        forecastTestObjectApac.Amount_Converted__c =12345;
        forecastTestObjectApac.Account_Name__c ='tetAccForeCast';
        forecastTestObjectApac.Amount__c =12345;
        forecastTestObjectApac.Billing_Country__c ='testInd';
        forecastTestObjectApac.Deal_Type__c ='ttForeCast';
        forecastTestObjectApac.Fiscal_Period__c ='ttForeCast';
        forecastTestObjectApac.Forecast_Bucket__c ='teForeCast';
        forecastTestObjectApac.Forecast_Category__c ='Pipeline';
        forecastTestObjectApac.Forecast_Date__c =Date.today() + 2;
        forecastTestObjectApac.Opportunity_ID__c = oppty.Id;
        forecastTestObjectApac.Opportunity_Name__c = 'testOppty';
        forecastTestObjectApac.Region__c = 'APAC';
        
        Forecast_Trending__c apacForecastTestObj = new Forecast_Trending__c();
        apacForecastTestObj.Name ='testForeCast';
        apacForecastTestObj.Amount_Converted__c =12345;
        apacForecastTestObj.Account_Name__c ='tetAccForeCast';
        apacForecastTestObj.Amount__c =12345;
        apacForecastTestObj.Billing_Country__c ='testInd';
        apacForecastTestObj.Deal_Type__c ='ttForeCast';
        apacForecastTestObj.Fiscal_Period__c ='ttForeCast';
        apacForecastTestObj.Forecast_Bucket__c ='teForeCast';
        apacForecastTestObj.Forecast_Category__c ='Pipeline';
        apacForecastTestObj.Forecast_Date__c =Date.today() - 1;
        apacForecastTestObj.Opportunity_ID__c = oppty.Id;
        apacForecastTestObj.Opportunity_Name__c = 'testOppty';
        apacForecastTestObj.Region__c = 'AMER';
        
        Forecast_Trending__c forecastObj = new Forecast_Trending__c();
        forecastObj.Name ='testForeCast';
        forecastObj.Amount_Converted__c =123435;
        forecastObj.Account_Name__c ='tetAcceForeCast';
        forecastObj.Amount__c =123457;
        forecastObj.Billing_Country__c ='testyInd';
        forecastObj.Deal_Type__c ='ttForeCuast';
        forecastObj.Fiscal_Period__c ='ttForyeCast';
        forecastObj.Forecast_Bucket__c ='teForeCast';
        forecastObj.Forecast_Category__c ='Pipeline';
        forecastObj.Forecast_Date__c =Date.today() - 1;
        forecastObj.Opportunity_ID__c = oppty.Id;
        forecastObj.Opportunity_Name__c = 'testOppty';
        forecastObj.Region__c = 'AMER';
        
        List<Forecast_Trending__c> lstForecastTestObject = new List<Forecast_Trending__c>();
        lstForecastTestObject.add(forecastTestObject);
        lstForecastTestObject.add(apacForecastTestObj);
        lstForecastTestObject.add(forecastTestObjectNew);
        lstForecastTestObject.add(forecastTestObjectSec);
        lstForecastTestObject.add(forecastTestObjectApac);
        lstForecastTestObject.add(forecastObj);
        insert lstForecastTestObject;
        
        WhatChangedReport objWhatChangedReport = new WhatChangedReport();
        objWhatChangedReport.OldDate = Date.today();
        objWhatChangedReport.LatestDate = Date.today();
        objWhatChangedReport.Init();
        objWhatChangedReport.getlstAMERForecastWrapperClass();
        objWhatChangedReport.getlstAMERPipeLineWrapperClass();
        objWhatChangedReport.getlstEMEAForecastWrapperClass();
        objWhatChangedReport.getlstEMEAPipeLineWrapperClass();
        objWhatChangedReport.getlstAPACForecastWrapperClass();
        objWhatChangedReport.getlstAPACPipeLineWrapperClass();
        objWhatChangedReport.getlstWrapData();
        
        delete forecastTestObjectNew;
        objWhatChangedReport.Init();
        
        delete forecastTestObjectSec;
        delete forecastTestObjectApac;
        objWhatChangedReport.Init();
        
        delete apacForecastTestObj;
        delete forecastObj;
        objWhatChangedReport.Init();
    }
}