src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Record type used for all Customer records.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Record type used for all Prospect records.</description>
        <label>Prospect</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>CS_Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>***** Asset  active Status ******</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Record_Type_Name__c</fullName>
        <description>Asset Record Type Name</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CS_Restoration_Milestone_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Mark Restoration Complete</inlineHelpText>
        <label>Restoration Milestone Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Severity_Change_Reason__c</fullName>
        <inlineHelpText>Severity Change Reason</inlineHelpText>
        <label>Severity Change Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Initial severity incorrect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Requested Modification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unresponsive Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect Severity</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Urgency__c</fullName>
        <description>Specify how urgently this particular Issue needs a solution</description>
        <inlineHelpText>Specify how urgently this particular Issue needs a solution</inlineHelpText>
        <label>Urgency</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immediate</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <picklist>
            <controllingField>Asset_Type__c</controllingField>
            <picklistValues>
                <fullName>1-Blocker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2-Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3-Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4-Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1–Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2–Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3–Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4–Cosmetic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <businessProcess>Proposal%2FContract</businessProcess>
        <description>Use this case type to track requests that can’t be defined as proposals or contracts (RFIs, RFPs, Communication, RALs, and EchoSign)</description>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <description>Support Contact</description>
        <label>Support</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Asset_Contact_Permissions__c.object
<CustomObject>
    <label>Asset Contact Permission</label>
    <nameField>
        <label>Product Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Contact Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_ByPass__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>ByPass from Triggers,WF Rules and Validation Rules</description>
    <fields>
        <fullName>CS_Disable_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>ByPass from Trigger</inlineHelpText>
        <label>Disable Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>GW ByPass</label>
</CustomObject>

src/objects/CS_Milestone_Business_Hours__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>**** Service Cloud  Milestone Business Hours ******</description>
    <label>GW Milestone Business Hours</label>
</CustomObject>

src/objects/CS_Request__c.object
<CustomObject>
    <fields>
        <fullName>CS_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CS_is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>Req-{00000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCS_Caseclose_Util.cls
@isTest
public class TestCS_Caseclose_Util {
	static Account customerAcc;
    static Contact customerContact;
    static User currentUsr;
    static Product2 prod;
    static User testUser;
    static CS_Asset_Contact_Permissions__c acp;
    static Entitlement ent;
    static CS_Milestone_Business_Hours__c mbh;
    
    static void setupTestData() {
        // query current test user
        currentUsr = [select Id, UserRole.Name from User where Id = :UserInfo.getUserId()];       
        
        
        // insert bypass custom setting to disable validation rule
        /*
        CS_ByPass__c byPassTrigger = new CS_ByPass__c();
        byPassTrigger.Name = 'CS_Disable_Trigger__c';
        byPassTrigger.CS_Disable_Trigger__c = true;
        byPassTrigger.SetupOwnerId = currentUsr.Id;
        insert byPassTrigger;
        */
        
        prod = CS_TestDataUtility.createProductRecord();
        customerAcc = CS_TestDataUtility.createCustomerAccount();
        customerContact = CS_TestDataUtility.createContact(customerAcc, 'Customer Support');
        // insert parent asset for customer account
        List<Asset> parentAssetsCustomer = CS_TestDataUtility.createParentAssetRecord(customerAcc, true);
            
        // insert child assets
        for (Integer i=0; i < parentAssetsCustomer.size(); i++) {
            if (i < parentAssetsCustomer.size() - 1) {
                CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Prospect');
            } else {
                CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Implementation');
            }
        }
        
         //if (parentAssetsCustomer != null && parentAssetsCustomer.size() > 0) {
             // create acp
            // acp = CS_TestDataUtility.createACP(parentAssetsCustomer[0], customerContact, 'Customer Support', true);
         //}
        
         mbh = CS_TestDataUtility.createMileStoneBusinessHours();
    }
    
    static testMethod void testCloseSTR() {
        setupTestData();
        
        Test.startTest();
        //query asset
        Asset childAsset = [Select Id, CS_Is_Active__c from Asset where CS_Record_Type_Name__c = 'Child Asset' and ParentId != null limit 1];
        // query case record type
        RecordType rt = [Select Name, developername from RecordType where sobjecttype = 'Case' and Name = 'Customer Support'];
        
        List<Case> caseList = new List<Case>();
        Case c = new Case();
        c.AssetId = childAsset.Id;
        c.AccountId = customerAcc.Id;
        c.RecordTypeId = rt.Id;
        c.ContactId = customerContact.Id;
        c.Severity__c = '1-Blocker';
        c.CS_Urgency__c = 'High';
        caseList.add(c);
        insert caseList;
        
        //query case
        Case insertedCase = [Select Id from Case limit 1];
        
        CS_Request__c rq = new CS_Request__c();
        rq.CS_Case__c = insertedCase.Id;
        insert rq;
        
        ent = CS_TestDataUtility.createEntitlement(childAsset, customerAcc);
        
        List<Case> cList = [Select Id from Case];
        Set<Id> caseIds = new Set<Id>();
        for (Case ca : cList) {
            caseIds.add(ca.Id);
        }
       
        CS_Caseclose_Util.CloseSTR(caseIds);
        Test.stopTest();
    }
    
    static testMethod void testCloseCMS() {
        setupTestData();
        
        Test.startTest();
        //query asset
        Asset childAsset = [Select Id, CS_Is_Active__c from Asset where CS_Record_Type_Name__c = 'Child Asset' and ParentId != null limit 1];
        ent = CS_TestDataUtility.createEntitlement(childAsset, customerAcc);
        // query case record type
        RecordType rt = [Select Name, developername from RecordType where sobjecttype = 'Case' and Name = 'Customer Support'];
        
        List<Case> caseList = new List<Case>();
        Case c = new Case();
        c.AssetId = childAsset.Id;
        c.AccountId = customerAcc.Id;
        c.RecordTypeId = rt.Id;
        c.ContactId = customerContact.Id;
        c.Severity__c = '1-Blocker';
        c.CS_Urgency__c = 'High';

        caseList.add(c);
        insert caseList;
        
        ent = CS_TestDataUtility.createEntitlement(childAsset, customerAcc);
        
        //query case
        Integer Before_Milesttone =0;
        Integer After_Milestone;
        Case insertedCase = [Select Id,Status from Case limit 1];
        InsertedCase.Status='Closed';
        Update InsertedCase;
        List<CaseMileStone> cmsList = [Select id from CaseMileStone where CaseId =:InsertedCase.id ];
        //System.assertEquals(Before_Milesttone,After_Milestone,'Case Milestone Not Closed');
        /*
        CS_Request__c rq = new CS_Request__c();
        rq.CS_Case__c = insertedCase.Id;
        insert rq;
 
        List<Case> cList = [Select Id from Case];
        Set<Id> caseIds = new Set<Id>();
        for (Case ca : cList) {
            caseIds.add(ca.Id);
        }
        
        CS_Caseclose_Util.CloseCMS(caseIds);
        */
        Test.stopTest();
    }
    
    static testMethod void testCloseRestorationMS() {
        setupTestData();
        testUser = CS_TestDataUtility.createTestUser();
        System.runAs(testUser) {
             Test.startTest();
           // Map<Id, Case> cIds = new Map<Id, Case>([select id from case]);
            //CS_Caseclose_Util.CloseRestorationMS(cIds.keySet());
            
            //query asset
            Asset childAsset = [Select Id, CS_Is_Active__c from Asset where CS_Record_Type_Name__c = 'Child Asset' and ParentId != null limit 1];
            // query case record type
            RecordType rt = [Select Name, developername from RecordType where sobjecttype = 'Case' and Name = 'Customer Support'];
			
            System.debug('++++++childAsset ' + childAsset.Id);
            ent = CS_TestDataUtility.createEntitlement(childAsset, customerAcc);
            System.debug('++++ent assetId ' + ent.AssetId + 'entitlement Id ' + ent.Id);
            
            List<Case> caseList = new List<Case>();
            Case c = new Case();
            c.AssetId = childAsset.Id;
            c.AccountId = customerAcc.Id;
            c.RecordTypeId = rt.Id;
            c.ContactId = customerContact.Id;
            c.Severity__c = '2-Blocker';
            c.CS_Urgency__c = 'High';
            caseList.add(c);
            insert caseList;
            
            List<Case> caseListToUpdate1 = new List<Case>();
            List<Case> cList1 = [Select Id, AssetId, EntitlementId, BusinessHoursId, CS_Restoration_Milestone_Completed__c from Case];
            Set<Id> caseIds = new Set<Id>();
            for (Case ca : cList1) {
                System.debug('+++++case assetId ' + ca.AssetId + ' | case entitle Id ' + ca.EntitlementId + ' | case businesshours ' + ca.BusinessHoursId);
                caseIds.add(ca.Id);
                ca.Severity__c = '1-Blocker';
                ca.CS_Severity_Change_Reason__c = 'Other';
				//ca.CS_Restoration_Milestone_Completed__c = true;
                caseListToUpdate1.add(ca);
                
            }
            update caseListToUpdate1;
            
            List<Case> caseListToUpdate2 = new List<Case>();
            List<Case> cList2 = [Select Id, AssetId, EntitlementId, BusinessHoursId, CS_Restoration_Milestone_Completed__c from Case];
            Set<Id> caseIds2 = new Set<Id>();
            for (Case ca : cList2) {
                System.debug('+++++case assetId ' + ca.AssetId + ' | case entitle Id ' + ca.EntitlementId + ' | case businesshours ' + ca.BusinessHoursId);
                caseIds2.add(ca.Id);
				ca.CS_Restoration_Milestone_Completed__c = true;
                caseListToUpdate2.add(ca);
                
            }
            update caseListToUpdate2;
            
            
            Map<Id, Case> updateCases = new Map<Id, Case> ([Select Id from Case where CS_Restoration_Milestone_Completed__c = true]);
            
            List<CaseMileStone> cmsList = [select MilestoneType.name,ActualElapsedTimeInDays, ActualElapsedTimeInHrs, ActualElapsedTimeInMins, BusinessHoursId, CaseId, CompletionDate, CreatedById, CreatedDate, ElapsedTimeInDays, ElapsedTimeInHrs, ElapsedTimeInMins, Id, IsCompleted, IsDeleted, IsViolated, LastModifiedById, LastModifiedDate, MilestoneTypeId, StartDate, StoppedTimeInDays, StoppedTimeInHrs, StoppedTimeInMins, SystemModstamp, TargetDate, TargetResponseInDays, TargetResponseInHrs, TargetResponseInMins, TimeRemainingInMins, TimeSinceTargetInMins from CaseMilestone
 where caseId in :caseIds and MilestoneType.name like '%Restoration%'];
            System.debug('cmsList ' + cmsList);
           CS_Caseclose_Util.CloseRestorationMS(caseIds2);
           Test.stopTest();
            
        }
    }
    
}