src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Participant_id__c</fullName>
        <externalId>true</externalId>
        <label>Participant ID</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <label>Payment Term</label>
        <picklist>
            <picklistValues>
                <fullName>Net 30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 90</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pw_cc__BillingCountryLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Country Lookup</label>
        <referenceTo>pw_cc__CountryObject__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Contact__c.object
<CustomObject>
    <description>This object allows tracking of multiple addresses/sites and Contact types.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill To \ Ship To</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bill To\ Ship To</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Participant_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Participant Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Site</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill To \ Ship To - All</relationshipLabel>
        <relationshipName>Account_Contacts1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecordStatus__c</fullName>
        <label>Record Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <label>Account Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Status__c</fullName>
        <label>Renewal Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Notified of Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract reviewed with Mgr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing strategy to Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ops Drafting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed/Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Action Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity from which this Contract was created.</description>
        <inlineHelpText>The Opportunity from which this Contract was created.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pw_cc__BillingCountryLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Country Lookup</label>
        <referenceTo>pw_cc__CountryObject__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CPQ_Wire_Message__c.object
<CustomObject>
    <label>Wire Message</label>
    <nameField>
        <displayFormat>M-{00}</displayFormat>
        <label>Wire Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wire Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Five_Digit_Id__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Current_Value__c</fullName>
        <label>Current Value</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Five Digit Id</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bill_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>As part of Track 3 - user story 4.</description>
        <label>Bill To</label>
        <referenceTo>Account_Contact__c</referenceTo>
        <relationshipLabel>Opportunities (Bill To)</relationshipLabel>
        <relationshipName>Bill_To_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CPQ_Renewal_In_Scope_DWP__c</fullName>
        <inlineHelpText>Used for Renewals only.</inlineHelpText>
        <label>Renewal In-Scope DWP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Net New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net New +</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DWP Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross Sell - Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross Sell - LOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross Sell - Geo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RPI/CPI Increase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer - Acquisition</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Premium_In_Scope__c</fullName>
        <inlineHelpText>This should be the deal premium in scope or the incremental DWP Adjustment. Used in conjunction with Price Rules to calculate the price for certain Products.</inlineHelpText>
        <label>Premium In Scope</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates this opportunity is a renewal opportunity.</description>
        <inlineHelpText>Indicates this opportunity is a renewal opportunity.</inlineHelpText>
        <label>Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewedContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract being renewed by this renewal opportunity. In case opportunity rolls up several contracts this points at the master contract.</description>
        <inlineHelpText>Contract being renewed by this renewal opportunity. If the several contracts roll up to this opportunity, this points at the master contract.</inlineHelpText>
        <label>Renewed Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>RenewalOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Child Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>CPQ_Royalties__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Royalties</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Sign_Date__c</fullName>
        <label>Contract Sign Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__BillingFrequency__c</fullName>
        <description>Defines the billing frequency.</description>
        <globalPicklist>SBQQ__BillingFrequency</globalPicklist>
        <inlineHelpText>Defines the billing frequency.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CPQ_OrderUtilityTest.cls
@isTest
private class CPQ_OrderUtilityTest {

    /**
     * Test method to create Opportunity for Contract test data
     */
    public static Opportunity createOppTestData1(Id accId){

      Opportunity objOpportunity = new Opportunity();
      objOpportunity.Name = 'TestOpportunity';
      objOpportunity.AccountId = accId;
      objOpportunity.StageName = 'Working';
      objOpportunity.CloseDate = System.Date.Today().addDays(15);
      objOpportunity.Opportunity_Type__c = 'Renewal Type';
      objOpportunity.CurrencyIsoCode = 'USD';
      insert objOpportunity;
      return objOpportunity;
    }
    /**
     * Test method to create Contract test data
     */
    public static Contract contractTestData(Id accId, Id oppId) {

      Contract contObj = new Contract();
      contObj.AccountId = accId;
      contObj.Status = 'Draft';
      contObj.CurrencyIsoCode = 'USD';
      contObj.StartDate = System.Today();
      contObj.SBQQ__Opportunity__c = oppId;
      contObj.Renewal_Status__c = 'Not Started ';
      // contObj.Invoice_Date__c = System.Today();
      insert contObj;
      return contObj;
    }

    /**
     * Test method to create Opportunity for Contract test data
     */
    public static Opportunity createOriginalOppTestData(Id accId){

      Opportunity objOpportunity = new Opportunity();
      objOpportunity.Name = 'TestOriginalOpportunity';
      objOpportunity.AccountId = accId;
      objOpportunity.StageName = 'Working';
      objOpportunity.CloseDate = System.Date.Today().addDays(15);
      objOpportunity.CPQ_Renewal_In_Scope_DWP__c = 6000000;
      objOpportunity.Premium_In_Scope__c = 6000000;
      objOpportunity.CurrencyIsoCode = 'USD';
      insert objOpportunity;
      return objOpportunity;
    }

    public static Account_Contact__c createBillToData(Id accId, Id contactId) {
        Five_Digit_Id__c recordCounter = new Five_Digit_Id__c(Current_Value__c = 1);
        insert recordCounter;
        Account_Contact__c billTo = new Account_Contact__c(
            Name = 'Bill To Account',
            RecordStatus__c = 'Active',
            Account__c = accId,
            Contact__c = contactId,
            Participant_Account__c = accId
        );

        insert billTo;
        return billTo;
    }

    /**
     * Test method to create Opportunity test data
     */
    public static Opportunity createOppTestData(Id accId, id oppId) {
            Contract contObj = contractTestData(accId, oppId);

            Contact objCon = new Contact(
                LastName = 'Test Contact',
                Email = 'test@contact.com'
            );
            insert objCon;

            Opportunity objOpportunity = new Opportunity();
            objOpportunity.pse__Parent_Opportunity__c = oppId;
            objOpportunity.Name = 'TestOpportunity';
            objOpportunity.AccountId = accId;
            objOpportunity.StageName = 'Working';
            objOpportunity.CloseDate = System.Date.Today().addDays(15);
            objOpportunity.Opportunity_Type__c = 'Net New +';
            objOpportunity.SBQQ__Renewal__c = true;
            objOpportunity.SBQQ__RenewedContract__c = contObj.Id;
            objOpportunity.CurrencyIsoCode = 'USD';
            objOpportunity.Bill_To__c = createBillToData(accId, objCon.Id).Id;

            insert objOpportunity;
            return objOpportunity;
    }

    /**
     * Test method to create SBQQ__Quote__c test data
     */
    public static SBQQ__Quote__c createQuoteTestData(Id oppId) {

            SBQQ__Quote__c objQuote = new SBQQ__Quote__c();
            objQuote.SBQQ__Opportunity2__c = oppId;
            objQuote.SBQQ__Primary__c = true;
            objQuote.CPQ_In_Scope_DWP_Input__c = 2;
            objQuote.CPQ_In_Scope_DWP_Input_Type__c = 'Direct DWP';
            objQuote.SBQQ__BillingFrequency__c = 'Monthly';
            objQuote.SBQQ__StartDate__c = System.Today();
            objQuote.SBQQ__SubscriptionTerm__c = 6;
            objQuote.SBQQ__Type__c = 'Quote';
            objQuote.CPQ_Royalties__c = false;
            //objQuote.CurrencyIsoCode = 'USD';
            //objAccount.Email = strEmail;
            //objAccount.Company = 'TestCompany';
            insert objQuote;
            return objQuote;
    }

    /**
     * Test method to check Order creation with WireMessage IsCompany = true
     */
    @isTest static void test_createOrder() {

           // insert account
           Account objAcc = CPQ_TestDataUtility.accountTestData(false);
           objAcc.Participant_id__c = '1378';
           objAcc.Payment_Term__c = 'Net 30';
           insert objAcc ;
           system.debug('Created Account: ' + objAcc);

           Opportunity originalOpp = createOriginalOppTestData(objAcc.Id);
           system.debug('Created Original Opp: ' + originalOpp);
           Opportunity objOpportunity = createOppTestData(objAcc.Id, originalOpp.Id);
           system.debug('Created Opportunity: ' + objOpportunity);
           SBQQ__Quote__c objQuote = createQuoteTestData(objOpportunity.Id);
           system.debug('Created Quote: ' + objQuote);
           List<sObject> testDataOfWireMessages = Test.loadData(CPQ_Wire_Message__c.sObjectType, 'CPQ_TestDataWireMessage');
           // Verify that all 3 test accounts were created
           //System.assert(testDataOfWireMessages.size() == 1);
           List<Order> lstOrder = [Select Id From Order];
           system.assertEquals(0,lstOrder.size());
           system.debug('Verify there was no Order so far');

           Test.startTest();
                //Id oppId,Id primaryQuoteId,Id accId,String basecurr,String l_classid
                String returned = CPQ_OrderUtility.createOrder(objOpportunity.Id,objQuote.Id,objAcc.Id,'USD');
                System.debug('------ returned ------ : ' + returned);
           Test.stopTest();
           List<Order> lstOrderInserted = [Select Id,SBQQ__Quote__c,Is_Primary__c,Status,Pricebook2Id,Contract_Sign_Date__c  From Order];
           system.assertNotEquals(null,lstOrder);
           system.assertEquals(objQuote.ID,lstOrderInserted[0].SBQQ__Quote__c );
           system.assertEquals(true,lstOrderInserted[0].Is_Primary__c );
           system.assertEquals('Draft',lstOrderInserted[0].Status);
           system.assertEquals(Test.getStandardPricebookId(),lstOrderInserted[0].Pricebook2Id);
           system.assertEquals(Date.today(),lstOrderInserted[0].Contract_Sign_Date__c );
    }

    /**
     * Test method to check Order record creation with Existing Order record
     */
    @isTest static void test_createOrderWithExistingOrder() {

        List<sObject> countryCode = Test.loadData(pw_cc__CountryObject__c.sObjectType, 'CPQ_TestDataCountryObject');
        pw_cc__CountryObject__c countryObj = (pw_cc__CountryObject__c)countryCode[2];

           // insert account
           Account objAcc = CPQ_TestDataUtility.accountTestData(false);
           objAcc.Participant_id__c = '1378';
           insert objAcc ;

           Opportunity originalOpp = createOriginalOppTestData(objAcc.Id);

           Contract contObj = contractTestData(objAcc.Id, originalOpp.Id);
           contObj.AccountId  = objAcc.ID;
           update contObj;

           Opportunity objOpportunity = createOppTestData(objAcc.Id, originalOpp.Id);
           SBQQ__Quote__c objQuote = createQuoteTestData(objOpportunity.Id);
           List<sObject> testDataOfWireMessages = Test.loadData(CPQ_Wire_Message__c.sObjectType, 'CPQ_TestDataWireMessage');
           // Verify that all 3 test accounts were created
           //System.assert(testDataOfWireMessages.size() == 1);
           List<Order> lstOrder = [Select Id From Order];
           system.assertEquals(0,lstOrder.size());

           Order orderObj = new Order();
           orderObj.AccountID = objAcc .ID;
           orderObj.EffectiveDate = System.TODAY();
           orderObj.CurrencyIsoCode = 'USD';
           orderObj.ContractID = contObj.ID;
           orderObj.Status = 'Draft';
           orderObj.OpportunityID =objOpportunity.ID;
           orderObj.Is_Primary__c = true;
           insert  orderObj ;

           Test.startTest();
               //Id oppId,Id primaryQuoteId,Id accId,String basecurr,String l_classid
               CPQ_OrderUtility.createOrder(objOpportunity.Id,objQuote.Id,objAcc.Id,'USD');
           Test.stopTest();
           List<Order> lstOrderInserted = [Select Id,SBQQ__Quote__c,Is_Primary__c,Status,Pricebook2Id,Contract_Sign_Date__c,CreatedDate
                                           From Order
                                           Order By CreatedDate  asc];
           system.assertNotEquals(null,lstOrder);
           system.assertEquals(objQuote.ID,lstOrderInserted[0].SBQQ__Quote__c );
           system.assertEquals(false,lstOrderInserted[0].Is_Primary__c );
           system.assertEquals('Draft',lstOrderInserted[0].Status);
           system.assertEquals(Test.getStandardPricebookId(),lstOrderInserted[1].Pricebook2Id);
           system.assertEquals(Date.today(),lstOrderInserted[1].Contract_Sign_Date__c );
    }

    /**
     * Test method to check Order creation With WireMessage isCompany=false
     */
    @isTest public static void test_createOrderWithOutCompanyWireMessage() {

              List<sObject> countryCode = Test.loadData(pw_cc__CountryObject__c.sObjectType, 'CPQ_TestDataCountryObject');
              pw_cc__CountryObject__c countryObj = (pw_cc__CountryObject__c)countryCode[2];

               // insert account
               Account objAcc = new Account();
               objAcc.Name = 'TestAcc';
               objAcc.pw_cc__BillingCountryLookup__c = countryObj.ID;
               objAcc.Participant_id__c = '1234';
               insert  objAcc;

               Contact contObj = new Contact();
               contObj.LastName = 'testcontact';
               contObj.Email = 'test@testorg.com';
               insert contObj;

               Account accObject = CPQ_TestDataUtility.accountTestData(false);
               accObject.Participant_id__c = '2351';
               insert accObject;
               system.debug('Created Account: ' + accObject);

               Account_Contact__c accContactObj = new Account_Contact__c();
               accContactObj.Name = 'testing';
               accContactObj.Contact__c =contObj.ID;
               accContactObj.Participant_Account__c = objAcc.ID;
               accContactObj.Account__c=accObject.ID;
               insert accContactObj;

               Opportunity originalOpp = createOriginalOppTestData(accObject.Id);
               system.debug('Created Original Opp: ' + originalOpp);

               Contract contractObj = contractTestData(accObject.Id, originalOpp.Id);
               system.debug('Created Contract: ' + contractObj);
               //Opportunity objOpportunity = CPQ_TestDataUtility.opportunityTestData(objAcc.Id,contractObj.ID,false);
               Opportunity objOpportunity = createOppTestData(accObject.Id, originalOpp.Id);
               system.debug('Created Opp: ' + objOpportunity);
               objOpportunity.Bill_To__c = accContactObj.ID;
               update  objOpportunity;
               system.debug('Updated Opp: ' + objOpportunity);

               SBQQ__Quote__c objQuote = createQuoteTestData(objOpportunity.Id);
               system.debug('Created Quote: ' + objQuote);
               List<sObject> testDataOfWireMessages = Test.loadData(CPQ_Wire_Message__c.sObjectType, 'CPQ_TestDataWireMessage');
               // Verify that all 3 test accounts were created
               //System.assert(testDataOfWireMessages.size() == 1);
               List<Order> lstOrder = [Select Id From Order];
               system.assertEquals(0,lstOrder.size());

               Test.startTest();
                   //Id oppId,Id primaryQuoteId,Id accId,String basecurr,String l_classid
                   CPQ_OrderUtility.createOrder(objOpportunity.Id,objQuote.Id,accObject.Id,'USD');
               Test.stopTest();
               List<Order> lstOrderInserted = [Select Id,SBQQ__Quote__c,Is_Primary__c,Status,Pricebook2Id,Contract_Sign_Date__c  From Order];
           system.assertNotEquals(null,lstOrder);
           system.assertEquals(objQuote.ID,lstOrderInserted[0].SBQQ__Quote__c );
           system.assertEquals(true,lstOrderInserted[0].Is_Primary__c );
           system.assertEquals('Draft',lstOrderInserted[0].Status);
           system.assertEquals(Test.getStandardPricebookId(),lstOrderInserted[0].Pricebook2Id);
           system.assertEquals(Date.today(),lstOrderInserted[0].Contract_Sign_Date__c );

        }

        /**
         * Test method to check Order creation With Currency = EUR
         */
        @isTest public static void test_createOrderWithCurrencyEURWireMessage() {

              List<sObject> countryCode = Test.loadData(pw_cc__CountryObject__c.sObjectType, 'CPQ_TestDataCountryObject');
              pw_cc__CountryObject__c countryObj = (pw_cc__CountryObject__c)countryCode[2];

               // insert account
               Account objAcc = new Account();
               objAcc.Name = 'TestAcc';
               objAcc.pw_cc__BillingCountryLookup__c = countryObj.ID;
               objAcc.Participant_id__c = '1234';
               insert  objAcc;

               Contact contObj = new Contact();
               contObj.LastName = 'testcontact';
               contObj.Email = 'test@testorg.com';
               insert contObj;

               Account accObject = CPQ_TestDataUtility.accountTestData(true);

               Account_Contact__c accContactObj = new Account_Contact__c();
               accContactObj.Name = 'testing';
               accContactObj.Contact__c =contObj.ID;
               accContactObj.Participant_Account__c = objAcc.ID;
               accContactObj.Account__c=accObject.ID;
               insert accContactObj;

               Opportunity originalOpp = createOriginalOppTestData(objAcc.Id);

               Contract contractObj = contractTestData(objAcc.Id, originalOpp.Id);
               Opportunity objOpportunity = CPQ_TestDataUtility.opportunityTestData(objAcc.Id,contractObj.ID,false);
               objOpportunity.Bill_To__c = accContactObj.ID;
               insert  objOpportunity;

               SBQQ__Quote__c objQuote = createQuoteTestData(objOpportunity.Id);
               List<sObject> testDataOfWireMessages = Test.loadData(CPQ_Wire_Message__c.sObjectType, 'CPQ_TestDataWireMessage');
               // Verify that all 3 test accounts were created
               //System.assert(testDataOfWireMessages.size() == 1);
               List<Order> lstOrder = [Select Id From Order];
               system.assertEquals(0,lstOrder.size());

               Test.startTest();
                   //Id oppId,Id primaryQuoteId,Id accId,String basecurr,String l_classid
                   CPQ_OrderUtility.createOrder(objOpportunity.Id,objQuote.Id,objAcc.Id,'EUR');
               Test.stopTest();
               List<Order> lstOrderInserted = [Select Id,SBQQ__Quote__c,Is_Primary__c,Status,Pricebook2Id,Contract_Sign_Date__c  From Order];
           system.assertNotEquals(null,lstOrder);
           system.assertEquals(objQuote.ID,lstOrderInserted[0].SBQQ__Quote__c );
           system.assertEquals(true,lstOrderInserted[0].Is_Primary__c );
           system.assertEquals('Draft',lstOrderInserted[0].Status);
           system.assertEquals(Test.getStandardPricebookId(),lstOrderInserted[0].Pricebook2Id);
           system.assertEquals(Date.today(),lstOrderInserted[0].Contract_Sign_Date__c );
        }


}