src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Record type used for all Customer records.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>CS_Pri_Supp_Org__c</fullName>
        <label>Primary Support Org</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting Enablement Group</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Primary_Supp_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pri. Support Partner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assets6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CS_Support_Group__c</fullName>
        <label>Support Group</label>
        <picklist>
            <picklistValues>
                <fullName>Policy System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claim System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Predictive Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Portals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GW Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cognos</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CS_Associated_Jira__c</fullName>
        <description>**Please enter multiple Jira separated by comma and no space should be left in between.</description>
        <inlineHelpText>**Please enter multiple Jira seperated by comma and no space should be left in between.</inlineHelpText>
        <label>Associated Jira</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Disposition__c</fullName>
        <label>Disposition</label>
        <picklist>
            <picklistValues>
                <fullName>Perf issue diagnosed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer to change configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer lacks product knowledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer not following best practices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance practices not followed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workaround suggested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product issue with no workaround</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need KB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need Tech Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation issue, high level direction provided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation issue, beyond scope of Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suggested Guidewire Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue outside of Guidewire product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accelerator issue with product issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accelerator issue and not product issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diagnostic patch used</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Root cause found</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Root cause not found</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outside Product Support Matrix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs internal escalation to CIM/CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doc. JIRA Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Platform JIRA Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bug JIRA Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Platform Gap JIRA Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation Direction Provided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Provided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functionality Clarified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Could Not Reproduce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Closed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>CS_ODC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>On Demand Consulting</description>
        <label>ODC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Owner_Team__c</fullName>
        <formula>IF( ISBLANK(Owner:User.Id),  CASE( Owner:Queue.QueueName , 
                                   	&apos;Support&apos;, &apos;Support&apos;,
                                        &apos;Implementation Queue&apos;, &apos;Enablement Queue&apos;,
&apos;ODC&apos;,&apos;ODC&apos;,
                                        &apos;Other&apos;) ,
                             TEXT(Owner:User.CS_User_Team__c) )</formula>
        <label>Owner Team</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Platform_Issue__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Platform Issue</description>
        <label>Platform Issue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Submitted_as_KB_Article__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submitted as KB Article</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Support_Group__c</fullName>
        <formula>TEXT(Asset.CS_Support_Group__c )</formula>
        <label>Support Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <picklist>
            <controllingField>Asset_Type__c</controllingField>
            <picklistValues>
                <fullName>1-Blocker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2-Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3-Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4-Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1–Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2–Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3–Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4–Cosmetic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Working_Days__c</fullName>
        <description>Working day calculation, counts the days in between the case created and case closed dates. Included the create date and closed date into count.</description>
        <formula>CASE( 
MOD( DateValue(CreatedDate) - DATE(1985,6,24),7), 

0 , CASE( MOD( Datevalue(ClosedDate) - DateValue(CreatedDate) ,7),1,2,2,3,3,4,4,5,5,5,6,5,1), 
1 , CASE( MOD( Datevalue(ClosedDate) - DateValue(CreatedDate),7),1,2,2,3,3,4,4,4,5,4,6,5,1), 
2 , CASE( MOD( Datevalue(ClosedDate) - DateValue(CreatedDate) ,7),1,2,2,3,3,3,4,3,5,4,6,5,1), 
3 , CASE( MOD( Datevalue(ClosedDate) - DateValue(CreatedDate) ,7),1,2,2,2,3,2,4,3,5,4,6,5,1), 
4 , CASE( MOD( Datevalue(ClosedDate) - DateValue(CreatedDate) ,7),1,1,2,1,3,2,4,3,5,4,6,5,1), 
5 , CASE( MOD( Datevalue(ClosedDate) - DateValue(CreatedDate),7),1,0,2,1,3,2,4,3,5,4,6,5,0), 
6 , CASE( MOD( Datevalue(ClosedDate) - DateValue(CreatedDate) ,7),1,1,2,2,3,3,4,4,5,5,6,5,0), 
999) 
+ 
(FLOOR(( Datevalue(ClosedDate) - DateValue(CreatedDate) )/7)*5)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Working Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <description>Support Contact</description>
        <label>Support</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Request__c.object
<CustomObject>
    <fields>
        <fullName>CS_Associated_Jira__c</fullName>
        <formula>CS_Case__r.CS_Associated_Jira__c</formula>
        <label>Associated Jira</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>Req-{00000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>CS_User_Team__c</fullName>
        <label>User Team</label>
        <picklist>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enablement-SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enablement-CE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enablement-Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CS_DevRequestReport.cls
/*
    *****************************************************************************************************************************
    Class Name - CS_DevRequestReport
    Class Type - Class to support VF Page CS_DevRequestReport 
    Test Class- CS_DevRequestReportTes
    Purpose- 
    
    *****************************************************************************************************************************
    
    Name        Email              Date             Notes 
    Suchitra                                        Initial Creation
    
    *****************************************************************************************************************************
 */

public class CS_DevRequestReport{

    public PageReference sendDates() {
        return null;
      }   
    public Date endDate { get; set; }
    public Date startDate { get; set; }

  
    public PageReference processRequests() {
        
        return null;
    }
     
    public List<wrapCasewithDevRequest> caseList{
            
                get {
                
                if (startDate != Null && endDate != Null){
                List<wrapCasewithDevRequest> lstWrapCase = new List<wrapCasewithDevRequest>();
                if (caseList== null) {
                String[] ownerTeamlist = new String[]{'Enablement Queue','Enablement-CE','Enablement-SE'};
                //Get the list of cases. 
                List<case> caseData = [Select  
                                            ID, 
                                            CaseNumber,
                                            Owner.Id,
                                            LastModifiedDate, 
                                            Owner.Name, 
                                            CS_Support_Group__c,
                                            Severity__c,
                                            Contact.Id,
                                            CS_Owner_Team__c,
                                            Contact.Name,
                                            Subject, 
                                            OwnerID, 
                                            Asset.ParentID,
                                            Asset.ID, 
                                            Asset.Name,
                                            Asset.Product2.Name,
                                            CreatedDate,
                                            ClosedDate,
                                            Status,
                                            CS_Disposition__c,
                                            CS_Platform_Issue__c,
                                            Working_Days__c,
                                            CS_Associated_Jira__c,
                                            Contact.Account.Name, 
                                            Contact.Account.RecordType.Name,
                                            Asset.Parent.Name, 
                                            Asset.Parent.Product2.Name, 
                                            Asset.CS_Primary_Supp_Partner__r.email, 
                                            Asset.CS_Primary_Supp_Partner__r.CS_User_Team__c,
                                            Asset.CS_Primary_Supp_Partner__r.Name,  
                                            Asset.CS_Pri_Supp_Org__c,
                    (SELECT Id,RecordType.Name,CreatedDate FROM Requests__r Where RecordType.Name ='Dev Request' OR RecordType.Name ='Enablement Request') FROM CASE WHERE ((ClosedDate >=:startDate OR ClosedDate =NULL) AND CreatedDate<=:endDate) AND (RecordType.Name=:'Customer Support' AND CS_ODC__c =:false ) AND  CS_Owner_Team__c in:ownerTeamlist AND CS_Submitted_as_KB_Article__c=:false ORDER BY CreatedDate ASC LIMIT 10000];
                    for (case caseRec:caseData){
                                  
                    
                     List<CS_Request__c> csRequestList = caseRec.Requests__r;
                     integer csDevRequestSize = 0;
                     integer csEnableRequestSize = 0;
                     
                     //If the Case has case team members, parse through and build the tags. 
                     if (csRequestList != NULL){
                         for (CS_Request__c csReq:csRequestList )
                          if (csReq.RecordType.Name == 'Dev Request'){
                             if (csReq.CreatedDate>=startDate && csReq.CreatedDate<=endDate)
                             {
                             csDevRequestSize ++;
                             }
                         }
                         else if (csReq.RecordType.Name == 'Enablement Request'){
                             csEnableRequestSize ++;
                         }
                      }
                      String closedateFormated = '';
                      boolean isEnablementReq = false; 
                      if (csEnableRequestSize >0){
                          isEnablementReq = true;
                      }
                      if ( caseRec.ClosedDate != NULL){
                          closedateFormated = caseRec.ClosedDate.format();
                      }
                      boolean isPartnerOrganization = false;
                      if (caseRec.Asset.CS_Primary_Supp_Partner__r != NULL){
                          if (!caseRec.Asset.CS_Primary_Supp_Partner__r.email.contains('guidewire.com')){
                          isPartnerOrganization =true;}
                      }
                     
                      wrapCasewithDevRequest wrapCase1 = new wrapCasewithDevRequest(caseRec,csDevRequestSize,isEnablementReq, caseRec.CreatedDate.format(),closedateFormated,isPartnerOrganization );
                      lstWrapCase.add(wrapCase1);
                   
                }
               }
           return lstWrapCase ;
        }
        return null;
        }
        set;
    }
      

         public class wrapCasewithDevRequest {
    
            public case caseRecord {get; set;}
            public integer countDevReq {get;set;}
            public boolean isEnableReq  {get;set;}
            public String createdDateFormated{get;set;}
            public String caseClosedDateFormated{get;set;}
            public boolean isPartnerCase  {get;set;}
     
            public wrapCasewithDevRequest (Case caseRecord, integer countDevReq, boolean countEnableReq,String createdDateFormated, String caseClosedDateFormated, boolean isPartnerCase) {
                this.caseRecord = caseRecord;
                this.countDevReq = countDevReq;
                this.isEnableReq = countEnableReq;
                
                this.createdDateFormated = createdDateFormated;
                this.caseClosedDateFormated= caseClosedDateFormated;
                this.isPartnerCase = isPartnerCase;
               
            }
        }
       
    }