src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Buying_Entity__c</fullName>
        <inlineHelpText>Whether, in our judgment, this entity makes independent decisions about system purchases (as opposed to a subsidiary that has no operational distinction from its parent).</inlineHelpText>
        <label>Buying Entity</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t Know</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Record type used for all Customer records.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Record type used for all Partner records.</description>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Customer_Commitment__c.object
<CustomObject>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <inlineHelpText>This should only be set if the person is in front of the customer for a different number of hours than the hours specified on the event.</inlineHelpText>
        <label>Event Hours (Partial)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Event__c</fullName>
        <label>Sales Event</label>
        <referenceTo>Sales_Event__c</referenceTo>
        <relationshipLabel>Customer Commitments</relationshipLabel>
        <relationshipName>Customer_Commitments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Who__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Commitments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Commitment</label>
    <nameField>
        <label>Customer Commitment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Commitments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Demo_Team__c.object
<CustomObject>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Event__c</fullName>
        <label>Sales Event</label>
        <referenceTo>Sales_Event__c</referenceTo>
        <relationshipLabel>Demo Teams</relationshipLabel>
        <relationshipName>Demo_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Demo Team</label>
    <nameField>
        <label>Demo Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Event_Possible_Date__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <label>Event Hours</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Event__c</fullName>
        <label>Sales Event</label>
        <referenceTo>Sales_Event__c</referenceTo>
        <relationshipLabel>Possible Dates</relationshipLabel>
        <relationshipName>Possible_Dates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Possible</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Possible Date</label>
    <nameField>
        <label>Possible Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Possible Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PRM_Referring_Partner2__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Referring Partner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Referring Partner)</relationshipLabel>
        <relationshipName>Opportunities6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Premium_In_Scope__c</fullName>
        <inlineHelpText>This should be the deal premium in scope or the incremental DWP Adjustment. Used in conjunction with Price Rules to calculate the price for certain Products.</inlineHelpText>
        <label>Premium In Scope</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SWOT_Opportunities__c</fullName>
        <description>The Opportunities aspect of the SWOT</description>
        <inlineHelpText>Opportunities EXTERNAL to Guidewire</inlineHelpText>
        <label>Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_SO__c</fullName>
        <inlineHelpText>Strategy for addressing the Opportunities in the context of our Strengths</inlineHelpText>
        <label>Strengths/Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_ST__c</fullName>
        <inlineHelpText>Strategy for addressing the Threats in the context of our Strengths</inlineHelpText>
        <label>Strengths/Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_WO__c</fullName>
        <inlineHelpText>Strategy for addressing Opportunities in the context of our Weaknesses</inlineHelpText>
        <label>Weaknesses/Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_WT__c</fullName>
        <inlineHelpText>Strategy for addressing the Threats in the context of our Weaknesses</inlineHelpText>
        <label>Weaknesses/Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strengths__c</fullName>
        <inlineHelpText>Guidewire Strengths</inlineHelpText>
        <label>Strengths</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Threats__c</fullName>
        <inlineHelpText>Threats external to Guidewire</inlineHelpText>
        <label>Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Weaknesses__c</fullName>
        <inlineHelpText>Guidewire Weaknesses</inlineHelpText>
        <label>Weaknesses</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Preparation__c.object
<CustomObject>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Event__c</fullName>
        <label>Sales Event</label>
        <referenceTo>Sales_Event__c</referenceTo>
        <relationshipLabel>Preparations</relationshipLabel>
        <relationshipName>Preparations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Who__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Preparations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Preparation</label>
    <nameField>
        <label>Preparation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preparations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Event Hours</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Events</relationshipLabel>
        <relationshipName>Sales_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Tentative</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Event_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Event__c</fullName>
        <label>Sales Event</label>
        <referenceTo>Sales_Event__c</referenceTo>
        <relationshipLabel>Sales Event Feedbacks</relationshipLabel>
        <relationshipName>Sales_Event_Feedbacks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Event Feedback</label>
    <nameField>
        <displayFormat>SEF-{0000}</displayFormat>
        <label>Sales Event Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Event Feedbacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestSalesEventController.cls
@isTest(seeAllData=true)
private class TestSalesEventController {

    static testMethod void validateController() {
        Id recordId = [Select Id from RecordType Where Name ='Partner' AND sObjectType='Account' limit 1].Id;
        system.debug('==****'+recordId);
        Account account = new Account();
        account.RecordTypeId = recordId;
        system.debug('=='+account.RecordType);
        account.Name = 'testAcc';
        account.Type = 'Other';
        account.Buying_Entity__c = 'Yes';
        account.Industry = 'Other';
        insert account;
        
        system.debug('==****'+account);
        
        Opportunity o = new Opportunity(SWOT_Strengths__c='S Value',
                                        SWOT_Weaknesses__c='W Value',
                                        SWOT_Opportunities__c = 'O Value',
                                        SWOT_Threats__c = 'T Value',
                                        SWOT_Strategy_SO__c = 'SO Value',
                                        SWOT_Strategy_ST__c = 'ST Value',
                                        SWOT_Strategy_WO__c = 'WO Value',
                                        SWOT_Strategy_WT__c = 'WT Value',
                                        Name = 'Test SWOT Opportunity',
                                        StageName = 'Qualified',
                                        CloseDate = Date.today(),
                                        Premium_In_Scope__c = 1000,
                                //      PRM_Referring_Partner2__c = account.Id,
                                        Amount=100   );
        insert o;
        
        
        Sales_Event__c event = new Sales_Event__c(Opportunity__c = o.Id, Status__c = 'Tentative');
        insert event;
        
        Event_Possible_Date__c pDate = new Event_Possible_Date__c (Name = 'Possible date test 1',
                                              Sales_Event__c = event.Id,
                                              Event_Hours__c = 5,
                                              Start_Date__c = Date.today().addDays(-3),
                                              End_Date__c = Date.today().addDays(-2)
                                              );
        
        insert pDate ;
        
         Customer_Commitment__c commitment = new Customer_Commitment__c(Name = 'Customer Commitment Test 1',
                                                                       Sales_Event__c = event.Id,
                                                                       Who__c = UserInfo.getUserId()
                                                                      );
                                                                      
        insert commitment;        
        
        Preparation__c prep = new Preparation__c(Name = 'Prep test 1',
                                              Sales_Event__c = event.Id,
                                              Who__c = UserInfo.getUserId()
                                              );
        
        insert prep;
        
        Demo_Team__c team = new Demo_Team__c(Name = 'Prep test 1',
                                              Sales_Event__c = event.Id,
                                              hours__c =10
                                              );
        
        insert team;
        
        
        Sales_Event_Feedback__c salesEventFeedback = new Sales_Event_Feedback__c();
        salesEventFeedback.Sales_Event__c = event.Id;
        insert salesEventFeedback;
        
        test.startTest();
        //SalesEventController
        ApexPages.StandardController controller = new ApexPages.StandardController(event);
        //put in ID so the controller has data
        PageReference pageRef = Page.SalesEvent;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', event.Id);
        //SalesEventController objExistingController = new SalesEventController();
        SalesEventController theExistingController = new SalesEventController(controller);
        theExistingController.strdelsaleseventfeedbackId =salesEventFeedback.Id;
        theExistingController.DeleteSaleEventFeedback();
        theExistingController.getlstSalesEventFeedback();
        //theExistingController.aId =salesEventFeedback.Id;
        //SalesEventController objExistingController = new SalesEventController(controller);
        
        //reloadEvent
        
        theExistingController.thisEvent = event;        
        //cancel
        theExistingController.cancel();
        //
        theExistingController.reloadEvent();
        
        //save
        theExistingController.save();

        System.assertEquals(theExistingController.thisEvent.Status__c , 'Tentative');
        //getCustomerCommitmentsList
        System.assertEquals(theExistingController.getCustomerCommitmentsList().size(), 1);

        //getPreparationsList
        System.assertEquals(theExistingController.getPreparationsList().size(), 1);
        
        //getDemoTeamsList
        System.assertEquals(theExistingController.getDemoteamsList().size(), 1);
        
        //getAllPossibleDatesList
        System.assertEquals(theExistingController.getAllPossibleDatesList().size(), 1);

        //static selectDate(String dateID, String eventID)
        SalesEventController.selectDate('' + pDate.Id, '' + theExistingController.thisEvent.Id);
        
        //static requestReview(String eventID)
        SalesEventController.requestReview(theExistingController.thisEvent.Id,'This is a test message');

        //static deleteCommitment(String commitID, String eventID)
        SalesEventController.deleteCommitment('' + commitment.Id, '' + theExistingController.thisEvent.Id);
        
        //static deletePreparation(String prepID, String eventID)
        SalesEventController.deletePreparation('' + prep.Id, '' + theExistingController.thisEvent.Id);
        
        //static deleteDemoteam(String TeamID, String eventID)
        SalesEventController.deleteDemoTeam('' + team.Id, '' + theExistingController.thisEvent.Id);

        
        theExistingController.reloadEvent();
        //System.assertEquals(theExistingController.thisEvent.Status__c , 'Confirmed');
        System.assertEquals(theExistingController.getPreparationsList().size(), 0);
        System.assertEquals(theExistingController.getAllPossibleDatesList().size(), 1);
        theExistingController.openFeedbackPage();
        theExistingController.getIsSalesOrPresalesManager();
        theExistingController.getIsPresalesManager();
        //SalesEventController.getIdOfAnnouncmentUser();
        Test.setCurrentPageReference(new PageReference('SalesEvent')); 
        System.currentPageReference().getParameters().put('id', account.Id);
        
        Test.setCurrentPageReference(new PageReference('SalesEvent'));
        System.currentPageReference().getParameters().put('id', salesEventFeedback.Id);
        SalesEventController existingController = new SalesEventController(controller);
        //ApexPages.currentPage().getParameters().put('id', salesEventFeedback.Id);
        //SalesEventController theExistingController = new SalesEventController(controller);

//        System.assertEquals('/apex/SWOT', nextPage);
       test.stopTest();
    }
}