src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LatAm</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Premium_In_Scope__c</fullName>
        <inlineHelpText>This should be the deal premium in scope or the incremental DWP Adjustment. Used in conjunction with Price Rules to calculate the price for certain Products.</inlineHelpText>
        <label>Premium In Scope</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>AMER</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Possible_Date__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <label>Event Hours</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Resource_Request__c</fullName>
        <label>Resource Request</label>
        <referenceTo>ResourceRequest__c</referenceTo>
        <relationshipLabel>Possible Dates</relationshipLabel>
        <relationshipName>Possible_Dates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Possible</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Possible Date</label>
    <nameField>
        <label>Possible Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Possible Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Resource_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Resource_Request__c</fullName>
        <label>Resource Request</label>
        <referenceTo>ResourceRequest__c</referenceTo>
        <relationshipLabel>Resource Assignments</relationshipLabel>
        <relationshipName>Resource_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Resource_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Resource Role</label>
        <referenceTo>Resource_Role__c</referenceTo>
        <relationshipLabel>Resource Assignments</relationshipLabel>
        <relationshipName>Resource_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Filled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Resource Assignment</label>
    <nameField>
        <label>Resource Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Resource_Hold__c.object
<CustomObject>
    <description>Used to indicate on a resource request that a specific person will likely be on this event.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resource_Request__c</fullName>
        <label>Resource Request</label>
        <referenceTo>ResourceRequest__c</referenceTo>
        <relationshipLabel>Resource Holds</relationshipLabel>
        <relationshipName>Resource_Holds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Who__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Resource_Holds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource Hold</label>
    <nameField>
        <label>Resource Hold Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Holds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Resource_Role__c.object
<CustomObject>
    <fields>
        <fullName>Resource_Request__c</fullName>
        <label>Resource Request</label>
        <referenceTo>ResourceRequest__c</referenceTo>
        <relationshipLabel>Resource Roles</relationshipLabel>
        <relationshipName>Resource_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>BillingCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Intelligence for InsuranceSuite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ClaimCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Data Managment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Portals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISO Templates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PolicyCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Predictive Analytics for Claims</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Predictive Analytics for Profitability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Predictive Analytics Model Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Predictive Analytics Scoring Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reinsurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Required</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Potentially Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Filled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Resource Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Resource ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ResourceRequest__c.object
<CustomObject>
    <description>A request for resources to staff an event.</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Please provide details that are specific to the demo such as the goal of the meeting, description of the audience, line of business, states, etc.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <description>Totals Hours in front of the customer</description>
        <label>Event Hours</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <inlineHelpText>Location of the event.  Leave blank if Presentation Type is Remote.</inlineHelpText>
        <label>Location</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Resource_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Presentation_Type__c</fullName>
        <label>Presentation Type</label>
        <picklist>
            <picklistValues>
                <fullName>On-site</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Remote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HQ Visit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fully Staffed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revoked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Resource Request</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestResourceRequestController.cls
@isTest(SeeAllData=true)
private class TestResourceRequestController 
{

    static testMethod void validateController()
    {
        
      //  User u=[select id,name from user where userrole.name like '%North American Sales%' and isActive=true limit 1];  
        User u=[select id,name from user where userrole.name like '%NA Account Executive - MPL%' and isActive=true limit 1]; 
        Opportunity opp = null;
        
       Test.startTest();
       system.runAs(u)
       {
        opp=new Opportunity();
       opp.StageName='Prospecting';
       opp.CloseDate=system.today();
       opp.Name='Test Opportinity';
       opp.Premium_In_Scope__c =1000;
       opp.Amount=2000.00;
       opp.region__c ='Amer';
       insert opp;
      
       }                 
        
       resourceRequest(opp.id);
    }
    
    static testMethod void validateController1()
    {
        
        User u=[select id,name from user where userrole.name like '%NA Sales Executive - IS%' and isActive=true limit 1];  
        Opportunity opp = null;
        
       Test.startTest();
       system.runAs(u)
       {
        opp=new Opportunity();
       opp.StageName='Prospecting';
       opp.CloseDate=system.today();
       opp.Name='Test Opportinity2';
       opp.Premium_In_Scope__c =10001;
       opp.Amount=20004.00;
       opp.region__c ='Amer';
       insert opp;
      
       }                 
        
       resourceRequest(opp.id);
    }
    
  /*  static testMethod void validateController2()
    {        
        User u=[select id,name from user where userrole.name like '%UKI Sales%' and isActive=true limit 1]; 
        Opportunity opp = null;
        
       Test.startTest();
       system.runAs(u)
       {
        opp=new Opportunity();
       opp.StageName='Prospecting';
       opp.CloseDate=system.today();
       opp.Name='Test Opportinity1';
       opp.Premium_In_Scope__c =10001;
       opp.Amount=20001.00;
       opp.region__c ='EMEA';
       insert opp;
      
       }                 
        
       resourceRequest1(opp.id);
    }
    */
    
    @future
    public static void resourceRequest(id oppid)
    {    
       //  User u = [select id,name,email,userroleid,userrole.name from user where userrole.name ='NA Sales Executive - PB' and isactive=true limit 1];
      //   system.runAs(u)
      //   {
        
         ResourceRequest__c req = new ResourceRequest__c(Opportunity__c = oppid,
                                                        Name = 'Request Test 1',
                                                        Status__c = 'Pending', 
                                                        Event_Hours__c = 5,
                                                        Presentation_Type__c = 'Demonstration',
                                                        Location__c = 'Austin, TX',
                                                        Description__c = 'Request Test 1 Description'
                                                        
                                                        );
        insert req;
                
        //now add a possible date to the request
        Resource_Role__c role = new Resource_Role__c(  Status__c='Required',
                                                       Resource_Request__c = req.Id,
                                                       Role__c = 'ClaimCenter'
                                                      );                                             
                                                      
        insert role;
        
        User u = [select id,name,email,userroleid, userrole.parentroleId from user where name='Brittany German' limit 1];
        system.runAs(u)
        {
        
        ApexPages.StandardController controller = new ApexPages.StandardController(req);
        //put in ID so the controller has data
        ApexPages.currentPage().getParameters().put('id', req.Id);
        ResourceRequestController theExistingController = new ResourceRequestController (controller);


//        .save();


        //revoke request
        ResourceRequestController.revokeRequest('' + req.Id);
        
        theExistingController.reloadRequest();

        // MATT DISABLED TEMPORARILY
//        System.assertEquals(theExistingController.resourceRequest.Status__c , 'Revoked');
        
            //reset status back to pending to continue test
        theExistingController.resourceRequest.Status__c = 'Pending';
        update theExistingController.resourceRequest;


        //add a few possible dates
        Possible_Date__c pDate = new Possible_Date__c(Name='Possible Date Test 1',
                                                       Start_Date__c = Date.today().addDays(-3),
                                                       End_Date__c = Date.today().addDays(-2),
                                                       Event_Hours__c = 5,
                                                       Resource_Request__c = req.Id
                                                      );
        insert pDate;        

        Possible_Date__c pDate2 = new Possible_Date__c(Name='Possible Date Test 2',
                                                       Start_Date__c = Date.today().addDays(-6),
                                                       End_Date__c = Date.today().addDays(-5),
                                                       Event_Hours__c = 5,
                                                       Resource_Request__c = req.Id
                                                      );
        insert pDate2;
        
//           List<Resource_Hold__c> allHolds = [SELECT Id, Who__c, Coverage_Area__c, Description__c FROM Resource_Hold__c where Resource_Request__c = :requestID ];       
        Resource_Hold__c newHold = new Resource_Hold__c(Who__c = UserInfo.getUserId(),
                                                        Description__c = 'Test',
                                                        Coverage_Area__c = 'ClaimCenter',
                                                        Resource_Request__c = req.Id
                                                       );
        insert newHold;                                                       
        
        //open request
        ResourceRequestController.openRequest(req.Id);
        theExistingController.reloadRequest();
        ResourceRequest__c theReq = [SELECT ID, Status__c, (SELECT ID from Resource_Assignments__r) from ResourceRequest__c where Id = :req.Id LIMIT 1];
        
        // MATT DISABLED TEMPORARILY
        //System.assertEquals(theReq.Status__c , 'Open');
        //System.assertEquals(theReq.Resource_Assignments__r.size() , 0);

        //addCurrentUserForSpecifiedRole
        ResourceRequestController.addCurrentUserForSpecifiedRole('ClaimCenter', req.Id);
        //theExistingController.reloadRequest();
        theReq = [SELECT ID, Status__c, (SELECT ID, Status__c from Resource_Assignments__r) from ResourceRequest__c where Id = :req.Id LIMIT 1];


        // MATT DISABLED TEMPORARILY
//        System.assertEquals(theReq.Resource_Assignments__r.size() , 1);
//        System.assertEquals(theReq.Resource_Assignments__r[0].Status__c , 'Pending');
        
        //confirmAssignment
        ResourceRequestController.confirmAssignment('' + theReq.Resource_Assignments__r[0].Id,'' +  theReq.Id);
        theReq = [SELECT ID, Status__c, (SELECT ID, Status__c from Resource_Assignments__r) from ResourceRequest__c where Id = :req.Id LIMIT 1];

        // MATT DISABLED TEMPORARILY
//        System.assertEquals(theReq.Resource_Assignments__r[0].Status__c , 'Selected');
        
        
        //releaseAssignment
        ResourceRequestController.releaseAssignment('' + theReq.Resource_Assignments__r[0].Id,'' +  theReq.Id);
        theReq = [SELECT ID, Status__c, (SELECT ID, Status__c from Resource_Assignments__r) from ResourceRequest__c where Id = :req.Id LIMIT 1];

        // MATT DISABLED TEMPORARILY
//        System.assertEquals(theReq.Resource_Assignments__r[0].Status__c , 'Pending');

        ResourceRequestController.confirmAssignment('' + theReq.Resource_Assignments__r[0].Id,'' +  theReq.Id);
        theReq = [SELECT ID, Status__c, (SELECT ID, Status__c from Resource_Assignments__r) from ResourceRequest__c where Id = :req.Id LIMIT 1];

        // MATT DISABLED TEMPORARILY

//        System.assertEquals(theReq.Resource_Assignments__r[0].Status__c , 'Selected');

        
        //getAllPossibleDatesList()
        theExistingController.getAllPossibleDatesList();
        //getPossibleDatesList()
        theExistingController.getPossibleDatesList();
        //selectDate
        pDate = [SELECT Id, Status__c from Possible_Date__c where Id = :pDate.Id LIMIT 1];
        pDate2 = [SELECT Id, Status__c from Possible_Date__c where Id = :pDate2.Id LIMIT 1];

        // MATT DISABLED TEMPORARILY
//        System.assertEquals(pDate.Status__c , 'Possible');
//        System.assertEquals(pDate2.Status__c , 'Possible');

        ResourceRequestController.selectDate('' + pDate.Id, '' + theReq.Id);
        pDate = [SELECT Id, Status__c from Possible_Date__c where Id = :pDate.Id LIMIT 1];
        pDate2 = [SELECT Id, Status__c from Possible_Date__c where Id = :pDate2.Id LIMIT 1];

        // MATT DISABLED TEMPORARILY
//        System.assertEquals(pDate.Status__c , 'Selected');
//        System.assertEquals(pDate2.Status__c , 'Not Selected');

        //convertRequest using holds
        ResourceRequestController.convertPendingRequestToEvent('' + req.Id);
        
        //complete request
        ResourceRequestController.completeRequest('' + req.Id, false);
        ResourceRequestController.completeRequest('' + req.Id, true);
        theExistingController.reloadRequest();
        theReq = [SELECT ID, Status__c, (SELECT ID from Resource_Assignments__r) from ResourceRequest__c where Id = :req.Id LIMIT 1];

        // MATT DISABLED TEMPORARILY
//        System.assertEquals(theReq.Status__c , 'Completed');

        //getRequestedResourceRolesAsSelect
        theExistingController.getRequestedResourceRolesAsSelect();
        //getRequestedResourceRoles
        theExistingController.getRequestedResourceRoles();
        
        
            //change some availabilities
        //saveResources
        theExistingController.clearAssignmentsList();
        List<ResourceRequestController.cResourceAssignment> theList = theExistingController.getAssignmentsList();

        theExistingController.saveResources();
        //clearAssignmentsList
        //getAssignmentsList
//        List<ResourceRequestController.cResourceAssignment> theList = theExistingController.getAssignmentsList();
        
        for(ResourceRequestController.cResourceAssignment cra : theList)
        {
            cra.enableEditRole();
            cra.changeRole();
            cra.getResourceName();
            cra.getAvailabilities();
            
        }
        
        //now delete it
        
        delete req;
          
        

//        System.assertEquals('/apex/SWOT', nextPage);
        }     
    }
}