src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Alliance_Type__c</fullName>
        <label>Alliance Type</label>
        <picklist>
            <picklistValues>
                <fullName>PartnerConnect - Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PartnerConnect - Consulting</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Prospective_Partner_Type__c</fullName>
        <description>populated by web form based on the lead origin</description>
        <inlineHelpText>What type of partner is this lead interested in applying for</inlineHelpText>
        <label>Prospective Partner Type</label>
        <picklist>
            <picklistValues>
                <fullName>PartnerConnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SolutionConnect</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Record type used for all Partner records.</description>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <label>Deal Type</label>
        <picklist>
            <picklistValues>
                <fullName>Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term with ramp up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term with ramp up and PBO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term with PBO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perpetual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subscription</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Cycle__c</fullName>
        <label>Payment Cycle</label>
        <picklist>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Prospect_Plan_Update_Time__c</fullName>
        <description>set through Attachment Trigger</description>
        <inlineHelpText>Date/Time the prospect plan file was last uploaded</inlineHelpText>
        <label>Prospect Plan Update Time</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TriggerTests.cls
@istest
public class TriggerTests{
    public static testmethod void testAttachments(){
        // create Account/Opportunity
        Account a = new Account(name = 'test');
        insert a;
        Opportunity o = new Opportunity(closedate = date.today().adddays(15), stagename = 'Prospecting', accountid = a.id, name = 'test',
            Deal_type__c = 'sample', payment_cycle__c = 'annual', amount = 1);
        insert o;
        // add attachment to Opp without ProspectPlan in the name
        Attachment a1 = new Attachment(name = 'some file.txt', body = blob.valueof('Test document body'), parentid = o.id);
        insert a1;
        // check the datetime stamp not populated
        o = [select id, prospect_plan_update_time__c from Opportunity where id = :o.id];
        system.assertequals(null, o.prospect_plan_update_time__c);
        // add file with prospectplan in name
        Attachment a2 = new Attachment(name = 'some file prospectPlan.txt', body = blob.valueof('Test document body'), parentid = o.id);
        insert a2;
        // check the datetime stamp not populated
        o = [select id, prospect_plan_update_time__c from Opportunity where id = :o.id];
        system.assertnotequals(null, o.prospect_plan_update_time__c);
    }
    
    public static testmethod void testAccountPartnerType(){
        // create account with blank alliance and prospective partner type
        Account a = new Account(name = 'test', prospective_partner_Type__c = 'First Option');
        insert a;
        a = [select id, prospective_partner_Type__c , alliance_type__c from Account where id = :a.id];
        system.assertequals(a.prospective_partner_Type__c, null);
        system.assertequals(a.alliance_type__c , 'First Option');
        // add new option in prospective
        a.prospective_partner_Type__c = 'Second Option';
        update a;
        a = [select id, prospective_partner_Type__c , alliance_type__c from Account where id = :a.id];
        system.assertequals(a.prospective_partner_Type__c, null);
        system.assert(a.alliance_type__c.contains('Second Option') && a.alliance_type__c.contains('First Option'));
        // add second option again
        a.prospective_partner_Type__c = 'Second Option';
        update a;
        a = [select id, prospective_partner_Type__c , alliance_type__c from Account where id = :a.id];
        system.assertequals(a.prospective_partner_Type__c, null);
        system.assertequals(a.alliance_type__c.countmatches('Second Option'), 1);                
    } 
}