src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Record type used for all Customer records.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Record type used for all Prospect records.</description>
        <label>Prospect</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>CS_Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>***** Asset  active Status ******</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Record_Type_Name__c</fullName>
        <description>Asset Record Type Name</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CS_Contact_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Licensed Product</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>CS_Asset_Contact_Permissions__c.CS_Contact__c</field>
                <operation>equals</operation>
                <valueField>$User.ContactId</valueField>
            </filterItems>
            <filterItems>
                <field>CS_Asset_Contact_Permissions__c.CS_IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>CS_Asset_Contact_Permissions__c.CS_Access_Type__c</field>
                <operation>equals</operation>
                <value>Customer Support, Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CS_Asset_Contact_Permissions__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CS_Restoration_Milestone_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Mark Restoration Complete</inlineHelpText>
        <label>Restoration Milestone Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Urgency__c</fullName>
        <description>Specify how urgently this particular Issue needs a solution</description>
        <inlineHelpText>Specify how urgently this particular Issue needs a solution</inlineHelpText>
        <label>Urgency</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immediate</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <picklist>
            <controllingField>Asset_Type__c</controllingField>
            <picklistValues>
                <fullName>1-Blocker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2-Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3-Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4-Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1–Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2–Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3–Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4–Cosmetic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <description>Support Contact</description>
        <label>Support</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Asset_Contact_Permissions__c.object
<CustomObject>
    <label>Asset Contact Permission</label>
    <nameField>
        <label>Product Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Contact Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Milestone_Business_Hours__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>**** Service Cloud  Milestone Business Hours ******</description>
    <fields>
        <fullName>CS_Business_Days__c</fullName>
        <label>Business Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CS_Entitlement_Process_Name__c</fullName>
        <description>Entitlement Process Name</description>
        <label>Entitlement Process Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Milestone_Name__c</fullName>
        <description>Milestone Name</description>
        <label>Milestone Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Severity__c</fullName>
        <label>Severity</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>GW Milestone Business Hours</label>
</CustomObject>

src/classes/TestCS_CaseMilestoneCalculation.cls
@isTest
public class TestCS_CaseMilestoneCalculation {
	static Account customerAcc;
    static Contact customerContact;
    static User currentUsr;
    static Product2 prod;
    static User testUser;
    static CS_Asset_Contact_Permissions__c acp;
    static Entitlement ent;
    static CS_Milestone_Business_Hours__c mbh;
    
    static void setupTestData() {
        // query current test user
        currentUsr = [select Id, UserRole.Name from User where Id = :UserInfo.getUserId()];       
        
        prod = CS_TestDataUtility.createProductRecord();
        customerAcc = CS_TestDataUtility.createCustomerAccount();
        customerContact = CS_TestDataUtility.createContact(customerAcc, 'Customer Support');
        // insert parent asset for customer account
        List<Asset> parentAssetsCustomer = CS_TestDataUtility.createParentAssetRecord(customerAcc, true);
            
        // insert child assets
        for (Integer i=0; i < parentAssetsCustomer.size(); i++) {
            if (i < parentAssetsCustomer.size() - 1) {
                CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Prospect');
            } else {
                CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Implementation');
            }
        }
        
         //if (parentAssetsCustomer != null && parentAssetsCustomer.size() > 0) {
             // create acp
          //   acp = CS_TestDataUtility.createACP(parentAssetsCustomer[0], customerContact, 'Customer Support', true);
         //}
        
         mbh = CS_TestDataUtility.createMileStoneBusinessHours();
        
        //query asset
        Asset childAsset = [Select Id, CS_Is_Active__c from Asset where CS_Record_Type_Name__c = 'Child Asset' and ParentId != null limit 1];
        
        acp = [Select Id from CS_Asset_Contact_Permissions__c limit 1];
        // query case record type
        RecordType rt = [Select Name, developername from RecordType where sobjecttype = 'Case' and Name = 'Customer Support'];
        
        // create entitlement
        ent = CS_TestDataUtility.createEntitlement(childAsset, customerAcc);
        
        List<Case> caseList = new List<Case>();
        Case c = new Case();
        c.AssetId = childAsset.Id;
        
        c.AccountId = customerAcc.Id;
        c.RecordTypeId = rt.Id;
        c.ContactId = customerContact.Id;
        c.Severity__c = '1-Blocker';
        c.CS_Urgency__c = 'High';
        c.CS_Contact_Asset__c = acp.Id;
        caseList.add(c);
        insert caseList;
        
        //query MileStone
        CaseMileStone cms = [Select Id, MilestoneType.Name from CaseMileStone limit 1];
        
        //query entitlement
        Entitlement insertedEnt = [Select Id, Name from Entitlement limit 1];
        
        List<CS_Milestone_Business_Hours__c> mbhListToInsert = new List<CS_Milestone_Business_Hours__c>();
        CS_Milestone_Business_Hours__c mbh1 = new CS_Milestone_Business_Hours__c();
        mbh1.Name = 'TestMBH1';
        mbh1.CS_Entitlement_Process_Name__c = insertedEnt.Name;
        mbh1.CS_Severity__c = '1-Blocker';
        mbh1.CS_Milestone_Name__c = cms.MilestoneType.Name;
        mbhListToInsert.add(mbh1);
        
        CS_Milestone_Business_Hours__c mbh2 = new CS_Milestone_Business_Hours__c();
        mbh2.Name = 'TestMBH2';
        mbh2.CS_Entitlement_Process_Name__c = 'Default';
        mbh2.CS_Business_Days__c = 10;
        mbhListToInsert.add(mbh2);
        
		insert mbhListToInsert;
    }
    
    static testMethod void testcalculateMilestoneTriggerTime() {
        setupTestData();
        Test.startTest();
        CaseMileStone cms = [Select MileStoneTypeId from CaseMileStone limit 1];
        
        Case c = [Select Id, AssetId, EntitlementId, BusinessHoursId, CS_Restoration_Milestone_Completed__c from Case limit 1];
           
        CS_CaseMilestoneCalculation cmsCalculation = new CS_CaseMilestoneCalculation();
        cmsCalculation.calculateMilestoneTriggerTime(c.Id, cms.MilestoneTypeId);
        Test.stopTest();
    }
    
    static testMethod void testCustomMilestoneCalculation() {
        setupTestData();
        Test.startTest();
        CaseMileStone cms = [Select MileStoneTypeId from CaseMileStone limit 1];
        
        Case c = [Select Id, AssetId, EntitlementId, BusinessHoursId, CS_Restoration_Milestone_Completed__c from Case limit 1];
           
        CS_CaseMilestoneCalculation cmsCalculation = new CS_CaseMilestoneCalculation();
        cmsCalculation.customMilestoneCalculation(c.Id, cms.MilestoneTypeId, true);
        Test.stopTest();
    }
}