src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Products_Purchased__c</fullName>
        <label>Products Purchased</label>
        <picklist>
            <picklistValues>
                <fullName>BillingCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ClaimCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Data Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DataHub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InfoCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MiAgents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Millbrook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile &amp; Portals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PolicyCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rating Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reinsurance Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standards-based Templates</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Record type used for all Partner records.</description>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>For use in filtering mailings; Top Mgmt is for CEO, COO, President, Chairman, etc.</description>
        <label>Subject  Area</label>
        <picklist>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claims</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Consulting</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>PRM_Partner_Account_Exec__c</fullName>
        <label>Partner Account Exec</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PRM_Partner_Account_Exec_s_Email__c</fullName>
        <label>Partner Account Exec ‘s Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PRMLeadTest.cls
@isTest
class PRMLeadTest
{
   
    
     static testMethod void testPRMLead()
    {
        
        
       List<Profile> lstProfile =[Select Id from Profile
                                    where profile.userlicense.name = 'Partner Community'];
       
       list<UserRole> lsturole = [select id from UserRole where name='Mitchell Partner Test Account Partner User'];  
        
       
               
        List<RecordType> lstRecordType = [Select Id from RecordType where Name ='Partner'];
        List<RecordType> lstPartnerOpptyRT = [Select Id from RecordType where Name ='Master Lead'];
       
        Account objAccount = New Account(name='TestProduct',Products_Purchased__c= 'BillingCenter');
        objAccount.RecordTypeId =lstRecordType[0].Id;
        insert objAccount; 
        
         
       
        Contact contact = new Contact();
        contact.LastName = 'testContact';
        contact.AccountId = objAccount.Id;
        contact.Category__c = 'Billing';
        insert contact;
       
    /*    User user = new User(alias = 'standt', email='stauserNw@testorg.com',
        emailencodingkey='UTF-8',state='gh', lastname='Testing', languagelocalekey='en_US',
        localesidkey='en_US', profileid = lstProfile[0].Id,  userroleid=lsturole[0].id, portalrole='manager',  
        timezonesidkey='America/Los_Angeles', username='stanuser@testRaksorg.com',
        ContactId = contact.Id );   


       
       User usr=[select id,name from user where id=:userinfo.getUserId()];
        system.runAs(usr)
        {
          
          insert user;
            objaccount.OwnerId = user.id;
           update objaccount;
            
        }  

  */
        
      //  list<user> ulst = [select id,name from user where profileid =: lstProfile[0].id and isactive=true ]; 
        
        list<user> ulst = [select id,name from user where profile.userlicense.name = 'Partner Community' and isactive=true ];
        
        
        system.runAs(ulst[0])
        {
            

            Lead lead = new Lead();
            lead.LastName = 'testLast';
            lead.Company = 'testCompany';
            lead.Industry = 'TPA';
            lead.Status = 'Open';
            lead.LeadSource = 'Direct Mail';
            lead.PRM_Partner_Account_Exec__c = 'testA';
            lead.PRM_Partner_Account_Exec_s_Email__c = 'partner@TEST1.COM';
            //lead.CurrencyIsoCode = 'USD - U.S. Dollar';
            insert lead;
        } 
    }  
        
}