src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Record type used for all Customer records.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Record type used for all Partner records.</description>
        <label>Partner</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Record type used for all Prospect records.</description>
        <label>Prospect</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>CS_Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>***** Asset  active Status ******</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Record_Type_Name__c</fullName>
        <description>Asset Record Type Name</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CS_Contact_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Licensed Product</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>CS_Asset_Contact_Permissions__c.CS_Contact__c</field>
                <operation>equals</operation>
                <valueField>$User.ContactId</valueField>
            </filterItems>
            <filterItems>
                <field>CS_Asset_Contact_Permissions__c.CS_IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>CS_Asset_Contact_Permissions__c.CS_Access_Type__c</field>
                <operation>equals</operation>
                <value>Customer Support, Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CS_Asset_Contact_Permissions__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CS_Access_Type__c</fullName>
        <label>Access Type</label>
        <picklist>
            <picklistValues>
                <fullName>General Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support (View Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <description>Support Contact</description>
        <label>Support</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Asset_Contact_Permissions__c.object
<CustomObject>
    <fields>
        <fullName>CS_Access_Type__c</fullName>
        <label>Access Type</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support (View Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipName>Asset_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset Contact Permission</label>
    <nameField>
        <label>Product Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Contact Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_ByPass__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>ByPass from Triggers,WF Rules and Validation Rules</description>
    <fields>
        <fullName>CS_Batch_Context__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Batch Context</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Disable_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>ByPass from Trigger</inlineHelpText>
        <label>Disable Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Disable_ValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ByPass from Validation Rules</description>
        <label>Disable ValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <label>GW ByPass</label>
</CustomObject>

src/objects/CS_Release__c.object
<CustomObject>
    <description>***Service Cloud **** This Object  maintains the Installable Product versions</description>
    <label>Release</label>
    <nameField>
        <label>Product Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/GW_Common_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>GW Common Settings</label>
</CustomObject>

src/classes/TestCS_CaseTriggerHandler.cls
@isTest
public class TestCS_CaseTriggerHandler {
  static User usr;
    static Account customerAcc;
    static Account partnerAcc;
    static Product2 prod;
    static ContentVersion contentVersion;
    static ContentDocumentLink cdl;
    static CS_Release__c release;
    static List<GW_Common_Settings__c> commonSettings;
    static CS_ByPass__c byPass;
    static Contact customerContact;
    static Contact customerContact1;
    static Contact partnerContact;
   
    
    private static void setupTestData() {
        commonSettings = CS_TestDataUtility.createGWCommentSettings();
        customerAcc = CS_TestDataUtility.createCustomerAccount();
        partnerAcc = CS_TestDataUtility.createPartnerAccount();
        customerContact = CS_TestDataUtility.createContact(customerAcc, 'Customer Support');
        customerContact1 = CS_TestDataUtility.createContact(customerAcc, 'General Customer');
        partnerContact = CS_TestDataUtility.createContact(partnerAcc, 'Partner');
        usr = CS_TestDataUtility.createTestUser();
        prod = CS_TestDataUtility.createProductRecord();
        release = CS_TestDataUtility.createRelease(prod);
        contentVersion = CS_TestDataUtility.createContentDocument();
        ContentVersion cv = [Select Id, ContentDocumentId from ContentVersion where Id = :contentVersion.Id];
        cdl = CS_TestDataUtility.createContentDocumentLink(cv.ContentDocumentId, release.Id);
        CS_TestDataUtility.createACPactivateUser();
    //byPass = CS_TestDataUtility.createByPass(usr);
       
    }

    Static testmethod Void testCustomerCaseCreation1(){

        setupTestData();
        
        // query current test user
        User currentUsr = [select Id, UserRole.Name from User where Id = :UserInfo.getUserId()];

        System.runAs(currentUsr) {
            Test.startTest();
            
            // insert bypass custom setting to disable validation rule
            CS_ByPass__c byPassValidation = new CS_ByPass__c();
            byPassValidation.Name = 'CS_Disable_ValidationRule__c';
            byPassValidation.CS_Batch_Context__c = true;
            byPassValidation.SetupOwnerId = currentUsr.Id;
            byPassValidation.CS_Disable_ValidationRule__c = true;
            insert byPassValidation;
            
            User customerCommunityTestUser = CS_TestDataUtility.createCustomerCommunityTestUser(customerContact);
             // insert parent asset for customer account
            List<Asset> parentAssetsCustomer = CS_TestDataUtility.createParentAssetRecord(customerAcc, true);
            
            // insert child assets
            for (Integer i=0; i < parentAssetsCustomer.size(); i++) {
                if (i < parentAssetsCustomer.size() - 1) {
                    CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Prospect', customerContact);
                } else {
                    CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Implementation', customerContact);
                }
            }
            
            //if (parentAssetsCustomer != null && parentAssetsCustomer.size() > 0) {
            //    // create acp
            //    CS_Asset_Contact_Permissions__c acp = CS_TestDataUtility.createACP(parentAssetsCustomer[0], customerContact, 'Customer Support', true);
            //}
            
            List<Asset> childAssets =  [Select Id, CS_Is_Active__c, ParentId from Asset where CS_Record_Type_Name__c = 'Child Asset'];
            System.debug('===childAssets Test==== ' + childAssets);
           
            //query asset
            Asset childAsset = [Select Id, CS_Is_Active__c from Asset where CS_Record_Type_Name__c = 'Child Asset' and ParentId != null limit 1];
            
            // query acp
            CS_Asset_Contact_Permissions__c acp = [Select Id, CS_Asset__r.ParentId from CS_Asset_Contact_Permissions__c where CS_Access_Type__C = 'Customer Support' limit 1];
            System.debug('=====test acp==== ' + acp);
            
            // query case record type
            RecordType rt = [Select Name, developername from RecordType where sobjecttype = 'Case' and Name = 'Customer Support'];
            Case c = new Case();
            c.AssetId = childAsset.Id;
            c.AccountId = customerAcc.Id;
            c.RecordTypeId = rt.Id;
            c.ContactId = customerContact.Id;
            c.CS_Contact_Asset__c = acp.Id; 
            c.Description = 'decription';
            insert c;
 
            Test.stopTest();
        }


    }
    
    static testMethod void testCustomerCaseCreation() {
        setupTestData();
        
        // query current test user
        User currentUsr = [select Id, UserRole.Name from User where Id = :UserInfo.getUserId()];

        System.runAs(currentUsr) {
            Test.startTest();
            
            // insert bypass custom setting to disable validation rule
            CS_ByPass__c byPassValidation = new CS_ByPass__c();
            byPassValidation.Name = 'CS_Disable_ValidationRule__c';
            byPassValidation.CS_Batch_Context__c = true;
            byPassValidation.SetupOwnerId = currentUsr.Id;
            byPassValidation.CS_Disable_ValidationRule__c = true;
            insert byPassValidation;
            
            User customerCommunityTestUser = CS_TestDataUtility.createCustomerCommunityTestUser(customerContact);
             // insert parent asset for customer account
            List<Asset> parentAssetsCustomer = CS_TestDataUtility.createParentAssetRecord(customerAcc, true);
            
            // insert child assets
            CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[0], 'Implementation', customerContact);
            //CS_Asset_Contact_Permissions__c  acp1 = CS_TestDataUtility.createACP(parentAssetsCustomer[0], customerContact, 'Customer Support', true);
            //CS_Asset_Contact_Permissions__c  acp2 = CS_TestDataUtility.createACP(parentAssetsCustomer[0], customerContact1, 'Customer Support (View Only)', true);
            
            List<Asset> childAssets =  [Select Id, CS_Is_Active__c, ParentId from Asset where CS_Record_Type_Name__c = 'Child Asset'];
            System.debug('===childAssets Test==== ' + childAssets);
           
            //query asset
            Asset childAsset = [Select Id, CS_Is_Active__c from Asset where CS_Record_Type_Name__c = 'Child Asset' and ParentId != null limit 1];
            
            // query acp
            CS_Asset_Contact_Permissions__c acp = [Select Id, CS_Asset__r.ParentId from CS_Asset_Contact_Permissions__c limit 1];
      System.debug('=====test acp==== ' + acp);
            
            // query case record type
            RecordType rt = [Select Name, developername from RecordType where sobjecttype = 'Case' and Name = 'Customer Support'];
            Case c = new Case();
            c.AssetId = childAsset.Id;
            c.AccountId = customerAcc.Id;
            c.RecordTypeId = rt.Id;
            c.ContactId = customerContact.Id;
            c.CS_Contact_Asset__c = acp.Id; 
            c.Description ='Description..';
            insert c;

            CS_Asset_Contact_Permissions__c  acp1 = [Select Id from CS_Asset_Contact_Permissions__c where CS_Access_Type__c = 'Customer Support' limit 1 ];
    
            CS_Asset_Contact_Permissions__c acp3= [Select id,CS_Access_Type__c from CS_Asset_Contact_Permissions__c where id =:acp1.id limit 1];
            CS_Asset_Contact_Permissions__c  AcpCS2GS= New CS_Asset_Contact_Permissions__c(id=acp3.id,CS_Access_Type__c='Customer Support (View Only)');
            Update AcpCS2GS;




            Test.stopTest();
        }
    }
    
    static testMethod void testCustomerCaseUpdate() {
        setupTestData();
        
        // query current test user
        User currentUsr = [select Id, UserRole.Name from User where Id = :UserInfo.getUserId()];

        Test.startTest();
        // insert parent asset for customer account
        List<Asset> parentAssetsCustomer = CS_TestDataUtility.createParentAssetRecord(customerAcc, true);
        
        // insert child assets
        for (Integer i=0; i < parentAssetsCustomer.size(); i++) {
            if (i < parentAssetsCustomer.size() - 1) {
                CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Prospect', customerContact);
            } else {
                CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Implementation', customerContact);
            }
        }
        
        //if (parentAssetsCustomer != null && parentAssetsCustomer.size() > 0) {
        //    // create acp
        //    CS_Asset_Contact_Permissions__c acp = CS_TestDataUtility.createACP(parentAssetsCustomer[0], customerContact, 'Customer Support', true);
        //}
        
                
        // insert bypass custom setting to disable validation rule
        CS_ByPass__c byPassValidation = new CS_ByPass__c();
        byPassValidation.Name = 'CS_Disable_ValidationRule__c';
        byPassValidation.CS_Batch_Context__c = true;
        byPassValidation.SetupOwnerId = currentUsr.Id;
        byPassValidation.CS_Disable_ValidationRule__c = true;
        insert byPassValidation;
       

        System.runAs(currentUsr) {
            
            // query acp
            CS_Asset_Contact_Permissions__c acp = [Select Id, CS_Asset__r.ParentId from CS_Asset_Contact_Permissions__c limit 1];
            System.debug('=====test acp==== ' + acp);

            //query asset
            Asset childAsset = [Select Id, CS_Is_Active__c from Asset where CS_Record_Type_Name__c = 'Child Asset' and ParentId != null limit 1];
            // query case record type
            RecordType rt = [Select Name, developername from RecordType where sobjecttype = 'Case' and Name = 'Customer Support'];
            Case c = new Case();
            c.AssetId = childAsset.Id;
            c.AccountId = customerAcc.Id;
            c.RecordTypeId = rt.Id;
            c.ContactId = customerContact.Id;
            c.CS_Contact_Asset__c = acp.Id; 
            c.Description = 'test';
            insert c;
         
            User customerCommunityTestUser = CS_TestDataUtility.createCustomerCommunityTestUser(customerContact);
            // query case
      Case insertedCase = [Select Id, CaseNumber, Status from Case limit 1];
      insertedCase.Status = 'Closed';
            update insertedCase;
            
        }
        Test.stopTest();
    }
    
    static testMethod void testCustomerCaseUpdateContact() {
        setupTestData();
         Test.startTest();
        // query current test user
        User currentUsr = [select Id, UserRole.Name from User where Id = :UserInfo.getUserId()];

        
        // insert parent asset for customer account
        List<Asset> parentAssetsCustomer = CS_TestDataUtility.createParentAssetRecord(customerAcc, true);
        
        // insert child assets
        for (Integer i=0; i < parentAssetsCustomer.size(); i++) {
            if (i < parentAssetsCustomer.size() - 1) {
                CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Prospect', customerContact);
            } else {
                CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Implementation', customerContact);
            }
        }
        
        //if (parentAssetsCustomer != null && parentAssetsCustomer.size() > 0) {
        //    // create acp
        //    CS_Asset_Contact_Permissions__c acp = CS_TestDataUtility.createACP(parentAssetsCustomer[0], customerContact, 'Customer Support', true);
        //}
        
                
        // insert bypass custom setting to disable validation rule
        CS_ByPass__c byPassValidation = new CS_ByPass__c();
        byPassValidation.Name = 'CS_Disable_ValidationRule__c';
        byPassValidation.CS_Batch_Context__c = true;
        byPassValidation.SetupOwnerId = currentUsr.Id;
        byPassValidation.CS_Disable_ValidationRule__c = true;
        insert byPassValidation;
        
        List<Asset> childAssets =  [Select Id, CS_Is_Active__c, ParentId from Asset where CS_Record_Type_Name__c = 'Child Asset'];
        System.debug('===childAssets Test==== ' + childAssets);
        
        Contact otherCustomerContact = CS_TestDataUtility.createContact(customerAcc, 'Customer Support');
        
        //query asset
        Asset childAsset = [Select Id, CS_Is_Active__c from Asset where CS_Record_Type_Name__c = 'Child Asset' and ParentId != null limit 1];
        
        // query acp
        CS_Asset_Contact_Permissions__c acp = [Select Id, CS_Asset__r.ParentId from CS_Asset_Contact_Permissions__c limit 1];
        System.debug('=====test acp==== ' + acp);
        
        System.runAs(currentUsr) {
           
            // query case record type
            RecordType rt = [Select Name, developername from RecordType where sobjecttype = 'Case' and Name = 'Customer Support'];
            Case c = new Case();
            c.AssetId = childAsset.Id;
            c.AccountId = customerAcc.Id;
            c.RecordTypeId = rt.Id;
            c.ContactId = customerContact.Id;
            c.CS_Contact_Asset__c = acp.Id; 
            c.Description = 'description';
            insert c;
         
            User customerCommunityTestUser = CS_TestDataUtility.createCustomerCommunityTestUser(customerContact);
            // query case 
      Case insertedCase = [Select Id, CaseNumber, ContactId from Case limit 1];
      insertedCase.ContactId = otherCustomerContact.Id;
            update insertedCase;
            Test.stopTest();
        }
    }
    
    static testMethod void testCustomerCaseCreation2() {
        setupTestData();
         // query current test user
        User currentUsr = [select Id, UserRole.Name from User where Id = :UserInfo.getUserId()];
       
        System.runAs(currentUsr) {
        
        
         Test.startTest();
             // insert bypass custom setting to disable validation rule
            /*
            CS_ByPass__c byPassTrigger = new CS_ByPass__c();
            byPassTrigger.Name = 'CS_Disable_Trigger__c';
            byPassTrigger.CS_Disable_Trigger__c = true;
            byPassTrigger.SetupOwnerId = currentUsr.Id;
          insert byPassTrigger;
            */
            // insert parent asset for customer account
            List<Asset> parentAssetsCustomer = CS_TestDataUtility.createParentAssetRecord(customerAcc, true);
            
            // insert child assets
            for (Integer i=0; i < parentAssetsCustomer.size(); i++) {
                if (i < parentAssetsCustomer.size() - 1) {
                    CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Prospect', customerContact);
                } else {
                    CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Implementation', customerContact);
                }
            }
            
            //if (parentAssetsCustomer != null && parentAssetsCustomer.size() > 0) {
            //    // create acp
            //    CS_Asset_Contact_Permissions__c acp = CS_TestDataUtility.createACP(parentAssetsCustomer[0], customerContact, 'Customer Support', true);
            //}
            // query acp
            //CS_Asset_Contact_Permissions__c acp = [Select Id, CS_Asset__r.ParentId from CS_Asset_Contact_Permissions__c limit 1];
            
            //User customerCommunityTestUser = CS_TestDataUtility.createCustomerCommunityTestUser(customerContact);
            System.runAs(currentUsr) {
               
                //query asset
            Asset childAsset = [Select Id, CS_Is_Active__c from Asset where CS_Record_Type_Name__c = 'Child Asset' and ParentId != null limit 1];
                
                // query acp
              CS_Asset_Contact_Permissions__c acp = [Select Id, CS_Asset__r.ParentId from CS_Asset_Contact_Permissions__c limit 1];
                
                // query case record type
                RecordType rt = [Select Name, developername from RecordType where sobjecttype = 'Case' and Name = 'Customer Support'];
                Case c = new Case();
                c.AssetId = childAsset.Id;
                c.AccountId = customerAcc.Id;
                c.RecordTypeId = rt.Id;
                c.ContactId = customerContact.Id;
                c.CS_Contact_Asset__c = acp.Id; 
                c.Description = 'Description';
                insert c;
                
            }
            
            Test.stopTest();
        }
    }



     static testMethod void testCustomerCaseCreation_with_ACP() {
        setupTestData();
        
        // query current test user
        User currentUsr = [select Id, UserRole.Name from User where Id = :UserInfo.getUserId()];

        System.runAs(currentUsr) {
            Test.startTest();
            
            // insert bypass custom setting to disable validation rule
            CS_ByPass__c byPassValidation = new CS_ByPass__c();
            byPassValidation.Name = 'CS_Disable_ValidationRule__c';
            byPassValidation.CS_Batch_Context__c = true;
            byPassValidation.SetupOwnerId = currentUsr.Id;
            byPassValidation.CS_Disable_ValidationRule__c = true;
            insert byPassValidation;
            
            User customerCommunityTestUser = CS_TestDataUtility.createCustomerCommunityTestUser(customerContact);
             // insert parent asset for customer account
            List<Asset> parentAssetsCustomer = CS_TestDataUtility.createParentAssetRecord(customerAcc, true);
            
            // insert child assets
            for (Integer i=0; i < parentAssetsCustomer.size(); i++) {
                if (i < parentAssetsCustomer.size() - 1) {
                    CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Prospect', customerContact);
                } else {
                    CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Implementation', customerContact);
                }
            }
            
            //if (parentAssetsCustomer != null && parentAssetsCustomer.size() > 0) {
                // create acp
              //  CS_Asset_Contact_Permissions__c acp = CS_TestDataUtility.createACP(parentAssetsCustomer[0], customerContact, 'Customer Support', true);
            //}
            
            List<Asset> childAssets =  [Select Id, CS_Is_Active__c, ParentId from Asset where CS_Record_Type_Name__c = 'Child Asset'];
            System.debug('===childAssets Test==== ' + childAssets);
           
            //query asset
            Asset childAsset = [Select Id, CS_Is_Active__c from Asset where CS_Record_Type_Name__c = 'Child Asset' and ParentId != null limit 1];
            
            // query acp
            CS_Asset_Contact_Permissions__c acp = [Select Id, CS_Asset__r.ParentId from CS_Asset_Contact_Permissions__c limit 1];
            System.debug('=====test acp==== ' + acp);
            
            // query case record type
            RecordType rt = [Select Name, developername from RecordType where sobjecttype = 'Case' and Name = 'Customer Support'];
            Case c = new Case();
            //c.AssetId = childAsset.Id;
            c.AccountId = customerAcc.Id;
            c.RecordTypeId = rt.Id;
            c.ContactId = customerContact.Id;
            c.CS_Contact_Asset__c = acp.Id; 
            c.Description = 'this is a description.. ';
            insert c;
 
            Test.stopTest();
        }
    }
}