src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Alliance_Type__c</fullName>
        <label>Alliance Type</label>
        <picklist>
            <picklistValues>
                <fullName>PartnerConnect - Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PartnerConnect - Consulting</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Record type used for all Customer records.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Record type used for all Partner records.</description>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CS_Access_Type__c</fullName>
        <label>Access Type</label>
        <picklist>
            <picklistValues>
                <fullName>General Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support (View Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MP_Certified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Partner Accelerator Certified</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Asset_Contact_Permissions__c.object
<CustomObject>
    <fields>
        <fullName>CS_Access_Type__c</fullName>
        <label>Access Type</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support (View Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Asset_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset Contact Permission</label>
    <nameField>
        <label>Product Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Contact Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MP_api_CartExtension.cls
/*
 * Developer: Janella Espiritu <janellae@slalomconsulting.com>
 * Description:
 *   This page enforces single quantity to 1 and determines if the current user can see the Checkout button
 */
global with sharing class MP_api_CartExtension extends ccrz.cc_api_CartExtension {
    global override Map<String,Object> preprocess( Map<String,Object> inputData ) {
        List<ccrz__E_CartItem__c> cartItems = (List<ccrz__E_CartItem__c>) inputData.get(ccrz.cc_api_CartExtension.PARAM_CARTITEMS);
        for (ccrz__E_CartItem__c cartItem : cartItems) {
            // enforce single quantity on orders
            cartItem.ccrz__Quantity__c = 1;
        }
        return inputData;
    }
    global override boolean allowCheckout(Map<String,Object> inputData){
        User u = [select Id, Contact.Account.Recordtype.Name, Contact.Account.Alliance_Type__c, ContactId, Contact.MP_Certified__c from User where Id =: ccrz.cc_CallContext.currUserId];
        
      //  Integer i = [select count() from CS_Asset_Contact_Permissions__c Where CS_Contact__c =:u.ContactId  and CS_Access_Type__c ='Certified'];
       
        Boolean returnVal = false;
        if(u.Contact.Account.Recordtype.Name == 'Customer'){
            returnVal = true;
        }
        else if(u.Contact.Account.Recordtype.Name == 'Partner'){
            if(u.Contact.Account.Alliance_Type__c == 'PartnerConnect - Solution'){
                returnVal = false;
            }
            else if(u.Contact.Account.Alliance_Type__c == 'PartnerConnect - Consulting'){
              //  if(i>0 || u.Contact.MP_Certified__c == true){
                  if(u.Contact.MP_Certified__c == true){
                    returnVal = true;
                }else{
                    returnVal = false;
                }
            }
        }
        return returnVal;
    }
}