src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Record type used for all Customer records.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Record type used for all Prospect records.</description>
        <label>Prospect</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>CS_Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>***** Asset  active Status ******</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Record_Type_Name__c</fullName>
        <description>Asset Record Type Name</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CS_Contact_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Licensed Product</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>CS_Asset_Contact_Permissions__c.CS_Contact__c</field>
                <operation>equals</operation>
                <valueField>$User.ContactId</valueField>
            </filterItems>
            <filterItems>
                <field>CS_Asset_Contact_Permissions__c.CS_IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>CS_Asset_Contact_Permissions__c.CS_Access_Type__c</field>
                <operation>equals</operation>
                <value>Customer Support, Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CS_Asset_Contact_Permissions__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CS_Access_Type__c</fullName>
        <label>Access Type</label>
        <picklist>
            <picklistValues>
                <fullName>General Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support (View Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <description>Support Contact</description>
        <label>Support</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Asset_Contact_Permissions__c.object
<CustomObject>
    <fields>
        <fullName>CS_Access_Type__c</fullName>
        <label>Access Type</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support (View Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipName>Asset_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CS_Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Asset_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset Contact Permission</label>
    <nameField>
        <label>Product Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Contact Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_ByPass__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>ByPass from Triggers,WF Rules and Validation Rules</description>
    <fields>
        <fullName>CS_Disable_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>ByPass from Trigger</inlineHelpText>
        <label>Disable Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>GW ByPass</label>
</CustomObject>

src/classes/TestUTL_CS_CaseTeamMemberUtility.cls
@isTest
public class TestUTL_CS_CaseTeamMemberUtility {
    static Account customerAcc;
    static Contact customerContact;
    static User currentUsr;
    static Product2 prod;
    static User testUser;
    static CaseTeamRole ctr;
    static CS_Asset_Contact_Permissions__c acp;
    
    static void setupTestData() {
        // query current test user
        currentUsr = [select Id, UserRole.Name from User where Id = :UserInfo.getUserId()];       
        
        // insert bypass custom setting to disable validation rule
        /*
        CS_ByPass__c byPassTrigger = new CS_ByPass__c();
        byPassTrigger.Name = 'CS_Disable_Trigger__c';
        byPassTrigger.CS_Disable_Trigger__c = true;
        byPassTrigger.SetupOwnerId = currentUsr.Id;
        insert byPassTrigger;
        */
        prod = CS_TestDataUtility.createProductRecord();
        customerAcc = CS_TestDataUtility.createCustomerAccount();
        customerContact = CS_TestDataUtility.createContact(customerAcc, 'Customer Support');
        // insert parent asset for customer account
        List<Asset> parentAssetsCustomer = CS_TestDataUtility.createParentAssetRecord(customerAcc, true);
            
        // insert child assets
        for (Integer i=0; i < parentAssetsCustomer.size(); i++) {
            if (i < parentAssetsCustomer.size() - 1) {
                CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Prospect');
            } else {
                CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer[i], 'Implementation');
            }
        }
        
         //if (parentAssetsCustomer != null && parentAssetsCustomer.size() > 0) {
             // create acp
            // acp = CS_TestDataUtility.createACP(parentAssetsCustomer[0], customerContact, 'Customer Support', true);
         //}
        
        //ctr = CS_TestDataUtility.createCaseTeamRole('Customer Support', 'Edit');
          ctr = [Select Id, Name, AccessLevel from CaseTeamRole where Name = 'Customer Support' limit 1];  
    }
    
    static testMethod void testCreateCaseTeamMember() {
        setupTestData();
        System.runAs(currentUsr) {
            User customerCommunityTestUser = CS_TestDataUtility.createCustomerCommunityTestUser(customerContact);
            
            //query asset
            Asset childAsset = [Select Id, CS_Is_Active__c from Asset where CS_Record_Type_Name__c = 'Child Asset' and ParentId != null limit 1];
            
            acp = [Select Id from CS_Asset_Contact_Permissions__c limit 1];
            // query case record type
            RecordType rt = [Select Name, developername from RecordType where sobjecttype = 'Case' and Name = 'Customer Support'];
            
            List<Case> caseList = new List<Case>();
            Case c = new Case();
            c.AssetId = childAsset.Id;
            c.AccountId = customerAcc.Id;
            c.RecordTypeId = rt.Id;
            c.ContactId = customerContact.Id;
            c.CS_Contact_Asset__c = acp.Id; 
            caseList.add(c);
            insert caseList;
            
            Set<String> accessTypes = new Set<String>();
            accessTypes.add('Customer Support');
            
            List<CS_Asset_Contact_Permissions__c> acpList = [Select Id, Name, CS_Contact__c,CS_Asset__c, CS_Access_Type__c from CS_Asset_Contact_Permissions__c];
            
            Test.startTest();
            UTL_CS_CaseTeamMemberUtility.createCaseTeamMember(caseList, accessTypes, acpList);
            Test.stopTest();
        }
    }
    
    static testMethod void testUpdateCaseTeamMember() {
        setupTestData();
        System.runAs(currentUsr) {
            User customerCommunityTestUser = CS_TestDataUtility.createCustomerCommunityTestUser(customerContact);
            
            //query asset
            Asset childAsset = [Select Id, CS_Is_Active__c from Asset where CS_Record_Type_Name__c = 'Child Asset' and ParentId != null limit 1];
            acp = [Select Id from CS_Asset_Contact_Permissions__c limit 1];
            // query case record type
            RecordType rt = [Select Name, developername from RecordType where sobjecttype = 'Case' and Name = 'Customer Support'];
            
            List<Case> caseList = new List<Case>();
            Case c = new Case();
            c.AssetId = childAsset.Id;
            c.AccountId = customerAcc.Id;
            c.RecordTypeId = rt.Id;
            c.ContactId = customerContact.Id;
            c.CS_Contact_Asset__c = acp.Id; 
            caseList.add(c);
            insert caseList;
            
            Set<String> accessTypes = new Set<String>();
            accessTypes.add('Customer Support');
            
            List<CS_Asset_Contact_Permissions__c> acpList = [Select Id, Name, CS_Contact__c,CS_Asset__c, CS_Access_Type__c from CS_Asset_Contact_Permissions__c];
            
            // query just inserted case
            Set<Id> caseIds = new Set<Id>();
            List<Case> cases = [Select Id from Case];
            for (Case ca : cases) {
                caseIds.add(ca.Id);
            }
            
            List<User> usrs = [Select Id from User];
            Set<Id> userIds = new Set<Id>();
            for (User u : usrs) {
                userIds.add(u.Id);
            }
            
            Test.startTest();
            UTL_CS_CaseTeamMemberUtility.updateCaseTeamMember(caseIds, userIds, accessTypes);
            Test.stopTest();
        }
    }
    
    static testMethod void testCreateCaseTeamMember2() {
        setupTestData();
        System.runAs(currentUsr) {
            User customerCommunityTestUser = CS_TestDataUtility.createCustomerCommunityTestUser(customerContact);
            
            //query asset
            Asset childAsset = [Select Id, CS_Is_Active__c from Asset where CS_Record_Type_Name__c = 'Child Asset' and ParentId != null limit 1];
            acp = [Select Id from CS_Asset_Contact_Permissions__c limit 1];
            // query case record type
            RecordType rt = [Select Name, developername from RecordType where sobjecttype = 'Case' and Name = 'Customer Support'];
            
            List<Case> caseList = new List<Case>();
            Case c = new Case();
            c.AssetId = childAsset.Id;
            c.AccountId = customerAcc.Id;
            c.RecordTypeId = rt.Id;
            c.ContactId = customerContact.Id;
            c.CS_Contact_Asset__c = acp.Id; 
            caseList.add(c);
            insert caseList;
            
            Set<String> accessTypes = new Set<String>();
            accessTypes.add('Customer Support');
            
            List<CS_Asset_Contact_Permissions__c> acpList = [Select Id, Name, CS_Contact__c,CS_Asset__c, CS_Access_Type__c from CS_Asset_Contact_Permissions__c];
            
            // query just inserted case
            Set<Id> caseIds = new Set<Id>();
            List<Case> cases = [Select Id from Case];
            for (Case ca : cases) {
                caseIds.add(ca.Id);
            }
            
            List<User> usrs = [Select Id from User];
            Set<Id> userIds = new Set<Id>();
            for (User u : usrs) {
                userIds.add(u.Id);
            }
            
            Test.startTest();
            UTL_CS_CaseTeamMemberUtility.CreateCaseTeamMember(caseIds, userIds, accessTypes);
            Test.stopTest();
        }
    }
    
    static testMethod void testDeleteCaseTeamMember() {
        setupTestData();
        System.runAs(currentUsr) {
            User customerCommunityTestUser = CS_TestDataUtility.createCustomerCommunityTestUser(customerContact);
            
            //query asset
            Asset childAsset = [Select Id, CS_Is_Active__c from Asset where CS_Record_Type_Name__c = 'Child Asset' and ParentId != null limit 1];
            acp = [Select Id from CS_Asset_Contact_Permissions__c limit 1];
            // query case record type
            RecordType rt = [Select Name, developername from RecordType where sobjecttype = 'Case' and Name = 'Customer Support'];
            
            List<Case> caseList = new List<Case>();
            Case c = new Case();
            c.AssetId = childAsset.Id;
            c.AccountId = customerAcc.Id;
            c.RecordTypeId = rt.Id;
            c.ContactId = customerContact.Id;
            c.CS_Contact_Asset__c = acp.Id; 
            caseList.add(c);
            insert caseList;
            
            Set<String> accessTypes = new Set<String>();
            accessTypes.add('Customer Support');
            
            List<CS_Asset_Contact_Permissions__c> acpList = [Select Id, Name, CS_Contact__c,CS_Asset__c, CS_Access_Type__c from CS_Asset_Contact_Permissions__c];
            
            // query just inserted case
            Set<Id> caseIds = new Set<Id>();
            List<Case> cases = [Select Id from Case];
            for (Case ca : cases) {
                caseIds.add(ca.Id);
            }
            
            List<User> usrs = [Select Id from User];
            Set<Id> userIds = new Set<Id>();
            for (User u : usrs) {
                userIds.add(u.Id);
            }
            
            Test.startTest();
            UTL_CS_CaseTeamMemberUtility.deleteCaseTeamMember(caseIds, userIds);
            Test.stopTest();
        }
    }
}