src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Products_Purchased__c</fullName>
        <label>Products Purchased</label>
        <picklist>
            <picklistValues>
                <fullName>BillingCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ClaimCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Data Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DataHub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InfoCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MiAgents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Millbrook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile &amp; Portals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PolicyCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rating Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reinsurance Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standards-based Templates</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Record type used for all Partner records.</description>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Extended_Support__c.object
<CustomObject>
    <description>Created for Shannon McColloch.  Used to track Extended Support records.  Related to Contracts and Accounts.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Extended Supports</relationshipLabel>
        <relationshipName>Extended_Supports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Look up to related Contract record.</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Extended Supports</relationshipLabel>
        <relationshipName>Extended_Supports</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Product_Version__c</fullName>
        <formula>TEXT(Product__r.Current_Product_Version__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulled from related Product record.</inlineHelpText>
        <label>Current Product Version</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Master of Extended Support custom object.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Extended Supports</relationshipLabel>
        <relationshipName>Extended_Supports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to product custom object.</description>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Extended Supports</relationshipLabel>
        <relationshipName>Extended_Supports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Extended Support</label>
    <nameField>
        <displayFormat>ES{000000}</displayFormat>
        <label>Extended Support Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Extended Supports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PRM_Referring_Partner2__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Referring Partner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Referring Partner)</relationshipLabel>
        <relationshipName>Opportunities6</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>Owner - Roopal Shah</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Add_On_Module_s__c</fullName>
        <label>Add On Module(s)</label>
        <picklist>
            <picklistValues>
                <fullName>Client Data Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rating Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reinsurance Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standards-based Templates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Reporting</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Current_Product_Version__c</fullName>
        <label>Current Product Version</label>
        <picklist>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Extended_Support__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for Roll Up Helper.  Ties Product to Extended Support.</description>
        <label>Extended Support</label>
        <referenceTo>Extended_Support__c</referenceTo>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product(C)</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products(C)</pluralLabel>
    <recordTypes>
        <fullName>BillingCenter</fullName>
        <active>true</active>
        <description>Use for BC</description>
        <label>BillingCenter</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProductHelperTest.cls
/******************************************************************************** 
Name: Test
Copyright © 2014 Guidewire
====================================================== 
====================================================== 
Purpose:
  Class
======================================================
====================================================== 
History  -------
VERSION  AUTHOR              DATE         DETAIL                 
1.0 -   Rakshik Bhan      5/15/2014   INITIAL DEVELOPMENT  
*********************************************************************************/
@isTest
public class ProductHelperTest    
{
   
    
    //Test method for ProductBeforeInsertBeforeUpdate Trigger
    testMethod static void test_ProductBeforeInsert()
    {
        Test.startTest();
        list<Account> listAccount = new list<Account>();
        list<Product__c> listProduct = new list<Product__c>();
        //insert Account (Master)
        List<RecordType> lstRecordType =[Select Id from RecordType where Name ='Partner'];
        
        Account objAccount = New Account(name='TestProduct',Products_Purchased__c= 'BillingCenter');
        objAccount.RecordTypeId =lstRecordType[0].Id;
        insert objAccount;
        
        Opportunity opportunity = new Opportunity();
        opportunity.Name ='testOpportunity';
        opportunity.AccountId =objAccount.Id;
        opportunity.Type ='Net New';
        opportunity.PRM_Referring_Partner2__c =objAccount.Id;
        opportunity.StageName ='Working';
        opportunity.CloseDate =Date.Today();
        Database.SaveResult saveResult =Database.insert( opportunity,false);
        //System.assert(saveResult.isSuccess());
        //Test for Bulkification           
         
         Contract contract = new Contract();
         contract.AccountId =objAccount.Id;
         contract.Status ='Draft';
         contract.Invoice_Date__c =Date.today();
         saveResult =Database.insert(contract,false);
         System.assert(saveResult.isSuccess());
         
         Product__c objP = new Product__C(Account__c = objAccount.id, Add_On_Module_s__c ='Standard Reporting' );
         objP.Current_Product_Version__c = '9';
         saveResult =Database.insert(objP,false);
         System.assert(saveResult.isSuccess());
         
         Extended_Support__c ess = new Extended_Support__c(); 
        ess.Product__c = objP.id;
        ess.Contract__c = contract.Id;//[select id from contract limit 1].id;
        ess.Opportunity__c = opportunity.Id; //[select id from Opportunity limit 1].id;
        saveResult =Database.insert(ess,false);
       //  System.assert(saveResult.isSuccess());
            
           //update Product
        objP.Add_On_Module_s__c ='Rating Management' ;
        objP.Current_Product_Version__c = '1';
        ProductHelper.IsExcecuted = false;
        update objP;
        
        Test.stopTest();
        
     }
    
     
}