src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Record type used for all Customer records.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>CS_Primary_Supp_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pri. Support Partner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assets6</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CS_ODC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>On Demand Consulting</description>
        <label>ODC</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <description>Support Contact</description>
        <label>Support</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Asset_Contact_Permissions__c.object
<CustomObject>
    <label>Asset Contact Permission</label>
    <nameField>
        <label>Product Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Contact Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_ByPass__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>ByPass from Triggers,WF Rules and Validation Rules</description>
    <fields>
        <fullName>CS_Disable_ValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ByPass from Validation Rules</description>
        <label>Disable ValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <label>GW ByPass</label>
</CustomObject>

src/objects/CS_Request__c.object
<CustomObject>
    <fields>
        <fullName>CS_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CS_Dev_Jira__c</fullName>
        <label>Dev Jira</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Escalation_Note__c</fullName>
        <inlineHelpText>Description/Synopsis</inlineHelpText>
        <label>Case Summary</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CS_Information_Request__c</fullName>
        <inlineHelpText>Question</inlineHelpText>
        <label>Information Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CS_Request_Status__c</fullName>
        <inlineHelpText>Request Status</inlineHelpText>
        <label>Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Answered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Updated by Requestor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on Requestor</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Request_Type__c</fullName>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>Long Term Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Term Request</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Submitted_First_Time__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box is checked when the request was first submitted</description>
        <label>Submitted First Time</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dev_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dev Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pgm_Request_Owner__c</fullName>
        <label>Pgm Request Owner</label>
        <picklist>
            <picklistValues>
                <fullName>BillingCenter PgM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ClaimCenter PgM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PolicyCenter PgM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Platform PgM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DataManagement PgM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Portals PgM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>Req-{00000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <recordTypes>
        <fullName>Dev_Request</fullName>
        <active>true</active>
        <description>Request Type for Dev</description>
        <label>Dev Request</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>CS_User_Team__c</fullName>
        <label>User Team</label>
        <picklist>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enablement-SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enablement-CE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enablement-Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CS_DevRequestReportTest.cls
/*
    *****************************************************************************************************************************
    Class Name - CS_DevRequestReportTest
    Class Type - Trigger Handler Test Ckass 
    Test Class- N/A
    Purpose- 
    
    *****************************************************************************************************************************
    
    Name        Email              Date             Notes 
    Suchitra                                        Initial Creation
    
    *****************************************************************************************************************************
 */
    
    @isTest
    
    private class CS_DevRequestReportTest{
    
        static testMethod void testCS_DevRequestReportTest() {
        
        
        
            test.StartTest();
            
            PageReference pageRef = Page.CS_DevRequestReport;
            Test.setCurrentPage(pageRef);
            
            
            Account acc = CS_TestDataUtility.createCustomerAccount();
            
            //create parent asset
            List<Asset> parentAsset = CS_TestDataUtility.createParentAssetRecord(acc,true);
            
            //create product
            Product2 prd = CS_TestDataUtility.createProductRecord();
            
            //create pricebook 
            Pricebook2 pb = CS_TestDataUtility.createPriceBook();
            
            //create pricebookentry 
            
            PricebookEntry pbe = CS_TestDataUtility.createPriceBookEntry(prd,pb);
            
            User usrRecord = CS_TestDataUtility.createServiceTestUser();
            
             usrRecord.CS_User_Team__c = 'Enablement-CE';
             
             update usrRecord;
            
            //create child asset
            Asset childAsset = CS_TestDataUtility.createChildAssetRecord(acc, prd, parentAsset[0], 'Implementation');
            
            childAsset.CS_Primary_Supp_Partner__c =  usrRecord.Id;
            
            update childAsset;
            
            //create contact
            Contact con = CS_TestDataUtility.createContact(acc, 'General Customer');
            
            //create service contract 
            ServiceContract sc = CS_TestDataUtility.createServiceContract(acc);  
            
            //create service contracl line items 
            ContractLineItem cntractLineItem =  CS_TestDataUtility.createServiceContractLineItem(sc,  pbe) ;  
            
            
            
            CS_ByPass__c byPassValidation = new CS_ByPass__c();
            byPassValidation.Name = 'CS_Disable_ValidationRule__c';
            byPassValidation.SetupOwnerId = UserInfo.getUserId();
            byPassValidation.CS_Disable_ValidationRule__c = true;
            insert byPassValidation;
            
            //Asset childAsset = CS_TestDataUtility.createChildAssetRecord(acc, prd, childAsset  , 'Production');
            
            
            CS_Asset_Contact_Permissions__c acp = CS_TestDataUtility.createACP(parentAsset[0], con, 'Customer Support', true);

            
            
            // create case
            Case c = CS_TestDataUtility.createCaseCS(acc,childAsset,con);  
            c.CS_ODC__c = false;
                    
            c.OwnerId = usrRecord.Id;
            
            update c; 
            
            
            
            User admin = [SELECT Id FROM user WHERE Profile.Name =:'System Administrator' AND IsActive=:true][0];
    
            
            system.runAs(admin){
                    
             
            RecordType rt = [Select id,name,DeveloperName from RecordType where SobjectType = 'CS_Request__c' and DeveloperName = 'Dev_Request'];
            
            
            CS_Request__c req = new CS_Request__c( recordTypeId = rt.Id,
                                         Pgm_Request_Owner__c ='BillingCenter PgM',
                                         CS_Request_Status__c ='Draft',
                                         CS_Information_Request__c ='Testing',
                                         CS_Case__c = c.Id,
                                         CS_Request_Type__c = 'Short Term Request' );
            
            //insert req;
            
            req.CS_Submitted_First_Time__c = true ;
            req.CS_Escalation_Note__c ='Testing the case';
            req.CS_Dev_Jira__c ='TestJira';
            req.Dev_Assignee__c = admin.Id;
            
            //update req;
            
            system.runAs(usrRecord){
            //test.startTest();
            CS_DevRequestReport caseData = new CS_DevRequestReport();
                        
            System.Debug('caseData is.. ' + caseData );
            
            caseData = new CS_DevRequestReport();
         
            
            List<CS_DevRequestReport.wrapCasewithDevRequest> lstWrappedCase = caseData.caseList;
                  
            caseData.startDate = date.today();
            caseData.endDate = (date.today()).addDays(2);
            
            List<CS_DevRequestReport.wrapCasewithDevRequest> lstWrappedCaseNew = caseData.caseList;
            
            
            caseData.processRequests();
            caseData.SendDates();
            
            }  
            test.stopTest();
        }
    
    }
    }