src/objects/Account_Contact__c.object
<CustomObject>
    <description>This object allows tracking of multiple addresses/sites and Contact types.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill To \ Ship To</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bill To</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ship To</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bill To\ Ship To</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <label>Account Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/trac_relatedAccountsLookup.cls
/**
 * @description 
 *
 * @author Tanminder Rai, Traction On Demand
 * @date May 25/2015
 */

public with sharing class trac_relatedAccountsLookup {

	public List<relatedListCls> relatedList {get; set;}

	public trac_relatedAccountsLookup(ApexPages.StandardController controller) {

		String accId = ApexPages.CurrentPage().getParameters().get('Id');
		Map<Id, Account_Contact__c> relatedACR = new Map<Id, Account_Contact__c>([SELECT Account__c, Contact_Name__c, Contact__c, Contact_Type__c FROM Account_Contact__c WHERE Account__c = :accId]);

		System.debug('relatedACR::'+relatedACR);

		Set<Id> contactIds = new Set<Id>();
		if(!relatedACR.isEmpty()){
			for ( Account_Contact__c acr : relatedACR.values() ){
				contactIds.add(acr.Contact__c);
			}
		}

		Map<Id, Contact> relatedContacts = new Map<Id, Contact>([SELECT Name, MailingAddress FROM Contact WHERE Id IN :contactIds]);
		
		System.debug('relatedContacts::'+relatedContacts);

		relatedList = new List<relatedListCls>();

		if(!relatedACR.isEmpty()){
			for ( Account_Contact__c acr : relatedACR.values() ){
				relatedList.add(new relatedListCls(acr, relatedContacts.get(acr.Contact__c) ));
			}
		}	
		System.debug('relatedList::'+relatedList);


	}

	//Wrapper Class
	class relatedListCls{
		public String name {get; private set;}
		public Address address {get; private set;}
		public String city {get; private set;}
		public String country {get; private set;}
		public String state {get; private set;}
		public String street {get; private set;}
		public String type {get; private set;}

		public relatedListCls(Account_Contact__c accountContact, Contact cont){
			name = accountContact.Contact_Name__c;
			address = cont.MailingAddress;
			if (address != null ){
				city = cont.MailingAddress.getCity() != null ? cont.MailingAddress.getCity(): '';
				country = cont.MailingAddress.getCountry() != null ? cont.MailingAddress.getCountry(): '';
				state = cont.MailingAddress.getState() != null ? cont.MailingAddress.getState(): '';
				street = cont.MailingAddress.getStreet() != null ? cont.MailingAddress.getStreet(): '';
			}

			type = accountContact.Contact_Type__c;
		}

	}
}