src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Participant_id__c</fullName>
        <externalId>true</externalId>
        <label>Participant ID</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PSA_Billing_Level__c</fullName>
        <description>PSA - Resource&apos;s billing level</description>
        <inlineHelpText>Resource billing level</inlineHelpText>
        <label>Billing Level</label>
        <picklist>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>105</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>110</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>130</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>140</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>220</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Blended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH Offshore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actuary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor17</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSA_PS_Level__c</fullName>
        <label>PS Level</label>
        <picklist>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>105</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>110</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>130</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>140</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>141</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>142</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>143</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>145</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>150</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>153</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>155</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>160</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>163</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>165</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>203</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>206</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>210</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>220</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>230</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>235</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>240</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>245</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>250</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>255</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>300</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>305</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>310</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pse__Practice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Practice</label>
        <referenceTo>pse__Practice__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>pse__Region__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PSA_Cost_Rate__c.object
<CustomObject>
    <fields>
        <fullName>PSA_Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used in combination with Legal Entity and PS Level to match with Resources</description>
        <inlineHelpText>Used in combination with Legal Entity and PS Level to match with Resources</inlineHelpText>
        <label>Department</label>
        <referenceTo>PSA_Department__c</referenceTo>
        <relationshipLabel>PSA Cost Rates</relationshipLabel>
        <relationshipName>PSA_Cost_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_PS_Level__c</fullName>
        <label>PS Level</label>
        <picklist>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>105</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>110</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>130</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>140</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>141</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>142</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>145</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>150</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>203</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>206</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>210</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>220</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>230</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>235</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>240</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>245</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>250</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>255</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>300</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>305</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>310</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>320</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>330</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>335</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>340</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>345</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>350</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PSA Cost Rate</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Cost Rate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSA Cost Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSA_Department__c.object
<CustomObject>
    <fields>
        <fullName>PSA_Department_Code__c</fullName>
        <externalId>true</externalId>
        <label>Department Code</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_PS_Department__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True if the department is considered to be part of Professional Services (as it relates to PSA)</description>
        <label>PS Department</label>
        <type>Checkbox</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSA_Entity__c.object
<CustomObject>
    <description>Represents the Guidewire billing legal entity associated with this project. Note, there is a flag required on legal entity set-up to identify if legal entity should be available as billing entity or not.</description>
    <fields>
        <fullName>PSA_Billing_Entity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing Entity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSA_Entity_Code__c</fullName>
        <externalId>true</externalId>
        <label>Entity Code</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_GLA_In__c</fullName>
        <description>Entity&apos;s GLA In code.  Used by intercompany transfer functionality and reporting</description>
        <inlineHelpText>Entity&apos;s GLA In code.  Used by intercompany transfer functionality and reporting</inlineHelpText>
        <label>GLA In</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_GLA_Out__c</fullName>
        <description>Entity&apos;s GLA Out code.  Used by intercompany transfer functionality and reporting</description>
        <inlineHelpText>Entity&apos;s GLA Out code.  Used by intercompany transfer functionality and reporting</inlineHelpText>
        <label>GLA Out</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Short_Name__c</fullName>
        <label>Short Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSA_PS_Level_Billing_Level__c.object
<CustomObject>
    <description>Contains a mapping of PS Level to Billing Levels</description>
    <fields>
        <fullName>PSA_Billing_Level__c</fullName>
        <label>Billing Level</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_PS_Level__c</fullName>
        <label>PS Level</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Title__c</fullName>
        <description>For informational purposes only</description>
        <inlineHelpText>For informational purposes only</inlineHelpText>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>PSA PS Level Billing Level</label>
    <nameField>
        <displayFormat>PLBL-{000}</displayFormat>
        <label>PS Level Billing Level Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSA PS Level Billing Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/psaContactTriggerHandlerTest.cls
@isTest
private class psaContactTriggerHandlerTest {
	
	@isTest static void test_method_one() {
		psaTestUtils.initDefaultWorkCalendar();
        //Create RPG
        pse__Region__c testR = psaTestUtils.createTestRegion('Corporate');
        pse__Practice__c testP = psaTestUtils.createTestPractice('Corporate');
        pse__Grp__c testG = psaTestUtils.createTestGroup('Corporate');
        Account a = psaTestUtils.createTestAccount('Test Account', '12345');
        a.Participant_id__c = '1234';
        update a;
        //Create 2 contacts, one to submit and one as the manager

        PSA_Department__c dep = new PSA_Department__C();
        dep.Name = 'Test Department';
        dep.PSA_Department_Code__c = '1243';
        dep.PSA_PS_Department__c = true;
        insert dep;

        PSA_PS_Level_Billing_Level__c level1 = new PSA_PS_Level_Billing_Level__c();
        level1.PSA_Billing_Level__c = '100';
        level1.PSA_PS_Level__c = '100';
        level1.PSA_Title__c = 'The Title';
        insert level1;

        PSA_PS_Level_Billing_Level__c level2 = new PSA_PS_Level_Billing_Level__c();
        level2.PSA_Billing_Level__c = '200';
        level2.PSA_PS_Level__c = '200';
        level2.PSA_Title__c = 'The Title 2';
        insert level2;

        PSA_Entity__c entity = new PSA_Entity__c();
        entity.PSA_Billing_Entity__c = false;
        entity.psa_entity_code__c = '1234';
        entity.PSA_GLA_In__c = '515324';
        entity.PSA_GLA_Out__c = '15345';
        entity.PSA_Short_Name__c = 'name1';
        insert entity;

        PSA_Cost_Rate__c rate = new PSA_Cost_Rate__c();
        rate.CurrencyIsoCode = 'USD';
        rate.PSA_Delivery_Cost_Rate__c = 123;
        rate.PSA_Effective_Date__c = Date.Today() - 5;
        rate.PSA_Fully_Loaded_Cost_Rate__c = 143;
        rate.PSA_Legal_Entity__c = entity.id;
        rate.PSA_PS_Level__c = '100';
        rate.PSA_Propagated_Date__c = Date.Today() - 4;
        rate.PSA_Department__c = dep.id;
        insert rate;

 

        Test.StartTest();
        User u = psaTestUtils.createTestUser('userCLD2', 'tuserCLD2@tuser.com', 'userCLD2', 'test2', 'tuserCLD2@tuser.com', 'tuserCLD2');
        Contact c = psaTestUtils.createTestResource(u, testR, testP, testG, false);
        c.LastName = 'Test1';
        c.PSA_Termination_Date__c = Date.today() + 15;
        c.PSA_Absence_Start_Date__c = Date.today() - 5;
        c.PSA_Absence_End_Date__c = Date.today() + 5;
        c.PSA_PS_Level__c = '100';
        c.PSA_Global_Mobile__c = true;
        insert c;

        User u2 = psaTestUtils.createTestUser('userCLD3', 'tuserCLD3@tuser.com', 'userCLD3', 'test3', 'tuserCLD3@tuser.com', 'tuserCLD3');
        Contact c2 = psaTestUtils.createTestResource(u2, testR, testP, testG, false);
        c2.PSA_Termination_Date__c = Date.today() + 15;
        c2.lastName = 'Test2';
        c2.PSA_Absence_Start_Date__c = Date.today() - 5;
        c2.PSA_Absence_End_Date__c = Date.today() + 5;
        c2.PSA_PS_Level__c = '100';
        c2.PSA_Global_Mobile__c = false;
        c2.PSA_Resource_Department__c = dep.id;
        insert c2;

        //Testing an updated contact where department changes, 
        PSA_Department__c dep2 = new PSA_Department__C();
        dep2.Name = 'Test Department';
        dep2.PSA_Department_Code__c = '1243';
        dep2.PSA_PS_Department__c = false;
        insert dep2;

        PSA_Department__c dep3 = new PSA_Department__C();
        dep3.Name = 'Test Department';
        dep3.PSA_Department_Code__c = '1243';
        dep3.PSA_PS_Department__c = false;
        insert dep3;

        PSA_Cost_Rate__c rate2 = new PSA_Cost_Rate__c();
        rate2.CurrencyIsoCode = 'USD';
        rate2.PSA_Delivery_Cost_Rate__c = 123;
        rate2.PSA_Effective_Date__c = Date.Today() - 5;
        rate2.PSA_Fully_Loaded_Cost_Rate__c = 143;
        rate2.PSA_Legal_Entity__c = entity.id;
        rate2.PSA_PS_Level__c = '200';
        rate2.PSA_Propagated_Date__c = Date.Today() - 4;
        rate2.PSA_Department__c = dep2.id;
        insert rate2;


        c2.PSA_Absence_End_Date__c = Date.Today() + 4;
        c2.PSA_Absence_Start_Date__c = Date.Today() - 6;
        c2.PSA_Resource_Department__c = dep3.id;
        c2.PSA_PS_Level__c = '300';
        c2.PSA_Global_Mobile__c = true;
        c2.PSA_Termination_Date__c = Date.Today() + 25;
        update c2;

        c2.PSA_Global_Mobile__c = false;
        update c2;


	}
	
	@isTest static void test_method_two() {
		// Implement test code
	}
	
}