src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Participant_id__c</fullName>
        <externalId>true</externalId>
        <label>Participant ID</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PSA_Billing_Level__c</fullName>
        <description>PSA - Resource&apos;s billing level</description>
        <inlineHelpText>Resource billing level</inlineHelpText>
        <label>Billing Level</label>
        <picklist>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>105</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>110</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>130</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>140</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>220</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Blended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH Offshore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actuary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor17</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSA_Resource_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource Entity</label>
        <referenceTo>PSA_Entity__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Worker_Id__c</fullName>
        <description>Unique, External Identifier from Workday</description>
        <externalId>true</externalId>
        <label>Worker Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>pse__Is_Resource_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Resource Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pse__Practice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Practice</label>
        <referenceTo>pse__Practice__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>pse__Region__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PSA_Card_Transaction__c.object
<CustomObject>
    <description>This object will contain the results of the BoA integration with Guidewire for handoff of corporate card transaction data.  The table below describes each data element:</description>
    <fields>
        <fullName>PSA_Card_Transaction_Stage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the staging object used to create this card transaction</description>
        <inlineHelpText>the staging object used to create this card transaction</inlineHelpText>
        <label>PSA Card Transaction Stage</label>
        <referenceTo>PSA_Card_Transaction_Stage__c</referenceTo>
        <relationshipLabel>PSA Card Transactions</relationshipLabel>
        <relationshipName>PSA_Card_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_EmployeeId__c</fullName>
        <description>Employee Id provided by Bank of America - for lookup of the corresponding PSA Resource / Salesforce User</description>
        <label>EmployeeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Expense_Type__c</fullName>
        <label>PSA Expense Type</label>
        <picklist>
            <picklistValues>
                <fullName>Airfare - Domestic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Airfare - International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visas/Passport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corp Apartment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taxi/Train/Public Transit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parking/Tolls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gas for Rental Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Mileage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meals - Self - Breakfast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meals - Self - Lunch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meals - Self - Dinner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meals - GW Emp Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meals - With 3rd Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meals - Per Diem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertain - GW Emp only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertain - With 3rd Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telecom - Mobile (Cell)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telecom - Non Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency exch/bank fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excess Baggage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Expense - T &amp; E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Laundry/Dry Cleaning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office Supplies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postage/Courier Cost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relocation Exp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tax Prep Cost for Addtl State(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tips/Gratuities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dept/Co Meetings &amp; Events</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSA_Incurred_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incurred Country</label>
        <referenceTo>pw_cc__CountryObject__c</referenceTo>
        <relationshipLabel>PSA Card Transactions</relationshipLabel>
        <relationshipName>PSA_Card_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Incurred_State_Province__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incurred State / Province</label>
        <referenceTo>pw_cc__State__c</referenceTo>
        <relationshipLabel>PSA Card Transactions</relationshipLabel>
        <relationshipName>PSA_Card_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Merchant_Country_Code__c</fullName>
        <description>For setting the expense description and incurred location info on the expense</description>
        <label>Merchant Country Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Operations_Review_Reason__c</fullName>
        <description>NUSR - (No Salesforce User Found)
NCNT - (No Contact Found)
NRSC - (Contact.pse__Is_Resource__c = False)
ACTV - (Contact.pse__Is_Resource_Active__c = False)
TERM - (Contact.PSA_Resource_Review_Status__c = ‘Termination’)
TRNS - (Contact.PSA_Resource_Review_Status__c = ‘Transfer Out’)
LCTN - (No matching country or state objects were found and so the Incurred Country and/or Incurred State / Province could not be set)</description>
        <label>Operations Review Reason</label>
        <picklist>
            <picklistValues>
                <fullName>NUSR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NRSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TERM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRNS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LCTN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSA_Operations_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Operations Review</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSA_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PSA Card Transactions</relationshipLabel>
        <relationshipName>PSA_Card_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Salesforce user associated with the EmployeeId value.  For mapping of the transaction to a PSA user. Each PSA Card Transaction record will be given ownership to this user, so that with private sharing enabled, users won’t be able to see each others’ card transaction info.</description>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PSA_Card_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PSA Card Transaction</label>
    <nameField>
        <label>PSA Card Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSA Card Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PSA_Card_Transaction_Stage__c.object
<CustomObject>
    <fields>
        <fullName>PSA_EmployeeId__c</fullName>
        <description>Employee Id provided by Bank of America - for lookup of the corresponding PSA Resource / Salesforce User.</description>
        <label>EmployeeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PSA Card Transaction Stage</label>
    <nameField>
        <displayFormat>CCTX-{00000000}</displayFormat>
        <label>Transaction Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSA Card Transaction Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PSA_Worker_Id__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Unique Worker Id from Workday</inlineHelpText>
        <label>Worker Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/psaCardTransactionLoaderTest.cls
/*************************************************************************
Name:           psaCardTransactionLoaderTest
Author:         CLD
Created Date:   10/20/2015
Description:    Tests related to psaCardTransactionLoader
*************************************************************************/
@isTest(seeAllData=false)
private class psaCardTransactionLoaderTest
{
    static PSA_Card_Transaction_Stage__c[] stageObjects;
    static Contact testResource;
    static Contact testResource2;

    static pw_cc__CountryObject__c pcc ;
    static pw_cc__State__c pcs ;

    static  {
        setupTestData();
    }

    @isTest static void itSchedulesAndLoadsCardTransactions()
    {
        Integer preTransCount = [select count() from PSA_Card_Transaction__c];

        Test.startTest();

        psaCardTransactionLoaderSchedule s = new psaCardTransactionLoaderSchedule();
        s.execute(null);

        Test.stopTest();

        // verify our card transactions were created
        Integer postTransCount = [select count() from PSA_Card_Transaction__c];
        system.assert(postTransCount > preTransCount);

        // cover unassigning card transactions!
        Set<Id> stageIds = new Set<Id>();
        for (PSA_Card_Transaction__c ct : [select id from PSA_Card_Transaction__c limit 2]){  stageIds.add(ct.id); }
        psaCardTransactionLoader.unassignCardTransactions(stageIds);
    }

    @isTest static void itSyncsResourceAndOwnerFromUser()
    {
        Test.startTest();

        PSA_Card_Transaction__c cardTrans = new PSA_Card_Transaction__c();
        cardTrans.PSA_Incurred_Country__c = pcc.id;
        cardTrans.PSA_Incurred_State_Province__c = pcs.id;

        insert cardTrans;

        cardTrans.PSA_Salesforce_User__c = testResource.pse__Salesforce_User__c;

        update cardTrans;

        psaCardTransactionLoader.syncResourceAndOwnerFromUser(new PSA_Card_Transaction__c[]{cardTrans});

        Test.stopTest();

        PSA_Card_Transaction__c psaCardTrans = [select id,PSA_Salesforce_User__c,PSA_Resource__c,OwnerId,PSA_Operations_Review__c, PSA_Operations_Review_Reason__c, PSA_Incurred_Country__c, PSA_Incurred_State_Province__c from PSA_Card_Transaction__c where id = :cardTrans.id];

        //system.debug('\n ***************** \n psaCardTrans > ' + psaCardTrans + '\n ************ \n');

        system.assert(psaCardTrans.PSA_Salesforce_User__c == testResource.pse__Salesforce_User__c);
        system.assert(psaCardTrans.PSA_Resource__c == testResource.id);
        system.assert(psaCardTrans.OwnerId == testResource.pse__Salesforce_User__c);

    }

    private static void setupTestData()
    {
        psaTestUtils.initDefaultWorkCalendar();
        //Create RPG
        pse__Region__c testR = psaTestUtils.createTestRegion('Corporate');
        pse__Practice__c testP = psaTestUtils.createTestPractice('Corporate');
        pse__Grp__c testG = psaTestUtils.createTestGroup('Corporate');

        //Create test account with a location so that locations will be created
        Account a = psaTestUtils.createTestAccount('Test Account', '12345');
        a.Participant_id__c = '1234';
        update a;
        PSA_Entity__c testentity = psaTestUtils.createTestEntity('Test E', '1234', 'TE', true);

        //User testUser = psaTestUtils.createTestUser('userCLD2', 'tuserCLD2@tuser.com', 'userCLD2', 'test2', 'tuserCLD2@tuser.com', 'tuserCLD2');
        User testUser = psaTestUtils.createTestUser('userCLD2', 'tuserCLD2@tuser.com', 'userCLD2', 'test2', 'tuserCLD2@tuser.com', 'tuserCLD2');
        testUser.PSA_Worker_Id__c = 'userCLD2';

        User testUser2 = psaTestUtils.createTestUser('uCLDTST', 'tuserCLDTST@tuser.com', 'uCLDTST', 'test2TST', 'tuserCLDTST@tuser.com', 'tuserCLD2TST');
        testUser2.PSA_Worker_Id__c = 'userCLDTEST';

        User testUser3 = psaTestUtils.createTestUser('userCLD3', 'tuseruserCLD3@tuser.com', 'userCLD3', 'test3TST', 'tuseruserCLD3@tuser.com', 'tuserCLD3');
        testUser3.PSA_Worker_Id__c = 'ACTV';

        update new User[]{testUser, testUser2, testUser3};

        //update testUser2;

        testResource = psaTestUtils.createTestResource(testUser, testR, testP, testG);
        testResource.PSA_Resource_Entity__c = testentity.id;
        testResource.PSA_Billing_Level__c = '120';
        testResource.PSA_Worker_Id__c = 'userCLD2';

        update testResource;


        testResource2 = psaTestUtils.createTestResource(testUser3, testR, testP, testG);
        testResource2.PSA_Resource_Entity__c = testentity.id;
        testResource2.PSA_Billing_Level__c = '120';
        testResource2.PSA_Worker_Id__c = 'ACTV';
        testResource2.pse__Is_Resource_Active__c = false;
        update testResource2;


        pcc = new pw_cc__CountryObject__c(
            pw_cc__IsoCode_3__c = 'USA',
            pw_cc__IsoCode_2__c = 'US'
        );
        insert pcc;

        pcs = new pw_cc__State__c(
            pw_cc__Country__c = pcc.id,
            pw_cc__IsoCode__c = 'VA');
        insert pcs;

        //PSA_Card_Expense_Type_Map__c expTypeMap = new PSA_Card_Expense_Type_Map__c(
        //    PSA_Card_Expense_Category_Code__c = 'Category1',
        //    PSA_Expense_Type__c = 'ExpType1'
        //);
        //insert expTypeMap;


        // dummy up some card transaction stage objects

        stageObjects = new PSA_Card_Transaction_Stage__c[]{};

        stageObjects.add(new PSA_Card_Transaction_Stage__c(
            PSA_EmployeeId__c = 'userCLD2',
            PSA_Merchant_Country_Code__c = 'USA',
            //PSA_Expense_Category_Code__c = 'Category1',
            PSA_Merchant_State_Province__c = 'VA'
        ));

        // should produce NUSR
        stageObjects.add(new PSA_Card_Transaction_Stage__c(
            PSA_EmployeeId__c = 'xyz',
            PSA_Merchant_Country_Code__c = 'USA',
            //PSA_Expense_Category_Code__c = 'Category1',
            PSA_Merchant_State_Province__c = 'VA'
        ));

        stageObjects.add(new PSA_Card_Transaction_Stage__c(
            PSA_EmployeeId__c = 'userCLDTEST',
            PSA_Merchant_Country_Code__c = 'USA',
            //PSA_Expense_Category_Code__c = 'Category1',
            PSA_Merchant_State_Province__c = 'VA'
        ));

        stageObjects.add(new PSA_Card_Transaction_Stage__c(
            PSA_EmployeeId__c = 'ACTV',
            PSA_Merchant_Country_Code__c = 'USA',
            //PSA_Expense_Category_Code__c = 'Category1',
            PSA_Merchant_State_Province__c = 'VA'
        ));

        // should produce LCTN
        stageObjects.add(new PSA_Card_Transaction_Stage__c(
            PSA_EmployeeId__c = 'userCLD2',
            PSA_Merchant_Country_Code__c = '',
            //PSA_Expense_Category_Code__c = 'Category1',
            PSA_Merchant_State_Province__c = ''
        ));


        insert stageObjects;
   }

}