src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Buying_Entity__c</fullName>
        <inlineHelpText>Whether, in our judgment, this entity makes independent decisions about system purchases (as opposed to a subsidiary that has no operational distinction from its parent).</inlineHelpText>
        <label>Buying Entity</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t Know</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Record type used for all Partner records.</description>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Feedback_Questions__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>true</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>false</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question_Section__c</fullName>
        <label>Question Section</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Feedback Questions</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Feedback Questions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PRM_Referring_Partner2__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Referring Partner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Referring Partner)</relationshipLabel>
        <relationshipName>Opportunities6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Premium_In_Scope__c</fullName>
        <inlineHelpText>This should be the deal premium in scope or the incremental DWP Adjustment. Used in conjunction with Price Rules to calculate the price for certain Products.</inlineHelpText>
        <label>Premium In Scope</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SWOT_Opportunities__c</fullName>
        <description>The Opportunities aspect of the SWOT</description>
        <inlineHelpText>Opportunities EXTERNAL to Guidewire</inlineHelpText>
        <label>Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_SO__c</fullName>
        <inlineHelpText>Strategy for addressing the Opportunities in the context of our Strengths</inlineHelpText>
        <label>Strengths/Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_ST__c</fullName>
        <inlineHelpText>Strategy for addressing the Threats in the context of our Strengths</inlineHelpText>
        <label>Strengths/Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_WO__c</fullName>
        <inlineHelpText>Strategy for addressing Opportunities in the context of our Weaknesses</inlineHelpText>
        <label>Weaknesses/Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_WT__c</fullName>
        <inlineHelpText>Strategy for addressing the Threats in the context of our Weaknesses</inlineHelpText>
        <label>Weaknesses/Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strengths__c</fullName>
        <inlineHelpText>Guidewire Strengths</inlineHelpText>
        <label>Strengths</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Threats__c</fullName>
        <inlineHelpText>Threats external to Guidewire</inlineHelpText>
        <label>Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Weaknesses__c</fullName>
        <inlineHelpText>Guidewire Weaknesses</inlineHelpText>
        <label>Weaknesses</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Event__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Events</relationshipLabel>
        <relationshipName>Sales_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Tentative</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Event_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Event__c</fullName>
        <label>Sales Event</label>
        <referenceTo>Sales_Event__c</referenceTo>
        <relationshipLabel>Sales Event Feedbacks</relationshipLabel>
        <relationshipName>Sales_Event_Feedbacks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Event Feedback</label>
    <nameField>
        <displayFormat>SEF-{0000}</displayFormat>
        <label>Sales Event Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Event Feedbacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Event_Feedback_Questions__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Feedback_Questions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Feedback Questions</label>
        <referenceTo>Feedback_Questions__c</referenceTo>
        <relationshipLabel>Sales Event Feedback Questions</relationshipLabel>
        <relationshipName>Sales_Event_Feedback_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Section__c</fullName>
        <label>Question Section</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Event_Feedback__c</fullName>
        <label>Sales Event Feedback</label>
        <referenceTo>Sales_Event_Feedback__c</referenceTo>
        <relationshipLabel>Sales Event Feedback Questions</relationshipLabel>
        <relationshipName>Sales_Event_Feedback_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Event__c</fullName>
        <formula>Sales_Event_Feedback__r.Sales_Event__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Event</label>
        <type>Text</type>
    </fields>
    <label>Sales Event Feedback Questions</label>
    <nameField>
        <displayFormat>SEFQ-{0000}</displayFormat>
        <label>Sales Event Feedback Questions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Event Feedback Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestSalesEventFBackOverrideExt.cls
@isTest(seeAllData=true)
private class TestSalesEventFBackOverrideExt
{
    static testMethod void SalesEventTest() {
        Id recordId = [Select Id from RecordType Where Name ='Partner' AND sObjectType='Account' limit 1].Id;
        system.debug('==****'+recordId);
        Account account = new Account();
        account.RecordTypeId = recordId;
        system.debug('=='+account.RecordType);
        account.Name = 'testAcc';
        account.Type = 'Other';
        account.Buying_Entity__c = 'Yes';
        account.Industry = 'Other';
        insert account;
        
        system.debug('==****'+account);
        
        Opportunity o = new Opportunity(SWOT_Strengths__c='S Value',
                                        SWOT_Weaknesses__c='W Value',
                                        SWOT_Opportunities__c = 'O Value',
                                        SWOT_Threats__c = 'T Value',
                                        SWOT_Strategy_SO__c = 'SO Value',
                                        SWOT_Strategy_ST__c = 'ST Value',
                                        SWOT_Strategy_WO__c = 'WO Value',
                                        SWOT_Strategy_WT__c = 'WT Value',
                                        Name = 'Test SWOT Opportunity',
                                        StageName = 'Qualified',
                                        CloseDate = Date.today(),
                                        Premium_In_Scope__c = 1000,
                                //      PRM_Referring_Partner2__c = account.Id,
                                        Amount=100   );
        insert o;
        
        
        Sales_Event__c event = new Sales_Event__c(Opportunity__c = o.Id, Status__c = 'Tentative');
        insert event;
        
        Sales_Event_Feedback__c salesEventFeedback = new Sales_Event_Feedback__c();
        salesEventFeedback.Sales_Event__c = event.Id;
        insert salesEventFeedback;
        
        Feedback_Questions__c feedbackQuestions = new Feedback_Questions__c();
        feedbackQuestions.Active__c = 'true';
        feedbackQuestions.Question_Section__c ='Preparation';
        insert feedbackQuestions;
        
        Feedback_Questions__c feedbackQuestions1 = new Feedback_Questions__c();
        feedbackQuestions1.Active__c = 'true';
        feedbackQuestions1.Question_Section__c ='Preparation';
        insert feedbackQuestions1;

        Feedback_Questions__c feedbackQuestions2 = new Feedback_Questions__c();
        feedbackQuestions2.Active__c = 'true';
        feedbackQuestions2.Question_Section__c ='Preparation';
        insert feedbackQuestions2;

        Feedback_Questions__c feedbackQuestions3 = new Feedback_Questions__c();
        feedbackQuestions3.Active__c = 'true';
        feedbackQuestions3.Question_Section__c  ='Event';
        insert feedbackQuestions3;

        Feedback_Questions__c feedbackQuestions4 = new Feedback_Questions__c();
        feedbackQuestions4.Active__c = 'true';
        feedbackQuestions4.Question_Section__c ='Event Comments';
        insert feedbackQuestions4;
        
        List<Sales_Event_Feedback_Questions__c> salesEventFBackQuestionList = new List<Sales_Event_Feedback_Questions__c>();
        salesEventFBackQuestionList.add( new Sales_Event_Feedback_Questions__c( Feedback_Questions__c = feedbackQuestions.Id, Sales_Event_Feedback__c = salesEventFeedback.Id, Answer__c = 'Not Applicable', Question_Section__c = 'Preparation'));
        salesEventFBackQuestionList.add( new Sales_Event_Feedback_Questions__c( Feedback_Questions__c = feedbackQuestions.Id, Sales_Event_Feedback__c = salesEventFeedback.Id, Answer__c = 'Neutral', Question_Section__c = 'Event'));
        salesEventFBackQuestionList.add( new Sales_Event_Feedback_Questions__c( Feedback_Questions__c = feedbackQuestions.Id, Sales_Event_Feedback__c = salesEventFeedback.Id, Answer__c = 'Negative', Question_Section__c = 'Preparation Section'));
        salesEventFBackQuestionList.add( new Sales_Event_Feedback_Questions__c( Feedback_Questions__c = feedbackQuestions.Id, Sales_Event_Feedback__c = salesEventFeedback.Id, Answer__c = 'Positive', Question_Section__c = 'Domain Expertise'));
        salesEventFBackQuestionList.add( new Sales_Event_Feedback_Questions__c( Feedback_Questions__c = feedbackQuestions.Id, Sales_Event_Feedback__c = salesEventFeedback.Id, Answer__c = null, Question_Section__c = 'Selling Skil'));
        salesEventFBackQuestionList.add( new Sales_Event_Feedback_Questions__c( Feedback_Questions__c = feedbackQuestions.Id, Sales_Event_Feedback__c = salesEventFeedback.Id, Answer__c = '', Question_Section__c = 'Event Comments'));
        
        insert salesEventFBackQuestionList;
        
        ApexPages.currentPage().getParameters().put('SalesEventId', event.Id);
        ApexPages.StandardController controller = new ApexPages.StandardController(salesEventFeedback);
        SalesEventFeedBackOverrideExtension objSalesEventFBackExNew = new SalesEventFeedBackOverrideExtension(controller);
        objSalesEventFBackExNew.updateAnswer();
        objSalesEventFBackExNew.getEventaccom();
        objSalesEventFBackExNew.getQuestions();
        objSalesEventFBackExNew.getEventFeedback();
        objSalesEventFBackExNew.getPresentation();
        objSalesEventFBackExNew.getPreparationSection();
        objSalesEventFBackExNew.getDomainExpSection();
        objSalesEventFBackExNew.getDomain();
        objSalesEventFBackExNew.getSkillSec();
        objSalesEventFBackExNew.getSelling();
        objSalesEventFBackExNew.getComments();
        objSalesEventFBackExNew.getAnswers();
        objSalesEventFBackExNew.feedbacksave();
        
        
        Sales_Event_Feedback_Questions__c salesEventFBackQuestions = new Sales_Event_Feedback_Questions__c();
        salesEventFBackQuestions.Sales_Event_Feedback__c = salesEventFeedback.Id;
        salesEventFBackQuestions.Feedback_Questions__c =feedbackQuestions.Id;
        insert salesEventFBackQuestions;
        
        Sales_Event_Feedback_Questions__c salesEventFBackQuestions1 = new Sales_Event_Feedback_Questions__c();
        salesEventFBackQuestions1.Sales_Event_Feedback__c = salesEventFeedback.Id;
        salesEventFBackQuestions1.answer__c = 'Not Applicable';
        salesEventFBackQuestions1.Feedback_Questions__c =feedbackQuestions1.Id;
        insert salesEventFBackQuestions1;
        
        Sales_Event_Feedback_Questions__c salesEventFBackQuestions3 = new Sales_Event_Feedback_Questions__c();
        salesEventFBackQuestions3.Sales_Event_Feedback__c = salesEventFeedback.Id;
        salesEventFBackQuestions3.answer__c = 'Neutral';
        salesEventFBackQuestions3.Feedback_Questions__c =feedbackQuestions2.Id;
        insert salesEventFBackQuestions3;
        
        Sales_Event_Feedback_Questions__c salesEventFBackQuestions2 = new Sales_Event_Feedback_Questions__c();
        salesEventFBackQuestions2.Sales_Event_Feedback__c = salesEventFeedback.Id;
        salesEventFBackQuestions2.answer__c = 'Negative';
        salesEventFBackQuestions2.Feedback_Questions__c =feedbackQuestions3.Id;
        insert salesEventFBackQuestions2;

        Sales_Event_Feedback_Questions__c salesEventFBackQuestions4 = new Sales_Event_Feedback_Questions__c();
        salesEventFBackQuestions4.Sales_Event_Feedback__c = salesEventFeedback.Id;
        salesEventFBackQuestions4.answer__c = 'Positive';
        salesEventFBackQuestions4.Feedback_Questions__c =feedbackQuestions4.Id;
        insert salesEventFBackQuestions4;
                
        //objSalesEventFBackExNew.questionSectionMap.put('Preparation', salesEventFBackQuestions);
        //objSalesEventFBackExNew.questionSectionMap.put('Preparation', salesEventFBackQuestions);
        //objSalesEventFBackExNew.questionSectionMap.put('Preparation', salesEventFBackQuestions);
        
        SalesEventFeedBackOverrideExtension.feedbackQuestionsWrapper objFeedbackQuestionsWrapper = new SalesEventFeedBackOverrideExtension.feedbackQuestionsWrapper(feedbackQuestions, salesEventFBackQuestions);
        SalesEventFeedBackOverrideExtension.feedbackQuestionsWrapper objFeedbackQuestionsWrapper1 = new SalesEventFeedBackOverrideExtension.feedbackQuestionsWrapper(feedbackQuestions, salesEventFBackQuestions1);
        SalesEventFeedBackOverrideExtension.feedbackQuestionsWrapper objFeedbackQuestionsWrapper2 = new SalesEventFeedBackOverrideExtension.feedbackQuestionsWrapper(feedbackQuestions, salesEventFBackQuestions2);
        SalesEventFeedBackOverrideExtension.feedbackQuestionsWrapper objFeedbackQuestionsWrapper3 = new SalesEventFeedBackOverrideExtension.feedbackQuestionsWrapper(feedbackQuestions, salesEventFBackQuestions3);
        SalesEventFeedBackOverrideExtension.feedbackQuestionsWrapper objFeedbackQuestionsWrapper4 = new SalesEventFeedBackOverrideExtension.feedbackQuestionsWrapper(feedbackQuestions, salesEventFBackQuestions4);
        //new SalesEventFeedBackOverrideExtension.feedbackQuestionsWrapper(null, new Sales_Event_Feedback_Questions__c( answer__c = 'Not Applicable'));
        //new SalesEventFeedBackOverrideExtension.feedbackQuestionsWrapper(null, new Sales_Event_Feedback_Questions__c( answer__c = 'Neutral'));
        //new SalesEventFeedBackOverrideExtension.feedbackQuestionsWrapper(null, new Sales_Event_Feedback_Questions__c( answer__c = 'Negative'));
        //new SalesEventFeedBackOverrideExtension.feedbackQuestionsWrapper(null, new Sales_Event_Feedback_Questions__c( answer__c = 'Positive'));
        
        List<SalesEventFeedBackOverrideExtension.feedbackQuestionsWrapper> lst = new List<SalesEventFeedBackOverrideExtension.feedbackQuestionsWrapper>();
        
        lst.add(objFeedbackQuestionsWrapper);
        lst.add(objFeedbackQuestionsWrapper1);
        lst.add(objFeedbackQuestionsWrapper2);
        lst.add(objFeedbackQuestionsWrapper3);
        lst.add(objFeedbackQuestionsWrapper4);
        lst.add(new SalesEventFeedBackOverrideExtension.feedbackQuestionsWrapper(null, null));
        SalesEventFeedBackOverrideExtension objSalesEventFBackExNew1 = new SalesEventFeedBackOverrideExtension(controller);
        objSalesEventFBackExNew1.questionSectionMap.put('Preparation', lst);
        objSalesEventFBackExNew1.questionSectionMap.put('Event', lst);
        objSalesEventFBackExNew1.questionSectionMap.put('Event Comments', lst);
        objSalesEventFBackExNew1.feedbacksave();
        objSalesEventFBackExNew1.getQuestions()[0].answer.answer__c='No';
        map<id,Sales_Event_Feedback_Questions__c> mapQuestionAnswer1 =new map<id,Sales_Event_Feedback_Questions__c>();
        mapQuestionAnswer1.put(salesEventFBackQuestions.Feedback_Questions__c,salesEventFBackQuestions);
        mapQuestionAnswer1.put(salesEventFBackQuestions1.Feedback_Questions__c,salesEventFBackQuestions1);
        mapQuestionAnswer1.put(salesEventFBackQuestions2.Feedback_Questions__c,salesEventFBackQuestions2);
        mapQuestionAnswer1.put(salesEventFBackQuestions3.Feedback_Questions__c,salesEventFBackQuestions3);
        mapQuestionAnswer1.put(salesEventFBackQuestions4.Feedback_Questions__c,salesEventFBackQuestions4);
        
        objSalesEventFBackExNew1.mapQuestionAnswer =mapQuestionAnswer1;
        objSalesEventFBackExNew1.mapQuestionAnswer.put(salesEventFBackQuestions.Feedback_Questions__c,salesEventFBackQuestions);
        objSalesEventFBackExNew1.mapQuestionAnswer.put(salesEventFBackQuestions1.Feedback_Questions__c,salesEventFBackQuestions1);
        objSalesEventFBackExNew1.mapQuestionAnswer.put(salesEventFBackQuestions2.Feedback_Questions__c,salesEventFBackQuestions2);
        objSalesEventFBackExNew1.mapQuestionAnswer.put(salesEventFBackQuestions3.Feedback_Questions__c,salesEventFBackQuestions3);
        objSalesEventFBackExNew1.mapQuestionAnswer.put(salesEventFBackQuestions4.Feedback_Questions__c,salesEventFBackQuestions4);
        //objSalesEventFBackExNew.feedbacksave();
        
        //objSalesEventFBackExNew1.getQuestions()[0].answer.answer__c='No';
        //objSalesEventFBackExNew1.feedbacksave();
        
        //objSalesEventFBackExNew1.getEventFeedback()[0].answer.answer__c='';
        //objSalesEventFBackExNew1.feedbacksave();
        
        //objSalesEventFBackExNew1.getComments()[0].answer.answer__c='Test';
        //objSalesEventFBackExNew1.feedbacksave();
        
        objSalesEventFBackExNew1.getEventFeedback()[0].answer.answer__c='No';
        objSalesEventFBackExNew1.getEventFeedback()[0].answer.comment__c='No';
        objSalesEventFBackExNew1.getPreparationSection()[0].answer.answer__c='No';
        objSalesEventFBackExNew1.feedbacksave();
        
        objSalesEventFBackExNew1.getPreparationSection()[0].answer.answer__c='Yes';
        String thousandChar ='qwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnm';
        thousandChar +='qwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnm';
        thousandChar +='qwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnm';
        thousandChar +='qwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnm';
        objSalesEventFBackExNew1.getEventFeedback()[0].answer.comment__c=thousandChar;
        objSalesEventFBackExNew1.feedbacksave();
        
        objSalesEventFBackExNew1.getEventFeedback()[0].answer.comment__c= 'test';
        objSalesEventFBackExNew1.getComments()[0].answer.comment__c= thousandChar;
        objSalesEventFBackExNew1.feedbacksave();
        
        objSalesEventFBackExNew1.getEventFeedback()[0].answer.comment__c= 'test';
        objSalesEventFBackExNew1.getComments()[0].answer.comment__c= 'test';
        objSalesEventFBackExNew1.feedbacksave();
    } 
}