src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Participant_id__c</fullName>
        <externalId>true</externalId>
        <label>Participant ID</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PSA_Absence_End_Date__c</fullName>
        <label>Absence End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PSA_Absence_Start_Date__c</fullName>
        <label>Absence Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PSA_Legal_First_Name__c</fullName>
        <label>Legal First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Legal_Last_Name__c</fullName>
        <label>Legal Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_PS_Level__c</fullName>
        <label>PS Level</label>
        <picklist>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>105</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>110</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>130</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>140</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>141</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>142</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>143</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>145</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>150</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>153</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>155</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>160</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>163</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>165</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>203</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>206</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>210</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>220</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>230</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>235</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>240</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>245</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>250</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>255</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>300</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>305</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>310</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSA_Resource_Stage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for Integration Logging</description>
        <inlineHelpText>Used for Integration Logging</inlineHelpText>
        <label>PSA Resource Stage</label>
        <referenceTo>PSA_Resource_Stage__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Termination_Date__c</fullName>
        <description>Passed from the Workday Integration</description>
        <inlineHelpText>Passed from the Workday Integration</inlineHelpText>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PSA_Worker_Id__c</fullName>
        <description>Unique, External Identifier from Workday</description>
        <externalId>true</externalId>
        <label>Worker Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PSA_Worker_Type__c</fullName>
        <label>Worker Type</label>
        <picklist>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contingent Worker</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pse__Practice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Practice</label>
        <referenceTo>pse__Practice__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>pse__Region__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Work_Calendar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Calendar</label>
        <referenceTo>pse__Work_Calendar__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PSA_Department__c.object
<CustomObject>
    <fields>
        <fullName>PSA_Department_Code__c</fullName>
        <externalId>true</externalId>
        <label>Department Code</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_PS_Department__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True if the department is considered to be part of Professional Services (as it relates to PSA)</description>
        <label>PS Department</label>
        <type>Checkbox</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSA_Entity__c.object
<CustomObject>
    <description>Represents the Guidewire billing legal entity associated with this project. Note, there is a flag required on legal entity set-up to identify if legal entity should be available as billing entity or not.</description>
    <fields>
        <fullName>PSA_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to the country for this entity</description>
        <label>Country</label>
        <referenceTo>pw_cc__CountryObject__c</referenceTo>
        <relationshipLabel>Entities</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Entity_Code__c</fullName>
        <externalId>true</externalId>
        <label>Entity Code</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSA_Resource_Stage__c.object
<CustomObject>
    <description>Staging object to hold new or updated resource-related information from an external system</description>
    <fields>
        <fullName>PSA_Absence_End_Date__c</fullName>
        <label>Absence End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PSA_Absence_Start_Date__c</fullName>
        <label>Absence Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PSA_City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Department__c</fullName>
        <label>Department</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PSA_Entity_Id__c</fullName>
        <label>Entity Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_GW_Integration_Id__c</fullName>
        <inlineHelpText>Id from source system</inlineHelpText>
        <label>GW Integration Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Legal_First_Name__c</fullName>
        <label>Legal First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Legal_Last_Name__c</fullName>
        <label>Legal Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Manager__c</fullName>
        <description>An external id from the source system (Workday).  There must be another Resource Stage record with an External Id set to this value.</description>
        <label>Manager</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Mobile_Phone__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PSA_PS_Level__c</fullName>
        <label>PS Level</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PSA_Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Resource_Status__c</fullName>
        <label>Resource Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_State_Province__c</fullName>
        <label>State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Termination_Date__c</fullName>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PSA_Time_Zone__c</fullName>
        <label>Time Zone</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Title__c</fullName>
        <label>Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_WD_Region_ID__c</fullName>
        <inlineHelpText>Maps the Workday Region Id (2 character code) to the PSA Region</inlineHelpText>
        <label>WD Region ID</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_WD_Work_Calendar_Name__c</fullName>
        <label>WD Work Calendar Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Worker_Id__c</fullName>
        <externalId>true</externalId>
        <label>Worker Id</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PSA_Worker_Type__c</fullName>
        <label>Worker Type</label>
        <picklist>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contingent Worker</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PSA Resource Stage</label>
    <nameField>
        <displayFormat>RSTG-{00000}</displayFormat>
        <label>Resource Stage Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSA Resource Stage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSA_Time_Zone__c.object
<CustomObject>
    <description>Used to map Workday Time Zone values to Salesforce User Record Time Zone picklist values</description>
    <fields>
        <fullName>PSA_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSA_Salesforce_Time_Zone__c</fullName>
        <label>Salesforce Time Zone</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Workday_Time_Zone__c</fullName>
        <label>Workday Time Zone</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Time Zone</label>
    <nameField>
        <displayFormat>TZ-{000}</displayFormat>
        <label>Time Zone Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PSA_Resource_Stage__c</fullName>
        <description>Used for Integration Logging</description>
        <inlineHelpText>Used for Integration Logging</inlineHelpText>
        <label>PSA Resource Stage</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Worker_Id__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Unique Worker Id from Workday</inlineHelpText>
        <label>Worker Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/psaWorkdayResourceIntegrationTest.cls
@isTest(seeAllData=false) 
private class psaWorkdayResourceIntegrationTest {
	static User managerUser;
	static Contact managerContact;
	static pse__Region__c testR;
	static pse__Practice__c testP;
	static pse__Grp__c testG;
	static Account testAccount;
	static pse__Timecard_Header__c tcHeader;
	static PSA_Resource_Stage__c testRS;
	static PSA_Department__c testDept;
	static PSA_Entity__c testEntity;
	static PSA_Time_Zone__c testTimeZone;
	static pse__Work_Calendar__c testWorkCalendar;

	@isTest static void ResourceIntegration() {
		psaTestUtils.disablePsaTriggers();

		//Create users, contacts, rpg, account, and project 
		setupTestData();

		testRS = createTestResourceStage('worker123456test', 'managertestuser12345');

		Test.startTest();

		testRS.PSA_PS_Level__c = null;
		update testRS;

		Test.stopTest();

	}

	private static PSA_Resource_Stage__c createTestResourceStage(String workerId, String managerWorkerId) {
		PSA_Resource_Stage__c rs = new PSA_Resource_Stage__c();
		Date testDate = Date.newInstance(2015, 1, 1);
		String entityCode = ([Select PSA_Entity_Code__c from PSA_Entity__c Order By PSA_Entity_Code__c Limit 1]).PSA_Entity_Code__c;
		String departmentCode = ([Select PSA_Department_Code__c from PSA_Department__c Order By PSA_Department_Code__c Limit 1]).PSA_Department_Code__c;
		String timeZone = ([Select PSA_Workday_Time_Zone__c from PSA_Time_Zone__c Order By PSA_Workday_Time_Zone__c Limit 1]).PSA_Workday_Time_Zone__c;
		String workCalendar = ([Select PSA_WD_Work_Calendar_Name__c from pse__Work_Calendar__c Order by PSA_WD_Work_Calendar_Name__c Limit 1]).PSA_WD_Work_Calendar_Name__c;
		String wdRegion = ([Select PSA_WD_Region_ID__c from pse__Region__c Order By PSA_WD_Region_ID__c Limit 1]).PSA_WD_Region_ID__c;

		rs.PSA_Worker_Id__c = workerId;
		rs.PSA_First_Name__c = 'Test';
		rs.PSA_Last_Name__c = 'Last Name';
		rs.PSA_Email__c = 'test@test123456.com';
		rs.PSA_Legal_First_Name__c = 'Test';
		rs.PSA_Legal_Last_Name__c = 'Last Name';
		rs.PSA_Mobile_Phone__c = '5555555555';
		rs.PSA_Phone__c = '5555555555';
		rs.PSA_City__c = 'Foster City';
		rs.PSA_State_Province__c = 'CA';
		rs.PSA_Postal_Code__c = '77777';
		rs.PSA_Country__c = 'United States';
		rs.PSA_PS_Level__c = '100';
		rs.PSA_Resource_Status__c = 'Active';
		rs.PSA_Time_Zone__c = timeZone;
		rs.PSA_Title__c = 'test title';
		rs.PSA_WD_Region_ID__c = wdRegion;
		rs.PSA_WD_Work_Calendar_Name__c = workCalendar;
		rs.PSA_Worker_Type__c = 'Employee';
		rs.PSA_Manager__c = managerWorkerId;
		rs.PSA_Absence_End_Date__c = testDate;
		rs.PSA_Absence_Start_Date__c = testDate;
		rs.PSA_Department__c = departmentCode;
		rs.PSA_Entity_Id__c = entityCode;
		rs.PSA_Termination_Date__c = testDate;
		rs.PSA_GW_Integration_Id__c = 'test integration id';

		insert rs;
		return rs;
	}

	private static void setupTestData() {
        psaTestUtils.initDefaultWorkCalendar();
        //Create RPG
        testR = psaTestUtils.createTestRegion('Corporate');
        testR.PSA_WD_Region_ID__c = 'AA';
        update testR;

        testP = psaTestUtils.createTestPractice('Corporate');
        testG = psaTestUtils.createTestGroup('Corporate');

        //Create test account with a location so that locations will be created
        testAccount = psaTestUtils.createTestAccount('Test Account', '12345');
        testAccount.Participant_id__c = '1234';
        testAccount.BillingStreet = '123 Sesame Street';
        testAccount.BillingCity = 'Sesame City';
        testAccount.BillingState = 'CA';
        testAccount.BillingPostalCode = '90210';
        testAccount.BillingCountry = 'USA';
        update testAccount;

        testEntity = psaTestUtils.createTestEntity('Test E', '1234', 'TE', true);

        PSA_Department__c dept = new PSA_Department__c();
        dept.Name = 'Test Department';
        dept.PSA_Department_Code__c = '1425';
        dept.PSA_PS_Department__c = true;
        insert dept;

		psaTestUtils.createTestResourcePractice(dept.Id, testEntity.Id, testP.Id);

        PSA_Time_Zone__c timeZone = new PSA_Time_Zone__c();
        timeZone.PSA_Workday_Time_Zone__c = 'test';
        timeZone.PSA_Salesforce_Time_Zone__c = 'sf time zone';
        timeZone.PSA_Active__c = true;
        insert timeZone;

        pse__Work_Calendar__c defaultWorkCalendar = new pse__Work_Calendar__c(Name='Test Work Calendar');
        defaultWorkCalendar.PSA_WD_Work_Calendar_Name__c = 'AA';
        insert defaultWorkCalendar;

        managerUser = psaTestUtils.createTestUser('UserCLD2', 'UserCLD2@tuser.com', 'UserCLD2', 'test', 'UserCLD2@tuser.com', 'UserCLD2');
        managerContact = psaTestUtils.createTestResource(managerUser, testR, testP, testG);
  		managerUser.PSA_Worker_Id__c = 'managertestuser12345';
  		update managerUser;
  		managerContact.PSA_Worker_Id__c = 'managertestuser12345';
  		update managerContact;

        //Grant all permission controls to the current user
        psaTestUtils.grantAllPermissionControls(UserInfo.getUserId(), testR.Id);

        //Create the PSA Integration custom setting record
        psaTestUtils.createPSAIntegrationCustomSetting();
	} 
}