src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Record type used for all Customer records.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>CS_Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>***** Asset  active Status ******</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Record_Type_Name__c</fullName>
        <description>Asset Record Type Name</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CS_Contact_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Licensed Product</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>CS_Asset_Contact_Permissions__c.CS_Contact__c</field>
                <operation>equals</operation>
                <valueField>$User.ContactId</valueField>
            </filterItems>
            <filterItems>
                <field>CS_Asset_Contact_Permissions__c.CS_IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>CS_Asset_Contact_Permissions__c.CS_Access_Type__c</field>
                <operation>equals</operation>
                <value>Customer Support, Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CS_Asset_Contact_Permissions__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CS_Urgency__c</fullName>
        <description>Specify how urgently this particular Issue needs a solution</description>
        <inlineHelpText>Specify how urgently this particular Issue needs a solution</inlineHelpText>
        <label>Urgency</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immediate</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <picklist>
            <controllingField>Asset_Type__c</controllingField>
            <picklistValues>
                <fullName>1-Blocker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2-Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3-Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4-Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1–Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2–Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3–Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4–Cosmetic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <description>Support Contact</description>
        <label>Support</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Asset_Contact_Permissions__c.object
<CustomObject>
    <label>Asset Contact Permission</label>
    <nameField>
        <label>Product Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Contact Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestCS_CaseTeamCustom.cls
@isTest
private class TestCS_CaseTeamCustom {
    static Account customerAcc;
    static Contact customerContact;
    static User currentUsr;
    static Product2 prod;
    static User testUser;
    static User testUser2;
    static CS_Asset_Contact_Permissions__c acp;
    static CaseTeamRole ctr;
    static CaseTeamMember ctm;
    static Case c;
    static User customerUser;
    static User customerCommunityTestUser;

    static testMethod void TestCS_CaseTeamCustom() {
		currentUsr = [select Id, UserRole.Name from User where Id = :UserInfo.getUserId()];

        System.runAs(currentUsr) {
            customerAcc = CS_TestDataUtility.createCustomerAccount();
        	customerContact = CS_TestDataUtility.createContact(customerAcc, 'Customer Support');
            prod = CS_TestDataUtility.createProductRecord();
            customerCommunityTestUser = CS_TestDataUtility.createCustomerCommunityTestUser(customerContact);
            // insert parent asset for customer account
            Asset parentAssetsCustomer = CS_TestDataUtility.createParentAsset(customerAcc, true);
                
            // insert child assets
            
            CS_TestDataUtility.createChildAssetRecord(customerAcc, prod, parentAssetsCustomer, 'Implementation');
            
            //query asset
            Asset childAsset = [Select Id, CS_Is_Active__c, ParentId from Asset where CS_Record_Type_Name__c = 'Child Asset' and ParentId != null limit 1];
            System.debug('=====childAssetId ==== ' + childAsset.Id + ' |===parentId ==== ' + childAsset.ParentId);
            // query case record type
            RecordType rt = [Select Name, developername from RecordType where sobjecttype = 'Case' and Name = 'Customer Support'];
    
            c = new Case();
            c.AssetId = childAsset.Id;
            c.AccountId = customerAcc.Id;
            c.RecordTypeId = rt.Id;
            c.ContactId = customerContact.Id;
            c.Severity__c = '3-Major';
            c.CS_Urgency__c = 'High';
            //c.CS_Contact_Asset__c = acp.Id;
    
            insert c;
            
            Test.startTest();
            
            ApexPages.StandardController con = new ApexPages.StandardController(c);
            CS_CaseTeamCustom controllerExt = new CS_CaseTeamCustom(con);
            
            List<CaseTeamMember> caseTeamMembers = controllerExt.getCaseContacts();
            Map<Id, String> userMap = controllerExt.getUserMap();
            
            Test.stopTest();
        }

    }
}