src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MPL_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MPL Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MPL_SalesReps</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Contact__c.object
<CustomObject>
    <description>This object allows tracking of multiple addresses/sites and Contact types.</description>
    <fields>
        <fullName>Participant_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Participant Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Site</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill To \ Ship To - All</relationshipLabel>
        <relationshipName>Account_Contacts1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <label>Account Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CPQ_Year_1_ARR_Amount__c</fullName>
        <formula>CPQ_Year_1_Net_Fees__c  * CPQ_Year_1_ARR__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the ARR Amount for Year 1. (Year 1 Net Fees x Year 1 ARR %)</inlineHelpText>
        <label>Year 1 ARR Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CPQ_Year_2_ARR_Amount__c</fullName>
        <formula>CPQ_Year_2_Net_Fees__c *  CPQ_Year_2_ARR__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the ARR Amount for Year 2. (Year 2 Net Fees x Year 2 ARR %)</inlineHelpText>
        <label>Year 2 ARR Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CPQ_Year_3_ARR_Amount__c</fullName>
        <formula>CPQ_Year_3_Net_Fees__c *  CPQ_Year_3_ARR__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the ARR Amount for Year 3. (Year 3 Net Fees x Year 3 ARR %)</inlineHelpText>
        <label>Year 3 ARR Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CPQ_Year_4_ARR_Amount__c</fullName>
        <formula>CPQ_Year_4_Net_Fees__c * CPQ_Year_4_ARR__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the ARR Amount for Year 4. (Year 4 Net Fees x Year 4 ARR %)</inlineHelpText>
        <label>Year 4 ARR Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CPQ_Year_5_ARR_Amount__c</fullName>
        <formula>CPQ_Year_5_Net_Fees__c *  CPQ_Year_5_ARR__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the ARR Amount for Year 5. (Year 5 Net Fees x Year 5 ARR %)</inlineHelpText>
        <label>Year 5 ARR Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>As part of Track 3 - user story 4.</description>
        <label>Ship To</label>
        <referenceTo>Account_Contact__c</referenceTo>
        <relationshipLabel>Opportunities (Ship To)</relationshipLabel>
        <relationshipName>Ship_To_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>CPQ_Opportunity_Product_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>By default, this will be the same as the Owner of the Primary Quote and Quote Line that originated this Opportunity Product.</inlineHelpText>
        <label>Opportunity Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CPQ_Year_1_ARR_Amount__c</fullName>
        <formula>SBQQ__QuoteLine__r.CPQ_Year_1_ARR_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year 1 License ARR Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CPQ_Year_2_ARR_Amount__c</fullName>
        <formula>SBQQ__QuoteLine__r.CPQ_Year_2_ARR_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year 2 License ARR Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CPQ_Year_3_ARR_Amount__c</fullName>
        <formula>SBQQ__QuoteLine__r.CPQ_Year_3_ARR_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year 3 License ARR Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CPQ_Year_4_ARR_Amount__c</fullName>
        <formula>SBQQ__QuoteLine__r.CPQ_Year_4_ARR_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year 4 License ARR Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CPQ_Year_5_ARR_Amount__c</fullName>
        <formula>SBQQ__QuoteLine__r.CPQ_Year_5_ARR_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year 5 License ARR Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Line_Code__c</fullName>
        <label>Product Line Code</label>
        <picklist>
            <controllingField>Product_line_Name__c</controllingField>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D&amp;A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DIG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordType.Name</field>
                <operation>equals</operation>
                <value>Standard Products</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>SKUs</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_line_Name__c</fullName>
        <label>Product Line Name</label>
        <picklist>
            <picklistValues>
                <fullName>Core processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data and Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Engagement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>Owner - Roopal Shah</description>
    <label>Product(C)</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products(C)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CPQ_OppProduct_Owner_Calc_Helper.cls
public class CPQ_OppProduct_Owner_Calc_Helper
{
  private boolean m_isExecuting = false;
  private integer BatchSize = 0;
  
  List<OpportunityLineItem> OppLineLst = new List<OpportunityLineItem>();
  Set<id> OpportunityIds = new Set<id>();
  Set<id> ProductIds = new Set<id>();
  
  //Static run variable
  private static boolean run = true;
  public static boolean runOnce()
  {
    if(run){
      run=false;
      return true;
    }else{
      return run;
    }
  }
  public static boolean runAfter = True;
  
  //Constructor
  public CPQ_OppProduct_Owner_Calc_Helper(boolean isExecuting, integer size)
  {
    m_isExecuting = isExecuting;
    BatchSize = size;
  }
  
  public void OnBeforeInsert(OpportunityLineItem[] newOppProducts, Map<ID,OpportunityLineItem> OppProductMap)
  {
      for(OpportunityLineItem line : newOppProducts)
	   {
	     if(line.OpportunityId != null || line.Product2Id != null)
		 {
		   OppLineLst.add(line);
		   OpportunityIds.add(line.OpportunityId);
		   ProductIds.add(line.Product2Id);		   
		 }
	   }
	   updateOppProductOwner(OppLineLst,OpportunityIds,ProductIds);
  }
  
  public void OnBeforeUpdate(OpportunityLineItem[] oldOppProducts, OpportunityLineItem[] updatedOppProducts, Map<ID, OpportunityLineItem> oldOppProductMap, Map<ID, OpportunityLineItem> newOppProductMap)
  {
     for(OpportunityLineItem line : updatedOppProducts)
	 {
       OpportunityLineItem oldOppline = oldOppProductMap.get(line.Id);
       if( line.OpportunityId != oldOppline.OpportunityId || line.Product2Id != oldOppline.Product2Id )
		{
		   OppLineLst.add(line);
		   OpportunityIds.add(line.OpportunityId);
		   ProductIds.add(line.Product2Id);		   
		}
	 }
	 
	 if( OppLineLst.size()>0 )
	     updateOppProductOwner(OppLineLst,OpportunityIds,ProductIds);
  }
   
   public void OnAfterInsert(OpportunityLineItem[] newOppProducts, Map<ID,OpportunityLineItem> OppProductMap)
   {
     
   }
   
   public void OnAfterUpdate(OpportunityLineItem[] oldOppProducts, OpportunityLineItem[] updatedOppProducts, Map<ID, OpportunityLineItem> oldOppProductMap, Map<ID, OpportunityLineItem> newOppProductMap)
   {
     
   }
   
   public void updateOppProductOwner(List<OpportunityLineItem> opplilst, set<Id> OppIds, set<Id> ProdIds)
   { 
	   Map<id,Opportunity> OppMap = new Map<id,Opportunity> ([select id,name, ownerId, AccountId, Account.MPL_Sales_Rep__c,Account.Name,Ship_To__c,Ship_To__r.Participant_Account__c from Opportunity where Id IN: OppIds]);
	           
       Map<id,Product2> ProdMap = new Map<id,Product2> ([select id,name,Product__c,Product__r.Product_line_Name__c, Product__r.Product_Line_Code__c from Product2 where Id IN: ProdIds]);      
      
       for(OpportunityLineItem oli : opplilst)
       {
	      Opportunity opp = OppMap.get(oli.OpportunityId);
          Product2 p =  ProdMap.get(oli.Product2Id);
         
		  if(p.Product__r.Product_line_Name__c =='Core processing' || p.Product__r.Product_line_Name__c == 'Data and Analytics' || p.Product__r.Product_line_Name__c =='Other')
		  {
		      if(opp.ownerId != null)
		          oli.CPQ_Opportunity_Product_Owner__c = opp.ownerId;
		  }
		  else if(p.Product__r.Product_line_Name__c =='Digital Engagement')
		  {
		      if(opp.Account.MPL_Sales_Rep__c != null)
		          oli.CPQ_Opportunity_Product_Owner__c = opp.Account.MPL_Sales_Rep__c; 
		  }
	  }
   }
}


// After update Trigger : Test for update of Sales Price.
   
   /*  system.debug('after update');
       set<id> LineIds = new set<Id>();
       for(OpportunityLineItem line : updatedOppProducts )
       {
           system.debug('New Line Price :' + line.unitPrice );
           
           system.debug('Old Line Price :' + oldOppProductMap.get(line.Id).unitPrice );
             system.debug('sales force Id :' + line.Id );
           
           if(line.unitPrice != oldOppProductMap.get(line.Id).unitPrice && (line.CPQ_Year_1_ARR_Amount__c != null || line.CPQ_Year_2_ARR_Amount__c != null || line.CPQ_Year_3_ARR_Amount__c != null || line.CPQ_Year_4_ARR_Amount__c != null || line.CPQ_Year_5_ARR_Amount__c != null))
               LineIds.add(line.Id);
       }
       system.debug('size :' + LineIds.size() );
       updateSalesPrice(LineIds,oldOppProductMap);
     
   
   public void updateSalesPrice(Set<Id> OppLineIds, Map<ID, OpportunityLineItem> OppProductMap )
   {
       runAfter = false;
       List<OpportunityLineItem> updatelst = new List<OpportunityLineItem> ();
       List<OpportunityLineItem> opplilst =[select id, unitPrice,CPQ_Year_1_ARR_Amount__c, CPQ_Year_2_ARR_Amount__c, CPQ_Year_3_ARR_Amount__c, CPQ_Year_4_ARR_Amount__c, CPQ_Year_5_ARR_Amount__c from OpportunityLineItem
                                            where Id =: OppLineIds];
       system.debug('priceList :' + opplilst.size() );
                                            
       for(OpportunityLineItem lin : opplilst)
       {
          // if(lin.unitPrice != OppProductMap.get(lin.Id).UnitPrice)
          // {
               system.debug('New Line Price 1 :' + lin.unitPrice );
               system.debug('Old Line Price 1 :' + OppProductMap.get(lin.Id).unitPrice );
               lin.UnitPrice = lin.CPQ_Year_1_ARR_Amount__c + lin.CPQ_Year_2_ARR_Amount__c + lin.CPQ_Year_3_ARR_Amount__c + lin.CPQ_Year_4_ARR_Amount__c + lin.CPQ_Year_5_ARR_Amount__c;
               system.debug('new price :' + lin.UnitPrice);
               updatelst.add(lin);
         //  }
       }
       system.debug('New List :' + updatelst.size() );
       if (!updatelst.isEmpty())
       {
           system.debug('Is empty ' );
          update updatelst;
       }
   }
   */