src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Participant_id__c</fullName>
        <externalId>true</externalId>
        <label>Participant ID</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Status__c</fullName>
        <label>Renewal Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Notified of Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract reviewed with Mgr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing strategy to Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ops Drafting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed/Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Action Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity from which this Contract was created.</description>
        <inlineHelpText>The Opportunity from which this Contract was created.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CPQ_Billing_Schedule__c.object
<CustomObject>
    <description>Billing Schedules will be created when orders are created and will contain all the broken out line items from the order based on the billing frequency</description>
    <fields>
        <fullName>Order_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Order Product</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Order Product must be related to the Order of this Billing Schedule.</errorMessage>
            <filterItems>
                <field>$Source.Order__c</field>
                <operation>equals</operation>
                <valueField>OrderItem.OrderId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Billing Schedules</relationshipLabel>
        <relationshipName>Billing_Schedules</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Billing Schedules</relationshipLabel>
        <relationshipName>Billing_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ch_AUTO_RENEWAL__c</fullName>
        <defaultValue>&apos;Y&apos;</defaultValue>
        <label>Auto Renewal</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ch_Baseline_Measure__c</fullName>
        <defaultValue>&apos;GWP = Gross Written Premiums&apos;</defaultValue>
        <label>Baseline Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ch_Escalation_Description__c</fullName>
        <defaultValue>&apos;Lesser of CPI or 3%&apos;</defaultValue>
        <label>Escalation Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ch_Escalation_on_Fees__c</fullName>
        <defaultValue>&apos;Y&apos;</defaultValue>
        <label>Escalation on Fees</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ch_Growth_Rate_Buffer__c</fullName>
        <defaultValue>&apos;&gt;0%&apos;</defaultValue>
        <label>Growth Rate Buffer</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ch_Growth_Rate_Clause__c</fullName>
        <defaultValue>&apos;Y&apos;</defaultValue>
        <label>Growth Rate Clause included in contract?</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ch_Notification_Required__c</fullName>
        <defaultValue>&apos;N&apos;</defaultValue>
        <label>Notification Required?</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ch_Perpetual_Buyout_Option__c</fullName>
        <defaultValue>&apos;N&apos;</defaultValue>
        <label>Contract has Perpetual Buyout Option?</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ch_Reduction_Rate_Clause__c</fullName>
        <defaultValue>&apos;N&apos;</defaultValue>
        <label>Reduction Rate Clause incl. in contract?</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ch_Term_Years__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Number of Term Year</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ch_Warranty_Period__c</fullName>
        <defaultValue>&apos;365 days from Notification Date&apos;</defaultValue>
        <label>Warranty Period</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>departmentid__c</fullName>
        <defaultValue>&apos;310&apos;</defaultValue>
        <label>Intacct Department Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>exchratetype__c</fullName>
        <defaultValue>&apos;Intacct Daily Rate&apos;</defaultValue>
        <label>Exchange Rate Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>price__c</fullName>
        <label>Price</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>transactiontype__c</fullName>
        <defaultValue>&apos;Automated Sales Order&apos;</defaultValue>
        <label>Sales Order Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>unit__c</fullName>
        <defaultValue>&apos;Each&apos;</defaultValue>
        <label>Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Schedule</label>
    <nameField>
        <displayFormat>BS-{000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CPQ_Wire_Message__c.object
<CustomObject>
    <fields>
        <fullName>BILL_TO_Country__c</fullName>
        <label>BILL TO Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Currency__c</fullName>
        <label>Local Currency</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Wire Message</label>
    <nameField>
        <displayFormat>M-{00}</displayFormat>
        <label>Wire Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wire Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Net New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net New +</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DWP Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross Sell - Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross Sell - LOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross Sell - Geo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RPI/CPI Increase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer - Acquisition</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wire_Message__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wire Message</label>
        <referenceTo>CPQ_Wire_Message__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>transactiontype__c</fullName>
        <defaultValue>&apos;Automated Sales Order&apos;</defaultValue>
        <label>Sales Order Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>price__c</fullName>
        <label>Price</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/CPQ_GenerateOrderFileTest.cls
/**
* ==================================================================================
*    Version        Date                          Comment
* ==================================================================================
*    Initial                          Test class for class CPQ_GenerateOrderFile
*                                       
*                                       
*/
@isTest
private class CPQ_GenerateOrderFileTest {

    
    /**
     * Method to Create Contract record 
     */
    public static Contract contractTestData(Id accId, Id oppId) {

        Contract contObj = new Contract();
        contObj.AccountId = accId;
        contObj.Status = 'Draft';
        contObj.CurrencyIsoCode = 'USD';
        contObj.StartDate = System.Today();
        contObj.SBQQ__Opportunity__c = oppId;
        contObj.Renewal_Status__c = 'Not Started ';
        // contObj.Invoice_Date__c = System.Today();
        insert contObj;
        return contObj;
    }

    /**
     * Method to Create Opportunity record 
     */
    public static Opportunity createOppTestData(Id accId) {

        Opportunity objOpportunity = new Opportunity();
        objOpportunity.Name = 'TestOpportunity';
        objOpportunity.AccountId = accId;
        objOpportunity.StageName = 'Working';
        objOpportunity.CloseDate = System.Date.Today().addDays(15);
        objOpportunity.Opportunity_Type__c = 'Renewal Type';
        objOpportunity.CurrencyIsoCode = 'USD';
        insert objOpportunity;
        return objOpportunity;
    }

    /**
     * Method to Create CPQ_Billing_Schedule__c record 
     */
    public static CPQ_Billing_Schedule__c createBillingSchedule(Order orderObj, OrderItem orderItemObj) {

        CPQ_Billing_Schedule__c billingScheduleObj = new CPQ_Billing_Schedule__c(
            transactiontype__c = 'Automated Sales Order 33',
            exchratetype__c = 'Intacct Daily Rate',
            ch_Warranty_Period__c = '365 days from Notification Date',
            quantity__c = 1,
            unit__c = 'Each',
            Order__c = orderObj.Id,
            Order_Product__c = orderItemObj.Id,
            departmentid__c = '310',
            ch_Baseline_Measure__c = 'GWP = Gross Written Premiums',
            ch_AUTO_RENEWAL__c = 'Y',
            ch_Term_Years__c = 1,
            ch_Escalation_on_Fees__c = 'Y',
            ch_Escalation_Description__c = 'Lesser of CPI or 3%',
            ch_Growth_Rate_Clause__c = 'Y',
            ch_Reduction_Rate_Clause__c = 'N',
            ch_Notification_Required__c = 'N',
            ch_Perpetual_Buyout_Option__c = 'N',
            ch_Growth_Rate_Buffer__c = '>0%'
        );
        insert billingScheduleObj;
        return billingScheduleObj;
    }

    /**
     * Method to Create Product2 record 
     */
    public static Product2 createProduct() {
        Product2 prod = new Product2(Name = 'Laptop X200',
            Family = 'Hardware');
        insert prod;
        return prod;
    }

    /**
     * Method to Create PriceBookEntry record 
     */
    public static PricebookEntry createPriceBookEntry(Product2 productObj) {

        Id pricebookId = Test.getStandardPricebookId();

        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = productObj.Id,
            UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        return standardPrice;
    }

    /**
     * Method to Create CPQ_Wire_Message__c record 
     */
    public static CPQ_Wire_Message__c createWiremessage() {
        CPQ_Wire_Message__c wiremessage = new CPQ_Wire_Message__c(
            Message__c = 'Incoming wire payment instruction: Currency USD To: SIL VLY BK SJ 3003 Tasman Drive, Santa Clara, CA Routing&Transit: 121140399 Account #: 3300604026',
            BILL_TO_Country__c = 'USD',
            Local_Currency__c = 'USD',
            CurrencyIsoCode = 'USD'
        );
        insert wiremessage;
        return wiremessage;
    }

    /**
     * Method to Create Order record 
     */
    public static Order createOrder(Account objAcc, Contract contObj, Opportunity objOpportunity, CPQ_Wire_Message__c wiremessage) {

        Id pricebookId = Test.getStandardPricebookId();

        Order orderObj = new Order();
        orderObj.AccountID = objAcc.ID;
        orderObj.EffectiveDate = System.TODAY();
        orderObj.CurrencyIsoCode = 'USD';
        orderObj.ContractID = contObj.ID;
        orderObj.Status = 'Draft';
        orderObj.OpportunityID = objOpportunity.ID;
        orderObj.Is_Primary__c = true;
        orderObj.Wire_Message__c = wiremessage.ID;
        orderObj.Pricebook2ID = pricebookId;
        insert orderObj;
        return orderObj;
    }

    /**
     * Method to Create OrderItem record 
     */
    public static OrderItem createOrderItem(Order orderObj, PricebookEntry standardPrice) {

        OrderItem orderItemObj = new Orderitem(
            OrderId = orderObj.Id,
            UnitPrice = 20000,
            Quantity = 1,
            price__c = 2204328,
            PriceBookEntryId = standardPrice.Id
        );
        insert orderItemObj;
        return orderItemObj;
    }

    /**
     * Method to test AttachmentRecord record 
     */
    @isTest static void test_AttachmentRecord() {

        Account objAcc = new Account();
        objAcc.Name = 'TestAcc';
        objAcc.Participant_id__c = '1234';
        insert objAcc;


        Opportunity objOpportunity = createOppTestData(objAcc.Id);

        Contract contObj = contractTestData(objAcc.Id, objOpportunity.Id);

        Product2 productObj = createProduct();

        Id pricebookId = Test.getStandardPricebookId();

        PricebookEntry standardPrice = createPriceBookEntry(productObj);

        CPQ_Wire_Message__c wiremessage = createWiremessage();

        Order orderObj = createOrder(objAcc, contObj, objOpportunity, wiremessage);

        OrderItem orderItemObj = createOrderItem(orderObj, standardPrice);

        CPQ_Billing_Schedule__c billingScheduleObj = createBillingSchedule(orderObj, orderItemObj);

        CPQ_GenerateOrderFile.createOrderAttachment(orderObj.Id);
        List < Attachment > attchmentList = [Select Id, Body, Name, ParentId From Attachment];
        System.assertEquals(attchmentList.size(), 1);
        System.assertEquals(attchmentList[0].ParentId, orderObj.Id);

    }
}