src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Participant_id__c</fullName>
        <externalId>true</externalId>
        <label>Participant ID</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Record type used for all Prospect records.</description>
        <label>Prospect</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>CS_Product__c</fullName>
        <formula>Product2.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PSA_Billing_Level__c</fullName>
        <description>PSA - Resource&apos;s billing level</description>
        <inlineHelpText>Resource billing level</inlineHelpText>
        <label>Billing Level</label>
        <picklist>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>105</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>110</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>130</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>140</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>220</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Blended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH Offshore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actuary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor17</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pse__Practice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Practice</label>
        <referenceTo>pse__Practice__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>pse__Region__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Release__c.object
<CustomObject>
    <description>***Service Cloud **** This Object  maintains the Installable Product versions</description>
    <fields>
        <fullName>CS_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordType.Name</field>
                <operation>contains</operation>
                <value>Standard Products,Entitled Product</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Product_Version</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Product Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Group_Name__c</fullName>
        <label>Product Group Name</label>
        <picklist>
            <controllingField>Product_line_Name__c</controllingField>
            <picklistValues>
                <fullName>Alliances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BillingCenter Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ClaimCenter Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core Add Ons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital experience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Portals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guidewire Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted InsuranceSuite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InsuranceSuite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Millbrook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PolicyCenter Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Predictive Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard-based Templates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underwriting Management</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/PSA_Rate__c.object
<CustomObject>
    <description>Custom - Records the suggested bill rate or average cost rate for a resource role in a region, practice, or group (for example, the bill rate for a Consultant in Europe) or for projects on an account. Use rate cards early in the staffing process, to provide information on likely billing and cost rates when creating resource requests. If configured, start and end dates on rate cards determine if the rate only applies to resource requests which lie between the given dates.</description>
    <fields>
        <fullName>PSA_Average_Cost_Rate__c</fullName>
        <description>PSA Average cost rate</description>
        <label>Average Cost Rate</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSA_Bill_Rate_Amount__c</fullName>
        <description>PSA Bill rate for resource</description>
        <label>Bill Rate</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSA_Bill_Rate_Set__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>PSA Bill Rate Set</description>
        <label>PSA Bill Rate Set</label>
        <referenceTo>PSA_Rate_Set__c</referenceTo>
        <relationshipName>PSA_Bill_Rates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Billing_Level__c</fullName>
        <description>PSA Billing Level</description>
        <label>Billing Level</label>
        <picklist>
            <picklistValues>
                <fullName>Default</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>105</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>110</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>130</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>140</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>220</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Blended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH Offshore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actuary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor16</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSA_End_Date__c</fullName>
        <description>PSA End date</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PSA_Start_Date__c</fullName>
        <description>PSA Start date</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>PSA Rate</label>
    <nameField>
        <displayFormat>PBR-{0000}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSA Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSA_Rate_Set__c.object
<CustomObject>
    <description>Custom - A PSA Rate Set, composed of multiple separate PSA Rates, determines which bill rates are applied to a project or an opportunity.</description>
    <fields>
        <fullName>PSA_Is_Global__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if this is the global PSA Rate Set</description>
        <label>Is Global</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSA_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PSA Project</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipName>PSA_Bill_Rate_Sets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PSA Rate Set</label>
    <nameField>
        <label>Rate Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSA Rate Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CS_AssignmentCaseControllerTest.cls
@isTest
private class CS_AssignmentCaseControllerTest 
{
    static testmethod void testAssignment()
    {
        psaTestUtils.initDefaultWorkCalendar();
        //Create RPG
        pse__Region__c testR = psaTestUtils.createTestRegion('Corporate');
        pse__Practice__c testP = psaTestUtils.createTestPractice('Corporate');
        pse__Grp__c testG = psaTestUtils.createTestGroup('Corporate');
      
        //Create test account with a location so that locations will be created
        Account a = psaTestUtils.createTestAccount('Test Account', '98675');
        a.Participant_id__c = '8796';
        update a;
        
         User u = psaTestUtils.createTestUser('tuCs', 'tuserCase@tuser.com', 'userCase', 'test22', 'tuserCase@tuser.com', 'tuserCa');
      
        //Create 2 contacts, one to submit and one as the manager
         Contact c = psaTestUtils.createTestResource(u, testR, testP, testG);
         c.PSA_Billing_Level__c = '110';
         update c;
         
     //  test.startTest();
        pse__Proj__c testProject = psaTestUtils.createTestProjectInProgress('Time Off', a, testR, testP, testG, null, c, u);
        testProject.PSA_Milestone_Required__c = false;
        update testProject;
        test.startTest();
        PSA_Rate_Set__c rs = new PSA_Rate_Set__c();
        rs.PSA_Project__c = testProject.id;
        rs.PSA_Is_Global__c = false;
        insert rs;

        PSA_Rate__c rate = new PSA_Rate__c();
        rate.psa_Billing_Level__c = '120';
        rate.PSA_Average_Cost_Rate__c = 35;
        rate.PSA_Bill_Rate_Amount__c = 80;
        rate.PSA_Start_Date__c = Date.Today() - 20;
        rate.PSA_End_Date__c = Date.Today() + 200;
        rate.PSA_Bill_Rate_Set__c = rs.id;
        insert rate;
       
       pse__Assignment__c testAssignment = psaTestUtils.createTestSimpleAssignment(testProject, c, 'Data Migration Specialist'); 
       
       system.debug('Total quries :' +Limits.getQueries());
              
       
        Product2 pd = new Product2();
        pd.Name='TestProduct'; 
        pd.ProductCode='TEPD';
        pd.Product_Group_Name__c = 'BillingCenter Group';
        insert pd;
        
         CS_Release__c release = new CS_Release__c();
         release.CS_Product__c = pd.Id;
         release.CS_IsActive__c = true;
         release.CS_Major_Release_version__c = '8';
         release.CS_Minor_Release_Version__c ='1';
         insert release;
        
        Asset parentAsset = new Asset();
        parentAsset.Name='TestParentAssetProspect'; 
                                     parentAsset.AccountId=a.Id; 
                                     parentAsset.CS_Support_Group__c='Billing System';
                                     parentAsset.Status = 'Prospect';
                                     parentAsset.CS_Is_Active__c = true;
        insert parentAsset;
        
        Asset childAst = CS_TestDataUtility.createChildAssetWithRelease(a,pd,parentAsset,release,'active');
      
       
       PageReference pref = Page.CS_CreateCase_for_PS;       
    
       Test.setCurrentPage(pref);
       ApexPages.currentPage().getParameters().put('id', testAssignment.id); 
       
       ApexPages.StandardController sc = new ApexPages.StandardController(testAssignment);
              
       AssignmentCaseController disCon = new AssignmentCaseController(sc);
       
     //  System.assertEquals(NUM_QUERY, Limits.getQueries());
       system.debug('Total quries :' +Limits.getLimitQueries());
       system.debug('Total quries :' +Limits.getQueries());
         
         List<SelectOption> assets = disCon.getAssetList();
         disCon.setAset(childAst.Id);
         List<SelectOption> versions = disCon.getVersionList();      
         PageReference result = disCon.checkResource();
         PageReference result1 = disCon.saveMe(); 
       test.stopTest();
    //   System.assertEquals(NUM_QUERY, Limits.getQueries());
      
   }
    
}