src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Alliance_Type__c</fullName>
        <label>Alliance Type</label>
        <picklist>
            <picklistValues>
                <fullName>PartnerConnect - Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PartnerConnect - Consulting</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>MPL_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MPL Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MPL_SalesReps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Products_Purchased__c</fullName>
        <label>Products Purchased</label>
        <picklist>
            <picklistValues>
                <fullName>BillingCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ClaimCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Data Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DataHub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InfoCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MiAgents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Millbrook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile &amp; Portals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PolicyCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rating Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reinsurance Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standards-based Templates</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Prospective_Partner_Type__c</fullName>
        <description>populated by web form based on the lead origin</description>
        <inlineHelpText>What type of partner is this lead interested in applying for</inlineHelpText>
        <label>Prospective Partner Type</label>
        <picklist>
            <picklistValues>
                <fullName>PartnerConnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SolutionConnect</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LatAm</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Sub_Region__c</fullName>
        <label>Sub Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Record type used for all Partner records.</description>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>For use in filtering mailings; Top Mgmt is for CEO, COO, President, Chairman, etc.</description>
        <label>Subject  Area</label>
        <picklist>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claims</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Consulting</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Region__c</fullName>
        <label>Sub Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountTgrHandlerTest.cls
@isTest
private class AccountTgrHandlerTest
{
    static testMethod void testAccountTgrHandler()
    {
        List<Profile> lstProfile =[Select Id from Profile 
                                    where profile.userlicense.name = 'Partner Community'];
        List<RecordType> lstRecordType = [Select Id from RecordType where Name ='Partner'];
        
        Account objAccount = New Account(name='TestProduct',Products_Purchased__c= 'BillingCenter', billingcountry ='Austria');
        objAccount.RecordTypeId =lstRecordType[0].Id;
        insert objAccount;
        
        Contact contact = new Contact();
        contact.LastName = 'testContact';
        contact.AccountId = objAccount.Id;
        contact.Category__c = 'Billing';
        insert contact;
        
        Region__c reg = new Region__c();
        reg.country__c= 'Poland';
        reg.sub_region__c= 'Pol';
        insert reg;
        
      
        
        list<user> ulst = [select id,name from user where profileid =: lstProfile[0].id and isactive=true ];
        
        Account firstAccount = New Account(name='TestProduct',Products_Purchased__c= 'BillingCenter', billingcountry ='Poland');
        firstAccount.MPL_Sales_Rep__c = ulst[0].Id;
        firstAccount.RecordTypeId =lstRecordType[0].Id;
        insert firstAccount;
        
        objAccount.MPL_Sales_Rep__c = ulst[0].Id;
        update objAccount;
    }
    
        public static testmethod void testAccountPartnerType(){
        // create account with blank alliance and prospective partner type
        Account a = new Account(name = 'test', prospective_partner_Type__c = 'First Option', billingcountry ='Poland');
        insert a;
        a = [select id, prospective_partner_Type__c , alliance_type__c from Account where id = :a.id];
        system.assertequals(a.prospective_partner_Type__c, null);
        system.assertequals(a.alliance_type__c , 'First Option');
        // add new option in prospective
        a.prospective_partner_Type__c = 'Second Option';
        update a;
        a = [select id, prospective_partner_Type__c , alliance_type__c from Account where id = :a.id];
        system.assertequals(a.prospective_partner_Type__c, null);
        system.assert(a.alliance_type__c.contains('Second Option') && a.alliance_type__c.contains('First Option'));
        // add second option again
        a.prospective_partner_Type__c = 'Second Option';
        update a;
        a = [select id, prospective_partner_Type__c , alliance_type__c from Account where id = :a.id];
        system.assertequals(a.prospective_partner_Type__c, null);
        system.assertequals(a.alliance_type__c.countmatches('Second Option'), 1);                
    }
}