src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resubmit Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <picklist>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Integrated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_Delivery_Method__c</fullName>
        <label>Invoice Delivery Method</label>
        <picklist>
            <picklistValues>
                <fullName>Electronic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <label>Payment Term</label>
        <picklist>
            <picklistValues>
                <fullName>Net 30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 90</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site</fullName>
    </fields>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <description>Record Type used for all Site Records</description>
        <label>Site</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Contact__c.object
<CustomObject>
    <description>This object allows tracking of multiple addresses/sites and Contact types.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill To \ Ship To</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bill To\ Ship To</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Integrated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <label>Account Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Print_As__c</fullName>
        <label>Print As</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Email__c</fullName>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/trac_ACRIntegrationManager.cls
/**
 * @description Set the AccountContacts Status to Pending
 * @author KJ, Traction On Demand
 * @date July 2/2015
 */

public class trac_ACRIntegrationManager {

    /****************************************************  
    *  trac_AccountACRIntegrationManager Public Method(s) 
    *****************************************************/

    public static void run (Map<Id,Account> accountOldMap, Map<Id,Account> accountNewMap) {
        Accounts qualifiedAccounts = new Accounts(accountOldMap, accountNewMap);

        if(qualifiedAccounts.Ids.size() > 0) {
            AccountContacts relatedAccountContacts = new AccountContacts();
            relatedAccountContacts.loadWhereAccountIds(qualifiedAccounts.Ids);
            relatedAccountContacts.setStatusPending();          
        }
    }   

    public static void run (Map<Id,Contact> contactOldMap, Map<Id,Contact> contactNewMap) {
        Contacts qualifiedContacts = new Contacts(contactOldMap, contactNewMap);

        if(qualifiedContacts.Ids.size() > 0) {
            AccountContacts relatedAccountContacts = new AccountContacts();
            relatedAccountContacts.loadWhereContactIds(qualifiedContacts.Ids);
            relatedAccountContacts.setStatusPending();          
        }
    }           

    /***************************************************************** Accounts Wrapper Class ****************************************************************/

    @TestVisible
    class Accounts {
        public Set<Id> Ids {get; private set;}
        private Id siteRecordTypeId;
        @TestVisible private String PENDING_APPROVAL_STATUS = 'Pending Approval';
        @TestVisible private String APPROVED_STATUS         = 'Approved';

        public Accounts(Map<Id,Account> accountOldMap, Map<Id,Account> accountNewMap) {
            siteRecordTypeId = getSiteRecordTypeId();
            this.Ids         = filter(accountOldMap, accountNewMap);            
        }

        /****************************************************  
        *  Accounts Private Method(s) 
        *****************************************************/

        private Set<Id> filter(Map<Id,Account> accountOldMap, Map<Id,Account> accountNewMap) {
            Set<Id> result = new Set<Id>();

            for(Account newAccount :accountNewMap.values()) {
                Account oldAccount = accountOldMap.get(newAccount.Id);
                if(
                    newAccount.RecordTypeId == siteRecordTypeId &&
                    (
                        oldAccount.BillingStreet              != newAccount.BillingStreet ||
                        oldAccount.BillingCity                != newAccount.BillingCity ||
                        oldAccount.BillingState               != newAccount.BillingState ||
                        oldAccount.BillingCountry             != newAccount.BillingCountry ||
                        oldAccount.BillingPostalCode          != newAccount.BillingPostalCode ||
                        oldAccount.Invoice_Delivery_Method__c != newAccount.Invoice_Delivery_Method__c ||
                        oldAccount.CurrencyIsoCode            != newAccount.CurrencyIsoCode ||
                        oldAccount.Payment_Term__c            != newAccount.Payment_Term__c 
                    )
                        
                ) {
                    result.add(newAccount.Id);
                }               
                                
                if(
                    newAccount.RecordTypeId       != siteRecordTypeId &&
                    oldAccount.Approval_Status__c == PENDING_APPROVAL_STATUS &&
                    newAccount.Approval_Status__c == APPROVED_STATUS                    
                ) {
                    result.add(newAccount.Id);
                }                               
            }
            return result;              
        }

        private Id getSiteRecordTypeId() {
           /* List<RecordType> siteRecordType = [
                SELECT Id 
                FROM RecordType 
                WHERE SObjectType = 'Account' 
                AND DeveloperName = 'Site'
            ];*/
            
            Id recordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Site').RecordTypeId;

            //if(siteRecordType.size() > 0)
            if(recordTypeId  != null)
                return recordTypeId;
            else
                throw new NoRecordTypeException('RecordType Site is not defined');
        }
    }

    /***************************************************************** Accounts Wrapper Class ****************************************************************/

    @TestVisible
    class Contacts {
        public Set<Id> Ids {get; private set;}

        public Contacts(Map<Id,Contact> contactOldMap, Map<Id,Contact> contactNewMap) {
            this.Ids = filter(contactOldMap, contactNewMap);
        }

        /****************************************************  
        *  Contacts Private Method(s) 
        *****************************************************/

        private Set<Id> filter(Map<Id,Contact> contactOldMap, Map<Id,Contact> contactNewMap) {
            Set<Id> result = new Set<Id>();

            for(Contact newContact :contactNewMap.values()) {
                Contact oldContact = contactOldMap.get(newContact.Id);
                if(
                    newContact.FirstName   != oldContact.FirstName ||
                    newContact.LastName    != oldContact.LastName ||
                    newContact.Print_As__c != oldContact.Print_As__c ||
                    newContact.Email       != oldContact.Email ||
                    newContact.Secondary_Email__c       != oldContact.Secondary_Email__c ||
                    newContact.Phone       != oldContact.Phone ||
                    newContact.OtherPhone       != oldContact.OtherPhone  
                ) {
                    result.add(newContact.Id);
                }
            }
            return result;
        }
    }

    /***************************************************************** AccountContacts Wrapper Class ****************************************************************/
    
    @TestVisible
    class AccountContacts {
        private List<Account_Contact__c> accountContacts; 
        private Map<Id,Account_Contact__c> updatedAccountContacts;

        @TestVisible private final String PENDING_STATUS = 'Pending Integration';

        public AccountContacts() {
            accountContacts        = new List<Account_Contact__c>();
            updatedAccountContacts = new Map<Id,Account_Contact__c>();
        }

        /****************************************************  
        *  AccountContacts Public Method(s) 
        *****************************************************/

        public void loadWhereAccountIds(Set<Id> ids) {
            if(ids.size() > 0) {
                accountContacts = [
                    SELECT Integration_Status__c
                    FROM Account_Contact__c
                    WHERE Account__c IN :ids
                ];
            }               
        }

        public void loadWhereContactIds(Set<Id> ids) {
            if(ids.size() > 0) {
                accountContacts = [
                    SELECT Integration_Status__c
                    FROM Account_Contact__c
                    WHERE Contact__c IN :ids
                ];
            }               
        }

        public void setStatusPending() {
            if(accountContacts.size() > 0) {
                for(Account_Contact__c anAccountContact :accountContacts) {
                    if(anAccountContact.Integration_Status__c != PENDING_STATUS) {
                        anAccountContact.Integration_Status__c = PENDING_STATUS;
                        updatedAccountContacts.put(anAccountContact.Id, anAccountContact);
                    }                   
                }
                if(updatedAccountContacts.size() > 0) {
                    update accountContacts;
                }               
            }               
        }
    }

    public class NoRecordTypeException extends Exception {}
}