src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resubmit Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Billing Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Billing_Zip_Postal_Code__c</fullName>
        <label>Billing Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Invoice_Delivery_Method__c</fullName>
        <label>Invoice Delivery Method</label>
        <picklist>
            <picklistValues>
                <fullName>Electronic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Participant_id__c</fullName>
        <externalId>true</externalId>
        <label>Participant ID</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <label>Payment Term</label>
        <picklist>
            <picklistValues>
                <fullName>Net 30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 90</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requested_Approval__c</fullName>
        <label>Requested Approval</label>
        <picklist>
            <picklistValues>
                <fullName>New Customer - Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer – Indirect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer - Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer – Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer - Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid POC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PartnerConnect - Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PartnerConnect - Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner - Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site</fullName>
    </fields>
    <fields>
        <fullName>pw_cc__BillingCountryLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Country Lookup</label>
        <referenceTo>pw_cc__CountryObject__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Record type used for all Customer records.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Record type used for all Prospect records.</description>
        <label>Prospect</label>
    </recordTypes>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <description>Record Type used for all Site Records</description>
        <label>Site</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Contact__c.object
<CustomObject>
    <description>This object allows tracking of multiple addresses/sites and Contact types.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill To \ Ship To</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Key__c</fullName>
        <externalId>true</externalId>
        <label>Contact Key</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bill To\ Ship To</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Participant_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Participant Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Site</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bill To \ Ship To - All</relationshipLabel>
        <relationshipName>Account_Contacts1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecordStatus__c</fullName>
        <label>Record Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <label>Account Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Four_Digit_Id__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Current_Value__c</fullName>
        <label>Current Value</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Four Digit Id</label>
</CustomObject>

src/classes/trac_AccountHandlerTest.cls
/**
 * @description Testing the account handler
 *
 * @author Tanminder Rai, Traction On Demand
 * @date May 25/2015
 */

@isTest
private class trac_AccountHandlerTest {

    public static Id PROS_RT;
    public static Id COUNTRY_ID; 

    private static void setRecordType(){
        RecordType rt = [SELECT id, Name FROM RecordType 
                                        WHERE sobjecttype='Account' 
                                        AND Name=:'Prospect' LIMIT 1];

        PROS_RT = rt.Id;
    }
    
    private static void setCountryId(){
      
      
      pw_cc__CountryObject__c country = new pw_cc__CountryObject__c(
                                  Name = 'Test Country',
                                  pw_cc__IsoCode_2__c = 'TC',
                                  pw_cc__IsoCode_3__c = 'TC'
                                );
      insert country;                           
      COUNTRY_ID = country.Id;
    }

   @isTest
    static void accountGenerateAutoNumTest(){

        insert new Four_Digit_Id__c(Current_Value__c = 1002);

        Account a = new Account(Name = 'Test', Approval_Status__c = 'Approved'); 
        insert a;

        for (Account accRetrieve :[SELECT Id, Participant_id__c
                                              FROM Account 
                                              WHERE Id=:a.Id]){
            System.assertEquals(String.ValueOf(1002), accRetrieve.Participant_id__c);
        }

        //The next account should get the next consecutive number
        Account a2 = new Account(Name = 'Test2', Approval_Status__c = 'Approved'); 
        insert a2;    
        for (Account accRetrieve :[SELECT Id, Participant_id__c
                                              FROM Account 
                                              WHERE Id=:a2.Id]){
            System.assertEquals(String.ValueOf(1003), accRetrieve.Participant_id__c);
        }            

        Account a3 = new Account(Name = 'Test3', Approval_Status__c = 'Approved'); 
        insert a3;    
        for (Account accRetrieve :[SELECT Id, Participant_id__c
                                              FROM Account 
                                              WHERE Id=:a3.Id]){
            System.assertEquals(String.ValueOf(1004), accRetrieve.Participant_id__c);
        } 

        //the participant Id should remain the same after updating if Participant_id__c already exists
        a.Email__c = 'test@test.com';
        update a;
        for (Account accRetrieve :[SELECT Id, Participant_id__c
                                              FROM Account 
                                              WHERE Id=:a.Id]){
            System.assertEquals(String.ValueOf(1002), accRetrieve.Participant_id__c);
        } 
     }

    //updating status to approved 
    @isTest
    static void accountGenerateAutoNumUpdateTest(){

        insert new Four_Digit_Id__c(Current_Value__c = 1002);

        Account a = new Account(Name = 'Test'); 
        insert a;

        for (Account accRetrieve :[SELECT Id, Participant_id__c
                                              FROM Account 
                                              WHERE Id=:a.Id]){
            System.assertEquals(NULL, accRetrieve.Participant_id__c);
        }

        a.Approval_Status__c = 'Approved';
        update a;

        for (Account accRetrieve :[SELECT Id, Participant_id__c
                                              FROM Account 
                                              WHERE Id=:a.Id]){
            System.assertEquals(String.ValueOf(1002), accRetrieve.Participant_id__c);
        }
    }

    // Test for query failure
    @isTest
    static void generateAutoNumberFailure(){
        Account a = new Account(Name = 'Test'); 
        insert a;

        for (Account accRetrieve :[SELECT Id, Participant_id__c
                                              FROM Account 
                                              WHERE Id=:a.Id]){
            System.assertEquals(NULL, accRetrieve.Participant_id__c);
        }

        trac_GenerateAutoNumber.TEST_EXCEPTION = true;

        // Attempt an update
        a.Approval_Status__c = 'Approved';
        try {
            update a;
            System.assert(False, 'Expected exception not thrown');
        } catch (DmlException exp) {
            // Success because the account was not updated
        }
    }

    //Bulk Test
    @isTest
    static void accountGenerateAutoNumBulkTest(){

        insert new Four_Digit_Id__c(Current_Value__c = 1000);

        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i<200 ; i++){
            accounts.add(new Account(Name = 'Test'+String.ValueOf(i), Approval_Status__c = 'Approved')); 
        }
        insert accounts;

        for (Account accRetrieve :[SELECT Id, Participant_id__c
                                              FROM Account 
                                              WHERE Id IN :accounts]){
            System.assertNotEquals(null, accRetrieve.Participant_id__c);
        }
    }

    //Testing that the record is submittted for approval
    @isTest
    static void accountAutoSubmitTest(){
        setRecordType();
        setCountryId();
        Account acc = new Account(
                                Name = 'Test Account', 
                                Approval_Status__c = 'Resubmit Required',
                                Participant_id__c = '6652',
                                RecordTypeId = PROS_RT,
                                Requested_Approval__c = 'New Customer - Direct',
                                /*BillingStreet = 'test',
                                BillingCity = 'test',
                                BillingCountry = 'Canada',
                                BillingPostalCode = 'test',*/
                                pw_cc__BillingCountryLookup__c = COUNTRY_ID,
                                Billing_Zip_Postal_Code__c = '0010',
                                Billing_City__c = 'test',
                                Billing_Street__c ='testStreet',
                                //update custom Account Billing address fields.
                                Invoice_Delivery_Method__c = 'E',
                                Payment_Term__c = 'Net 30'
                                );       
        Test.startTest();
        insert acc;
        Test.stopTest();

        update acc;

        List<ProcessInstance> processInstances = [select Id, Status from ProcessInstance where TargetObjectId = :acc.id];
        System.assertEquals(1, processInstances.size());
    }

     @isTest
     private static void validateAccountContactDeletetion(){
        setRecordType();
        setCountryId();
        Test.startTest();
        List<Contact> contList = createContact(2);
        Account acc = new Account(Name = 'Test',  pw_cc__BillingCountryLookup__c = COUNTRY_ID,
                                Billing_Zip_Postal_Code__c = '0010',
                                Participant_id__c = '6666',
                                Billing_City__c = 'test',
                                Billing_Street__c ='testStreet',
                                //update custom Account Billing address fields.
                                Invoice_Delivery_Method__c = 'E',
                                Payment_Term__c = 'Net 30',recordTypeid = Schema.SObjectType.Account.RecordTypeInfosByName.get('Site').RecordTypeId);
        insert acc;
        
        Account acc1 = new Account(
                                Name = 'Test Account', 
                                Participant_id__c = '6652',
                                RecordTypeId = PROS_RT,
                                pw_cc__BillingCountryLookup__c = COUNTRY_ID,
                                Billing_Zip_Postal_Code__c = '0010',
                                Billing_City__c = 'test',
                                Billing_Street__c ='testStreet',
                                Invoice_Delivery_Method__c = 'E',
                                Payment_Term__c = 'Net 30'
                                );       
        insert acc1;

        Account_Contact__c accountContact = new Account_Contact__c(Contact__c = contList[0].Id, RecordStatus__c  = 'Active',Contact_Key__c ='test', Account__c=acc.Id, Participant_Account__c=acc1.Id); 
        insert accountContact;

         try{
             delete contList;
          }catch(DmlException ex){
          }
          try{
            delete acc;
          }catch(DmlException ex){
          }
        Test.stopTest();
     
     }

private static List<Contact> createContact(Integer howMany){
    List<Contact> contList = new List<Contact>();
    for (Integer i = 0; i < howMany; i++){
      contList.add( new Contact(LastName='Test'+i, Email='test@test.com') );
    }
    insert contList;
    return contList;    
  }

}