src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>CS_Product__c</fullName>
        <formula>Product2.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Version__c</fullName>
        <formula>CS_Product_Version__r.CS_Version__c+&apos; &apos;+BLANKVALUE(TEXT(CS_Product_Version__r.CS_Patch_Version__c),&apos;&apos;)</formula>
        <inlineHelpText>Product Version</inlineHelpText>
        <label>Version</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CS_Product_Group__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Product Group listed on Community Resource Page</description>
    <fields>
        <fullName>CS_Product_Group_Name__c</fullName>
        <description>**** Picklist Values of Product Group on Community Resource Page *****</description>
        <label>Product Group Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>GW Product Group</label>
</CustomObject>

src/objects/CS_Release__c.object
<CustomObject>
    <description>***Service Cloud **** This Object  maintains the Installable Product versions</description>
    <fields>
        <fullName>CS_Localization__c</fullName>
        <label>Localization</label>
        <picklist>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dutch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>English</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>English (AU-NZ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>English (GB)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Major_Release_version__c</fullName>
        <inlineHelpText>Major Release Version (1, 2, 3, 4, 5, 6…)</inlineHelpText>
        <label>Major Release Version</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Minor_Release_Version__c</fullName>
        <inlineHelpText>Minor Release Version (1, 2, 3, 4, 5, 6…)</inlineHelpText>
        <label>Minor Release Version</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Patch_Version__c</fullName>
        <description>Patch Version (Patch 1, Patch 2…)</description>
        <inlineHelpText>Patch Version (Patch 1, Patch 2…)</inlineHelpText>
        <label>Patch Version</label>
        <picklist>
            <picklistValues>
                <fullName>Patch 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patch 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patch 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patch 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patch 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patch 6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patch 7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patch 8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patch 9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patch 10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patch 11</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordType.Name</field>
                <operation>contains</operation>
                <value>Standard Products,Entitled Product</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Product_Version</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CS_Release_Type__c</fullName>
        <label>Release Type</label>
        <picklist>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Localization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold Master</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Version__c</fullName>
        <formula>TEXT(CS_Major_Release_version__c) + &apos;.&apos; +  IF(NOT(ISPICKVAL(CS_Minor_Release_Version__c, &apos;&apos;)), TEXT(CS_Minor_Release_Version__c), &apos;0&apos;) +  IF(NOT(ISPICKVAL(CS_Maintenance_Release_Version__c, &apos;&apos;)), &apos;.&apos; + TEXT(CS_Maintenance_Release_Version__c), &apos;&apos;)</formula>
        <label>Version</label>
        <type>Text</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Product Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Group_Name__c</fullName>
        <label>Product Group Name</label>
        <picklist>
            <controllingField>Product_line_Name__c</controllingField>
            <picklistValues>
                <fullName>Alliances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BillingCenter Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ClaimCenter Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core Add Ons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital experience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Portals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guidewire Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted InsuranceSuite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InsuranceSuite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Millbrook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PolicyCenter Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Predictive Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard-based Templates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underwriting Management</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/CS_ResourcesController.cls
/*
*****************************************************************************************************************************
Class Name - CS_ResourcesController
Class Type -  Controller
Test Class-
Purpose-  Resource  filter Lightning Component Controller


*****************************************************************************************************************************

Name        Email              Date             Notes 
Shan xu                                            Initial Creation

*****************************************************************************************************************************
*/
public without  sharing class CS_ResourcesController {
    static User user {
        get {
            return [Select Id, AccountId, ContactId from User where Id = :UserInfo.getUserId()];
        }
    }
    
    @AuraEnabled
    public static List<String> getReleaseProducts() {
        List<CS_Release__c> releases = [Select CS_Product__r.Name, CS_Product__c from CS_Release__c];
        Set<String> productNameSet = new Set<String>();
        for (CS_Release__c r : releases) {
            productNameSet.add(r.CS_Product__r.Name);
        }
        List<String> productNameList = new List<String>(productNameSet);
        System.debug('productNameList ' + productNameList);
        return productNameList;
    }
    
    @AuraEnabled
    public static List<String> getProductVersions (String product) {
        List<CS_Release__c> releases = [Select CS_Minor_Release_Version__c, CS_Patch_Version__c, CS_Major_Release_version__c, CS_Version__c, CS_Release_Type__c, CS_Localization__c, CS_Product__c from CS_Release__c
                                        where CS_Product__r.Name = :product
                                        order by CS_Version__c desc];
        Set<String> productVersionSet = new Set<String>();
        for (CS_Release__c r: releases) {
            productVersionSet.add(r.CS_Version__c);
        }
        system.debug('product versions ' + productVersionSet);
        return new List<String>(productVersionSet);
    }
    
    
    @AuraEnabled
    public static List<String> getLanguagePickval() {
        List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = CS_Release__c.CS_Localization__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        for (Schema.PicklistEntry p : ple) {
            options.add(p.getLabel());
        }
        return options;
    }
    
    
    @AuraEnabled
    public static Map<String, String> getReleaseProductByAsset(String assetId) {
        Asset asset = [Select Id, Product2Id, Product2.Name, Product2.Product_Group_Name__c from Asset where Id = :assetId];

       
        Map<String, String> assetProductMap = new Map<String, String>();
        if (asset != null) {
            assetProductMap.put('product', asset.Product2.Name);
            assetProductMap.put('productGroup', asset.Product2.Product_Group_Name__c);
        }
         System.debug('assetProductMap ' + assetProductMap);
        return assetProductMap;
    }

    // Method created by Mani on 8/20  to display Product Groups on Resource Page
    @AuraEnabled
    public static List<String> getProductGroupPickvals() {
      List<String> options = new List<String>();      
        // Find all the Product Group in the custom setting GW Product Group
        Map<String, CS_Product_Group__c> PGs = CS_Product_Group__c.getAll();
        // Sort them by name
        List<String> PGNames = new List<String>();
        PGNames.addAll(PGs.keySet());
        PGNames.sort();
        // Create the Select Options.
        for (String PGName : PGNames) {
            CS_Product_Group__c PG = PGs.get(PGName);
            options.add(PG.CS_Product_Group_Name__c);
        }
        return options;
     }
   
    @AuraEnabled
    public static List<String> getProductsByProductGroup(String productGroup) {
        List<CS_Release__c> releases = [Select CS_Product__r.Name, CS_Product__c from CS_Release__c where CS_Product__r.Product_Group_Name__c = :productGroup];
        Set<String> productNameSet = new Set<String>();
        for (CS_Release__c r : releases) {
            productNameSet.add(r.CS_Product__r.Name);
        }
        List<String> productNameList = new List<String>(productNameSet);
        System.debug('productNameList ' + productNameList);
        return productNameList;
    }
}