src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>CS_Product__c</fullName>
        <formula>Product2.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Record_Type_Name__c</fullName>
        <description>Asset Record Type Name</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CS_Release__c.object
<CustomObject>
    <description>***Service Cloud **** This Object  maintains the Installable Product versions</description>
    <fields>
        <fullName>CS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordType.Name</field>
                <operation>contains</operation>
                <value>Standard Products,Entitled Product</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Product_Version</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Product Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CS_Software_Downloads__c.object
<CustomObject>
    <fields>
        <fullName>CS_Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Software Downloads</relationshipLabel>
        <relationshipName>Software_Downloads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CS_Document_Id__c</fullName>
        <label>Document Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_FileExtension__c</fullName>
        <label>FileExtension</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_File_Id__c</fullName>
        <label>Version Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_File_Type__c</fullName>
        <label>File Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Product__c</fullName>
        <formula>BLANKVALUE(CS_Asset__r.Product2.Product__r.Name, CS_Asset__r.Product2.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Release</label>
        <referenceTo>CS_Release__c</referenceTo>
        <relationshipLabel>Software Downloads</relationshipLabel>
        <relationshipName>Software_Downloads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Software Download</label>
    <nameField>
        <label>Software Downloads Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Software Downloads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordType.Name</field>
                <operation>equals</operation>
                <value>Standard Products</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>SKUs</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>Owner - Roopal Shah</description>
    <label>Product(C)</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products(C)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CS_Softwaredownload_Util.cls
/*
*****************************************************************************************************************************
Class Name - CS_Softwaredownload_Util
Class Type - Util
Test Class-
Purpose- 


*****************************************************************************************************************************

Name        Email              Date             Notes 
Mani                                           Initial Creation
Mani       manig@slalom.Com   08/04/2016       Updated to Asset Grouping Changes 
Mani       manig@slalom.Com   08/25/2016       Modified for DE434
Mani G     manig@slalom.com  08/26/2016        For Partner Certified Assets , Releases will happen to assets linked to main Releases
Mani G     manig@slalom.com  09/28/2016        Commenting the code which populates the Content Version link to SD
*****************************************************************************************************************************
*/
public  class CS_Softwaredownload_Util 
{

    @future
    public  Static Void  ProcessDownloads(Set<Id> SetPVIds,Set<Id> LstAssetids)
    {    
        List<CS_Software_Downloads__c> LstCS= New List<CS_Software_Downloads__c>();
        Set<Id> PrdId= New Set<id>();
        List <CS_Release__c> LstRelease= New List<CS_Release__c>([Select id,CS_Product__c,Name from  CS_Release__c where id in:SetPVIds]);
        for(CS_Release__c csr:LstRelease){PrdId.add(csr.CS_Product__c);}
        //System.debug('LstRelease='+LstRelease);
        //System.debug('PrdId=='+PrdId);
        //List<Asset> LstAsset= New List<Asset>([Select id,Product2id ,Product2.Product__c from asset Where Product2.Product__c in : PrdId 
        List<Asset> LstAsset= New List<Asset>([Select id,Product2id ,Product2.Product__c from asset Where Product2id in : PrdId 
                                                and id in :LstAssetids and   CS_Record_Type_Name__C='Child Asset']);
        System.debug('LstAsset'+LstAsset);
        List<ContentDocumentLink> LstCDL = New  List<ContentDocumentLink>([Select Id, ContentDocument.Title, ContentDocument.FileExtension, 
                                                                            ContentDocument.LatestPublishedVersionId, 
                                                                            ContentDocument.FileType, LinkedEntityId, ContentDocumentId 
                                                                            from ContentDocumentLink where LinkedEntityId 
                                                                            in :SetPVIds]);
        Set<id> SetCD=New Set<id>();
        for(ContentDocumentLink cdl : LstCDL) {
            SetCD.add(cdl.ContentDocumentId);
        }
        system.debug('SetCD==' +SetCD);
        List<ContentDocument> LstCD= [Select Id, Title, FileExtension, LatestPublishedVersionId, FileType from ContentDocument where Id in :SetCD];
        Map<id,Map<Id,ContentDocument>> MMapCD= New Map<id,Map<Id,ContentDocument>>();
        Map<Id,ContentDocument> MapCD= New Map<id,ContentDocument>();
        for (ContentDocument newCD : LstCD) {
            for (ContentDocumentLink newCDL : LstCDL) { 
                    MapCD.Put(newCDL.LinkedEntityId,newCD);
                    MMapCD.put(newCDL.LinkedEntityId,MapCD);
            }
        }
        for (CS_Release__c csr :LstRelease ){
                for (Asset ast:LstAsset){
                        CS_Software_Downloads__c newCS = New CS_Software_Downloads__c ();
                        if(csr.CS_Product__c == ast.Product2id ){
                                newCS.CS_Asset__c=ast.id;
                                //newCS.CS_File_Id__c=(String) MMapCD.get(csr.id).get(csr.id).get('LatestPublishedVersionId');
                                //newCS.CS_File_Type__c=(String) MMapCD.get(csr.id).get(csr.id).get('FileType');
                                newCS.CS_Release__c=csr.id;
                                //newCS.CS_FileExtension__c=(String) MMapCD.get(csr.id).get(csr.id).get('FileExtension');
                                //newCS.Name=(String) MMapCD.get(csr.id).get(csr.id).get('Title');
                                newCS.Name=csr.name;
                                //newCS.CS_Document_Id__c=(String) MMapCD.get(csr.id).get(csr.id).get('Id');
                        }
                        LstCS.add(newCS);  
                }
        }
        if (lstCS != null && !lstCS.isEmpty()) {
            try {
                Insert lstCS;
            } catch (DmlException ex) {
                System.debug('DmlException ' + ex.getMessage());
                CS_ExceptionHandler.createErrorRecordMessage( 'Error Occured While Publishing Release Records to Asset'+ ex.getMessage(),'CS_Softwaredownload_Util.ProcessDownloads ');
            }
        }
        
}
}