src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>CS_Primary_Supp_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pri. Support Partner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assets6</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CS_Owner_Team__c</fullName>
        <formula>IF( ISBLANK(Owner:User.Id),  CASE( Owner:Queue.QueueName , 
                                   	&apos;Support&apos;, &apos;Support&apos;,
                                        &apos;Implementation Queue&apos;, &apos;Enablement Queue&apos;,
&apos;ODC&apos;,&apos;ODC&apos;,
                                        &apos;Other&apos;) ,
                             TEXT(Owner:User.CS_User_Team__c) )</formula>
        <label>Owner Team</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <picklist>
            <controllingField>Asset_Type__c</controllingField>
            <picklistValues>
                <fullName>1-Blocker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2-Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3-Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4-Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1–Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2–Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3–Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4–Cosmetic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <description>Support Contact</description>
        <label>Support</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>CS_User_Team__c</fullName>
        <label>User Team</label>
        <picklist>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enablement-SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enablement-CE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enablement-Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CaseDataReportwithTeam.cls
/*
Apex Class Name - CaseDataController
Description - UsedBy the CaseDataReportwithTeam VF Page to print the cases in a certain view. 
*/

public class CaseDataReportwithTeam{

        public PageReference processRequests() {
            
            return null;
        }
        
        public String userSelected {get; set;}
        public String userList {get; set;}
                
        public List<SelectOption> getUserIDs() {
            List<SelectOption> options = new List<SelectOption>();
            List<User> userList = new List<User>([Select ID, Name, FirstName, LastName from User Where IsActive = True AND User.Profile.UserLicense.Name = 'Salesforce' AND CS_User_Team__c ='Support' ORDER By NAME ASC]);
            for (User usr:userList){
            options.add(new SelectOption(usr.Id,usr.Name));
            }
            return options;
        }

        public List<wrapCase> caseList{
            
                get {
                
                ID userID =  UserInfo.getUserId(); 
      
                if (userSelected != null )
                { 
                    if (userSelected !=''){
                    userID = userSelected ; 
                    }
                }
                
                System.Debug('The User ID is..' + userId);
                
                List<wrapCase> lstWrapCase = new List<wrapCase>();
                if (caseList== null) {

                
                //Get the list of cases. 
                List<case> caseData = [Select CaseNumber, ID, Owner.Id,LastModifiedDate, Owner.Name, Severity__c,Contact.Id,Contact.Name,Subject, OwnerID, Asset.ParentID,CreatedDate,Status, Asset.Parent.Name, Asset.CS_Primary_Supp_Partner__c, Asset.CS_Primary_Supp_Partner__r.Name,  (SELECT MemberID, Member.Username, Member.Name, TeamRole.Name FROM TeamMembers) FROM CASE WHERE (CS_Owner_Team__c='Support' AND Status != 'Closed' AND Status!= 'Verified' AND RecordType.Name= 'Customer Support' AND ISClosed = false) ORDER BY CreatedDate DESC LIMIT 10000 ];
                for (case caseRec:caseData){
                
                     string highlightMyName = '';
                     string endhighlightMyName = '';
                     String assetPrimaryContact = '';
                     String caseOwnerStartTag = '';
                     String caseOwnerEndTag = '';
                     String collaborator='';
                     String followtheSun='';
                     String leads='';
                     Set<ID> collaboratorIDs = new Set<ID>();
                     Set<ID> followtheSunIDs= new Set<ID>();
                     Set<ID> leadIDs= new Set<ID>();
                     
                     
                    //Datetime createdTimeCust;
                     if (caseRec.Asset.CS_Primary_Supp_Partner__c != Null){
                         if (caseRec.Asset.CS_Primary_Supp_Partner__c ==userID){
                         
                         assetPrimaryContact   = '<mark>' + caseRec.Asset.CS_Primary_Supp_Partner__r.Name + '</mark>';
                         }
                         else {
                         assetPrimaryContact = caseRec.Asset.CS_Primary_Supp_Partner__r.Name;
                         }
                    }
                   
                    //Highlight the Owner 
                    if (caseRec.OwnerId ==userID){

                        caseOwnerStartTag = '<mark>' ; 
                        caseOwnerEndTag = '</mark>';
                    }
                  
                    
                    
                     CaseTeamMember CaseTeamMember= new CaseTeamMember();
                     List<CaseTeamMember> caseTeamMemberList = caseRec.TeamMembers;
                     //If the Case has case team members, parse through and build the tags. 
                     if (caseTeamMemberList!= NULL){
                     for (CaseTeamMember teamMember: caseTeamMemberList )
                     {
                        
                        string teamMemberName = teamMember.Member.Name;
                        
                        if (teamMember.MemberID ==userID){
                        highlightMyName = '<mark>' ;
                        endhighlightMyName = '</mark>';
                        }
                        if (teamMember.TeamRole.Name.toUpperCase() == 'COLLABORATOR')
                         { 
                             if (collaborator != ''){ 
                             collaborator = collaborator  + ' , ' + highlightMyName +  teamMemberName + endhighlightMyName ;} 
                             else {
                             collaborator =  highlightMyName + teamMemberName + endhighlightMyName ;
                             }
                             collaboratorIDs.add(teamMember.MemberID);
                         }
                        else if (teamMember.TeamRole.Name.toUpperCase() =='FOLLOW THE SUN')
                         {
                             if (followtheSun!= ''){ 
                             followtheSun= followtheSun+ ', ' + highlightMyName + teamMemberName + endhighlightMyName ;} 
                             else {
                             followtheSun= highlightMyName + teamMemberName + endhighlightMyName ;
                             }
                             followtheSunIDs.add(teamMember.MemberID);
                         }
                          else if (teamMember.TeamRole.Name.toUpperCase() =='LEADS')
                         {
                             if (leads != ''){ 
                             leads = leads + ', ' + highlightMyName + teamMemberName + endhighlightMyName ;} 
                             else {
                             leads = highlightMyName + teamMemberName + endhighlightMyName ;
                             }
                             leadIDs.add(teamMember.MemberID);
                         }
                         
                         highlightMyName = '' ;
                         endhighlightMyName = '';
                      }
                      
                     
                   }
                   if (caseRec.OwnerId == userID || caseRec.Asset.CS_Primary_Supp_Partner__c ==userID || 
                   collaboratorIDs.contains(userID) || 
                   followtheSunIDs.contains(userID)  || 
                   leadIDs.contains(userID)) 
                   {
                   wrapCase wrapCase1 = new wrapCase(caseRec,caseOwnerStartTag, caseOwnerEndTag, assetPrimaryContact,collaborator,followtheSun,leads, caseRec.CreatedDate.format(),caseRec.LastModifiedDate.format());
                   lstWrapCase.add(wrapCase1 );
                   }
                }
               }
           return lstWrapCase ;
        }
        set;
    }
      
    
    public class wrapCase {
    
            public case caseRecord {get; set;}
            public String collaborator{get;set;}
            public String caseOwnerStartTag{get;set;}
            public String caseOwnerEndTag{get;set;}
            public String followtheSun{get;set;}
            public String leads{get;set;}
            public String createdDateFormated{get;set;}
            public String lastModDateFormated{get;set;}
            public String assetPrimaryContact{get;set;}
    
     
            public wrapCase(Case caseRecord, String caseOwnerStartTag, String caseOwnerEndTag, String assetPrimaryContact, String collaborator, String FollowtheSun, String leads, String createdDateFormated, String lastModDateFormated) {
                this.caseRecord = caseRecord;
                this.caseOwnerStartTag = caseOwnerStartTag;
                this.caseOwnerEndTag = caseOwnerEndTag;
                this.collaborator = collaborator;
                this.assetPrimaryContact = assetPrimaryContact;
                this.followtheSun =  followtheSun; 
                this.leads = leads;
                this.createdDateFormated = createdDateFormated;
                this.lastModDateFormated = lastModDateFormated;
            }
        }
       
    }