src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CS_Associated_Jira__c</fullName>
        <description>**Please enter multiple Jira separated by comma and no space should be left in between.</description>
        <inlineHelpText>**Please enter multiple Jira seperated by comma and no space should be left in between.</inlineHelpText>
        <label>Associated Jira</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <description>Support Contact</description>
        <label>Support</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Request__c.object
<CustomObject>
    <fields>
        <fullName>CS_Associated_Jira__c</fullName>
        <formula>CS_Case__r.CS_Associated_Jira__c</formula>
        <label>Associated Jira</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Case_Number__c</fullName>
        <formula>CS_Case__r.CaseNumber</formula>
        <label>Case Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CS_Customer_Commitment__c</fullName>
        <label>Customer Commitment</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CS_Dev_Current_Status__c</fullName>
        <label>Dev Current Status</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CS_Dev_Jira__c</fullName>
        <label>Dev Jira</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Escalation_Note__c</fullName>
        <inlineHelpText>Description/Synopsis</inlineHelpText>
        <label>Case Summary</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CS_Escalation_Request_Date__c</fullName>
        <label>Request Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CS_Fix_by_Version__c</fullName>
        <label>Requested Fix Version</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Information_Request__c</fullName>
        <inlineHelpText>Question</inlineHelpText>
        <label>Information Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CS_Next_Dev_Response__c</fullName>
        <label>Next Response Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CS_Request_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Guidewire Internal person submitting the request. (Please choose Guidewire employees only)</inlineHelpText>
        <label>Request Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CS_Request_Reason__c</fullName>
        <label>Request Reason</label>
        <picklist>
            <controllingField>CS_Request_Type__c</controllingField>
            <picklistValues>
                <fullName>None Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Request/Feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Fix Commitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immediate Patch Commitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dev Provided Workaround</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dev Validate Workaround/Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fix in Patch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fix in Maintenance Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Address in Next Major Release</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Request_Status__c</fullName>
        <inlineHelpText>Request Status</inlineHelpText>
        <label>Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Answered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Updated by Requestor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on Requestor</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Request_Type__c</fullName>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>Long Term Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Term Request</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Submitted_First_Time__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box is checked when the request was first submitted</description>
        <label>Submitted First Time</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Owner_Email__c</fullName>
        <description>Case owner&apos;s email is populated from workflow field update.</description>
        <label>Case Owner Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Dev_Assignee_Group__c</fullName>
        <label>Dev Assignee Group</label>
        <picklist>
            <picklistValues>
                <fullName>CorePerf Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Team</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dev_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dev Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pgm_Request_Owner__c</fullName>
        <label>Pgm Request Owner</label>
        <picklist>
            <picklistValues>
                <fullName>BillingCenter PgM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ClaimCenter PgM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PolicyCenter PgM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Platform PgM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DataManagement PgM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Portals PgM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>Req-{00000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CS_DevRequestEmailHelper.cls
/*
*****************************************************************************************************************************
Class Name - CS_DevRequestEmailHelper
Class Type -  Helper class for Email.
Test Class-
Purpose- 

*****************************************************************************************************************************

Name        Email              Date             Notes 
hari                           9/23/2016       created it.
*****************************************************************************************************************************
*/

public with  sharing class CS_DevRequestEmailHelper
{
    public Set < String > noDuplicates = new Set < String > ();
    private static string replyToAddress='noreply@salesforce.com';
    
        
    public void SendDevRequestEmail(set<id> ReqIds, set<id> CaseIds)
    {
         Map<id, List<CaseTeamMember>> CaseteamMap = new Map<id, List<CaseTeamMember>>();
         
          List<CaseTeamMember> caseTeamMembers = new List<CaseTeamMember> ([SELECT Id, Member.Id, Member.Email, TeamRole.Name, ParentId FROM CaseTeamMember WHERE ParentId IN: caseIds
                                                                                  AND TeamRole.Name NOT IN('Customer Case Contact','Customer Support', 'Customer Support (View Only)', 'Partner') ]);
                                                                                  
           for(CaseTeamMember tm : caseTeamMembers)
           {
             if(CaseteamMap.containsKey(tm.ParentId))
             {
                List<CaseTeamMember> tLst = CaseteamMap.get(tm.ParentId);
                tLst.add(tm);
                CaseteamMap.put(tm.ParentId, tLst);
             }   
             else
             {
                List<CaseTeamMember> tLst = new List<CaseTeamMember>();
                tLst.add(tm);
                CaseteamMap.put(tm.ParentId, tLst);
             }
           }
           
           List<CS_Request__c> reqEmailLst = [Select id,name,CS_Request_Owner__c,CS_Request_Owner__r.Name,Pgm_Request_Owner__c,CS_Request_Status__c, CS_Information_Request__c, CS_Case__c, CS_Escalation_Note__c, CS_Fix_by_Version__c, CS_Customer_Commitment__c, CS_Dev_Jira__c,
                                              CS_Next_Dev_Response__c, CS_Associated_Jira__c, Dev_Assignee__c,CS_Escalation_Request_Date__c, CS_Request_Type__c, CS_Dev_Current_Status__c, CS_Request_Reason__c, Dev_Assignee_Group__c,CS_Request_Owner__r.Email,Dev_Assignee__r.Email,
                                              Case_Owner_Email__c,Dev_Assignee__r.Name,CS_Submitted_First_Time__c,CS_Case__r.Owner.Email,CS_Case_Number__c,CS_Case__r.CaseNumber from CS_Request__c where Id IN: ReqIds ];
                                              
           OrgWideEmailAddress LstOrgAddress= [SELECT id, Address FROM OrgWideEmailAddress WHERE DisplayName ='Guidewire Community'];
           Messaging.SingleEmailMessage[] emailMessageList = new Messaging.SingleEmailMessage[]{};
           
         for(CS_Request__c Req: reqEmailLst)
         {
          if(Req.CS_Submitted_First_Time__c == true)
           {
              Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
              String[] toAddresses = new String[]{}; 
              
              if(Req.CS_Request_Owner__r.Email != null)
              {
                 toAddresses.add(Req.CS_Request_Owner__r.Email);
              }
              
              if(Req.Dev_Assignee__r.Email != null)
              {
                 toAddresses.add(Req.Dev_Assignee__r.Email);
              }
              
              if(Req.CS_Case__r.Owner.Email != null)
              {
                 toAddresses.add(Req.CS_Case__r.Owner.Email);
              }
              
              if(CaseteamMap.size() >0 && CaseteamMap.get(Req.CS_Case__c).size() >0)
              {
               for (CaseTeamMember member: CaseteamMap.get(Req.CS_Case__c))
               {
                    system.debug('member email==' + member.member.email +' Team Role==' + member.TeamRole.Name + 'Dup Check==' + noDuplicates);
                    
                    if(member.Member.Email != null && isNewAddress(member.Member.Email) )
                    {
                       if (member.TeamRole.Name == 'GW Watcher') 
                        {
                            toAddresses.add(member.Member.Email);
                        }
                        if (member.TeamRole.Name == 'Follow the Sun')
                        {
                            toAddresses.add(member.Member.Email);
                        }
                        if (member.TeamRole.Name == 'Leads')
                        {
                            toAddresses.add(member.Member.Email);
                        }
                        if (member.TeamRole.Name == 'Collaborator') 
                        {
                            toAddresses.add(member.Member.Email);
                        }
                    }
                }
               } 
               
               mail.setToAddresses(toAddresses);       
               mail.setSubject('Fields updated for the following Dev Request - '+ Req.Name);
               mail.setReplyTo(replyToAddress);
               
               if(LstOrgAddress!=null)
               {
                 mail.setOrgWideEmailAddressId(LstOrgAddress.id);
               } 
               string table ='Hello,';
                            table = table +'<br>';
                            table = table +'<br>';
                            table = table + 'There is an update for some of the fields on the below Dev Request.';
                            table = table +'<br>';
                            table = table +'<br>';
                            table = table + '<b>Request Owner :</b>' + Req.CS_Request_Owner__r.Name + '<br>';
                            table = table + '<b>Pgm Request Owner :</b>' + Req.Pgm_Request_Owner__c + '<br>';
                            table = table + '<b>Request Status :</b>' + Req.CS_Request_Status__c + '<br>';
                            table = table + '<b>Request Date :</b>' + Req.CS_Escalation_Request_Date__c +'<br>';
                            table = table + '<b>Information Request :</b>' + Req.CS_Information_Request__c +'<br>';
                            table = table + '<b>Case :</b>' + Req.CS_Case_Number__c +'<br>';
                            table = table + '<b>Case Summary :</b>' + Req.CS_Escalation_Note__c +'<br>';
                            table = table + '<b>Requested Fix Version :</b>' + Req.CS_Fix_by_Version__c +'<br>';
                            table = table + '<b>Customer Commitment :</b>' + Req.CS_Customer_Commitment__c +'<br>';
                            table = table + '<b>Dev Jira :</b>' + Req.CS_Dev_Jira__c +'<br>';
                            table = table + '<b>Associated Jira :</b>' + Req.CS_Associated_Jira__c +'<br>';
                            table = table + '<b>Request Type :</b>' + Req.CS_Request_Type__c +'<br>';
                            table = table + '<b>Request Reason :</b>' + Req.CS_Request_Reason__c +'<br>';
                            table = table + '<b>Next Response Date :</b>' + Req.CS_Next_Dev_Response__c +'<br>';
                            table = table + '<b>Dev Assignee :</b>' + Req.Dev_Assignee__r.Name +'<br>';
                            table = table + '<b>Dev Current Status :</b>' + Req.CS_Dev_Current_Status__c +'<br>';
                            table = table + '<b>Dev Assignee Group :</b>' + Req.Dev_Assignee_Group__c +'<br>';
                            table = table +'<br>';
                            table = table +'<br>';
                            table = table +'<br>';
                            table = table + 'Here is the link to the Dev Request :';
                            table = table + '<a href="'+URL.getSalesforceBaseUrl().toExternalForm()+'/'+Req.id+'"><b>'+Req.Name+'</b></a>';
                            
                      mail.setHtmlBody(Table);
                      emailMessageList.add(mail);
              }
           }
              Messaging.sendEmail(emailMessageList);
      }
      
       public Boolean isNewAddress(String inAddress) 
       {
        Boolean bool = false;
        Integer initialCount = noDuplicates.size();
        noDuplicates.add(inAddress);
        if(noDuplicates.size()>initialCount)
        {
            bool = true;
        } 
        else
        {
            bool = false;
        }
        return bool;
       }

}