src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CPQ_In_Scope_DWP__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>In-Scope Delta DWP Ranges</relationshipLabel>
        <relationshipName>CPQ_In_Scope_DWP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Premium_Amount__c</fullName>
        <label>Premium Amount</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>In-Scope DWP</label>
    <nameField>
        <displayFormat>Range-{000000}</displayFormat>
        <label>Range Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>In-Scope DWPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CPQ_Create_Service_Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Service Contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CPQ_Renewal_In_Scope_DWP__c</fullName>
        <inlineHelpText>Used for Renewals only.</inlineHelpText>
        <label>Renewal In-Scope DWP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Premium_In_Scope__c</fullName>
        <inlineHelpText>This should be the deal premium in scope or the incremental DWP Adjustment. Used in conjunction with Price Rules to calculate the price for certain Products.</inlineHelpText>
        <label>Premium In Scope</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates this opportunity is a renewal opportunity.</description>
        <inlineHelpText>Indicates this opportunity is a renewal opportunity.</inlineHelpText>
        <label>Renewal</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordType.Name</field>
                <operation>equals</operation>
                <value>Standard Products</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>SKUs</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_line_Name__c</fullName>
        <label>Product Line Name</label>
        <picklist>
            <picklistValues>
                <fullName>Core processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data and Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Engagement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__BillingFrequency__c</fullName>
        <description>Determines how often this product will be invoiced.</description>
        <globalPicklist>SBQQ__BillingFrequency</globalPicklist>
        <inlineHelpText>Determines how often this product will be invoiced.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionTerm__c</fullName>
        <description>Term length of this subscription. Only applicable if the product is a subscription.</description>
        <inlineHelpText>Term length of this subscription. Only applicable if the product is a subscription.</inlineHelpText>
        <label>Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>Owner - Roopal Shah</description>
    <label>Product(C)</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products(C)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CPQ_In_Scope_DWP_Calc_HelperTest.cls
@isTest
public class CPQ_In_Scope_DWP_Calc_HelperTest {

    public static final String NET15 = 'Net 15';
    public static final String MONTHLY = 'Monthly';
    public static final String SEMIANNUAL = 'Semiannual';

    public static testMethod void opportunityInsertTest() {
        Account account = CPQ_TestDataUtility.accountTestData(true);

        Opportunity originalOppty = CPQ_Quote_Utilities_Test.createOpportunity(account.Id, null, null, 1, false);
        // SBQQ__Quote__c originalQuote = createQuote(originalOppty.Id, false);
        // originalQuote.SBQQ__Primary__c = true;
        // update originalQuote;

        Contract originalContract = CPQ_Quote_Utilities_Test.createContract(account.Id, originalOppty.Id);
        Opportunity renewalOppty1 = CPQ_Quote_Utilities_Test.createOpportunity(account.Id, originalOppty.Id, originalContract.Id, 4, true);

        List<CPQ_In_Scope_DWP__c> inScopeList = [
            SELECT Id
                , Premium_Amount__c
             FROM CPQ_In_Scope_DWP__c
            WHERE Opportunity__c = :renewalOppty1.Id
        ];

        System.assert( inScopeList.size() == 0 );
    }

    public static testMethod void opportunityUpdateTest() {
        Account account = CPQ_TestDataUtility.accountTestData(true);

        Opportunity originalOppty = CPQ_Quote_Utilities_Test.createOpportunity(account.Id, null, null, 1, false);


        Contract originalContract = CPQ_Quote_Utilities_Test.createContract(account.Id, originalOppty.Id);
        Opportunity renewalOppty1 = CPQ_Quote_Utilities_Test.createOpportunity(account.Id, originalOppty.Id, originalContract.Id, 4, true);

        Product2 prod2Obj1 = CPQ_TestDataUtility.productTestData(false);
        prod2Obj1.Product_line_Name__c ='Core processing';
        insert prod2Obj1;

        Product2 prod2Obj = CPQ_TestDataUtility.productTestData(false);
        prod2Obj.Product__c = prod2Obj1.Id;
        insert prod2Obj;

        PricebookEntry pbEntryObj = CPQ_TestDataUtility.pbEntryTestData(prod2Obj.Id, true);
        Id pricebookId = Test.getStandardPricebookId();

        SBQQ__Quote__c quoteObj = CPQ_TestDataUtility.quoteTestData(renewalOppty1.Id, false);
        quoteObj.SBQQ__StartDate__c = Date.today();
        quoteObj.SBQQ__EndDate__c = Date.today();
        quoteObj.SBQQ__PaymentTerms__c = NET15;
        quoteObj.SBQQ__SubscriptionTerm__c = 6;
        quoteObj.SBQQ__BillingFrequency__c  = SEMIANNUAL;
        quoteObj.SBQQ__Opportunity2__c  = renewalOppty1.Id;
        quoteObj.SBQQ__Primary__c = true;
        quoteObj.CPQ_Prorated_Start_Date__c = System.Today();
        insert quoteObj;

        SBQQ__QuoteLine__c  quoteLineItemObj = CPQ_TestDataUtility.quoteLineItemTestData(prod2Obj.Id, quoteObj.Id, false);
        SBQQ__QuoteLine__c  quoteLineItemObj2 = CPQ_TestDataUtility.quoteLineItemTestData(prod2Obj.Id, quoteObj.Id, false);

        List<SBQQ__QuoteLine__c> lstQuoteLineItemToInsert = new List<SBQQ__QuoteLine__c>();
        lstQuoteLineItemToInsert.add(quoteLineItemObj);
        lstQuoteLineItemToInsert.add(quoteLineItemObj2);
        insert lstQuoteLineItemToInsert;

        originalOppty.CPQ_Renewal_In_Scope_DWP__c = 1;
        originalOppty.Premium_In_Scope__c = 7000000;
        update originalOppty;

        CPQ_In_Scope_DWP__c inScopeObj = new CPQ_In_Scope_DWP__c(
            Premium_Amount__c = '100',
            Opportunity__c = renewalOppty1.Id
        );
        insert inScopeObj;


        Test.startTest();

            CPQ_In_Scope_DWP_Calc_Helper.run = true;

            renewalOppty1.CPQ_Create_Service_Contract__c = true;
            renewalOppty1.SBQQ__Renewal__c = true;
            renewalOppty1.Premium_In_Scope__c = 6000000;
            update renewalOppty1;
        Test.stopTest();

        List<CPQ_In_Scope_DWP__c> inScopeList = [
            SELECT Id
                , Premium_Amount__c
             FROM CPQ_In_Scope_DWP__c
            WHERE Opportunity__c = :renewalOppty1.Id
        ];

        System.assert( inScopeList.size() > 0 );
    }
}