src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CS_Access_Type__c</fullName>
        <label>Access Type</label>
        <picklist>
            <picklistValues>
                <fullName>General Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support (View Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Is_Disabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Disabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_RightNow_ID__c</fullName>
        <externalId>true</externalId>
        <label>RightNow ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Do_Not_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Do not contact this person via email or direct mail.  Full Opt-Out.</description>
        <inlineHelpText>Do not contact this person via email or direct mail.  Full Opt-Out.</inlineHelpText>
        <label>Do Not Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_longer_with_firm__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No longer with firm</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>- Will bring in the related Contat and Partner User Information from the triggre on the User.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CS_Asset_Contact_Permissions__c.object
<CustomObject>
    <fields>
        <fullName>CS_Access_Type__c</fullName>
        <label>Access Type</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support (View Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipName>Asset_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CS_Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Asset_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CS_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_RightNow_ID__c</fullName>
        <externalId>true</externalId>
        <label>RightNow ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Asset Contact Permission</label>
    <nameField>
        <label>Product Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Contact Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ACPActivationUserHandler.cls
public without sharing class ACPActivationUserHandler
{
    public static boolean allow = true;
    
    public static void stopTrigger()
    {
       allow = false; 
    }
    
    public static boolean RunTrigger()
    {
      return allow;    
    }
    
    @future
    public static void activateACP(Map<Id,Id> mapUser)
    {
       Map<Id, User> mapUserQ = new Map<Id, User>([Select ID, IsActive from User Where Id in:mapUser.keyset()]);
       List<CS_Asset_Contact_Permissions__c> acpLst =[Select id,name,CS_Access_Type__c,CS_Asset__c,CS_IsActive__c,CS_Contact__c, CS_Contact__r.User__r.IsActive ,CS_RightNow_ID__c from CS_Asset_Contact_Permissions__c where CS_Contact__c IN: mapUser.Values()];
       List<CS_Asset_Contact_Permissions__c> updateacpLst = new List<CS_Asset_Contact_Permissions__c>();
       List<Contact> contactList = new List<Contact>();
       
       if(acpLst.size() >0)
       {
           for(CS_Asset_Contact_Permissions__c acp : acpLst)
            {
               if (acp.CS_Contact__r.User__r.IsActive){
               acp.CS_IsActive__c = true;
               } else {
                   acp.CS_IsActive__c = false;
               }
               updateacpLst.add(acp);
               
             }
        }
        
       if (mapUser != NULL){
       
        if (mapUser.size() >0)
        { 
            for (Id usr:mapUser.keySet()){
            Contact c = new Contact();
            c.ID = mapUser.get(usr);
            c.User__c = usr;
            if (!mapUserQ.get(usr).IsActive)
            {
                c.CS_Is_Disabled__c = true;
                c.No_longer_with_firm__c = true; 
                c.Do_Not_Contact__c = true;
            } else {
                c.CS_Is_Disabled__c = false;
                 c.No_longer_with_firm__c = false; 
                c.Do_Not_Contact__c = false;
            }
            contactList.add(c);
            }
        }
       
       }
       
       
       ACPActivationUserHandler.stopTrigger();
       if (updateacpLst.size() > 0 ){
       Update updateacpLst; 
       }
       if (contactList.size() > 0){
        update contactList;
       }
    }
}