src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>SBQQ__PrimaryQuote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points to primary quote on this opportunity.</description>
        <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
        <label>Primary Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>PrimaryOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CPQ_OrderActivationUtilityTest.cls
/* =================================================================================================
*   Version     Date                   Comment
* =================================================================================================
*   1.0         03-Apr-2017           Test class for CPQ_OrderActivationUtility.
**/
@isTest
private class CPQ_OrderActivationUtilityTest {

    /**
    * Test method to check deactivate related Orders when Order status is updayed to 'Activated'
    */
    @isTest static void testToDeactivateRelatedOrders() {
        Account accObj = CPQ_TestDataUtility.accountTestData(true);

        Opportunity oppObj = CPQ_TestDataUtility.opportunityForContTestData(accObj.Id, true);

        Contract contractObj = CPQ_TestDataUtility.contractTesData(accObj.Id, oppObj.Id, true);

        Opportunity oppWithContract = CPQ_TestDataUtility.opportunityTestData(accObj.Id, contractObj.Id, true);

        Product2 prod2Obj = CPQ_TestDataUtility.productTestData(true);

        PricebookEntry pbEntryObj = CPQ_TestDataUtility.pbEntryTestData(prod2Obj.Id, true);

        SBQQ__Quote__c quoteObj = CPQ_TestDataUtility.quoteTestData(oppWithContract.Id, true);

        oppWithContract.SBQQ__PrimaryQuote__c = quoteObj.Id;
        update oppWithContract;

        List<Order> lstOrder = CPQ_TestDataUtility.orderTestData(accObj.Id,oppWithContract.Id, true);

        OrderItem orderItemObj = CPQ_TestDataUtility.orderItemTestData(lstOrder[0].Id, pbEntryObj.Id, true);

        Order testOrder = CPQ_TestDataUtility.singleOrderUpdate(accObj.Id,oppWithContract.Id, true);

        OrderItem orderItemObjForTestOrder = CPQ_TestDataUtility.orderItemTestData(testOrder.Id, pbEntryObj.Id, true);

        System.Test.startTest();
            testOrder.Status = 'Activated';
            update testOrder;
            lstOrder[0].Status = 'Activated';
            update lstOrder[0];
        System.Test.stopTest();

        List<Order> lstOrderStatusDeactivated = [SELECT Id
                                                      , Status
                                                      FROM Order WHERE Status = 'Deactivated'];
        List<Order> lstOrderStatusDraft = [SELECT Id
                                                , Status
                                                FROM Order WHERE Status = 'Draft'];

        System.assertEquals(1,lstOrderStatusDeactivated.size());
        System.assertEquals(testOrder.Id,lstOrderStatusDeactivated[0].Id);
        System.assertEquals(3,lstOrderStatusDraft.size());
    }
}