src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CPQ_Billing_Schedule__c.object
<CustomObject>
    <description>Billing Schedules will be created when orders are created and will contain all the broken out line items from the order based on the billing frequency</description>
    <fields>
        <fullName>Order_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Order Product</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Order Product must be related to the Order of this Billing Schedule.</errorMessage>
            <filterItems>
                <field>$Source.Order__c</field>
                <operation>equals</operation>
                <valueField>OrderItem.OrderId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Billing Schedules</relationshipLabel>
        <relationshipName>Billing_Schedules</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Billing Schedules</relationshipLabel>
        <relationshipName>Billing_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>startdate__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <label>Billing Schedule</label>
    <nameField>
        <displayFormat>BS-{000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Original_Opportunity_New__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Test . used in Process builder</description>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Original Opportunity)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryQuote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points to primary quote on this opportunity.</description>
        <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
        <label>Primary Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>PrimaryOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates this opportunity is a renewal opportunity.</description>
        <inlineHelpText>Indicates this opportunity is a renewal opportunity.</inlineHelpText>
        <label>Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewedContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract being renewed by this renewal opportunity. In case opportunity rolls up several contracts this points at the master contract.</description>
        <inlineHelpText>Contract being renewed by this renewal opportunity. If the several contracts roll up to this opportunity, this points at the master contract.</inlineHelpText>
        <label>Renewed Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>RenewalOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>CPQ_First_Period_Prorated_Amount__c</fullName>
        <label>Prorated Period Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>First_Invoice_Date__c</fullName>
        <label>Prorated Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Period_Start_Date__c</fullName>
        <label>Prorated Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__BillingFrequency__c</fullName>
        <description>Defines the billing frequency.</description>
        <globalPicklist>SBQQ__BillingFrequency</globalPicklist>
        <inlineHelpText>Defines the billing frequency.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>SBQQ__BillingFrequency__c</fullName>
        <description>Defines the billing frequency.</description>
        <globalPicklist>SBQQ__BillingFrequency</globalPicklist>
        <inlineHelpText>Defines the billing frequency.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote line where this order product is created from.</description>
        <inlineHelpText>The quote line where this order product is created from.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>OrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionTerm__c</fullName>
        <label>Subscription Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>startdate__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SBQQ__BillingFrequency__c</fullName>
        <description>Determines how often this product will be invoiced.</description>
        <globalPicklist>SBQQ__BillingFrequency</globalPicklist>
        <inlineHelpText>Determines how often this product will be invoiced.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionTerm__c</fullName>
        <description>Term length of this subscription. Only applicable if the product is a subscription.</description>
        <inlineHelpText>Term length of this subscription. Only applicable if the product is a subscription.</inlineHelpText>
        <label>Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sku_Type__c</fullName>
        <label>SKU Type</label>
        <picklist>
            <picklistValues>
                <fullName>License</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revenue share</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliance Program</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/CPQ_BillingScheduleCreatorUtilityTest.cls
/* =================================================================================================
*   Version     Date                   Comment
* =================================================================================================
*   1.0         04-Apr-2017           Test class for CPQ_BillingScheduleCreatorUtility.
**/
@isTest
public with sharing class CPQ_BillingScheduleCreatorUtilityTest {

    public static final String NET15 = 'Net 15';
    public static final String MONTHLY = 'Monthly';
    public static final String SEMIANNUAL = 'Semiannual';
    public static Id accountId;
    public static Id serviceContractId;
    public static Id opportunityId;
    public static Id contractId;
    public static Id quoteId;

    /*@testSetup static void commonObjects() {

        Account accObj = CPQ_TestDataUtility.accountTestData(true);
        accountId = accObj.Id;

        ServiceContract serviceContrObj = CPQ_TestDataUtility.serviceContractTestData(accObj.Id, true);
        serviceContractId = serviceContrObj.Id;

        Opportunity oppObj = CPQ_TestDataUtility.opportunityForContTestData(accObj.Id, true);
        opportunityId = oppObj.Id;



    }*/

    /**
     * Test method to check OrderItem and SBQQ__QuoteLine__c created accordingly
     **/
    @isTest static void renewalMaintenanceCreateOrderItemBillingSchedule() {

        //Account obj = [Select Id,Name From Account Where Name = 'Test Account' Limit 1];
        Account accObj = CPQ_TestDataUtility.accountTestData(true);

        Opportunity oppObj = CPQ_TestDataUtility.opportunityForContTestData(accObj.Id, false);
        oppObj.Original_Opportunity_New__c = opportunityId;
        insert oppObj;

        Contract contractObj = CPQ_TestDataUtility.contractTesData(accObj.Id,oppObj.Id,true);

        oppObj.SBQQ__RenewedContract__c = contractObj.Id;
        update oppObj;
        //Opportunity oppWithContract1 = CPQ_TestDataUtility.opportunityTestData(accObj.Id, contractObj.Id, false);

        SBQQ__Quote__c quoteObj1 = CPQ_TestDataUtility.quoteTestData(oppObj.Id, false);

        // Opportunity oppWithContract = CPQ_TestDataUtility.opportunityTestData(accObj.Id, contractObj.Id, false);
        // oppWithContract.Service_Contract__c = serviceContractId;
        oppObj.SBQQ__PrimaryQuote__c = quoteObj1.Id;
        oppObj.SBQQ__Renewal__c = true;
        update oppObj;


        Product2 prod2Obj = CPQ_TestDataUtility.productTestData(false);
        prod2Obj.Sku_Type__c = CPQ_BillingScheduleCreatorUtility.PRODUCT_SKU_TYPE_MAINTENANCE;
        insert prod2Obj;

        PricebookEntry pbEntryObj = CPQ_TestDataUtility.pbEntryTestData(prod2Obj.Id, true);
        Id pricebookId = Test.getStandardPricebookId();

        SBQQ__Quote__c quoteObj = CPQ_TestDataUtility.quoteTestData(oppObj.Id, false);
        quoteObj.SBQQ__StartDate__c = Date.today() + 1;
        quoteObj.SBQQ__EndDate__c = Date.today().addYears(1).addMonths(2);
        quoteObj.SBQQ__PaymentTerms__c = NET15;
        quoteObj.SBQQ__SubscriptionTerm__c = 6;
        quoteObj.SBQQ__BillingFrequency__c  = 'Monthly';
        quoteObj.SBQQ__Opportunity2__c  = oppObj.Id;
        quoteObj.SBQQ__Primary__c = true;
        quoteObj.CPQ_Prorated_Start_Date__c = System.Today();
        insert quoteObj;

        SBQQ__QuoteLine__c  quoteLineItemObj = CPQ_TestDataUtility.quoteLineItemTestData(prod2Obj.Id, quoteObj.Id, false);
        quoteLineItemObj.CPQ_Last_Quote_Invoiced_Support__c = 1000000;
        insert quoteLineItemObj;

        System.Test.startTest();
        Order orderObj = CPQ_TestDataUtility.singleOrderUpdate(accObj.Id, oppObj.Id, false);
        orderObj.Is_Primary__c = true;
        orderObj.SBQQ__Quote__c = quoteObj.Id;
        orderObj.SBQQ__BillingFrequency__c  = 'Monthly';
        orderObj.First_Invoice_Date__c = System.Today();
        orderObj.First_Period_Start_Date__c = System.Today();
        insert orderObj;

         quoteObj.SBQQ__Type__c = CPQ_BillingScheduleCreatorUtility.SBQQ_TYPE_RENEWAL;
         update quoteObj;

         System.debug('...CPQ_Order_BillingSchedule_Helper.run before order' + CPQ_Order_BillingSchedule_Helper.run);

         CPQ_Order_BillingSchedule_Helper.run = true;
         update orderObj;

         System.Test.stopTest();

         List<OrderItem> lstOrderItem = [SELECT Id
                                              , OrderId
                                              , Product2Id
                                          FROM OrderItem
                                         WHERE OrderId =: orderObj.Id
                                          ];
         system.debug('...lstOrderItem: '+lstOrderItem);

         List<CPQ_Billing_Schedule__c> lstBillingSchedule = [
         SELECT Id
             , Name
             , Order__c
             , startdate__c
             , Order_Product__c
             FROM CPQ_Billing_Schedule__c
             WHERE Order_Product__c =: lstOrderItem[0].Id
         ];
         System.assertEquals(1, lstOrderItem.size());
         System.assertEquals(15, lstBillingSchedule.size());
    }

    // @isTest static void renewalMaintenanceZeroCreateOrderItemBillingSchedule() {
    //
    //     //Account obj = [Select Id,Name From Account Where Name = 'Test Account' Limit 1];
    //     Account accObj = CPQ_TestDataUtility.accountTestData(true);
    //
    //     Opportunity oppObj = CPQ_TestDataUtility.opportunityForContTestData(accObj.Id, false);
    //     oppObj.Original_Opportunity_New__c = opportunityId;
    //     insert oppObj;
    //
    //     Contract contractObj = CPQ_TestDataUtility.contractTesData(accObj.Id,oppObj.Id,true);
    //
    //     oppObj.SBQQ__RenewedContract__c = contractObj.Id;
    //     update oppObj;
    //     //Opportunity oppWithContract1 = CPQ_TestDataUtility.opportunityTestData(accObj.Id, contractObj.Id, false);
    //
    //     SBQQ__Quote__c quoteObj1 = CPQ_TestDataUtility.quoteTestData(oppObj.Id, false);
    //
    //     // Opportunity oppWithContract = CPQ_TestDataUtility.opportunityTestData(accObj.Id, contractObj.Id, false);
    //     // oppWithContract.Service_Contract__c = serviceContractId;
    //     oppObj.SBQQ__PrimaryQuote__c = quoteObj1.Id;
    //     oppObj.SBQQ__Renewal__c = true;
    //     update oppObj;
    //
    //
    //     Product2 prod2Obj = CPQ_TestDataUtility.productTestData(false);
    //     prod2Obj.Sku_Type__c = CPQ_BillingScheduleCreatorUtility.PRODUCT_SKU_TYPE_MAINTENANCE;
    //     insert prod2Obj;
    //
    //     PricebookEntry pbEntryObj = CPQ_TestDataUtility.pbEntryTestData(prod2Obj.Id, true);
    //     Id pricebookId = Test.getStandardPricebookId();
    //
    //     SBQQ__Quote__c quoteObj = CPQ_TestDataUtility.quoteTestData(oppObj.Id, false);
    //     quoteObj.SBQQ__StartDate__c = Date.today() + 1;
    //     quoteObj.SBQQ__EndDate__c = Date.today().addYears(1).addMonths(2);
    //     quoteObj.SBQQ__PaymentTerms__c = NET15;
    //     quoteObj.SBQQ__SubscriptionTerm__c = 6;
    //     quoteObj.SBQQ__BillingFrequency__c  = 'Monthly';
    //     quoteObj.SBQQ__Opportunity2__c  = oppObj.Id;
    //     quoteObj.SBQQ__Primary__c = true;
    //     quoteObj.CPQ_Prorated_Start_Date__c = System.Today();
    //     insert quoteObj;
    //
    //     SBQQ__QuoteLine__c  quoteLineItemObj = CPQ_TestDataUtility.quoteLineItemTestData(prod2Obj.Id, quoteObj.Id, true);
    //
    //     System.Test.startTest();
    //     Order orderObj = CPQ_TestDataUtility.singleOrderUpdate(accObj.Id, oppObj.Id, false);
    //     orderObj.Is_Primary__c = true;
    //     orderObj.SBQQ__Quote__c = quoteObj.Id;
    //     orderObj.SBQQ__BillingFrequency__c  = 'Monthly';
    //     orderObj.First_Invoice_Date__c = System.Today();
    //     orderObj.First_Period_Start_Date__c = System.Today();
    //     insert orderObj;
    //
    //      quoteObj.SBQQ__Type__c = CPQ_BillingScheduleCreatorUtility.SBQQ_TYPE_RENEWAL;
    //      update quoteObj;
    //
    //      CPQ_Order_BillingSchedule_Helper.run = true;
    //      update orderObj;
    //
    //      System.Test.stopTest();
    //
    // }


    @isTest static void renewalLicensecreateOrderItemBillingSchedule() {

        //Account obj = [Select Id,Name From Account Where Name = 'Test Account' Limit 1];
        Account accObj = CPQ_TestDataUtility.accountTestData(true);

        Opportunity oppObj = CPQ_TestDataUtility.opportunityForContTestData(accObj.Id, false);
        oppObj.Original_Opportunity_New__c = opportunityId;
        insert oppObj;

        Contract contractObj = CPQ_TestDataUtility.contractTesData(accObj.Id,oppObj.Id,true);

        oppObj.SBQQ__RenewedContract__c = contractObj.Id;
        update oppObj;
        //Opportunity oppWithContract1 = CPQ_TestDataUtility.opportunityTestData(accObj.Id, contractObj.Id, false);

        SBQQ__Quote__c quoteObj1 = CPQ_TestDataUtility.quoteTestData(oppObj.Id, false);

        // Opportunity oppWithContract = CPQ_TestDataUtility.opportunityTestData(accObj.Id, contractObj.Id, false);
        // oppWithContract.Service_Contract__c = serviceContractId;
        oppObj.SBQQ__PrimaryQuote__c = quoteObj1.Id;
        oppObj.SBQQ__Renewal__c = true;
        update oppObj;

        Product2 prod2Obj = CPQ_TestDataUtility.productTestData(false);
        prod2Obj.Sku_Type__c = CPQ_BillingScheduleCreatorUtility.PRODUCT_SKU_TYPE_LICENSE;
        insert prod2Obj;

        PricebookEntry pbEntryObj = CPQ_TestDataUtility.pbEntryTestData(prod2Obj.Id, true);
        Id pricebookId = Test.getStandardPricebookId();

        SBQQ__Quote__c quoteObj = CPQ_TestDataUtility.quoteTestData(oppObj.Id, false);
        quoteObj.SBQQ__StartDate__c = Date.today() + 1;
        quoteObj.SBQQ__EndDate__c = Date.today().addYears(1);
        quoteObj.SBQQ__PaymentTerms__c = NET15;
        quoteObj.SBQQ__SubscriptionTerm__c = 6;
        quoteObj.SBQQ__BillingFrequency__c  = 'Monthly';
        quoteObj.SBQQ__Opportunity2__c  = oppObj.Id;
        quoteObj.SBQQ__Primary__c = true;
        quoteObj.CPQ_Prorated_Start_Date__c = System.Today();
        insert quoteObj;

        SBQQ__QuoteLine__c  quoteLineItemObj = CPQ_TestDataUtility.quoteLineItemTestData(prod2Obj.Id, quoteObj.Id, false);
        quoteLineItemObj.CPQ_Last_Quote_Invoiced_License__c = 1000000;
        insert quoteLineItemObj;

        System.Test.startTest();

        Order orderObj = CPQ_TestDataUtility.singleOrderUpdate(accObj.Id, oppObj.Id, false);
        orderObj.Is_Primary__c = true;
        orderObj.SBQQ__Quote__c = quoteObj.Id;
        orderObj.SBQQ__BillingFrequency__c  = 'Monthly';
        orderObj.First_Invoice_Date__c = System.Today();
        orderObj.First_Period_Start_Date__c = System.Today();
        orderObj.CPQ_First_Period_Prorated_Amount__c = 5000;
        insert orderObj;


         quoteObj.SBQQ__Type__c = CPQ_BillingScheduleCreatorUtility.SBQQ_TYPE_RENEWAL;
         update quoteObj;

         CPQ_Order_BillingSchedule_Helper.run = true;
         update orderObj;

         System.Test.stopTest();
         List<OrderItem> lstOrderItem = [SELECT Id
                                     , OrderId
                                     , Product2Id
                                 FROM OrderItem
                                WHERE OrderId =: orderObj.Id
                                 ];
        system.debug('...lstOrderItem: '+lstOrderItem);

        List<CPQ_Billing_Schedule__c> lstBillingSchedule = [
        SELECT Id
            , Name
            , Order__c
            , startdate__c
            , Order_Product__c
            FROM CPQ_Billing_Schedule__c
            WHERE Order_Product__c =: lstOrderItem[0].Id
        ];
        System.assertEquals(1, lstOrderItem.size());
        System.assertEquals(13, lstBillingSchedule.size());
    }

    @isTest static void otherCreateOrderItemBillingSchedule() {

        //Account obj = [Select Id,Name From Account Where Name = 'Test Account' Limit 1];
        Account accObj = CPQ_TestDataUtility.accountTestData(true);

        Opportunity oppObj = CPQ_TestDataUtility.opportunityForContTestData(accObj.Id, false);
        oppObj.Original_Opportunity_New__c = opportunityId;
        insert oppObj;

        Contract contractObj = CPQ_TestDataUtility.contractTesData(accObj.Id,oppObj.Id,true);

        oppObj.SBQQ__RenewedContract__c = contractObj.Id;
        update oppObj;
        //Opportunity oppWithContract1 = CPQ_TestDataUtility.opportunityTestData(accObj.Id, contractObj.Id, false);

        SBQQ__Quote__c quoteObj1 = CPQ_TestDataUtility.quoteTestData(oppObj.Id, false);

        // Opportunity oppWithContract = CPQ_TestDataUtility.opportunityTestData(accObj.Id, contractObj.Id, false);
        // oppWithContract.Service_Contract__c = serviceContractId;
        oppObj.SBQQ__PrimaryQuote__c = quoteObj1.Id;
        oppObj.SBQQ__Renewal__c = true;
        update oppObj;

        Product2 prod2Obj = CPQ_TestDataUtility.productTestData(true);

        PricebookEntry pbEntryObj = CPQ_TestDataUtility.pbEntryTestData(prod2Obj.Id, true);
        Id pricebookId = Test.getStandardPricebookId();

        SBQQ__Quote__c quoteObj = CPQ_TestDataUtility.quoteTestData(oppObj.Id, false);
        quoteObj.SBQQ__StartDate__c = Date.today() + 1;
        quoteObj.SBQQ__EndDate__c = Date.today().addYears(1);
        quoteObj.SBQQ__PaymentTerms__c = NET15;
        quoteObj.SBQQ__SubscriptionTerm__c = 6;
        quoteObj.SBQQ__BillingFrequency__c  = 'Monthly';
        quoteObj.SBQQ__Opportunity2__c  = oppObj.Id;
        quoteObj.SBQQ__Primary__c = true;
        quoteObj.CPQ_Prorated_Start_Date__c = System.Today();
        insert quoteObj;

        SBQQ__QuoteLine__c  quoteLineItemObj = CPQ_TestDataUtility.quoteLineItemTestData(prod2Obj.Id, quoteObj.Id, false);
        quoteLineItemObj.CPQ_Last_Quote_Invoiced_License__c = 1000000;
        insert quoteLineItemObj;

        System.Test.startTest();

        Order orderObj = CPQ_TestDataUtility.singleOrderUpdate(accObj.Id, oppObj.Id, false);
        orderObj.Is_Primary__c = true;
        orderObj.SBQQ__Quote__c = quoteObj.Id;
        orderObj.SBQQ__BillingFrequency__c  = 'Monthly';
        orderObj.First_Invoice_Date__c = System.Today();
        orderObj.First_Period_Start_Date__c = System.Today();
        insert orderObj;

         CPQ_Order_BillingSchedule_Helper.run = true;
         update orderObj;

         System.Test.stopTest();
         List<OrderItem> lstOrderItem = [SELECT Id
                                     , OrderId
                                     , Product2Id
                                 FROM OrderItem
                                WHERE OrderId =: orderObj.Id
                                 ];
        system.debug('...lstOrderItem: '+lstOrderItem);

        // List<CPQ_Billing_Schedule__c> lstBillingSchedule = [
        // SELECT Id
        //     , Name
        //     , Order__c
        //     , startdate__c
        //     , Order_Product__c
        //     FROM CPQ_Billing_Schedule__c
        //     WHERE Order_Product__c =: lstOrderItem[0].Id
        // ];
        System.assertEquals(1, lstOrderItem.size());
        //System.assertEquals(13, lstBillingSchedule.size());
    }


}