src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Data_Classification__c</fullName>
        <label>Data Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Restricted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guidewire Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Date_Published__c</fullName>
        <label>Date Published</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Usage_Terms__c</fullName>
        <label>Usage Terms</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/objects/GW_Common_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Boolean_Value__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Boolean Value</label>
        <type>Checkbox</type>
    </fields>
    <label>GW Common Settings</label>
</CustomObject>

src/classes/UpdateDatePublishedHandler.cls
public class UpdateDatePublishedHandler 
{
    public void documentHandler(list<ContentVersion> doculst)
    {
    	if(GW_Common_Settings__c.getInstance('EnableContentVersionTrigger').Boolean_Value__c){
	        for(ContentVersion cv : doculst)
	        {
	           cv.Date_Published__c = date.today();
	            
	           if(cv.Data_Classification__c != null && cv.Data_Classification__c =='Customer Restricted' )
	               cv.usage_terms__c = 'This asset contains Guidewire Customer proprietary and confidential information. It is intended for Guidewire Internal use on a need-to-know basis only.'; 
	            
	           if(cv.Data_Classification__c != null && cv.Data_Classification__c =='Guidewire Internal' )
	               cv.usage_terms__c = 'This asset contains Guidewire proprietary and confidential information. It is intended for Guidewire Internal use on a need-to-know basis only.';
	       
	           if(cv.Data_Classification__c != null && cv.Data_Classification__c =='Public' )
	               cv.usage_terms__c = 'This asset contains information that can be publicly distributed through authorized company channels.';
	        }
       }
    }
    
    public void versionHandler(list<ContentVersion> verlst, map<id,ContentVersion> oldMap)
    {
    	if(GW_Common_Settings__c.getInstance('EnableContentVersionTrigger').Boolean_Value__c){
	        for(ContentVersion cv: verlst)
	        {         
	            ContentVersion cvOld = oldmap.get(cv.id);
	            
	            if(cvOld .VersionNumber != cv.VersionNumber)
	                cv.Date_Published__c = cv.LastModifiedDate.date(); 
	        
	            if(cv.Data_Classification__c != null && cv.Data_Classification__c =='Customer Restricted' )
	               cv.usage_terms__c = 'This asset contains Guidewire Customer proprietary and confidential information. It is intended for Guidewire Internal use on a need-to-know basis only.'; 
	            
	           if(cv.Data_Classification__c != null && cv.Data_Classification__c =='Guidewire Internal' )
	               cv.usage_terms__c = 'This asset contains Guidewire proprietary and confidential information. It is intended for Guidewire Internal use on a need-to-know basis only.';
	       
	           if(cv.Data_Classification__c != null && cv.Data_Classification__c =='Public' )
	               cv.usage_terms__c = 'This asset contains information that can be publicly distributed through authorized company channels.';                
	        }
    	}
    }
}