src/objects/CPQ_Billing_Schedule__c.object
<CustomObject>
    <description>Billing Schedules will be created when orders are created and will contain all the broken out line items from the order based on the billing frequency</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Billing Schedules</relationshipLabel>
        <relationshipName>Billing_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Billing Schedule</label>
    <nameField>
        <displayFormat>BS-{000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CPQ_Wire_Message__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Wire Message</label>
    <nameField>
        <displayFormat>M-{00}</displayFormat>
        <label>Wire Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wire Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Wire_Message__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wire Message</label>
        <referenceTo>CPQ_Wire_Message__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CPQ_GenerateOrderFile.cls
global with sharing class CPQ_GenerateOrderFile {

    public static final String STR_ORDER_COLUMNS = Label.CPQ_GenerateOrder;//list of column names for csv
    public static final String STR_MESSAGE = 'message';//message
    public static final String STR_FILENAME = 'Sales Order Document.csv';//message

    public static final Map<String, Schema.SObjectField> MAPFIELD_META =
        Schema.SObjectType.CPQ_Billing_Schedule__c.fields.getMap();

    /**
     * Method to Create Sales Order from Button on opportunity
     */
    Webservice static String createOrderAttachment(Id pOrderId) {

        Set<String> setBillingScheduleFields = MAPFIELD_META.keySet();
        Set<String> setBillingSch = new Set<String>();
        String newBillingSceduleField ;
        String bsQuery = 'SELECT ';

        bsQuery += String.join(new List<String>(setBillingScheduleFields), ', ');

        bsQuery += ' , Order__r.Wire_Message__r.Message__c FROM CPQ_Billing_Schedule__c WHERE Order__c = : pOrderId ';

        List<CPQ_Billing_Schedule__c> lstBillingSchedules = (List<CPQ_Billing_Schedule__c>) Database.query(bsQuery);

        if(lstBillingSchedules != null && !lstBillingSchedules.IsEmpty() && lstBillingSchedules[0].Order__c !=null) {
            String strHeader = STR_ORDER_COLUMNS.remove('__c') + '\n';
            String finalstr = strHeader ;
            List<String> strFieldNamelist = STR_ORDER_COLUMNS.deleteWhitespace().split(',');
            String recordString ='';
            String strWireMsg = '';
            if(lstBillingSchedules[0].Order__r.Wire_Message__c != null && lstBillingSchedules[0].Order__r.Wire_Message__r.Message__c != null) {
                strWireMsg = lstBillingSchedules[0].Order__r.Wire_Message__r.Message__c;
            }
            for(CPQ_Billing_Schedule__c objBillingSched:lstBillingSchedules) {
                for(String strFieldAPIName: strFieldNamelist) {
                    if(!strFieldAPIName.equalsIgnoreCase(STR_MESSAGE)) {
                        if(objBillingSched.get(strFieldAPIName) != null) {
                            recordString += String.valueOf(objBillingSched.get(strFieldAPIName)).escapeCsv() + ',';
                        } else {
                            setBillingSch.add(MAPFIELD_META.get(strFieldAPIName).getDescribe().getLabel());
                        }
                    } else if(STR_MESSAGE.equalsIgnoreCase(strFieldAPIName) && String.isNotBlank(strWireMsg)) {
                        recordString += strWireMsg.escapeCsv() + ',';
                    } else if(STR_MESSAGE.equalsIgnoreCase(strFieldAPIName) && String.isBlank(strWireMsg)) {
                        setBillingSch.add('Order > Wire Message');
                    } else {
                        recordString += ''+ ',';
                    }
                    recordString += '\n';
                }
                finalstr = finalstr + recordString;
            }
            if(!setBillingSch.isEmpty()) {
                newBillingSceduleField = String.join(new List<String>(setBillingSch), ', ');
            }
            if(String.isBlank(newBillingSceduleField)) {
                Attachment attachment = new Attachment();
                attachment.Body = Blob.valueOf(finalstr);
                attachment.Name = STR_FILENAME;
                attachment.ParentId = lstBillingSchedules[0].Order__c;
                try {
                    insert attachment;
                } catch(DmlException exceptionInstance) {
                    System.debug('Exception occurred : ' + exceptionInstance.getMessage());
                }
            }
        }
        return newBillingSceduleField;
    }
}