src/objects/CS_Asset_Contact_Permissions__c.object
<CustomObject>
    <fields>
        <fullName>CS_Access_Type__c</fullName>
        <label>Access Type</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support (View Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipName>Asset_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CS_Evaluation_End_Date__c</fullName>
        <description>Prospect Evaluation End Date</description>
        <label>Evaluation End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CS_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Asset Contact Permission</label>
    <nameField>
        <label>Product Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Contact Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CS_ACP_Deactivate_Prospect.cls
/*
******************************************************************************************************************************
Controller Class Name- CS_ACP_Deactivate_Prospect
Object - CS_Asset_Contact_Permissions__c
Purpose- Trigger Handler 
*****************************************************************************************************************************

Name     Email              Date         Notes 
Shan Xu  shanx@slalom.com      			 Initial Creation

*****************************************************************************************************************************
*/
global class CS_ACP_Deactivate_Prospect implements Schedulable {
	global void execute(SchedulableContext sc) {
		//MyBatchClass b = new MyBatchClass();
		//database.executebatch(b);(
				deactivateProspect();
				deactivate_ACP();

	}
	List<CS_Asset_Contact_Permissions__c> newACP=New List<CS_Asset_Contact_Permissions__c>();

	 public void deactivateProspect()
	 {

	 		List<CS_Asset_Contact_Permissions__c> AcpUpdate= New List<CS_Asset_Contact_Permissions__c>(
	 		[Select id,CS_IsActive__c,CS_Access_Type__c,CS_Evaluation_End_Date__c from CS_Asset_Contact_Permissions__c 
	 		 where CS_Access_Type__c='Prospect' and  CS_Evaluation_End_Date__c=Today]);


	 		for(CS_Asset_Contact_Permissions__c acp: AcpUpdate){
				CS_Asset_Contact_Permissions__c  updACP= new CS_Asset_Contact_Permissions__c(Id=acp.id,CS_IsActive__c=False);
				newACP.add(updACP);

		}

		Update newACP;

	 }

// Deactivate ACPS on Asset  based on Asset out of service date 
	 public void deactivate_ACP()
	 {

	 		List<CS_Asset_Contact_Permissions__c> AcpUpdate= New List<CS_Asset_Contact_Permissions__c>(
	 		[Select id,CS_IsActive__c,CS_Access_Type__c,CS_Evaluation_End_Date__c from CS_Asset_Contact_Permissions__c 
	 		 where   CS_Asset__r.UsageEndDate=Today]);


	 		for(CS_Asset_Contact_Permissions__c acp: AcpUpdate){
				CS_Asset_Contact_Permissions__c  updACP= new CS_Asset_Contact_Permissions__c(Id=acp.id,CS_IsActive__c=False);
				newACP.add(updACP);

		}

		Update newACP;

	 }
}