src/objects/CS_BoxTokens__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>stores tokens for box</description>
    <fields>
        <fullName>Access_Token__c</fullName>
        <label>Email_Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientId__c</fullName>
        <label>ClientId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientSecret__c</fullName>
        <label>ClientSecret</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refresh_Token__c</fullName>
        <label>Refresh Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Box Tokens</label>
</CustomObject>

src/classes/CS_DownloadFileFromBoxTest.cls
@isTest
private class CS_DownloadFileFromBoxTest {
	
	static testMethod void testRedirectToBox() {

        
        CS_BoxTokens__c cBox = new CS_BoxTokens__c();
        cBox.Name = 'BoxDev';
        cBox.Refresh_Token__c = 'fahgafhgs';
        cBox.ClientId__c = 'fahgafhgs';
        cBox.ClientSecret__c = 'fahgafhgs';
        cBox.Access_Token__c = 'abc@xyz.com';

        insert cBox;
        // Set mock callout class 
        test.starttest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(true));

        String res = CS_DownloadFileFromBox.downloadBoxFile('abc123');

        CS_DownloadFileFromBox.sendEmailMssg('abc@xyz.com','12345');

        test.stoptest();
    }

    static testMethod void testRedirectToBoxBadRequest() {

        
        CS_BoxTokens__c cBox = new CS_BoxTokens__c();
        cBox.Name = 'BoxDev';
        cBox.Refresh_Token__c = 'fahgafhgs';
        cBox.ClientId__c = 'fahgafhgs';
        cBox.ClientSecret__c = 'fahgafhgs';
        cBox.Access_Token__c = 'abc@xyz.com';

        insert cBox;
        // Set mock callout class 
        test.starttest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(false));

        String res = CS_DownloadFileFromBox.downloadBoxFile('abc123');        

        test.stoptest();
    }
	
}