src/objects/CS_BoxTokens__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>stores tokens for box</description>
    <fields>
        <fullName>ClientId__c</fullName>
        <label>ClientId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientSecret__c</fullName>
        <label>ClientSecret</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refresh_Token__c</fullName>
        <label>Refresh Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Box Tokens</label>
</CustomObject>

src/classes/CS_BoxTokenGeneratorTest.cls
@isTest
private class CS_BoxTokenGeneratorTest {
    
    @isTest static void testConstructor() {
        // Implement test code

        CS_BoxTokens__c cBox = new CS_BoxTokens__c();
        cBox.Name = 'BoxDev';
        cBox.Refresh_Token__c = 'fahgafhgs';
        cBox.ClientId__c = 'fahgafhgs';
        cBox.ClientSecret__c = 'fahgafhgs';

        insert cBox;
        // Set mock callout class 
        test.starttest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(true));

        CS_BoxTokenGenerator rbox = new CS_BoxTokenGenerator();

        test.stoptest();
    }
    
    @isTest static void testConnectBox() {
        // Implement test code

        CS_BoxTokens__c cBox = new CS_BoxTokens__c();
        cBox.Name = 'BoxDev';
        cBox.Refresh_Token__c = 'fahgafhgs';
        cBox.ClientId__c = 'fahgafhgs';
        cBox.ClientSecret__c = 'fahgafhgs';

        insert cBox;
        // Set mock callout class 
        test.starttest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(true));

        CS_BoxTokenGenerator rBox = new CS_BoxTokenGenerator();

        rBox.connectBox();

        test.stoptest();
    }
    
    @isTest static void testRedirectBox() {
        // Implement test code

        CS_BoxTokens__c cBox = new CS_BoxTokens__c();
        cBox.Name = 'BoxDev';
        cBox.Refresh_Token__c = 'fahgafhgs';
        cBox.ClientId__c = 'fahgafhgs';
        cBox.ClientSecret__c = 'fahgafhgs';

        insert cBox;
        // Set mock callout class 
        test.starttest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(true));

        CS_BoxTokenGenerator rBox = new CS_BoxTokenGenerator();

        rBox.redirectbox();

        test.stoptest();
    }
}