src/objects/CS_ByPass__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>ByPass from Triggers,WF Rules and Validation Rules</description>
    <fields>
        <fullName>CS_Batch_Context__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Batch Context</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Disable_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>ByPass from Trigger</inlineHelpText>
        <label>Disable Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Disable_ValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ByPass from Validation Rules</description>
        <label>Disable ValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Disable_WF_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Bypass from WF Rules</description>
        <label>Disable WF Rules</label>
        <type>Checkbox</type>
    </fields>
    <label>GW ByPass</label>
</CustomObject>

src/classes/CPQ_PB_UpdateQuoteLineProrated_Test.cls
@isTest
private class CPQ_PB_UpdateQuoteLineProrated_Test {

  @isTest static void testUpdateProratedLicense() {

    CS_ByPass__c byPassValidationAndTrigger = new CS_ByPass__c();
    byPassValidationAndTrigger.CS_Disable_Trigger__c = true;
    byPassValidationAndTrigger.CS_Disable_ValidationRule__c = true;
    byPassValidationAndTrigger.CS_Batch_Context__c = true;
    byPassValidationAndTrigger.CS_Disable_WF_Rules__c = true;
    byPassValidationAndTrigger.SetupOwnerId = UserInfo.getUserId();
    insert byPassValidationAndTrigger;

    Account account = CS_TestDataUtility.createProspectAccount();

    Opportunity originalOppty = CPQ_Quote_Utilities_Test.createOpportunity(account.Id, null, null, 1, false);
    SBQQ__Quote__c originalQuote = CPQ_Quote_Utilities_Test.createQuote(originalOppty.Id, false);

    Id pricebookId = Test.getStandardPricebookId();
    Product2 product1 = CPQ_QuoteLine_Utilities_Test.createProduct('Billing Center License', 'License');
    PricebookEntry pbEntry1 = CPQ_QuoteLine_Utilities_Test.createPbEntry(product1.Id, pricebookId);
    Product2 product2 = CPQ_QuoteLine_Utilities_Test.createProduct('Maintenance - Standard', 'Maintenance');
    PricebookEntry pbEntry2 = CPQ_QuoteLine_Utilities_Test.createPbEntry(product2.Id, pricebookId);

    List<SBQQ__QuoteLine__c> quoteLineList = new List<SBQQ__QuoteLine__c>();
    quoteLineList.add(CPQ_QuoteLine_Utilities_Test.createQuoteLineItem(product1.Id, originalQuote.Id));
    quoteLineList.add(CPQ_QuoteLine_Utilities_Test.createQuoteLineItem(product2.Id, originalQuote.Id));
    quoteLineList.add(CPQ_QuoteLine_Utilities_Test.createQuoteLineItem(product1.Id, originalQuote.Id));
    quoteLineList.add(CPQ_QuoteLine_Utilities_Test.createQuoteLineItem(product2.Id, originalQuote.Id));
    insert quoteLineList;

    Test.startTest();
    List<Id> quoteIds = new List<Id>();
    quoteIds.add(originalQuote.Id);
    CPQ_PB_UpdateQuoteLineProratedLicense.updateProratedLicense(quoteIds);
    Test.stopTest();
  }

}