src/objects/CS_Error_Logs__c.object
<CustomObject>
    <description>Error Object to  log the exceptions</description>
    <fields>
        <fullName>CS_Called_Method__c</fullName>
        <label>Called Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Error_Message__c</fullName>
        <description>** Error Message ****</description>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CS_Object_Name__c</fullName>
        <description>**** Object Name *****</description>
        <label>Object Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Record_Id__c</fullName>
        <description>*** Error  Record ID *******</description>
        <label>Record Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>user for error occurred</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Err-{000000}</displayFormat>
        <label>Error Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CS_ExceptionHandler.cls
/*
*****************************************************************************************************************************
Class Name - CS_ExceptionHandler
Class Type -  Handler
Test Class-
Purpose- Error Log Handler

*****************************************************************************************************************************

Name        Email              Date             Notes 
Mani                                           Initial Creation


*****************************************************************************************************************************
*/
global without sharing class CS_ExceptionHandler {
    public CS_ExceptionHandler() {
        
    }

// Method used to catch exception on Customer Onboarding Setup via Service Contract
  @future
     public static void createErrorRecord(string exceptionMessage,Id ObjectId){
         CS_Error_Logs__c newErrorRecord = new CS_Error_Logs__c();
         newErrorRecord.CS_Error_Message__c = exceptionMessage;
         newErrorRecord.CS_Record_Id__c=ObjectId;
         newErrorRecord.CS_User__c=UserInfo.getUserId();
         newErrorRecord.CS_Object_Name__c=String.valueOf(ObjectId.getSObjectType());
         Database.insert(newErrorRecord,false);
     }

     @future
     public static void createErrorRecordMessage(string exceptionMessage,String Calledmethod){
         CS_Error_Logs__c newErrorRecord = new CS_Error_Logs__c();
         newErrorRecord.CS_Error_Message__c = exceptionMessage;
         newErrorRecord.CS_User__c=UserInfo.getUserId();
         newErrorRecord.CS_Called_Method__c=Calledmethod;
         Database.insert(newErrorRecord,false);
     }

}