src/objects/CS_Milestone_Business_Hours__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>**** Service Cloud  Milestone Business Hours ******</description>
    <fields>
        <fullName>CS_Business_Days__c</fullName>
        <label>Business Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CS_Entitlement_Process_Name__c</fullName>
        <description>Entitlement Process Name</description>
        <label>Entitlement Process Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Exception_Email__c</fullName>
        <defaultValue>&apos;mgunasekaran@guidewire.com&apos;</defaultValue>
        <description>***** Email Id to Send Exception *****</description>
        <label>Exception Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CS_Milestone_Name__c</fullName>
        <description>Milestone Name</description>
        <label>Milestone Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Severity__c</fullName>
        <label>Severity</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>GW Milestone Business Hours</label>
</CustomObject>

src/classes/CS_DisplayMilestoneCtrl.cls
/*
******************************************************************************************************************************
Controller Class Name- CS_DisplayMilestoneCtrl
Object - Case
Purpose- 
*****************************************************************************************************************************

Name            Email              Date         Notes 
Mani G                              09/03/2016       Initial Creation

*****************************************************************************************************************************
*/
public with sharing class CS_DisplayMilestoneCtrl {

	private final Entitlement mysObject;
    private list<CS_Milestone_Business_Hours__c> displayMilestone;

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public CS_DisplayMilestoneCtrl(ApexPages.StandardController stdController) {
        this.mysObject = (Entitlement)stdController.getRecord();

    }
     public List<CS_Milestone_Business_Hours__c> getdisplayMilestone() {
        Entitlement SlaProcessname=[Select SlaProcess.name from entitlement where id =:mysObject.id];
        displayMilestone= New List<CS_Milestone_Business_Hours__c>([select CS_Business_Days__c, CS_Entitlement_Process_Name__c,
                                                                     CS_Exception_Email__c, CS_Milestone_Name__c, CS_Severity__c
                                                                     from CS_Milestone_Business_Hours__c  
                                                                     where CS_Entitlement_Process_Name__c =:SlaProcessname.SlaProcess.name
                                                                     order by CS_Severity__c asc ]);
        return displayMilestone;
     }
}