src/objects/CS_Request__c.object
<CustomObject>
    <fields>
        <fullName>CS_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CS_Request_Status__c</fullName>
        <inlineHelpText>Request Status</inlineHelpText>
        <label>Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Answered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Updated by Requestor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on Requestor</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_Request_Type__c</fullName>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>Long Term Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Term Request</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CS_is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>Req-{00000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CS_Caseclose_Util.cls
/*
******************************************************************************************************************************
Controller Class Name- CS_Caseclose_Util
Object - Case
Purpose- Util  Class   for Case Close  Component
*****************************************************************************************************************************

Name     Email              Date         Notes 
ManiG  manig@slalom.com                	Initial Creation
ManiG manig@slalom.com 		09/14/2016	Try Catch Block
*****************************************************************************************************************************
*/
public with sharing class CS_Caseclose_Util {


	Public Static void CloseSTR(Set<Id> CaseIds){
	System.debug('Cases Sent to Close===' + CaseIds);
	 List <CS_Request__c> LstUpdateCSR = New  List<CS_Request__c>();
	 List<CS_Request__c>  CSR= New  List<CS_Request__c> ([Select id,CS_is_Active__c,CS_Request_Type__c,
	 								                      CS_Case__c from  CS_Request__c where 
	 								                      CS_Case__c in:CaseIds and CS_Request_Status__c !='Answered'
	 								                      and  CS_Request_Type__c !='Long Term Request']);
	 //System.debug('Request to Update'+CSR);
	 If (CSR.size() >0 ){
	 	For(CS_Request__c nCsr :CSR ){
	 		 CS_Request__c newCSR= New CS_Request__c (id=nCsr.id,CS_Request_Status__c='Answered');
	 		 LstUpdateCSR.add(newCSR);
	 	}
	 	//System.debug('Request to Update=='+LstUpdateCSR);
	 	
	 	try {
            Update LstUpdateCSR;
        } catch (DmlException ex) {
            CS_ExceptionHandler.createErrorRecordMessage(ex.getMessage(), 'CloseSTR'); 
        }
	 	
	 }
	}

	Public Static void CloseCMS (Set<Id> CaseIds){

	List<CaseMilestone> lstUpdateCMS = New  List<CaseMilestone>();
	List<CaseMilestone>  CMS =New  List<CaseMilestone> ([Select id,iscompleted,caseid from CaseMilestone where caseid in:CaseIds and iscompleted =false]);


	If (CMS.size() >0 ){
	 	For(CaseMilestone nCms :CMS ){
	 		 CaseMilestone newCMS= New CaseMilestone (id=nCms.id,Completiondate=system.today());
	 		 lstUpdateCMS.add(newCMS);
	 	}
	 	//System.debug('Request to Update=='+LstUpdateCSR);
	 	try {
            Update lstUpdateCMS;
        } catch (DmlException ex) {
            CS_ExceptionHandler.createErrorRecordMessage(ex.getMessage(), 'CloseCMS'); 
        }
	 	
	 }


	}

	Public Static void CloseRestorationMS (Set<Id> CaseIds){
	
	List<CaseMilestone> lstUpdateCMS = New  List<CaseMilestone>();
	List<CaseMilestone>  CMS =New  List<CaseMilestone> ([Select id,MilestoneType.name ,iscompleted,caseid from CaseMilestone 
									where caseid in:CaseIds and iscompleted =false and MilestoneType.name like  '%Restoration%' ]);

	System.debug('CMS Value==' + CMS);
	If (CMS.size() >0 ){
	 	For(CaseMilestone nCms :CMS ){
	 		 CaseMilestone newCMS= New CaseMilestone (id=nCms.id,Completiondate=system.now());
	 		 lstUpdateCMS.add(newCMS);
            System.debug('=====lstUpdateCMS ==== ' + lstUpdateCMS);
	 	}
	 	System.debug('Request to Update=='+lstUpdateCMS);
        try {
            Update lstUpdateCMS;
        } catch (DmlException ex) {
            CS_ExceptionHandler.createErrorRecordMessage(ex.getMessage(), 'CloseRestorationMS'); 
        }
	 	
	}
}

}