src/objects/Customer_Commitment__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Event__c</fullName>
        <label>Sales Event</label>
        <referenceTo>Sales_Event__c</referenceTo>
        <relationshipLabel>Customer Commitments</relationshipLabel>
        <relationshipName>Customer_Commitments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Who__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Commitments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Commitment</label>
    <nameField>
        <label>Customer Commitment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Commitments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer_Commitment_Date_Range__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Commitment__c</fullName>
        <label>Customer Commitment</label>
        <referenceTo>Customer_Commitment__c</referenceTo>
        <relationshipLabel>Date Ranges</relationshipLabel>
        <relationshipName>Date_Ranges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <label>End</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Date Range</label>
    <nameField>
        <displayFormat>CCDR-{00000000}</displayFormat>
        <label>Range ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Date Ranges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Premium_In_Scope__c</fullName>
        <inlineHelpText>This should be the deal premium in scope or the incremental DWP Adjustment. Used in conjunction with Price Rules to calculate the price for certain Products.</inlineHelpText>
        <label>Premium In Scope</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SWOT_Opportunities__c</fullName>
        <description>The Opportunities aspect of the SWOT</description>
        <inlineHelpText>Opportunities EXTERNAL to Guidewire</inlineHelpText>
        <label>Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_SO__c</fullName>
        <inlineHelpText>Strategy for addressing the Opportunities in the context of our Strengths</inlineHelpText>
        <label>Strengths/Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_ST__c</fullName>
        <inlineHelpText>Strategy for addressing the Threats in the context of our Strengths</inlineHelpText>
        <label>Strengths/Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_WO__c</fullName>
        <inlineHelpText>Strategy for addressing Opportunities in the context of our Weaknesses</inlineHelpText>
        <label>Weaknesses/Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_WT__c</fullName>
        <inlineHelpText>Strategy for addressing the Threats in the context of our Weaknesses</inlineHelpText>
        <label>Weaknesses/Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strengths__c</fullName>
        <inlineHelpText>Guidewire Strengths</inlineHelpText>
        <label>Strengths</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Threats__c</fullName>
        <inlineHelpText>Threats external to Guidewire</inlineHelpText>
        <label>Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Weaknesses__c</fullName>
        <inlineHelpText>Guidewire Weaknesses</inlineHelpText>
        <label>Weaknesses</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Event__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Events</relationshipLabel>
        <relationshipName>Sales_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Sales Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestCustomerCommitmentController.cls
@isTest(seeAllData=true)
private class TestCustomerCommitmentController {

    static testMethod void validateController() {

        Opportunity o = new Opportunity(SWOT_Strengths__c='S Value',
                                        SWOT_Weaknesses__c='W Value',
                                        SWOT_Opportunities__c = 'O Value',
                                        SWOT_Threats__c = 'T Value',
                                        SWOT_Strategy_SO__c = 'SO Value',
                                        SWOT_Strategy_ST__c = 'ST Value',
                                        SWOT_Strategy_WO__c = 'WO Value',
                                        SWOT_Strategy_WT__c = 'WT Value',
                                        Name = 'Test SWOT Opportunity',
                                        StageName = 'Qualified',
                                        CloseDate = Date.today(),
                                        Premium_In_Scope__c = 1000,
                                        Amount=100   );
    
        insert o;
        Sales_Event__c event = new Sales_Event__c(Opportunity__c = o.Id);
        insert event;
        
        Customer_Commitment__c commitment = new Customer_Commitment__c(Name = 'Customer Commitment Test 1',
                                                                       Sales_Event__c = event.Id,
                                                                       Who__c = UserInfo.getUserId()
                                                                      );
                                                                      
        insert commitment;
        
        Customer_Commitment_Date_Range__c dateRange = new Customer_Commitment_Date_Range__c(Start__c = Date.today().addDays(3), 
                                                                         End__c = Date.today().addDays(4),
                                                                         Note__c = 'note',                                                                         
                                                                         customer_commitment__c = commitment.Id);
        insert dateRange;
                
        
        ApexPages.StandardController controller = new ApexPages.StandardController(commitment);
        ApexPages.currentPage().getParameters().put('SalesEventID', event.Id);        
        CustomerCommitmentController theNewController = new CustomerCommitmentController (controller);
        //put in ID so the second controller has data
        ApexPages.currentPage().getParameters().remove('SalesEventID');
        ApexPages.currentPage().getParameters().put('id', commitment.Id);
        CustomerCommitmentController theExistingController = new CustomerCommitmentController (controller);


//        theNewController.possibleDate.Start__c = DateTime.now().addDays(-3);
//        theNewController.possibleDate.End__c = DateTime.now().addDays(-2);
        theNewController.save();
        theExistingController.save();
        theNewController.getAllDateRanges();
        theExistingController.getAllDateRanges();
        
        CustomerCommitmentController.deleteDateRange(dateRange.id,commitment.id);

        //test for new comment
        
        
//        post = [SELECT Id, CommentCount from FeedItem where Id = :post.Id LIMIT 1];
//        System.assertEquals(post.CommentCount, 2);
    
//        sc.save();
//        String nextPage = sc.save().getUrl();
//        System.assertEquals('/apex/SWOT', nextPage);
        
    
    }
}