src/objects/Customer_Information__c.object
<CustomObject>
    <description>Owner - Roopal Shah</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>contains</operation>
                <value>Customer-Direct, Customer-Indirect</value>
            </filterItems>
            <infoMessage>Account type must be Customer-Direct or Customer-Indirect</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Information</relationshipLabel>
        <relationshipName>Customer_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Information</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Cust Info ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer_Story__c.object
<CustomObject>
    <description>Owner - Roopal Shah</description>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Customer_Info_ID__r.Account_Name__c</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Information - Do not use</label>
        <referenceTo>Customer_Information__c</referenceTo>
        <relationshipLabel>Customer Stories</relationshipLabel>
        <relationshipName>Customer_Stories1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Story_Title__c</fullName>
        <label>Story Title</label>
        <type>TextArea</type>
    </fields>
    <label>Customer Story</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Story Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StorySearchController_TEST.cls
@isTest
private class StorySearchController_TEST {
    
    @isTest static void testSearch() {
    
    //  Insert some accounts
        Integer iSize = 20;
        List<Account>accts = new List<Account>{};
        for(Integer i = 0; i<iSize; i++){
            Accts.add(new Account(Name = 'test', BillingStreet='test', BillingCountry='United States',BillingCity='test',BillingState='California'));
        }
        insert accts;   
    
    //  Insert some cust info & stories 
        List<Customer_Information__c> infos = new List<Customer_Information__c>{};
        List<Customer_Story__c> stories = new List<Customer_Story__c>{};
        for(Account a : accts){         
            infos.add( new Customer_Information__c(Account__c = a.id));
            stories.add( new Customer_Story__c(story_title__c='test'));         
        }
        insert infos;
        insert stories;             
        
    //  Set search results          
        List<Id> fixedSearchResults = new List<Id>{};
        for(Customer_Story__c s : stories)fixedSearchResults.add(s.id);         
        Test.setFixedSearchResults(fixedSearchResults);         
            
    //  Controller
        SearchStoryController d = new SearchStoryController();              
        
    //  Set the default search type & scope     
        d.SelectSearchType();
        d.setDefaultFilters();
        
    //  get filters
        d.getFilters();

    //  Search Stories    
        d.keyword = 'test';
        d.searchType = 'story';
        d.FindResults();

    //  Query Stories    
        d.keyword = null;
        d.searchType = 'story';
        d.doSearch();
                
    //  Query Infos
        d.searchType = 'info';
        d.doSearch();

    //  add a filter
        d.AddFilter();
        
    //  remove a filter
        d.currentFilterID = 0;
        d.removeFilter();

    //  Select a filter
        d.currentFilter = d.idTOfilter.get(0);
        d.currentFilter.selectedField = d.currentFilter.filterFields[0].getValue();
        d.SelectFilterType();
    
    //  Clear filters so search will work
        d.ClearFilters();
        d.getFilters();
        
    //  search stories      
        d.searchType = 'story';     
        d.doSearch();
    
    //  search infos
        d.searchType = 'info';      
        d.doSearch();
        
    //  get ids for sub searches            
        d.ProductCustomerInfoIDs();
        d.StoryCustomerInfoIDs();
        
    
   }


}