src/objects/Customer_Commitment__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Event__c</fullName>
        <label>Sales Event</label>
        <referenceTo>Sales_Event__c</referenceTo>
        <relationshipLabel>Customer Commitments</relationshipLabel>
        <relationshipName>Customer_Commitments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Who__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Commitments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Commitment</label>
    <nameField>
        <label>Customer Commitment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Commitments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>AMER</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Personal_Event__c.object
<CustomObject>
    <description>Used to store things like vacation, no travel, OOO, etc.</description>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>No Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out Of Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Tentative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Personal Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Preparation__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Event__c</fullName>
        <label>Sales Event</label>
        <referenceTo>Sales_Event__c</referenceTo>
        <relationshipLabel>Preparations</relationshipLabel>
        <relationshipName>Preparations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Who__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Preparations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Preparation</label>
    <nameField>
        <label>Preparation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preparations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Event__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_End_Date__c</fullName>
        <label>Confirmed End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Confirmed_Start_Date__c</fullName>
        <label>Confirmed Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Tentative</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Participant__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Who__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Participant</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Preparation__c.object
<CustomObject>
    <fields>
        <fullName>Who__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Preparations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Preparation</label>
    <nameField>
        <label>Preparation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preparations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Event__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_End_Date__c</fullName>
        <label>Confirmed End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Confirmed_Start_Date__c</fullName>
        <label>Confirmed Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Demonstration</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Sale Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proof of Concept</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI / RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Consulting Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Workshop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Workshop Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Alignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Tracking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Consultation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HQ Visit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Events</relationshipLabel>
        <relationshipName>Sales_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Presentation_Type__c</fullName>
        <label>Presentation Type</label>
        <picklist>
            <controllingField>Event_Type__c</controllingField>
            <picklistValues>
                <fullName>On-site</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Remote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HQ Visit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Tentative</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScheduledSalesEventStatusUpdater.cls
global class ScheduledSalesEventStatusUpdater
 {  
    global static void execute() {
  
      
       Date todayDate = Date.today();
      
       Sales_Event__c[] eventsToUpdate =  [SELECT Id, Name, Confirmed_End_Date__c, Confirmed_Start_Date__c, Description__c, 
                                                  Event_Type__c, Presentation_Type__c, Location__c, Status__c, 
                                                  Opportunity__c,  Opportunity__r.Name,  Opportunity__r.region__c, Opportunity__r.ownerid,
                                    (SELECT Id , Who__c, Who__r.Name, Coverage_Area__c, Sales_Event__c FROM Customer_Commitments__r ),
                                    (SELECT Id, Start__c, End__c, Who__c, Who__r.Name, Note__c, Hours__c FROM Preparations__r  )

                                           FROM Sales_Event__c
                                           WHERE 
                                             Status__c = 'Confirmed' AND
                                              ((Event_Type__c <> 'RFI / RFP' AND
                                              Confirmed_End_Date__c < :todayDate)
                                               OR
                                               (Event_Type__c = 'RFI / RFP' AND
                                                RFx_External_Due__c < :todayDate)
                                              )
                                              //name = 'Test Chatter Post'
                                          ];
       
       for(Sales_Event__c thisEvent : eventsToUpdate )
       {
           thisEvent.Status__c  = 'Completed';
           
           //also need to post accordingly for updates
           
            System.Debug(' &&&&&&&&&&&&&  Requesting Review of recent sales event ' + thisEvent.ID);
                    
            String communityId = null;
            ConnectApi.FeedType feedType = ConnectApi.FeedType.Record;
            String userToMention = UserInfo.getUserId(); 
            String subjectId = thisEvent.Id;
            String completedText = null;
            String ApacCompletedText = null;
            
            ConnectApi.MessageBodyInput messageInput = new ConnectApi.MessageBodyInput();
            messageInput.messageSegments = new List<ConnectApi.MessageSegmentInput>();
            
            ConnectApi.TextSegmentInput textSegment = new ConnectApi.TextSegmentInput();
            completedText = 'This event has been completed.  Please review to make sure your preparation time is still accurate\n';
            ApacCompletedText = 'This event has been completed.  Please review to make sure your preparation time is still accurate and provide your feedback here\n';
           
           
           if(thisEvent.opportunity__r.region__c != null) 
           {
           textSegment.text = !thisEvent.opportunity__r.region__c.equals('AMER')?
                     ApacCompletedText + (URL.getSalesforceBaseUrl().toExternalForm() + '/apex/SalesEventFeedback?SalesEventId='+ thisEvent.id + '\n'):completedText ;
           }
           else
              textSegment.text = completedText;
           
           messageInput.messageSegments.add(textSegment);
           
           
            //need to loop over the customer commitments and preprataions to get the unique set of people
            Set<Id> usersToMention = new Set<Id>();
            for(Preparation__c thePrepItem : thisEvent.Preparations__r)
            {
                if(thePrepItem.Who__c != null)
                {
                    usersToMention.add(thePrepItem.Who__c);            
                }
            }
            
            for(Customer_Commitment__c theCommitmentItem : thisEvent.Customer_Commitments__r )
            {
                if(theCommitmentItem.Who__c != null)
                {
                    usersToMention.add(theCommitmentItem.Who__c);            
                }
            }
            
            //APAC Region only - Add Oppty Owner
            if(thisEvent.opportunity__r.region__c != null && !thisEvent.opportunity__r.region__c.equals('AMER'))
            {    
    //        if(!thisEvent.opportunity__r.region__c.equals('AMER'))
            
                usersToMention.add(thisEvent.opportunity__r.ownerid);
            }
       
            for(Id theUserToMention : usersToMention)
            {
            
                ConnectApi.MentionSegmentInput mentionSegment = new ConnectApi.MentionSegmentInput();
                mentionSegment.id = theUserToMention;
                messageInput.messageSegments.add(mentionSegment);
                    
            }
                                   
            ConnectApi.FeedItemInput input = new ConnectApi.FeedItemInput();
            input.body = messageInput;
            
            ConnectApi.FeedItem feedItemRep = ConnectApi.ChatterFeeds.postFeedItem(communityId, feedType, subjectId, input, null);                
                           
                               
                   
       }
       
       update eventsToUpdate;
      
      
       // now let's do the same for personal events
      Personal_Event__c[]  peventsToUpdate = [Select Id, Status__c, End__c from Personal_Event__c
                                              WHERE Status__c = 'Confirmed'  and End__c < :Date.today()];
                                              
       
       for(Personal_Event__c thisEvent : peventsToUpdate  )
       {
           thisEvent.Status__c  = 'Completed';
       }

       update peventsToUpdate;

       
       // and finally let's do the same for projects
       Project_Event__c[] projectEventsToUpdate =  [SELECT Id, Name, Confirmed_End_Date__c, Confirmed_Start_Date__c, Description__c, 
                                                  Status__c, Project__c, Project__r.Name,
                                    (SELECT Id , Who__c, Who__r.Name, Project_Event__c FROM Project_Participants__r ),
                                    (SELECT Id, Start__c, End__c, Who__c, Who__r.Name, Note__c, Hours__c FROM Preparations__r  )

                                           FROM Project_Event__c
                                           WHERE 
                                              Status__c = 'Confirmed' AND
                                              Confirmed_End_Date__c < :todayDate
                                             
                                          ];
       
       for(Project_Event__c thisEvent : projectEventsToUpdate )
       {
           thisEvent.Status__c  = 'Completed';
           
           //also need to post accordingly for updates
           
            System.Debug(' &&&&&&&&&&&&&  Requesting Review of recent project event ' + thisEvent.ID);
                    
            String communityId = null;
            ConnectApi.FeedType feedType = ConnectApi.FeedType.Record;
            String userToMention = UserInfo.getUserId(); 
            String subjectId = thisEvent.Id;
            
            ConnectApi.MessageBodyInput messageInput = new ConnectApi.MessageBodyInput();
            messageInput.messageSegments = new List<ConnectApi.MessageSegmentInput>();
            
            ConnectApi.TextSegmentInput textSegment = new ConnectApi.TextSegmentInput();
            textSegment.text = 'This event has been completed.  Please review to make sure your preparation time is still accurate\n';
            messageInput.messageSegments.add(textSegment);
            
            //need to loop over the customer commitments and preprataions to get the unique set of people
            Set<Id> projectUsersToMention = new Set<Id>();
            for(Project_Preparation__c thePrepItem : thisEvent.Preparations__r)
            {
                if(thePrepItem.Who__c != null)
                {
                    projectUsersToMention.add(thePrepItem.Who__c);            
                }
            }
            
            for(Project_Participant__c theParticipationItem : thisEvent.Project_Participants__r )
            {
                if(theParticipationItem.Who__c != null)
                {
                    projectUsersToMention.add(theParticipationItem.Who__c);            
                }
            }
       
            for(Id theUserToMention : projectUsersToMention)
            {
            
                ConnectApi.MentionSegmentInput mentionSegment = new ConnectApi.MentionSegmentInput();
                mentionSegment.id = theUserToMention;
                messageInput.messageSegments.add(mentionSegment);
                    
            }
                                   
            ConnectApi.FeedItemInput input = new ConnectApi.FeedItemInput();
            input.body = messageInput;
            
            ConnectApi.FeedItem feedItemRep = ConnectApi.ChatterFeeds.postFeedItem(communityId, feedType, subjectId, input, null);                                   
       }
       
       update projectEventsToUpdate;
   }
 }