src/objects/Event_Possible_Date__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <label>Event Hours</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Event__c</fullName>
        <label>Sales Event</label>
        <referenceTo>Sales_Event__c</referenceTo>
        <relationshipLabel>Possible Dates</relationshipLabel>
        <relationshipName>Possible_Dates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Possible</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Possible Date</label>
    <nameField>
        <label>Possible Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Possible Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>SWOT_Strengths__c</fullName>
        <inlineHelpText>Guidewire Strengths</inlineHelpText>
        <label>Strengths</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Sales_Event_Count__c</fullName>
        <label>Sales Event Count</label>
        <summaryForeignKey>Sales_Event__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sales_Event_Total_Cust_Hours__c</fullName>
        <label>Sales Event Total Cust Hours</label>
        <summarizedField>Sales_Event__c.Customer_Hours__c</summarizedField>
        <summaryForeignKey>Sales_Event__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sales_Event_Total_Hours__c</fullName>
        <description>Total Hours (Customer + Preparation) on all Sales Events</description>
        <formula>Sales_Event_Total_Cust_Hours__c + Sales_Event_Total_Prep_Hours__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Hours (Customer + Preparation) on all Sales Events</inlineHelpText>
        <label>Sales Event Total Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Event_Total_Prep_Hours__c</fullName>
        <label>Sales Event Total Prep Hours</label>
        <summarizedField>Sales_Event__c.Preparation_Hours__c</summarizedField>
        <summaryForeignKey>Sales_Event__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Possible_Date__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <label>Event Hours</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Possible</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Possible Date</label>
    <nameField>
        <label>Possible Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Possible Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Preparation__c.object
<CustomObject>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Event__c</fullName>
        <label>Sales Event</label>
        <referenceTo>Sales_Event__c</referenceTo>
        <relationshipLabel>Preparations</relationshipLabel>
        <relationshipName>Preparations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Who__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Preparations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Preparation</label>
    <nameField>
        <label>Preparation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preparations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ResourceRequest__c.object
<CustomObject>
    <description>A request for resources to staff an event.</description>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <description>Totals Hours in front of the customer</description>
        <label>Event Hours</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Demonstration</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Sale Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proof of Concept</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI / RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Consulting Workshop</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFx_Internal_Due__c</fullName>
        <label>RFP Internal Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fully Staffed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revoked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Resource Request</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Event__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_End_Date__c</fullName>
        <label>Confirmed End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Confirmed_Start_Date__c</fullName>
        <label>Confirmed Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Demonstration</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Sale Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proof of Concept</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI / RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Consulting Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Workshop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Workshop Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Alignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Tracking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Consultation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HQ Visit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>List_Of_People__c</fullName>
        <description>Calculated list of people based on who participated</description>
        <label>People</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RFx_Internal_Due__c</fullName>
        <label>RFP Internal Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Tentative</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Support_Request__c.object
<CustomObject>
    <description>Represents requests for support for things such as documents, strategy discussions, and other internal or non-staffing requests.</description>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <summarizedField>Support_Request_Preparation__c.Hours__c</summarizedField>
        <summaryForeignKey>Support_Request_Preparation__c.Sales_Support_Request__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Dossier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Representative Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Hypothesis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Map</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VITO Letter</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Support Request</label>
    <nameField>
        <displayFormat>SSR-{00000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Support Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SalesRepOverviewController.cls
public with sharing class SalesRepOverviewController {

    public Map<Id,Sales_Event__c> salesEventMap {get; set;} 
    public Map<Id,String> tentativeDateMapStarts {get; set;} 
    public Map<Id,String> tentativeDateMapEnds {get; set;} 
    public Map<Id,String> tentativeDateMapDurations {get; set;} 

    public Map<Id,ResourceRequest__c> resourceRequestMap {get; set;} 
    public Map<Id,String> requestDateMapStarts {get; set;} 
    public Map<Id,String> requestDateMapEnds {get; set;} 
    public Map<Id,String> requestDateMapDurations {get; set;} 
    
    

  public Preparation__c viewForUser {get;set;}
  public Boolean showOnlyActiveOpps {get;set;}
  public Boolean showOnlyActiveEvents {get;set;}

  public Boolean showOpenResourceRequests {get;set;}
  public Boolean showOpenSupportRequests {get;set;}

  public SalesRepOverviewController()
  {
      viewForUser = new Preparation__c();
      //temporary
      User currentUser = [SELECT Id, Name from User where Id = :UserInfo.getUserId() LIMIT 1];
      viewForUser.Who__c = currentUser.Id;
      
      showOnlyActiveOpps = false;
      showOnlyActiveEvents = true;
      showOpenResourceRequests = true;
      showOpenSupportRequests = true;
            
      reloadPage();
  }
  
    public void reloadPage()
    {
        if(viewForUser.Who__c != null)
        {
            User userWithName = [Select Id, Name from User where Id = :viewForUser.Who__c LIMIT 1];
            viewForUser.Who__r = userWithName;
        }
        
        salesEventMap = new Map<Id,Sales_Event__c>();
        tentativeDateMapStarts = new Map<Id,String> ();
        tentativeDateMapEnds = new Map<Id,String> ();
        tentativeDateMapDurations = new Map<Id,String> ();
    
        resourceRequestMap = new Map<Id,ResourceRequest__c>();
        requestDateMapStarts = new Map<Id,String> ();
        requestDateMapEnds = new Map<Id,String> ();
        requestDateMapDurations = new Map<Id,String> ();

    }  

  public Boolean getIsPresalesManager() {
      return GWUserProfileHelper.isPresalesManager();
  }


    public String getPageBlockTitle() {
        if(viewForUser != null && viewForUser.Who__c != null)
        {
            return viewForUser.Who__r.Name + '\'s Opportunities and Events';
        }
        return 'Please specify an individual above.';
    }
      
      
    public List<Opportunity> getFilteredOpportunityList() {
        if(viewForUser.Who__c != null)
        {  
            List<String> openOpps = new List<String>{'Lead','Qualified','Evaluating','Red Flag', 'Finalist','Selected','Final Approvals'};    
                
            Opportunity[] listOfOpps = new List<Opportunity>();    
                
            if(showOnlyActiveEvents)
            {
                listOfOpps =  [Select Id, Name, Amount, StageName, CloseDate, Sales_Event_Count__c, Sales_Event_Total_Hours__c,Sales_Event_Total_Cust_Hours__c, Sales_Event_Total_Prep_Hours__c, SWOT_Strengths__c,
                        (SELECT Id, Name, Status__c, RFx_Internal_Due__c,Confirmed_Start_Date__c, Confirmed_End_Date__c, 
                                Event_Type__c, List_Of_People__c, LastModifiedDate, Event_Hours__c, Customer_Hours__c, Preparation_Hours__c, Stage__c 
                           from Sales_Events__r
                           WHERE (Status__c != 'Completed' AND Status__c != 'Canceled')
                           ORDER BY Status__c, Confirmed_Start_Date__c DESC ),
                        (SELECT Id, Name, Description__c, RolesAsString__c, Event_Type__c, Status__c, LastModifiedDate
                           from Resource_Requests__r
                           WHERE (Status__c = 'Pending' OR Status__C = 'Open' OR Status__C = 'Fully Staffed')),
                        (SELECT Id,Type__c, Description__c, Status__c, Assigned_To__c, Hours__c, Requested_Completion_Date__c, Target_Completion_Date__c, LastModifiedDate
                           from Sales_Support_Requests__r
                           WHERE (Status__c = 'Not Started' OR Status__C = 'In Progress'))
                           
                                                                        
                        from Opportunity 
                        where OwnerId = :viewForUser.Who__c
                          and StageName in :openOpps
                        Order By CloseDate];        
                
            }    
            else
            {
                 listOfOpps =  [Select Id, Name, Amount, StageName, CloseDate, Sales_Event_Count__c, Sales_Event_Total_Hours__c, Sales_Event_Total_Cust_Hours__c, Sales_Event_Total_Prep_Hours__c, SWOT_Strengths__c,
                        (SELECT Id, Name, Status__c, RFx_Internal_Due__c,Confirmed_Start_Date__c, Confirmed_End_Date__c, 
                                Event_Type__c, List_Of_People__c, LastModifiedDate, Event_Hours__c, Customer_Hours__c, Preparation_Hours__c, Stage__c 
                           from Sales_Events__r
                           ORDER BY Status__c, Confirmed_Start_Date__c DESC ),
                        (SELECT Id, Name, Description__c, RolesAsString__c, Event_Type__c, Status__c, LastModifiedDate
                           from Resource_Requests__r
                           WHERE (Status__c = 'Pending' OR Status__C = 'Open' OR Status__C = 'Fully Staffed')),
                        (SELECT Id,Type__c, Description__c, Status__c, Assigned_To__c, Hours__c, Requested_Completion_Date__c, Target_Completion_Date__c, LastModifiedDate
                           from Sales_Support_Requests__r
                           WHERE (Status__c = 'Not Started' OR Status__C = 'In Progress'))
                        from Opportunity 
                        where OwnerId = :viewForUser.Who__c
                          and StageName in :openOpps
                        Order By CloseDate];        
                
            }
                
                            
            //build the event map from the above opps

        List<Opportunity> toReturn = new List<Opportunity>();
        List<Id> relevantEventIDs = new List<Id>();
        List<Id> relevantRequestIDs = new List<Id>();
        
//        if(possibleDates.size() > 0)
//        {
            for(Opportunity opp : listOfOpps)
            {
                //first add to list of opportunities if needed
                if(!showOnlyActiveOpps || opp.Sales_Events__r.size() > 0 || opp.Resource_Requests__r.size() > 0 || opp.Sales_Support_Requests__r.size() > 0)
                {
                    toReturn.add(opp);
                }
            
                for(Sales_Event__c sevent : opp.Sales_Events__r)
                {
                    relevantEventIDs.add(sevent.Id);
                
                }        

                for(ResourceRequest__c rrequest : opp.Resource_Requests__r)
                {
                    relevantRequestIDs.add(rrequest.Id);
                
                }        

            
            }
            
//        }               
        
          //build maps of dates for sales events
            Sales_Event__c[] sevents = 
                        [SELECT Id, Name, Status__c, RFx_Internal_Due__c,Confirmed_Start_Date__c, Confirmed_End_Date__c, 
                            Event_Type__c, List_Of_People__c, LastModifiedDate, Event_Hours__c, Customer_Hours__c, Preparation_Hours__c, Stage__c,
                            (SELECT Id, Start_Date__c, End_Date__c, Status__c, Event_Hours__c from Possible_Dates__r
                             WHERE Status__c = 'Possible')
                         from Sales_Event__c
                         WHERE Id in :relevantEventIDs
                         ORDER BY Status__c, Confirmed_Start_Date__c DESC ];
                                
            for(Sales_Event__c thisSEvent : sevents)
            {
                salesEventMap.put(thisSEvent.Id, thisSEvent);
                if(thisSEvent.Status__c == 'Tentative')
                {
                    String currentValStarts = tentativeDateMapStarts.get(thisSEvent.Id);
                    if(currentValStarts == null) 
                    {
                     tentativeDateMapStarts.put(thisSEvent.Id, '');
                     tentativeDateMapEnds.put(thisSEvent.Id, '');
                     tentativeDateMapDurations.put(thisSEvent.Id, '');
                    }
                    
                    for(Event_Possible_Date__c pdate : thisSEvent.Possible_Dates__r)
                    {
                        if(pdate.Status__c == 'Possible')
                        {
                            //add an entry to the three maps
                            
//                            tentativeDateMap.put(pdate.Id,

                                currentValStarts = tentativeDateMapStarts.get(thisSEvent.Id);
                                String currentValEnds = tentativeDateMapEnds.get(thisSEvent.Id);
                                String currentValDurations = tentativeDateMapDurations.get(thisSEvent.Id);
                                if(currentValStarts != null && currentValStarts != '')
                                {
                                    currentValStarts += '<br/>';
                                    currentValEnds += '<br/>';
                                    currentValDurations += '<br/>';
                                }
                                currentValStarts += pdate.Start_Date__c.format();
                                currentValEnds += pdate.End_Date__c.format();
                                currentValDurations += pdate.Event_Hours__c;
                                
                                tentativeDateMapStarts.put(thisSEvent.Id, currentValStarts);
                                tentativeDateMapEnds.put(thisSEvent.Id, currentValEnds);
                                tentativeDateMapDurations.put(thisSEvent.Id, currentValDurations);

                        }
                         //
                    
                    }
                }
            }                     
                  
                  
            //build maps for resource requests     
                          
         ResourceRequest__c[] rrequests = 
                        [SELECT Id, Name, Status__c, RFx_Internal_Due__c, 
                            Event_Type__c,  LastModifiedDate, Event_Hours__c,
                            (SELECT Id, Start_Date__c, End_Date__c, Status__c, Event_Hours__c from Possible_Dates__r
                             WHERE Status__c = 'Possible' or Status__c = 'Selected' or Status__c = 'Preferred' )
                         from ResourceRequest__c
                         WHERE Id in :relevantRequestIDs
                         ORDER BY Status__c];

            for(ResourceRequest__c thisRRequest : rrequests)
            {
                resourceRequestMap.put(thisRRequest.Id, thisRRequest);


                String currentValStarts = requestDateMapStarts.get(thisRRequest.Id);
                if(currentValStarts == null) 
                {
                 requestDateMapStarts.put(thisRRequest.Id, '');
                 requestDateMapEnds.put(thisRRequest.Id, '');
                 requestDateMapDurations.put(thisRRequest.Id, '');
                }
                
                for(Possible_Date__c pdate : thisRRequest.Possible_Dates__r)
                {
                    if(pdate.Status__c == 'Possible' || pdate.Status__c == 'Selected'|| pdate.Status__c == 'Preferred')
                    {
                        //add an entry to the three maps
                        
//                            tentativeDateMap.put(pdate.Id,

                            currentValStarts = requestDateMapStarts.get(thisRRequest.Id);
                            String currentValEnds = requestDateMapEnds.get(thisRRequest.Id);
                            String currentValDurations = requestDateMapDurations.get(thisRRequest.Id);
                            if(currentValStarts != null && currentValStarts != '')
                            {
                                currentValStarts += '<br/>';
                                currentValEnds += '<br/>';
                                currentValDurations += '<br/>';
                            }
                            currentValStarts += pdate.Start_Date__c.format();
                            currentValEnds += pdate.End_Date__c.format();
                            currentValDurations += pdate.Event_Hours__c;
                            
                            requestDateMapStarts.put(thisRRequest.Id, currentValStarts);
                            requestDateMapEnds.put(thisRRequest.Id, currentValEnds);
                            requestDateMapDurations.put(thisRRequest.Id, currentValDurations);

                    }
                     //
                
                }
            }                     

                            
            return toReturn;        
                    
        }
        return null;
    }
      

}