src/objects/Extended_Support__c.object
<CustomObject>
    <description>Created for Shannon McColloch.  Used to track Extended Support records.  Related to Contracts and Accounts.</description>
    <fields>
        <fullName>Current_Product_Version__c</fullName>
        <formula>TEXT(Product__r.Current_Product_Version__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulled from related Product record.</inlineHelpText>
        <label>Current Product Version</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to product custom object.</description>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Extended Supports</relationshipLabel>
        <relationshipName>Extended_Supports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version_RUH__c</fullName>
        <description>Used by Roll Up Helper.  Used to capture Version from the Product record.</description>
        <label>Version RUH</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>Extended Support</label>
    <nameField>
        <displayFormat>ES{000000}</displayFormat>
        <label>Extended Support Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Extended Supports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>Owner - Roopal Shah</description>
    <fields>
        <fullName>Current_Product_Version__c</fullName>
        <label>Current Product Version</label>
        <picklist>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Extended_Support__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for Roll Up Helper.  Ties Product to Extended Support.</description>
        <label>Extended Support</label>
        <referenceTo>Extended_Support__c</referenceTo>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product(C)</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products(C)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PouplateProdESHandler.cls
public without sharing class PouplateProdESHandler
{
    public static boolean isExecuted =false;
    
    public static void onCreation(List<Extended_Support__c> lstExtendedSupport)
    {
        Set<Id> setProductIds =new Set<Id>();
        Map<Id, Product__c> mapProduct;
        
        for(Extended_Support__c extendedSupport :lstExtendedSupport)
            setProductIds.add(extendedSupport.product__c);
        
        updateVersionRuh(setProductIds, lstExtendedSupport);
    }
    
    public static void onUpdation(List<Extended_Support__c> lstExtendedSupport, Map<Id,Extended_Support__c> mapOldExtendedSupport)
    {
        Map<Id,Extended_Support__c> mapExtendedSupport =new Map<Id,Extended_Support__c>([Select Version_RUH__c,Product__r.Current_Product_Version__c from Extended_Support__c where Id =:lstExtendedSupport]);
        Set<Id> setProductIds =new Set<Id>();
        
        for(Extended_Support__c extendedSupport :lstExtendedSupport)
        {
            if(extendedSupport.product__c != mapOldExtendedSupport.get(extendedSupport.Id).product__c)
                setProductIds.add(extendedSupport.product__c);
        }
        
        updateVersionRuh(setProductIds, lstExtendedSupport);
        isExecuted =true;
    }
    
    static void updateVersionRuh(Set<Id> setProductIds, List<Extended_Support__c> lstExtSupport)
    {
        Map<Id, Product__c> mapProduct;
        
        if(!setProductIds.isEmpty())
        {
            mapProduct =new Map<Id, Product__c>([Select Current_Product_Version__c from Product__c where Id IN:setProductIds]);
        }
        
        if(mapProduct != null && mapProduct.size() >0)
        {
            for(Extended_Support__c extendedSupport :lstExtSupport)
            {
                extendedSupport.Version_RUH__c =mapProduct.get(extendedSupport.product__c).Current_Product_Version__c;
            }
        }
    }
    
    public static void updateProduct(List<Extended_Support__c> lstExtSupport)
    {
        Map<id,id> mapProductIdExtendedSupport = new Map<id,id>();
        for(Extended_Support__c ess :lstExtSupport)
        {
            mapProductIdExtendedSupport.put(ess.Product__c,ess.id);
        }
        List<Product__c> lstProduct = [Select Id,name,Extended_Support__c from Product__c where id =:mapProductIdExtendedSupport.keyset()];
        for(Product__c ppp:lstProduct)
        {
            ppp.Extended_Support__c = mapProductIdExtendedSupport.get(ppp.id);
        }
        update lstProduct ;
    }
}