src/objects/Extended_Support__c.object
<CustomObject>
    <description>Created for Shannon McColloch.  Used to track Extended Support records.  Related to Contracts and Accounts.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Extended Supports</relationshipLabel>
        <relationshipName>Extended_Supports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Look up to related Contract record.</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Extended Supports</relationshipLabel>
        <relationshipName>Extended_Supports</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Product_Version__c</fullName>
        <formula>TEXT(Product__r.Current_Product_Version__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulled from related Product record.</inlineHelpText>
        <label>Current Product Version</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Master of Extended Support custom object.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Extended Supports</relationshipLabel>
        <relationshipName>Extended_Supports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to product custom object.</description>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Extended Supports</relationshipLabel>
        <relationshipName>Extended_Supports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Extended Support</label>
    <nameField>
        <displayFormat>ES{000000}</displayFormat>
        <label>Extended Support Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Extended Supports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>Owner - Roopal Shah</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Current_Product_Version__c</fullName>
        <label>Current Product Version</label>
        <picklist>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Extended_Support__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for Roll Up Helper.  Ties Product to Extended Support.</description>
        <label>Extended Support</label>
        <referenceTo>Extended_Support__c</referenceTo>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product(C)</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products(C)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestPouplateProdESHandler.cls
@isTest(seealldata=true) 
Public Class TestPouplateProdESHandler{
static testMethod void myTest(){
Account acc = new Account();
acc.Name = 'Test1';
insert acc;
Product__c ppp = new Product__c();
//ppp.Name = 'Product1';
ppp.Account__c = acc.id;
ppp.Current_Product_Version__c ='3';
insert ppp;

Product__c product = new Product__c();
product.Account__c = acc.id;
product.Current_Product_Version__c ='7';
insert product;

Extended_Support__c ess = new Extended_Support__c(); 
ess.Product__c = ppp.id;
ess.Contract__c = [select id from contract limit 1].id;
ess.Opportunity__c = [select id from Opportunity limit 1].id;
insert ess;

ess.product__c =product.Id;
update ess;

}
}