src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Support_Request__c.object
<CustomObject>
    <description>Represents requests for support for things such as documents, strategy discussions, and other internal or non-staffing requests.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Support Requests</relationshipLabel>
        <relationshipName>Sales_Support_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actual_Completion_Date__c</fullName>
        <label>Actual Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Support Requests</relationshipLabel>
        <relationshipName>Sales_Support_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_Completion_Date__c</fullName>
        <label>Requested Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Completion_Date__c</fullName>
        <label>Target Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Dossier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Representative Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Hypothesis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Map</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VITO Letter</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Support Request</label>
    <nameField>
        <displayFormat>SSR-{00000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Support Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestVC_Dash2Controller.cls
@isTest(seealldata=true)
private class TestVC_Dash2Controller
{ 
    static testmethod void vcdash2Test()
    {
       Account acc=new Account();
       acc.name='test account';
       acc.BillingCountry='US';
       insert acc; 
        
       Opportunity opp=new Opportunity();
       opp.StageName='Prospecting'; 
       opp.CloseDate=system.today();
       opp.Name='Test Opportinity'; 
       opp.AccountId=acc.id;
        opp.Amount=400;
       insert opp;
        
      /* CollaborationGroup cgp = new CollaborationGroup();
        cgp.Name='VC Staffing';
        cgp.CollaborationType='public';        
        insert cgp;
       */
       
        Sales_Support_Request__c ssr=new Sales_Support_Request__c();
        // ssr.name='test support req';
        ssr.Type__c='Dossier';
        ssr.Status__c='Not Started';
        ssr.Requested_Completion_Date__c=date.newinstance(2014, 2, 24);
        ssr.Opportunity__c=opp.id;
        insert ssr;
        
        Sales_Support_Request__c ssr1=new Sales_Support_Request__c();
       // ssr1.name='test support req';
        ssr1.Type__c='Dossier';
        ssr1.Status__c='Not Started';
        ssr1.Requested_Completion_Date__c=date.newinstance(2014, 1, 24);
        ssr1.Opportunity__c=opp.id;
        insert ssr1;
        
        Test.startTest();
        VC_Dash2Controller cntrl=new VC_Dash2Controller();
        String year=cntrl.getMyRequestRange();
        system.assertEquals(year, '2014');
        cntrl.reloadPage();
        cntrl.getTheFilteredList();
        
        Test.stopTest();        
    }    
    
    static testmethod void vcdash2Test1()
    {
       Account acc=new Account();
       acc.name='test account';
       acc.BillingCountry='US';
       insert acc; 
        
        Sales_Support_Request__c ssr=new Sales_Support_Request__c();
        //ssr.name='test support req';
        ssr.Type__c='Dossier';
        ssr.Status__c='Completed';
        ssr.Actual_Completion_Date__c=date.newinstance(2014, 2, 24);
        ssr.Account__c=acc.id;
        //ssr.Opportunity__c=opp.id;
        insert ssr;
        
        Sales_Support_Request__c ssr1=new Sales_Support_Request__c();
        //ssr1.name='test support req';
        ssr1.Type__c='Dossier';
        ssr1.Status__c='Completed';
        ssr1.Actual_Completion_Date__c=date.newinstance(2014, 1, 24);
        ssr1.Account__c=acc.id;
        //ssr.Opportunity__c=opp.id;
        insert ssr1;
        
        Test.startTest();
        VC_Dash2Controller cntrl=new VC_Dash2Controller();
        String year=cntrl.getMyRequestRange();
        system.assertEquals(year, '2014');
        cntrl.reloadPage();
        cntrl.getTheFilteredList();
        
        Test.stopTest();        
    }    
  
    static testmethod void vcdash2Test2()
    {
       Account acc=new Account();
       acc.name='test account';
       acc.BillingCountry='US';
       insert acc; 
        
        Sales_Support_Request__c ssr=new Sales_Support_Request__c();
        //ssr.name='test support req';
        ssr.Type__c='Dossier';
        ssr.Status__c='In Progress';
        ssr.Target_Completion_Date__c=date.newinstance(2014, 2, 24);
        ssr.Account__c=acc.id;
        //ssr.Opportunity__c=opp.id;
        insert ssr;
        
        Sales_Support_Request__c ssr1=new Sales_Support_Request__c();
        //ssr1.name='test support req';
        ssr1.Type__c='Dossier';
        ssr1.Status__c='In Progress';
        ssr1.Target_Completion_Date__c=date.newinstance(2014, 1, 24);
        ssr1.Account__c=acc.id;
        //ssr.Opportunity__c=opp.id;
        insert ssr1;
        
        Test.startTest();
        VC_Dash2Controller cntrl=new VC_Dash2Controller();
        String year=cntrl.getMyRequestRange();
        system.assertEquals(year, '2014');
        cntrl.reloadPage();
        List<VC_Dash2Controller.RequestWrapper> reqWrplst=cntrl.getTheFilteredList();
        VC_Dash2Controller.RequestWrapper reqwrapper=reqWrplst[0];
        reqwrapper.getRequestDateAsString();
        reqwrapper.setResultDate(date.today());
        reqwrapper.getResultDate();
      
        Test.stopTest();        
    }    
    
}