src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Data_Management_Approved_PMM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Data Management Approved (PMM)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Data_Management_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Data Management Approved (PM)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>InsuranceSuite_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>InsuranceSuite Approved (PM)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Insurance_Suite_Approved_PMM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>InsuranceSuite Approved (PMM)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Live_Approved_PPM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Live Approved (PPM)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Live_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Live Approved (PM)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mobile_Portals_Approved_PMM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobile &amp; Portals Approved (PMM)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mobile_Portals_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobile &amp; Portals Approved (PM)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Premium_In_Scope__c</fullName>
        <inlineHelpText>This should be the deal premium in scope or the incremental DWP Adjustment. Used in conjunction with Price Rules to calculate the price for certain Products.</inlineHelpText>
        <label>Premium In Scope</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Request_Data_Management_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Request Data Management Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_Insurance_Suite_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Request approval to sell InsuranceSuite including Mitchell in the Opportunity&apos;s region.</inlineHelpText>
        <label>Request InsuranceSuite Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_Live_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Request Live Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_Mobile_Portals_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Request Mobile &amp; Portals Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_Standards_based_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Request approval for Standards Based Templates</inlineHelpText>
        <label>Standards Based Templates Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standards_based_Templates_Approved_PMM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Standards Based Templates Approved (PMM)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standards_based_Templates_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Standards Based Templates Approved (PM)</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestUpdateApproversHandler.cls
@istest
private class TestUpdateApproversHandler 
{
    static testmethod void ApproversTest()
    {
       
        opportunity opp = new opportunity (StageName = 'Prospecting', CloseDate = system.today(),
                                           Name='testopp', Amount=500,
                                           Premium_In_Scope__c = 100,
                                          InsuranceSuite_Approved__c = false, Insurance_Suite_Approved_PMM__c = false, 
                                          Data_Management_Approved__c = false, Data_Management_Approved_PMM__c = false,
                                          Mobile_Portals_Approved__c = false, Mobile_Portals_Approved_PMM__c = false,
                                          Standards_based_Templates_Approved__c = false, Standards_based_Templates_Approved_PMM__c = false,
                                          Live_Approved__c = false, Live_Approved_PPM__c = false,
                                         // Standard_Reporting_Approved_PM__c = false, Standard_Reporting_Approved_PMM__c = false, 
                                          Request_Live_Approval__c = false, Request_Insurance_Suite_Approval__c = false,
                                          Request_Data_Management_Approval__c = false, Request_Mobile_Portals_Approval__c = false,
                                          Request_Standards_based_Approval__c = false); //Request_Standard_Reporting_Approval__c=false);
                                          
        
        insert opp;
        
        opp.InsuranceSuite_Approved__c = true;
        opp.Insurance_Suite_Approved_PMM__c = true; 
        opp.Data_Management_Approved__c = true;
        opp.Data_Management_Approved_PMM__c = true;
        opp.Mobile_Portals_Approved__c = true;
        opp.Mobile_Portals_Approved_PMM__c = true;
        opp.Standards_based_Templates_Approved__c = true;
        opp.Standards_based_Templates_Approved_PMM__c = true;
        opp.Live_Approved__c = true;
        opp.Live_Approved_PPM__c = true;
      //  opp.Standard_Reporting_Approved_PM__c = true;
     //   opp.Standard_Reporting_Approved_PMM__c = true;
        opp.Request_Live_Approval__c = true;
        opp.Request_Insurance_Suite_Approval__c = true;
        opp.Request_Data_Management_Approval__c = true;
        opp.Request_Mobile_Portals_Approval__c = true;
        opp.Request_Standards_based_Approval__c = true;
      //  opp.Request_Standard_Reporting_Approval__c=true;
      
              
        update opp;
      }        
    }