src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ResourceRequest__c.object
<CustomObject>
    <description>A request for resources to staff an event.</description>
    <fields>
        <fullName>Event_Goals__c</fullName>
        <label>Event Goals</label>
        <length>1500</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Demonstration</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Sale Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proof of Concept</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI / RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Consulting Workshop</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <inlineHelpText>Location of the event.  Leave blank if Presentation Type is Remote.</inlineHelpText>
        <label>Location</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Resource_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Presentation_Type__c</fullName>
        <label>Presentation Type</label>
        <picklist>
            <picklistValues>
                <fullName>On-site</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Remote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HQ Visit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFx_External_Due__c</fullName>
        <label>RFP External Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RFx_Internal_Due__c</fullName>
        <label>RFP Internal Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RFx_Received__c</fullName>
        <label>RFP Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fully Staffed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revoked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Resource Request</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Event__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_End_Date__c</fullName>
        <label>Confirmed End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Confirmed_Start_Date__c</fullName>
        <label>Confirmed Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Goals__c</fullName>
        <label>Event Goals</label>
        <length>1500</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Demonstration</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Sale Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proof of Concept</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI / RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Consulting Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Workshop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Workshop Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Alignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Tracking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Consultation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HQ Visit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Events</relationshipLabel>
        <relationshipName>Sales_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Presentation_Type__c</fullName>
        <label>Presentation Type</label>
        <picklist>
            <controllingField>Event_Type__c</controllingField>
            <picklistValues>
                <fullName>On-site</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Remote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HQ Visit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFx_External_Due__c</fullName>
        <label>RFP External Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RFx_Internal_Due__c</fullName>
        <label>RFP Internal Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RFx_Received__c</fullName>
        <label>RFP Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Tentative</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ServicesDirectorEmailHandler.cls
public class ServicesDirectorEmailHandler 
{   
    public static void SalesEventEmail(id userid, string usrname, sales_event__c salesEvent )
    {
        string url = Label.Valid_URL;
        
        String startDate = '';
        String endDate = '';
        Time t1 = Time.newInstance(0, 0, 0, 0);
        
        if(salesevent.Confirmed_Start_Date__c != null)
        startDate = Datetime.newInstance(salesevent.Confirmed_Start_Date__c, t1).format('YYYY-MM-dd');
                    
        if(salesevent.Confirmed_End_Date__c != null)
        endDate = Datetime.newInstance(salesevent.Confirmed_End_Date__c, t1).format('YYYY-MM-dd');
        
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        
        message.setSaveAsActivity(false);
        message.setTargetObjectId(userid);
        message.setSubject('A new Sales Event has been created for the '+salesevent.Opportunity__r.Name+'');
        message.setHtmlbody('Hello&nbsp'+usrname+', <br> <br> This is to notify that a new Sales Event is created for the opportunity: <a href=" '+url+'/'+Salesevent.Opportunity__c+' ">'
                            +salesevent.Opportunity__r.Name+' </a> <br><br> <table align="left"> <tr> <td> Event:</td> <td>'
                            +salesevent.Name+'</td> </tr> <tr> <td> Event Type: </td> <td>'+salesevent.Event_Type__c+
                            '</td> </tr><tr> <td> Stage: </td> <td> '+salesevent.Opportunity__r.stageName+'</td> </tr> <tr> <td> Presentation Type:</td> <td> '+salesevent.Presentation_Type__c+
                           '</td> </tr> <tr> <td> Location: </td> <td>'+salesevent.Location__c+'</td> </tr> <tr> <td> Start Date: </td> <td>'
                            +startdate+'</td> </tr> <tr> <td> End Date: </td> <td>'
                            +enddate+'</td> </tr><tr> </tr> <tr>  Event Goals: <br><br>'+salesevent.Event_Goals__c+
                           '</tr> <tr> Thank you. </tr> </table>');
        
         Messaging.sendEmail(new Messaging.SingleEmailMessage[] {message});
        
    }
    
    public static void ResourceRequestEmail(id userid, string usrname, ResourceRequest__c ResReqst)
    {
        string url = Label.Valid_URL;
        
        String InternalDate = '';
        String externalDate = '';
        String ReceivedDate ='';
        Time t1 = Time.newInstance(0, 0, 0, 0);
        
        if(resreqst.RFx_Received__c != null)
        ReceivedDate = Datetime.newInstance(resreqst.RFx_Received__c, t1).format('YYYY-MM-dd');
                    
        if(resreqst.RFx_Internal_Due__c != null)
        InternalDate = Datetime.newInstance(resreqst.RFx_Internal_Due__c, t1).format('YYYY-MM-dd');
        
        if(resreqst.RFx_External_Due__c != null)
        externalDate = Datetime.newInstance(resreqst.RFx_External_Due__c, t1).format('YYYY-MM-dd');
        
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        
        message.setSaveAsActivity(false);
        message.setTargetObjectId(userid);
        message.setSubject('A new Resource Request has been created for the '+ResReqst.Opportunity__r.Name+'');
        message.setHtmlbody('Hello&nbsp'+usrname+', <br> <br> This is to notify that a new Resource Request is created for the opportunity: <a href=" '+url+'/'+ResReqst.Opportunity__c+' ">'
                            +ResReqst.Opportunity__r.Name+' </a> <br><br> <table align="left"> <tr> <td> Event:</td> <td>'
                            +ResReqst.Name+'</td> </tr> <tr> <td> Event Type: </td> <td>'+ResReqst.Event_Type__c+
                            '</td> </tr><tr> <td> Stage: </td> <td> '+ResReqst.Opportunity__r.stageName+'</td> </tr> <tr> <td> Presentation Type:</td> <td> '
                            +ResReqst.Presentation_Type__c+'<tr> <td> Status:</td> <td> '+ResReqst.Status__c+'</td> </tr> <tr> <td> Location: </td> <td>'
                            +ResReqst.Location__c+'</td> </tr> <tr> <td> RFP Received Date: </td> <td>'
                            +ReceivedDate+'</td> </tr> <tr> <td>  RFP Internal Due Date: </td> <td>'
                            +InternalDate+'</td> </tr> <tr> <td> RFP External Due Date: </td> <td>'
                            +externalDate+'</td> </tr> <tr> </tr> <tr>  Event Goals: <br><br>'+ResReqst.Event_Goals__c+
                           '</tr> <tr> Thank you. </tr> </table>');
        
         Messaging.sendEmail(new Messaging.SingleEmailMessage[] {message});
     }   

}