src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>AMER</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ResourceRequest__c.object
<CustomObject>
    <description>A request for resources to staff an event.</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Please provide details that are specific to the demo such as the goal of the meeting, description of the audience, line of business, states, etc.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Goals__c</fullName>
        <label>Event Goals</label>
        <length>1500</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Demonstration</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Sale Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proof of Concept</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI / RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Consulting Workshop</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <inlineHelpText>Location of the event.  Leave blank if Presentation Type is Remote.</inlineHelpText>
        <label>Location</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Resource_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Presentation_Type__c</fullName>
        <label>Presentation Type</label>
        <picklist>
            <picklistValues>
                <fullName>On-site</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Remote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HQ Visit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RolesAsString__c</fullName>
        <label>Roles List</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fully Staffed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revoked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Resource Request</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ResourceRequest_Chatter_Group__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To store chatter group names.</description>
    <fields>
        <fullName>GroupName__c</fullName>
        <label>GroupName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegionName__c</fullName>
        <label>RegionName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Resource Request Chatter Group</label>
</CustomObject>

src/classes/ResourceRequestsHandler.cls
public class ResourceRequestsHandler
{
    public void ResourceRequestGroup(set<id> Reqids)
    {
     
    List<ResourceRequest__c> Reqlst = [SELECT Id, Name, Description__c, Event_Type__c,RolesAsString__c, event_goals__c, Presentation_Type__c, Location__c, Status__c, Opportunity__c, Opportunity__r.Name, Opportunity__r.Region__c ,CreatedById,CreatedBy.Name, CreatedDate, LastModifiedById, LastModifiedDate
                                      FROM ResourceRequest__c WHERE Id IN: Reqids];
      
    List<feeditem> feeditems = new list<feeditem>();
  
    Map<string, CollaborationGroup> CollGroupMap = new Map<string, CollaborationGroup>();
    List<string> groupLst = new List<string>();
    Map<String,String> regionMap = new Map<string,string>();
        
   //ResourceRequest_Chatter_Group__c is a custom setting which has the fields RegionName__c,GroupName__c.
    List<ResourceRequest_Chatter_Group__c> regionGroupLst = ResourceRequest_Chatter_Group__c.getall().values();
    
    for(ResourceRequest_Chatter_Group__c req : regionGroupLst)
    {
       groupLst.add(req.GroupName__c);
       regionMap.put(req.GroupName__c,req.RegionName__c);
    }
    
    List<CollaborationGroup> SCGroups = [SELECT Id, Name from CollaborationGroup WHERE Name IN : groupLst];
       
    for(CollaborationGroup cg: SCGroups)
    {
        if(regionMap.containskey(cg.name))
            collgroupmap.put(regionMap.get(cg.name), cg);
    }
    
    for(ResourceRequest__c req : Reqlst)
    {
        if(req.Opportunity__r.Region__c != null)
        {
           if(req.status__c == 'Pending' && collgroupmap.containsKey(req.Opportunity__r.Region__c))
           { 
               CollaborationGroup sCStaffingGroup = collgroupmap.get(req.Opportunity__r.Region__c);
                            
                FeedItem post2 = new FeedItem();
                post2.ParentId = sCStaffingGroup.Id;   // requestID; //fix this to be the right group
                post2.Body = 'New Pending Resource Request created by: '+Req.CreatedBy.Name;          
           //   post2.Body = 'New Staffing Request:\n' + Req.Opportunity__r.Name + ' - '+Req.Name +' ('+Req.Event_Type__c+')'; // \nRoles Needed: ' + Req.RolesAsString__c;
                post2.Title = Req.Opportunity__r.Name + ' - '+Req.Name +' ('+Req.Event_Type__c+')';
                post2.LinkUrl = URL.getSalesforceBaseUrl().toExternalForm() + '/' + Req.ID;
                feeditems.add(post2);
          }
        }      
    }  
    insert feeditems;
    }
}