src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Premium_In_Scope__c</fullName>
        <inlineHelpText>This should be the deal premium in scope or the incremental DWP Adjustment. Used in conjunction with Price Rules to calculate the price for certain Products.</inlineHelpText>
        <label>Premium In Scope</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SWOT_Opportunities__c</fullName>
        <description>The Opportunities aspect of the SWOT</description>
        <inlineHelpText>Opportunities EXTERNAL to Guidewire</inlineHelpText>
        <label>Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_SO__c</fullName>
        <inlineHelpText>Strategy for addressing the Opportunities in the context of our Strengths</inlineHelpText>
        <label>Strengths/Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_ST__c</fullName>
        <inlineHelpText>Strategy for addressing the Threats in the context of our Strengths</inlineHelpText>
        <label>Strengths/Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_WO__c</fullName>
        <inlineHelpText>Strategy for addressing Opportunities in the context of our Weaknesses</inlineHelpText>
        <label>Weaknesses/Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_WT__c</fullName>
        <inlineHelpText>Strategy for addressing the Threats in the context of our Weaknesses</inlineHelpText>
        <label>Weaknesses/Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strengths__c</fullName>
        <inlineHelpText>Guidewire Strengths</inlineHelpText>
        <label>Strengths</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Threats__c</fullName>
        <inlineHelpText>Threats external to Guidewire</inlineHelpText>
        <label>Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Weaknesses__c</fullName>
        <inlineHelpText>Guidewire Weaknesses</inlineHelpText>
        <label>Weaknesses</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Event__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_End_Date__c</fullName>
        <label>Confirmed End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Confirmed_Start_Date__c</fullName>
        <label>Confirmed Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Event Hours</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Demonstration</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Sale Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proof of Concept</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI / RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Consulting Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Workshop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Workshop Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Alignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Tracking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Consultation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HQ Visit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Events</relationshipLabel>
        <relationshipName>Sales_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>RFx_Internal_Due__c</fullName>
        <label>RFP Internal Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Tentative</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestPresalesMetricsController.cls
@isTest(seeAllData=true)
private class TestPresalesMetricsController {

    static testMethod void validateController() {
        Opportunity o = new Opportunity(SWOT_Strengths__c='S Value',
                                        SWOT_Weaknesses__c='W Value',
                                        SWOT_Opportunities__c = 'O Value',
                                        SWOT_Threats__c = 'T Value',
                                        SWOT_Strategy_SO__c = 'SO Value',
                                        SWOT_Strategy_ST__c = 'ST Value',
                                        SWOT_Strategy_WO__c = 'WO Value',
                                        SWOT_Strategy_WT__c = 'WT Value',
                                        Name = 'Test SWOT Opportunity',
                                        StageName = 'Qualified',
                                        CloseDate = Date.today(),
                                        Premium_In_Scope__c = 1000,
                                        Amount=100   );
    
        insert o;
        
        
        //create an event for the current user
        
        Sales_Event__c event1 = new Sales_Event__c(Name='Test Event 1',
                                                   Opportunity__c = o.Id,
                                                   Confirmed_Start_Date__c = Date.today(),
                                                   Confirmed_End_Date__c = Date.today().addDays(1),
                                                   Event_Hours__c = 8,
                                                   Event_Type__c = 'Demonstration',
                                                   Status__c = 'Confirmed');
                                                   
        

        insert event1;

        Sales_Event__c event2 = new Sales_Event__c(Name='Test Event 1',
                                                   Opportunity__c = o.Id,
                                                   RFx_Internal_Due__c = Date.today(),
                                                   Event_Hours__c = 8,
                                                   Event_Type__c = 'RFI / RFP',
                                                   Status__c = 'Confirmed');
                                                   
        

        insert event2;
                
                
        PresalesMetricsController pmc = new PresalesMetricsController();
        //this might be called by constructer, but let's call it anyway
        pmc.reloadPage();
        
        
         
    }
}