src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Services_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Services Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesTaDV</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ResourceRequest__c.object
<CustomObject>
    <description>A request for resources to staff an event.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Resource_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Resource Request</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ResourceRequestServicesDirectorHandler.cls
public class ResourceRequestServicesDirectorHandler
{
    public void UpdateResourceRequest(list<ResourceRequest__c> reqlst)
    {
        set<id> oppids= new set<id>();
        
        for(ResourceRequest__c req: reqlst)
          oppids.add(req.opportunity__c);
        
        map<id,opportunity> oppmap = new map<id,opportunity>([select id,name,services_director__c, services_director__r.Name, stageName 
                                                              from opportunity where id=: oppids]);
        
        for(ResourceRequest__c req: reqlst)
        {
            opportunity opp = oppmap.get(req.Opportunity__c);
            
            if(opp.services_director__c != null)
               ServicesDirectorEmailHandler.ResourceRequestEmail(opp.Services_Director__c,opp.Services_Director__r.Name, req);
         }
    }

}