src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Premium_In_Scope__c</fullName>
        <inlineHelpText>This should be the deal premium in scope or the incremental DWP Adjustment. Used in conjunction with Price Rules to calculate the price for certain Products.</inlineHelpText>
        <label>Premium In Scope</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>AMER</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestServicesDirectorForecastHandler.cls
@isTest(seeAllData = true)
public class TestServicesDirectorForecastHandler 
{
    static testmethod void ForecastTest()
    {   
        Profile p = [SELECT Id FROM Profile WHERE Name='GW Inside/Sales Ops']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testingser', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standusertest@testorg.com');
        insert u;
        
                
        opportunity opp = new opportunity (StageName = 'Prospecting', CloseDate = system.today(),
                                           Name='testopp', Amount=500, Region__c ='EMEA', 
                                           Premium_In_Scope__c = 100);             
                                          
        insert opp; 
        
    
    }        

}