src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Premium_In_Scope__c</fullName>
        <inlineHelpText>This should be the deal premium in scope or the incremental DWP Adjustment. Used in conjunction with Price Rules to calculate the price for certain Products.</inlineHelpText>
        <label>Premium In Scope</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SWOT_Opportunities__c</fullName>
        <description>The Opportunities aspect of the SWOT</description>
        <inlineHelpText>Opportunities EXTERNAL to Guidewire</inlineHelpText>
        <label>Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_SO__c</fullName>
        <inlineHelpText>Strategy for addressing the Opportunities in the context of our Strengths</inlineHelpText>
        <label>Strengths/Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_ST__c</fullName>
        <inlineHelpText>Strategy for addressing the Threats in the context of our Strengths</inlineHelpText>
        <label>Strengths/Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_WO__c</fullName>
        <inlineHelpText>Strategy for addressing Opportunities in the context of our Weaknesses</inlineHelpText>
        <label>Weaknesses/Opportunities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strategy_WT__c</fullName>
        <inlineHelpText>Strategy for addressing the Threats in the context of our Weaknesses</inlineHelpText>
        <label>Weaknesses/Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Strengths__c</fullName>
        <inlineHelpText>Guidewire Strengths</inlineHelpText>
        <label>Strengths</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Threats__c</fullName>
        <inlineHelpText>Threats external to Guidewire</inlineHelpText>
        <label>Threats</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SWOT_Weaknesses__c</fullName>
        <inlineHelpText>Guidewire Weaknesses</inlineHelpText>
        <label>Weaknesses</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Support_Request__c.object
<CustomObject>
    <description>Represents requests for support for things such as documents, strategy discussions, and other internal or non-staffing requests.</description>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <summarizedField>Support_Request_Preparation__c.Hours__c</summarizedField>
        <summaryForeignKey>Support_Request_Preparation__c.Sales_Support_Request__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Support Requests</relationshipLabel>
        <relationshipName>Sales_Support_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_Completion_Date__c</fullName>
        <label>Requested Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Dossier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Representative Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Hypothesis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Map</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VITO Letter</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Support Request</label>
    <nameField>
        <displayFormat>SSR-{00000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Support Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Support_Request_Preparation__c.object
<CustomObject>
    <fields>
        <fullName>End__c</fullName>
        <label>End</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Support_Request__c</fullName>
        <label>Sales Support Request</label>
        <referenceTo>Sales_Support_Request__c</referenceTo>
        <relationshipLabel>Preparations</relationshipLabel>
        <relationshipName>Preparations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Who__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Support_Preparations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Preparation</label>
    <nameField>
        <label>Preparation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preparations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestSupportRequestPreparationController.cls
@isTest(seeAllData=true)
public class TestSupportRequestPreparationController{

    static testMethod void validateController() {
        //create an opportunity
        Opportunity o = new Opportunity(SWOT_Strengths__c='S Value',
                                        SWOT_Weaknesses__c='W Value',
                                        SWOT_Opportunities__c = 'O Value',
                                        SWOT_Threats__c = 'T Value',
                                        SWOT_Strategy_SO__c = 'SO Value',
                                        SWOT_Strategy_ST__c = 'ST Value',
                                        SWOT_Strategy_WO__c = 'WO Value',
                                        SWOT_Strategy_WT__c = 'WT Value',
                                        Name = 'Test SWOT Opportunity',
                                        StageName = 'Qualified',
                                        CloseDate = Date.today(),
                                        Premium_In_Scope__c = 1000,
                                        Amount=100   );
    
        insert o;
        

        Sales_Support_Request__c suppRequest = new Sales_Support_Request__c(Requested_Completion_Date__c = Date.today().addDays(220),
                                                                           Type__c='Dossier',
                                                                           Opportunity__c = o.Id);
        
        insert suppRequest;

        
        Support_Request_Preparation__c prep = new Support_Request_Preparation__c(Name = 'Prep test 1',
                                              Sales_Support_Request__c = suppRequest.Id,
                                              Who__c = UserInfo.getUserId(),
                                              Start__c = Date.today(),
                                              End__c = Date.today(),
                                              Hours__c = 4
                                              );
        
        insert prep;

       
        ApexPages.StandardController controller = new ApexPages.StandardController(prep);
 
        //put in ID so the controller has data
        ApexPages.currentPage().getParameters().put('id', prep.Id);
        SupportRequestPreparationController theExistingController = new SupportRequestPreparationController (controller);

        ApexPages.currentPage().getParameters().put('RequestID', suppRequest.Id);

        SupportRequestPreparationController theExistingControllerA = new SupportRequestPreparationController (controller);
        
        theExistingController.save();

        

        
    }
}