src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Premium_In_Scope__c</fullName>
        <inlineHelpText>This should be the deal premium in scope or the incremental DWP Adjustment. Used in conjunction with Price Rules to calculate the price for certain Products.</inlineHelpText>
        <label>Premium In Scope</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RFI_Approval_SC__c</fullName>
        <label>RFI Approval - SC</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFI_Approval_SD__c</fullName>
        <label>RFI Approval - SD</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFP_Approval_SC__c</fullName>
        <label>RFP Approval - SC</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFP_Approval_SD__c</fullName>
        <label>RFP Approval - SD</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>AMER</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Services_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Services Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesTaDV</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestRFIRFPApprovalHandler.cls
@isTest(seeAllData = true)
public class TestRFIRFPApprovalHandler 
{
    static testmethod void ApproversTestEmea()
    {   
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testingser', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standusertestha@testorg.com');
        insert u;
        
                
        opportunity opp = new opportunity (StageName = 'Prospecting', CloseDate = system.today(),
                                           Name='testopp', Amount=500, Region__c ='EMEA', Services_Director__c = u.id,
                                           Premium_In_Scope__c = 100,RFI_Approval_Sd__c = 'Approved',RFi_Approval_Sc__c = 'Approved',
                                           RFp_Approval_Sd__c = 'Approved',RFp_Approval_SC__c = 'Approved');             
                                          
        insert opp; 
        
    
        opp.RFI_Approval_SC__c = 'denied'; 
        opp.RFI_Approval_SD__c = 'denied';
        opp.RFP_Approval_SC__c = 'Denied';
        opp.RFP_Approval_SD__c = 'denied';  
        update opp;
          
     } 
    
     static testmethod void ApproversTestAmer()
     {   
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testingser', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standusertestha1@testorg.com');
        insert u;
        
                
        opportunity opp = new opportunity (StageName = 'Prospecting', CloseDate = system.today(),
                                           Name='testopp', Amount=500, Region__c ='Amer', Services_Director__c = u.id,
                                           Premium_In_Scope__c = 100,RFI_Approval_Sd__c = 'Approved',RFi_Approval_Sc__c = 'Approved',
                                           RFp_Approval_Sd__c = 'Approved',RFp_Approval_SC__c = 'Approved');             
                                          
        insert opp; 
        
    
        opp.RFI_Approval_SC__c = 'denied'; 
        opp.RFI_Approval_SD__c = 'denied';
        opp.RFP_Approval_SC__c = 'Denied';
        opp.RFP_Approval_SD__c = 'denied';  
        update opp;
          
     } 
    
    static testmethod void ApproversTestApac()
    {   
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testingser', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standusertestha2@testorg.com');
        insert u;
        
                
        opportunity opp = new opportunity (StageName = 'Prospecting', CloseDate = system.today(),
                                           Name='testopp', Amount=500, Region__c ='APAC', Services_Director__c = u.id,
                                           Premium_In_Scope__c = 100,RFI_Approval_Sd__c = 'Approved',RFi_Approval_Sc__c = 'Approved',
                                           RFp_Approval_Sd__c = 'Approved',RFp_Approval_SC__c = 'Approved');             
                                          
        insert opp; 
        
    
        opp.RFI_Approval_SC__c = 'denied'; 
        opp.RFI_Approval_SD__c = 'denied';
        opp.RFP_Approval_SC__c = 'Denied';
        opp.RFP_Approval_SD__c = 'denied';  
        update opp;
          
     }      
}