src/objects/Possible_Date__c.object
<CustomObject>
    <fields>
        <fullName>Date_is_Flexible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Date is Flexible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <label>Event Hours</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Resource_Request__c</fullName>
        <label>Resource Request</label>
        <referenceTo>ResourceRequest__c</referenceTo>
        <relationshipLabel>Possible Dates</relationshipLabel>
        <relationshipName>Possible_Dates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Possible</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Possible Date</label>
    <nameField>
        <label>Possible Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Possible Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ResourceRequest__c.object
<CustomObject>
    <description>A request for resources to staff an event.</description>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <description>Totals Hours in front of the customer</description>
        <label>Event Hours</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FeedAnnouncementID__c</fullName>
        <description>Stores the ID of the feed post to the group accouncement.</description>
        <label>FeedAnnouncementID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fully Staffed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revoked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Resource Request</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ResourceRequestDateController.cls
public with sharing class ResourceRequestDateController {

    public Possible_Date__c possibleDate{ get; set;}
    public Possible_Date__c possibleDateOriginal{ get; set;}
    public ResourceRequest__c resourceRequest { get; set;}


    public ResourceRequestDateController(ApexPages.StandardController controller) {
        String requestID = ApexPages.currentPage().getParameters().get('ResReqID');
        if(requestID != null)
        {  //it is a new role, so let's set it up accordingly
            possibleDate = new Possible_Date__c();
                
            resourceRequest = [SELECT Id, FeedAnnouncementID__c from ResourceRequest__c
                                    WHERE Id = :requestID  LIMIT 1];
                
            possibleDate.Resource_Request__c = resourceRequest.Id ;
        }
        else
        { // it is an existing role, so just look it up from the ID
             possibleDate = [SELECT Id, Start_Date__c, End_Date__c, Status__c, Note__c,Event_Hours__c,Date_is_Flexible__c, Resource_Request__c FROM Possible_Date__c
                   WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
              
           resourceRequest = [SELECT Id, FeedAnnouncementID__c from ResourceRequest__c
                                    WHERE Id = :possibleDate.Resource_Request__c LIMIT 1];
        }
        possibleDateOriginal = possibleDate.clone();
    }
    
   public PageReference save() {
   
       try{
     
          upsert possibleDate;
       } catch(DMLException e){
//           ApexPages.Message msg = new ApexPages.Message(Apexpages.Severity.ERROR, e.getdmlMessage(0) );
//           ApexPages.addMessage(msg);
           return null;
       }        
        //update the feed of the request with the information
        if(possibleDateOriginal.Start_Date__c == null) //is new possible date
        {
                //if the request is open, then we should announce the added date
            if(resourceRequest.FeedAnnouncementID__c != null)
            {
                FeedComment fcomment = new FeedComment();
                fcomment.FeedItemId = resourceRequest.FeedAnnouncementID__c; 
                fcomment.CommentBody = 'A new date has been added to the request.';
                insert fcomment;
                
            }
        }
        else // is old role
        {
            if(resourceRequest.FeedAnnouncementID__c != null)
            {
                FeedComment fcomment = new FeedComment();
                fcomment.FeedItemId = resourceRequest.FeedAnnouncementID__c; 
                fcomment.CommentBody = 'A date has been updated on the request.';
                insert fcomment;
            }
        }
        //return to page for resource request
        PageReference reqPage = new ApexPages.StandardController(resourceRequest).view();
        reqPage.setRedirect(true);
        return reqPage ;
    }
    
    

}