src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestProjectListController.cls
@isTest(seeAllData=false)
private class TestProjectListController {

    static testMethod void validateController() {
   

       Project__c newProject = new Project__c(Name='New Project',Status__c = 'Active',Description__c='Description');
       insert newProject;


       ProjectListController controller = new ProjectListController();
       
       System.assertEquals(controller.theProjects.size(), 1);
       
       controller.status = 'Inactive';
       controller.reloadPage();
       System.assertEquals(controller.theProjects.size(), 0);

       controller.status = 'All';
       controller.reloadPage();
       System.assertEquals(controller.theProjects.size(), 1);
       
       ProjectListController.deleteProject(newProject.Id);
       controller.reloadPage();
       System.assertEquals(controller.theProjects.size(), 0);
       
   
   }
   
}