src/objects/Project_Date_Range__c.object
<CustomObject>
    <fields>
        <fullName>End__c</fullName>
        <label>End</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Participant__c</fullName>
        <label>Project Participant</label>
        <referenceTo>Project_Participant__c</referenceTo>
        <relationshipLabel>Date Ranges</relationshipLabel>
        <relationshipName>Date_Ranges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Date Range</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Range ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Date Ranges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Participant__c.object
<CustomObject>
    <label>Project Participant</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectParticipantDateRangeController.cls
public with sharing class ProjectParticipantDateRangeController {

    public Project_Date_Range__c dateRange{get;set;}
    public Project_Participant__c participant{get;set;}


    public ProjectParticipantDateRangeController(ApexPages.StandardController controller) {

        String partId = ApexPages.currentPage().getParameters().get('ProjectParticipantID');
        if(partId != null)
        {//it is a new commitment, so let's set it up accordingly
            dateRange = new Project_Date_Range__c();
                
            participant = [SELECT Id from Project_Participant__c
                                        WHERE Id = :partId LIMIT 1];
                    
            dateRange.Project_Participant__c = participant.Id ;        
        }
        else
        { //it already exists, so look it up from the ID
              dateRange = [SELECT Id,  Start__c, End__c, Note__c, Project_Participant__c
                                     FROM Project_Date_Range__c
                                     WHERE Id=:ApexPages.currentPage().getParameters().get('id')];

              participant = [SELECT Id from  Project_Participant__c
                                        WHERE Id = :dateRange.Project_Participant__c LIMIT 1];
        }

    }

   public PageReference save() {
        
       try{
          upsert dateRange;
       } catch(DMLException e){
//           ApexPages.Message msg = new ApexPages.Message(Apexpages.Severity.ERROR, e.getdmlMessage(0) );
//           ApexPages.addMessage(msg);
           return null;
       }     
         
      //need to recalc event hours so save salesEvent now
       update participant;
  
        //return to page for the event
       PageReference reqPage = new ApexPages.StandardController(participant).view();
        reqPage.setRedirect(true);
        return reqPage ;
   }
}