src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Event__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <label>Event Hours</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Events</relationshipLabel>
        <relationshipName>Project_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Tentative</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Event_Possible_Date__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <label>Event Hours</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Event__c</fullName>
        <label>Project Event</label>
        <referenceTo>Project_Event__c</referenceTo>
        <relationshipLabel>Possible Dates</relationshipLabel>
        <relationshipName>Possible_Dates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Possible</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Possible Date</label>
    <nameField>
        <label>Possible Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Possible Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Participant__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <label>Event Hours (Partial)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Event__c</fullName>
        <label>Project Event</label>
        <referenceTo>Project_Event__c</referenceTo>
        <relationshipLabel>Project Participants</relationshipLabel>
        <relationshipName>Project_Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Who__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Participant</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Preparation__c.object
<CustomObject>
    <fields>
        <fullName>End__c</fullName>
        <label>End</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Event__c</fullName>
        <label>Project Event</label>
        <referenceTo>Project_Event__c</referenceTo>
        <relationshipLabel>Preparations</relationshipLabel>
        <relationshipName>Preparations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Who__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Preparations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Preparation</label>
    <nameField>
        <label>Preparation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preparations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestProjectEventController.cls
@isTest(seeAllData=true)
private class TestProjectEventController {

static testMethod void validateController() {
        
        Project__c proj = new Project__c(Name='Test Project',
                                      Status__c='Active',
                                      Description__c='Description');
        
        insert proj;        
        
        Project_Event__c projEvent = new Project_Event__c(Name='Test Project',
                                              Status__c='Tentative',
                                              Project__c = proj.Id);
        
        insert projEvent;
        
        
        Project_Event_Possible_Date__c pDate = new Project_Event_Possible_Date__c (Name = 'Possible date test 1',
                                              Project_Event__c = projEvent.Id,
                                              Event_Hours__c = 5,
                                              Start_Date__c = Date.today().addDays(-3),
                                              End_Date__c = Date.today().addDays(-2)
                                              );
        
        insert pDate ;
        
         Project_Participant__c participant = new Project_Participant__c(Name = 'Customer Commitment Test 1',
                                                                       Project_Event__c = projEvent.Id,
                                                                       Who__c = UserInfo.getUserId()
                                                                      );
                                                                      
        insert participant ;        
        
        Project_Preparation__c prep = new Project_Preparation__c(Name = 'Prep test 1',
                                              Project_Event__c = projEvent.Id,
                                              Who__c = UserInfo.getUserId(),
                                              Start__c = Date.today().addDays(3),
                                              End__c = Date.today().addDays(4),
                                              Hours__c = 4
                                              
                                              );
        
        insert prep;
        
        //SalesEventController
        ApexPages.StandardController controller = new ApexPages.StandardController(projEvent);
        //put in ID so the controller has data
        ApexPages.currentPage().getParameters().put('id', projEvent.Id);
        ProjectEventController theExistingController = new ProjectEventController (controller);

        
        
        //reloadEvent
        
        theExistingController.thisEvent.Status__c = 'Canceled';        
        //cancel
        //
        theExistingController.reloadEvent();
        //save
//        theExistingController.save();

        System.assertEquals(theExistingController.thisEvent.Status__c , 'Tentative');
        //getCustomerCommitmentsList
        System.assertEquals(theExistingController.getProjectParticipantsList().size(), 1);
        //getPreparationsList
        System.assertEquals(theExistingController.getProjectPreparationsList().size(), 1);

        //getAllPossibleDatesList
        System.assertEquals(theExistingController.getAllPossibleDatesList().size(), 1);

        //static selectDate(String dateID, String eventID)
        ProjectEventController.selectDate('' + pDate.Id, '' + theExistingController.thisEvent.Id);
        
        //static requestReview(String eventID)
        ProjectEventController.requestReview(theExistingController.thisEvent.Id,'This is a test message');

        //static deleteCommitment(String commitID, String eventID)
        ProjectEventController.deleteParticipant('' + participant.Id, '' + theExistingController.thisEvent.Id);
        
        //static deletePreparation(String prepID, String eventID)
        ProjectEventController.deletePreparation('' + prep.Id, '' + theExistingController.thisEvent.Id);

        
        theExistingController.reloadEvent();
        System.assertEquals(theExistingController.thisEvent.Status__c , 'Confirmed');
        System.assertEquals(theExistingController.getProjectPreparationsList().size(), 0);
        System.assertEquals(theExistingController.getAllPossibleDatesList().size(), 1);


       
        

//        System.assertEquals('/apex/SWOT', nextPage);
       
    }
}