src/objects/Project_Date_Range__c.object
<CustomObject>
    <fields>
        <fullName>End__c</fullName>
        <label>End</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Participant__c</fullName>
        <label>Project Participant</label>
        <referenceTo>Project_Participant__c</referenceTo>
        <relationshipLabel>Date Ranges</relationshipLabel>
        <relationshipName>Date_Ranges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Date Range</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Range ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Date Ranges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Event__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <label>Event Hours</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Participant__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <label>Event Hours (Partial)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Event__c</fullName>
        <label>Project Event</label>
        <referenceTo>Project_Event__c</referenceTo>
        <relationshipLabel>Project Participants</relationshipLabel>
        <relationshipName>Project_Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Who__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Participant</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectParticipantController.cls
public with sharing class ProjectParticipantController {

   public Project_Participant__c participant{get;set;}
    public Project_Participant__c participantOriginal {get;set;}
    public Project_Event__c projectEvent{get;set;}
    public Boolean isNew {get;set;}

    public ProjectParticipantController(ApexPages.StandardController controller) {
     //let's set the resource request on the object here
        //let's see if it is already set...if not, let's pull it from the request
        isNew = false;
        String projectEventID= ApexPages.currentPage().getParameters().get('ProjectEventID');
        if(projectEventID!= null)
        {//it is a new participant, so let's set it up accordingly
            isNew = true;
            participant= new Project_Participant__c();
                
            projectEvent = [SELECT Id from Project_Event__c
                                        WHERE Id = :projectEventID LIMIT 1];
                    
            participant.Project_Event__c = projectEvent.Id ;
            //let's default it the current user
            participant.Who__c = UserInfo.getUserId();
        
        }
        else
        { //it already exists, so look it up from the ID
              participant = [SELECT Id, Name, Who__c, Description__c, Event_Hours__c, Project_Event__c,
                                      (SELECT Start__c, End__C, Note__C from Date_Ranges__r)
                                     FROM Project_Participant__c
                                     WHERE Id=:ApexPages.currentPage().getParameters().get('id')];

            projectEvent = [SELECT Id from Project_Event__c
                                        WHERE Id = :participant.Project_Event__c LIMIT 1];
        }
        participantOriginal = participant.clone(); // Copy
    }

 public List<Project_Date_Range__c> getAllDateRanges()
   {
       List<Project_Date_Range__c> drs = [SELECT Start__c, End__C, Note__C, Project_Participant__c from Project_Date_Range__c where Project_Participant__c = :participant.Id];
        return drs;
   }
    
        
   public PageReference save() {
        upsert participant;
        //return to page for resource request
  
      //need to recalc event hours so save projectEvent now
       update projectEvent;
  
       PageReference reqPage = new ApexPages.StandardController(projectEvent).view();
        reqPage.setRedirect(true);
        return reqPage ;
   }
    
    @RemoteAction
    public static String deleteDateRange(String rangeID, String commitID)
    {
       Project_Date_Range__c toDelete = [SELECT Id FROM Project_Date_Range__c where Id = :rangeID];
        if(toDelete != null)
        {
            delete toDelete;  

        }

        return 'success';
    }
}