src/objects/Project_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <label>Event Hours</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Tentative</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Event_Possible_Date__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Hours__c</fullName>
        <label>Event Hours</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Event__c</fullName>
        <label>Project Event</label>
        <referenceTo>Project_Event__c</referenceTo>
        <relationshipLabel>Possible Dates</relationshipLabel>
        <relationshipName>Possible_Dates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Possible</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Possible Date</label>
    <nameField>
        <label>Possible Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Possible Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectEventPossibleDateController.cls
public with sharing class ProjectEventPossibleDateController {

    public Project_Event_Possible_Date__c possibleDate{get;set;}
    public Project_Event_Possible_Date__c possibleDateOriginal {get;set;}
    public Project_Event__c projectEvent {get;set;}


    public ProjectEventPossibleDateController(ApexPages.StandardController controller) {
  //let's see if it is already set...if not, let's pull it from the event

        String projectEventID= ApexPages.currentPage().getParameters().get('ProjectEventID');
        if(projectEventID!= null)
        {//it is a new commitment, so let's set it up accordingly
            possibleDate= new Project_Event_Possible_Date__c();
                
            projectEvent = [SELECT Id from Project_Event__c
                                        WHERE Id = :projectEventID LIMIT 1];
                    
            possibleDate.Project_Event__c = projectEvent.Id ;        
        }
        else
        { //it already exists, so look it up from the ID
              possibleDate = [SELECT Id, Status__c, Start_Date__c, End_Date__c, Event_Hours__c, Note__c, Project_Event__c
                                     FROM Project_Event_Possible_Date__c
                                     WHERE Id=:ApexPages.currentPage().getParameters().get('id')];

            projectEvent = [SELECT Id from Project_Event__c
                                        WHERE Id = :possibleDate.Project_Event__c LIMIT 1];
        }
        possibleDateOriginal = possibleDate.clone(); // Copy
    }
    
  public PageReference save() {
       try{
     
          upsert possibleDate;
       } catch(DMLException e){
//           ApexPages.Message msg = new ApexPages.Message(Apexpages.Severity.ERROR, e.getdmlMessage(0) );
//           ApexPages.addMessage(msg);
           return null;
       }       
      //need to recalc event hours so save projectEvent now
       update projectEvent;
  
        //return to page for the event
       PageReference reqPage = new ApexPages.StandardController(projectEvent).view();
        reqPage.setRedirect(true);
        return reqPage ;
   }
}