src/objects/PSA_Card_Transaction__c.object
<CustomObject>
    <description>This object will contain the results of the BoA integration with Guidewire for handoff of corporate card transaction data.  The table below describes each data element:</description>
    <fields>
        <fullName>PSA_Amount_in_Original_Currency__c</fullName>
        <description>The amount of the transaction, in terms of the OriginalCurrencyCode. This will be used to set the expense amount.

Note: If the transaction is brought in by the integration as a debit, this will be a negative value.</description>
        <label>Amount in Original Currency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSA_Charge_Type__c</fullName>
        <label>Charge Type</label>
        <picklist>
            <picklistValues>
                <fullName>Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSA_Merchant_Country_Code__c</fullName>
        <description>For setting the expense description and incurred location info on the expense</description>
        <label>Merchant Country Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Merchant_Name__c</fullName>
        <description>For setting the expense description</description>
        <label>Merchant Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Salesforce user associated with the EmployeeId value.  For mapping of the transaction to a PSA user. Each PSA Card Transaction record will be given ownership to this user, so that with private sharing enabled, users won’t be able to see each others’ card transaction info.</description>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PSA_Card_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PSA Card Transaction</label>
    <nameField>
        <label>PSA Card Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSA Card Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PSA_Card_Transaction_Item__c.object
<CustomObject>
    <fields>
        <fullName>GW_Card_Reimbursement_Amount__c</fullName>
        <label>GW Card Reimbursement Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PSA_Amount_in_Original_Currency__c</fullName>
        <label>Amount in Original Currency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSA_Card_Transaction__c</fullName>
        <label>PSA Card Transaction</label>
        <referenceTo>PSA_Card_Transaction__c</referenceTo>
        <relationshipLabel>PSA Card Transaction Items</relationshipLabel>
        <relationshipName>PSA_Card_Transaction_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PSA_Charge_Type__c</fullName>
        <label>Charge Type</label>
        <picklist>
            <picklistValues>
                <fullName>Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PSA Card Transaction Item</label>
    <nameField>
        <displayFormat>PCT-{00000}</displayFormat>
        <label>PSA Card Transaction Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSA Card Transaction Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreditCardUnassignedPersonalTest.cls
@isTest(seeAllData=true)
public class CreditCardUnassignedPersonalTest 
{
    static testmethod void Unassigned()
    {
        Profile p = [SELECT Id FROM Profile WHERE Name='GW Standard Platform User'];
        
        User U = new User(Alias = 'stest', Email='testuser@testorg.com',EmailEncodingKey='UTF-8', 
                                   LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US', ProfileId = p.Id,
                                   TimeZoneSidKey='America/Los_Angeles', UserName='testhariuser@testorg.com');
        
        insert U;        
        
        PSA_Card_Transaction__c CardTrans= new PSA_Card_Transaction__c();
                CardTrans.Name = 'Test';
                CardTrans.PSA_Salesforce_User__c = u.id;
                CardTrans.PSA_Merchant_Name__c = 'AMFAM MADISON 6008';
                CardTrans.PSA_Amount_in_Original_Currency__c = 1000;
                CardTrans.PSA_Merchant_Country_Code__c = 'USA'; 
                CardTrans.PSA_Charge_Type__c ='Company';
      
                insert CardTrans; 
        
        CreditCardTransUnassigned.CardTransactions();
    } 
    
    static testmethod void Personal()
    {
        Profile p = [SELECT Id FROM Profile WHERE Name='GW Standard Platform User'];
        
        User U = new User(Alias = 'stest', Email='testuser@testorg.com',EmailEncodingKey='UTF-8', 
                                   LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US', ProfileId = p.Id,
                                   TimeZoneSidKey='America/Los_Angeles', UserName='testhari1user@testorg.com');
        
        insert U;        
        
        PSA_Card_Transaction__c CardTrans= new PSA_Card_Transaction__c();
                CardTrans.Name = 'Test1';
                CardTrans.PSA_Salesforce_User__c = u.id;
                CardTrans.PSA_Merchant_Name__c = 'AMFAM MADISON 6008';
                CardTrans.PSA_Amount_in_Original_Currency__c = 1000;
                CardTrans.PSA_Merchant_Country_Code__c = 'USA'; 
                CardTrans.CurrencyIsoCode ='USD';
                CardTrans.PSA_Charge_Type__c ='Itemized';
      
                insert CardTrans; 
        
        PSA_Card_Transaction_Item__c item = new PSA_Card_Transaction_Item__c();
               item.PSA_Card_Transaction__c = CardTrans.id;
               item.CurrencyIsoCode ='USD';
               item.PSA_Charge_Type__c ='Personal';
               item.PSA_Amount_in_Original_Currency__c = 200;
               item.GW_Card_Reimbursement_Amount__c = 100;
        
              insert item;
        
        PSA_Card_Transaction__c CardTrans1= new PSA_Card_Transaction__c();
                CardTrans1.Name = 'Test11';
                CardTrans1.PSA_Salesforce_User__c = u.id;
                CardTrans1.PSA_Merchant_Name__c = 'AMFAM MADISON 60081';
                CardTrans1.PSA_Amount_in_Original_Currency__c = 10001;
                CardTrans1.PSA_Merchant_Country_Code__c = 'USA'; 
                CardTrans1.PSA_Charge_Type__c ='Personal';
                CardTrans1.CurrencyIsoCode ='USD';
      
                insert CardTrans1; 
        
        CreditCardPersonal.CardTransactionItems();
    }
    
}