src/objects/PSA_Invoice_Summary_Line__c.object
<CustomObject>
    <description>Contains categorized subtotals of Billing Event Items so they can be presented on the invoice</description>
    <fields>
        <fullName>PSA_Summary_Line_Type__c</fullName>
        <description>Each option contains a valid category according to which billing event items will be subtotaled and displayed on an invoice</description>
        <inlineHelpText>Categories according to which billing event items will be subtotaled and displayed on an invoice</inlineHelpText>
        <label>Summary Line Type</label>
        <picklist>
            <picklistValues>
                <fullName>Billable Expenses Charge - As % of Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billable Expenses Charge - As Flat Amount per Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billable Expenses Charge - As Incurred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billable Expenses Charge - Fixed Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billable Expenses Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting Services Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Discount - Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holdback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holdback Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Credits</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice Summary Line</label>
    <nameField>
        <label>Summary Line Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Summary Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/psaInvoiceSummaryLineSortWrapper.cls
/****************************************************************************************
Name            : psaInvoiceSummaryLineSortWrapper
Author          : CLD Partners
Created Date    : April 22, 2015
Description     : Sorts Invoice Summary Lines by the Summary Line Type field
Revisions       : 4/22/15  - Initial version
				: 
******************************************************************************************/
global with sharing class psaInvoiceSummaryLineSortWrapper implements Comparable {
	public PSA_Invoice_Summary_Line__c invoiceSummaryLine;

	//Constructor
	public psaInvoiceSummaryLineSortWrapper(PSA_Invoice_Summary_Line__c invoiceSummaryLineIn) {
		invoiceSummaryLine = invoiceSummaryLineIn;
	}	

    // Compare Invoice Summary Lines based on the Invoice Summary Line Type.
    global Integer compareTo(Object compareTo) {
        // Cast argument to OpportunityWrapper
        psaInvoiceSummaryLineSortWrapper compareToInvoiceSummaryLine = (psaInvoiceSummaryLineSortWrapper)compareTo;
        
        // The return value of 0 indicates that both elements are equal.
        Integer returnValue = 0;
        if (invoiceSummaryLine.PSA_Summary_Line_Type__c > compareToInvoiceSummaryLine.invoiceSummaryLine.PSA_Summary_Line_Type__c) {
            // Set return value to a positive value.
            returnValue = 1;
        } else if (invoiceSummaryLine.PSA_Summary_Line_Type__c < compareToInvoiceSummaryLine.invoiceSummaryLine.PSA_Summary_Line_Type__c) {
            // Set return value to a negative value.
            returnValue = -1;
        }
        
        return returnValue;       
    }
}