src/objects/PSA_Billing_Stage__c.object
<CustomObject>
    <description>The PSA Billing Stage object will be accessed by the Invoice Application integration for updates needed to billing events, including Integration Status and invoice information.</description>
    <fields>
        <fullName>PSA_Billing_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Id of related Billing Event</description>
        <label>Billing Event</label>
        <referenceTo>pse__Billing_Event__c</referenceTo>
        <relationshipLabel>PSA Billing Stage</relationshipLabel>
        <relationshipName>PSA_Billing_Stage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_GW_Integration_Id__c</fullName>
        <description>Source Id used to uniquely identify the associated source system record</description>
        <label>GW Integration Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>PSA Billing Stage</label>
    <nameField>
        <displayFormat>BS-{00000}</displayFormat>
        <label>Billing Stage Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSA Billing Stage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSA_Expense_Stage__c.object
<CustomObject>
    <description>The PSA Expense Stage object will be accessed by the Accounting Application (Intacct) integration for updates needed to expense reports, including Reimbursement Status.</description>
    <fields>
        <fullName>PSA_Expense_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Id (record name) of the expense report to update (e.g., “ER-39843”). This is used for lookup of the expense report</description>
        <label>Expense Report</label>
        <referenceTo>pse__Expense_Report__c</referenceTo>
        <relationshipLabel>PSA Expense Stage</relationshipLabel>
        <relationshipName>PSA_Expense_Stage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_GW_Integration_Id__c</fullName>
        <description>Source Id used to uniquely identify the associated source system record</description>
        <label>GW Integration Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>PSA Expense Stage</label>
    <nameField>
        <displayFormat>ES-{00000}</displayFormat>
        <label>Expense Stage Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSA Expense Stage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSA_Integration_Log__c.object
<CustomObject>
    <description>Record of specific integration executions</description>
    <fields>
        <fullName>PSA_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to related assignment</description>
        <inlineHelpText>Look up to related assignment</inlineHelpText>
        <label>Assignment</label>
        <referenceTo>pse__Assignment__c</referenceTo>
        <relationshipLabel>PSA Integration Logs</relationshipLabel>
        <relationshipName>PSA_Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Billing_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for Integration Logging lookup</description>
        <inlineHelpText>Used for Integration Logging lookup</inlineHelpText>
        <label>Billing Event</label>
        <referenceTo>pse__Billing_Event__c</referenceTo>
        <relationshipLabel>PSA Integration Logs</relationshipLabel>
        <relationshipName>PSA_Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Debug_Message__c</fullName>
        <label>Debug Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PSA_Expense_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for Integration Logging lookup</description>
        <inlineHelpText>Used for Integration Logging lookup</inlineHelpText>
        <label>Expense Report</label>
        <referenceTo>pse__Expense_Report__c</referenceTo>
        <relationshipLabel>PSA Integration Logs</relationshipLabel>
        <relationshipName>PSA_Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_GW_Integration_Id__c</fullName>
        <description>Record identifier from a source system, not a PSA object id</description>
        <inlineHelpText>Record identifier from a source system, not a PSA object id</inlineHelpText>
        <label>GW Integration Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Integration_Type__c</fullName>
        <label>Integration Type</label>
        <picklist>
            <picklistValues>
                <fullName>Resource-New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource-Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource-LOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource-Transfer Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource-Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing-Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expense-Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time Off Request-New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time Off Request-Correction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSA_Log_Category__c</fullName>
        <label>Log Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Log_Type__c</fullName>
        <label>Log Type</label>
        <picklist>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSA_Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Reference_Id__c</fullName>
        <description>The id of the related staging record</description>
        <inlineHelpText>The id of the related staging record</inlineHelpText>
        <label>Reference Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for Integration Logging lookup</description>
        <inlineHelpText>Used for Integration Logging lookup</inlineHelpText>
        <label>Resource</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PSA Integration Logs</relationshipLabel>
        <relationshipName>PSA_Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Schedule_Exception__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Schedule exception for the time off request</description>
        <inlineHelpText>Schedule exception for the time off request</inlineHelpText>
        <label>Schedule Exception</label>
        <referenceTo>pse__Schedule_Exception__c</referenceTo>
        <relationshipLabel>PSA Integration Logs</relationshipLabel>
        <relationshipName>PSA_Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule</label>
        <referenceTo>pse__Schedule__c</referenceTo>
        <relationshipLabel>PSA Integration Logs</relationshipLabel>
        <relationshipName>PSA_Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PSA_Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PSA Integration Log</label>
    <nameField>
        <displayFormat>ILOG-{000000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSA Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSA_Resource_Stage__c.object
<CustomObject>
    <description>Staging object to hold new or updated resource-related information from an external system</description>
    <fields>
        <fullName>PSA_GW_Integration_Id__c</fullName>
        <inlineHelpText>Id from source system</inlineHelpText>
        <label>GW Integration Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>PSA Resource Stage</label>
    <nameField>
        <displayFormat>RSTG-{00000}</displayFormat>
        <label>Resource Stage Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSA Resource Stage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSA_Time_Off_Stage__c.object
<CustomObject>
    <description>Staging object to hold Time Off requests from and external system that will be used to update assignments, schedules, and timecards in PSA</description>
    <fields>
        <fullName>PSA_GW_Integration_Id__c</fullName>
        <label>GW Integration Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>PSA Time Off Stage</label>
    <nameField>
        <displayFormat>TOS-{00000}</displayFormat>
        <label>Time Off Stage Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSA Time Off Stage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PSA_Resource_Stage__c</fullName>
        <description>Used for Integration Logging</description>
        <inlineHelpText>Used for Integration Logging</inlineHelpText>
        <label>PSA Resource Stage</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/psaIntegrationUtils.cls
/****************************************************************************************
Name            : psaIntegrationUtils
Author          : CLD Partners
Created Date    : March 12, 2015
Description     : Contains methods to process Integrations, including logging errors
Revisions       : 3/12/15 - Initial version
				: 4/13/15 - Switched logic in the updateGWIds method to use nested for loops
******************************************************************************************/
public with sharing class psaIntegrationUtils {
	public static final String LOG_TYPE_ERROR = 'Error';
	public static final String LOG_TYPE_WARNING  = 'Warning';
	public static final String LOG_TYPE_INFORMATION  = 'Information';
	public static final String INTERGRATION_TYPE_NEW_RESOURCE  = 'Resource-New';
	public static final String INTERGRATION_TYPE_UPDATED_RESOURCE  = 'Resource-Update';
	public static final String INTERGRATION_TYPE_LOA  = 'Resource-LOA';
	public static final String INTERGRATION_TYPE_TERMINATION  = 'Resource-Termination';
	public static final String INTERGRATION_TYPE_NEW_TIME_OFF_REQUEST  = 'Time Off Request-New';
	public static final String INTERGRATION_TYPE_TIME_OFF_REQUEST_CORRECTION  = 'Time Off Request-Correction';
	public static final String INTERGRATION_TYPE_BILLING_UPDATE  = 'Billing-Update';
	public static final String INTERGRATION_TYPE_EXPENSE_UPDATE  = 'Expense-Update';
	public static final String INTERGRATION_TYPE_PROJECT_REVENUE  = 'Project Revenue';
	public static List<PSA_Integration_Log__c> integrationLogsToUpdate;

	public psaIntegrationUtils(){}

	public static void logDatabaseErrors(Database.Error[] errs, Boolean writeToIntegrationLog, String referenceId, 
			String integrationType, String logCategory, String gwIntegrationId, Id targetId) {
        
        for(Database.Error err : errs) {
            System.debug('The following error has occurred.');                    
            System.debug(err.getStatusCode() + ': ' + err.getMessage());
            System.debug('Fields that affected this error: ' + err.getFields());

	        if (writeToIntegrationLog) {
				//Write an entry to the Integration Log
				String logMessage = err.getStatusCode() + ': ' + err.getMessage();
				writeLogEntry(referenceId, logCategory, integrationType, 
					psaIntegrationUtils.LOG_TYPE_ERROR, logMessage.left(255), String.valueOf(err.getFields()), 
					gwIntegrationId, targetId);
	        }
        }
	}

	public static void logDatabaseErrors(Database.Error[] errs, Boolean writeToIntegrationLog, String referenceId, 
			String integrationType, String logCategory, Id targetId) {
        for(Database.Error err : errs) {
            System.debug('The following error has occurred.');                    
            System.debug(err.getStatusCode() + ': ' + err.getMessage());
            System.debug('Fields that affected this error: ' + err.getFields());

	        if (writeToIntegrationLog) {
				//Write an entry to the Integration Log
				String logMessage = err.getStatusCode() + ': ' + err.getMessage();
				writeLogEntry(referenceId, logCategory, integrationType, 
					psaIntegrationUtils.LOG_TYPE_ERROR, logMessage.left(255), String.valueOf(err.getFields()), 
					null, targetId);
	        }
        }
	}

	public static Boolean writeLogEntry(String referenceId, String logCategory, String integrationType, 
			String logType, String message, String debugMessage, String gwIntegrationId, Id targetId) {
		Boolean successFlag = true; //assume success
		PSA_Integration_Log__c integrationLog = new PSA_Integration_Log__c();
		integrationLog.PSA_Reference_Id__c = referenceId;
		integrationLog.PSA_Integration_Type__c = integrationType;
		integrationLog.PSA_Log_Type__c = logType;
		integrationLog.PSA_Log_Category__c = logCategory;
		integrationLog.PSA_Message__c = message;
		integrationLog.PSA_Debug_Message__c = debugMessage;
		integrationLog.PSA_GW_Integration_Id__c = gwIntegrationId;
		if (logCategory == 'Resource') {
			integrationLog.PSA_Resource__c = targetId;
		}
		if (logCategory == 'User') {
			integrationLog.PSA_User__c = targetId;
		}
		if (logCategory == 'Billing Event') {
			integrationLog.PSA_Billing_Event__c = targetId;
		}
		if (logCategory == 'Expense Report') {
			integrationLog.PSA_Expense_Report__c = targetId;
		}
		if (logCategory == 'Assignment') {
			integrationLog.PSA_Assignment__c = targetId;
		}
		if (logCategory == 'Schedule') {
			integrationLog.PSA_Schedule__c = targetId;
		}
		if (logCategory == 'Schedule Exception') {
			integrationLog.PSA_Schedule_Exception__c = targetId;
		}

		insert integrationLog;
		return successFlag;
	}

	public static void updateGWIds(String updateType) {
		integrationLogsToUpdate = new List<PSA_Integration_Log__c>();
		Set<String> integrationLogReferenceIds = new Set<String>();

		List<PSA_Integration_Log__c> integrationLogs = 
			[Select Id, PSA_Reference_Id__c, PSA_GW_Integration_Id__c, LastModifiedDate 
				From PSA_Integration_Log__c
				Where PSA_Reference_Id__c != null 
				And PSA_GW_Integration_Id__c = null
				Order By LastModifiedDate Desc
				LIMIT 25000
			];
		if (integrationLogs != null && integrationLogs.size() > 0) {
			for (PSA_Integration_Log__c integrationLog : integrationLogs) {
				integrationLogReferenceIds.add(integrationLog.PSA_Reference_Id__c);
			}
		
			if (updateType == 'Resource') {
				List<PSA_Resource_Stage__c> resourceStageList = 
					[Select Id, PSA_GW_Integration_Id__c
						From PSA_Resource_Stage__c
						Where Id In :integrationLogReferenceIds
					];
				for (PSA_Resource_Stage__c resourceStage : resourceStageList) {
					for (PSA_Integration_Log__c integrationLog : integrationLogs) {
						if (integrationLog.PSA_Reference_Id__c == resourceStage.Id) {
							setGWId(integrationLog, resourceStage.PSA_GW_Integration_Id__c);
							continue;
						}
					}
				}
			}

			if (updateType == 'Expense Report') {
				List<PSA_Expense_Stage__c> expenseStageList = 
					[Select Id, PSA_GW_Integration_Id__c
						From PSA_Expense_Stage__c
						Where Id In :integrationLogReferenceIds
					];
				for (PSA_Expense_Stage__c expenseStage : expenseStageList) {
					for (PSA_Integration_Log__c integrationLog : integrationLogs) {
						if (integrationLog.PSA_Reference_Id__c == expenseStage.Id) {
							setGWId(integrationLog, expenseStage.PSA_GW_Integration_Id__c);
							continue;
						}
					}
				}
			}

			if (updateType == 'Billing Event') {
				List<PSA_Billing_Stage__c> billingStageList = 
					[Select Id, PSA_GW_Integration_Id__c
						From PSA_Billing_Stage__c
						Where Id In :integrationLogReferenceIds
					];
				//System.debug('Billing Stage List: ' + billingStageList);

				for (PSA_Billing_Stage__c billingStage : billingStageList) {
					for (PSA_Integration_Log__c integrationLog : integrationLogs) {
						if (integrationLog.PSA_Reference_Id__c == billingStage.Id) {
							setGWId(integrationLog, billingStage.PSA_GW_Integration_Id__c);
							continue;
						}
					}
				}
			}

			if (updateType == 'Assignment') {
				List<PSA_Time_Off_Stage__c> timeOffStageList = 
					[Select Id, PSA_GW_Integration_Id__c
						From PSA_Time_Off_Stage__c
						Where Id In :integrationLogReferenceIds
					];
				for (PSA_Time_Off_Stage__c timeOffStage : timeOffStageList) {
					for (PSA_Integration_Log__c integrationLog : integrationLogs) {
						if (integrationLog.PSA_Reference_Id__c == timeOffStage.Id) {
							setGWId(integrationLog, timeOffStage.PSA_GW_Integration_Id__c);
							continue;
						}
					}
				}
			}

			if (integrationLogsToUpdate != null && integrationLogs.size() > 0) {
				update integrationLogsToUpdate;
			}
		}
	}

	private static void setGWId(PSA_Integration_Log__c integrationLog, String gwId) {
		integrationLog.PSA_GW_Integration_Id__c = gwId;
		integrationLogsToUpdate.add(integrationLog);
	}

    public static void disableASMTriggers(String enabled) {
        //disable timecard ASM triggers
        appirio_core__Config_Value__c[] tcsCoreValues = [
            select Id,
                   appirio_core__Value__c,
                   appirio_core__Config_Option__c
              from appirio_core__Config_Value__c
             where appirio_core__config_Option__r.appirio_core__Group_Key__c = 'asm-triggers'
               and (appirio_core__config_Option__r.name = 'handlebillingeventitemchange'
                or appirio_core__config_Option__r.name = 'handletransactionfortimecard'
                or appirio_core__config_Option__r.name = 'handletransactionformilestone'
                or appirio_core__config_Option__r.name = 'beforeMiscellaneousAdjustmentChange'
                or appirio_core__config_Option__r.name = 'beforeMilestoneChange'
                or appirio_core__config_Option__r.name = 'afterExpenseReportChange'
                or appirio_core__config_Option__r.name = 'handleExpenseLineChange'
                or appirio_core__config_Option__r.name = 'handleExpenseReportUpdate'
                or appirio_core__config_Option__r.name = 'updateExpenseReportForExpense'
                or appirio_core__config_Option__r.name = 'beforeBudgetChange'
                or appirio_core__config_Option__r.name = 'handleTransactionForBudget'
                or appirio_core__config_Option__r.name = 'handleactualsfortransaction'
                or appirio_core__config_Option__r.name = 'handleBillingEventChange')
            order by appirio_core__config_Option__r.name
            limit 13];

        if (tcsCoreValues != null && !tcsCoreValues.isEmpty())
        {
           
          tcsCoreValues[0].appirio_core__Value__c = enabled;
          tcsCoreValues[1].appirio_core__Value__c = enabled;
          tcsCoreValues[2].appirio_core__Value__c = enabled;
          tcsCoreValues[3].appirio_core__Value__c = enabled;
          tcsCoreValues[4].appirio_core__Value__c = enabled;
          tcsCoreValues[5].appirio_core__Value__c = enabled;
          tcsCoreValues[6].appirio_core__Value__c = enabled;
          tcsCoreValues[7].appirio_core__Value__c = enabled;
          tcsCoreValues[8].appirio_core__Value__c = enabled;
          tcsCoreValues[9].appirio_core__Value__c = enabled;
          tcsCoreValues[10].appirio_core__Value__c = enabled;
          tcsCoreValues[11].appirio_core__Value__c = enabled;
          tcsCoreValues[12].appirio_core__Value__c = enabled;
          update tcsCoreValues;
        }        
    }
}