src/objects/PSA_Project_Forecast__c.object
<CustomObject>
    <description>The central repository for calculated billing forecast information. Each record contains a summary of scheduled and forecast billings for a project and month, without regard to forecast category.</description>
    <fields>
        <fullName>PSA_For_Month_Ending__c</fullName>
        <description>Date representing the last day of the month to which the record relates</description>
        <formula>PSA_Time_Period__r.pse__End_Date__c</formula>
        <label>For Month Ending</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PSA_Forecast_Billings__c</fullName>
        <description>Roll-Up Summary of Forecast Billings from related detail items</description>
        <inlineHelpText>Sum of Forecast Billings from related Project Forecast Detail records</inlineHelpText>
        <label>Forecast Billings</label>
        <summarizedField>PSA_Project_Forecast_Detail__c.PSA_Forecast_Billings__c</summarizedField>
        <summaryFilterItems>
            <field>PSA_Project_Forecast_Detail__c.PSA_Include_in_Forecast__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>PSA_Project_Forecast_Detail__c.PSA_Project_Forecast__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PSA_Item_Key__c</fullName>
        <description>Unique key generated by the forecast calculation identifying the source of the calculated and/or summarized info, allowing the calculation process to find and update previously created records</description>
        <label>Item Key</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Project__c</fullName>
        <description>Project for the forecast record</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>PSA Project Forecasts</relationshipLabel>
        <relationshipName>PSA_Project_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PSA_Scheduled_Cost__c</fullName>
        <description>Sum of Scheduled Cost from Project Forecast Detail records with source of assignment or resource request</description>
        <inlineHelpText>Sum of Scheduled Cost from related Project Forecast Detail records with source of Assignment or Resource Request</inlineHelpText>
        <label>Scheduled Cost</label>
        <summarizedField>PSA_Project_Forecast_Detail__c.PSA_Scheduled_Cost__c</summarizedField>
        <summaryFilterItems>
            <field>PSA_Project_Forecast_Detail__c.PSA_Include_in_Forecast__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>PSA_Project_Forecast_Detail__c.PSA_Project_Forecast__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PSA_Scheduled_Days__c</fullName>
        <description>Roll-Up Summary of Scheduled Days from related detail records</description>
        <inlineHelpText>Sum of Scheduled Days from related Project Forecast Detail records, providing total days worked that are scheduled for the period</inlineHelpText>
        <label>Scheduled Days</label>
        <summarizedField>PSA_Project_Forecast_Detail__c.PSA_Scheduled_Days__c</summarizedField>
        <summaryFilterItems>
            <field>PSA_Project_Forecast_Detail__c.PSA_Include_in_Forecast__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>PSA_Project_Forecast_Detail__c.PSA_Project_Forecast__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PSA_Scheduled_Hours_Seasonal__c</fullName>
        <description>Summary of seasonally-adjusted scheduled hours from related resource requests and assignments</description>
        <inlineHelpText>Summary of seasonally-adjusted scheduled hours from related resource requests and assignments</inlineHelpText>
        <label>Scheduled Hours Seasonal</label>
        <summarizedField>PSA_Project_Forecast_Detail__c.PSA_Scheduled_Hours_Seasonal__c</summarizedField>
        <summaryFilterItems>
            <field>PSA_Project_Forecast_Detail__c.PSA_Include_in_Forecast__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>PSA_Project_Forecast_Detail__c.PSA_Project_Forecast__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PSA_Scheduled_Hours__c</fullName>
        <description>Sum of Scheduled Hours from any related Project Forecast Detail records with source of Assignment or Resource Request</description>
        <inlineHelpText>Sum of Scheduled Hours from any related Project Forecast Detail records with source of Assignment or Resource Request</inlineHelpText>
        <label>Scheduled Hours</label>
        <summarizedField>PSA_Project_Forecast_Detail__c.PSA_Scheduled_Hours__c</summarizedField>
        <summaryFilterItems>
            <field>PSA_Project_Forecast_Detail__c.PSA_Include_in_Forecast__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>PSA_Project_Forecast_Detail__c.PSA_Project_Forecast__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PSA_Scheduled_Time_Billings__c</fullName>
        <description>Roll-Up Summary of Scheduled Time Billings from related detail items with source of Assignment or Resource Request</description>
        <inlineHelpText>Sum of Scheduled Time Billings from related detail items with source of Assignment or Resource Request</inlineHelpText>
        <label>Scheduled Time Billings</label>
        <summarizedField>PSA_Project_Forecast_Detail__c.PSA_Scheduled_Time_Billings__c</summarizedField>
        <summaryFilterItems>
            <field>PSA_Project_Forecast_Detail__c.PSA_Include_in_Forecast__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>PSA_Project_Forecast_Detail__c.PSA_Project_Forecast__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>PSA Project Forecast</label>
    <nameField>
        <displayFormat>PF-{0000000}</displayFormat>
        <label>Project Forecast Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSA Project Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PSA_Project_Forecast_Detail__c.object
<CustomObject>
    <description>Provides detail level for rollup to monthly PSA Project Forecast records, with each record referencing an assigment, resource request, or sum of scheduled expense or fixed fee services billings or billing rule adjustments</description>
    <fields>
        <fullName>PSA_For_Month_Ending__c</fullName>
        <description>Date representing the last day of the month to which the record relates</description>
        <formula>PSA_Project_Forecast__r.PSA_For_Month_Ending__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>For Month Ending</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PSA_Forecast_Billings__c</fullName>
        <description>Scheduled Billings multiplied by Forecast Category Percent</description>
        <formula>PSA_Scheduled_Billings__c *  PSA_Forecast_Category_Percent__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Scheduled Billings multiplied by Forecast Category Percent</inlineHelpText>
        <label>Forecast Billings</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSA_Forecast_Category_Percent__c</fullName>
        <description>A percentage representing the confidence level associated with the Forecast Category value</description>
        <inlineHelpText>A percentage representing the confidence level associated with the Forecast Category value.  This is supplied from the percentages defined in PSA Forecast Settings.</inlineHelpText>
        <label>Forecast Category Percent</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PSA_Forecast_Category__c</fullName>
        <description>For weighting of calculated billings based on a confidence level percentage associated with each category. If the source record doesn’t have its own Forecast Category value, the value is supplied as the Project&apos;s Forecast Category.</description>
        <inlineHelpText>For weighting of calculated billings based on a confidence level percentage associated with each category. If the source record doesn’t have its own Forecast Category value, the value is supplied as the Project&apos;s Forecast Category.</inlineHelpText>
        <label>Forecast Category</label>
        <picklist>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pipeline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Committed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSA_Forecast_Source__c</fullName>
        <description>Description of the source of the forecast detail</description>
        <inlineHelpText>Description of the source of the forecast detail, for use in reporting</inlineHelpText>
        <label>Forecast Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Forecast_Type__c</fullName>
        <description>Specifies the type of record comprising the forecast detail source</description>
        <inlineHelpText>Specifies the type of record comprising the forecast detail source</inlineHelpText>
        <label>Forecast Type</label>
        <picklist>
            <picklistValues>
                <fullName>Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Fee Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services Adjustment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSA_Item_Key__c</fullName>
        <description>Unique key generated by the forecast calculation identifying the source of the calculated and/or summarized info, allowing the calculation process to find and update previously created records.</description>
        <label>Item Key</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Project_Forecast__c</fullName>
        <label>PSA Project Forecast</label>
        <referenceTo>PSA_Project_Forecast__c</referenceTo>
        <relationshipLabel>PSA Project Forecast Details</relationshipLabel>
        <relationshipName>PSA_Project_Forecast_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PSA_Scheduled_Cost__c</fullName>
        <description>Scheduled hours times cost rate for a related resource request or assignment (if applicable), and month</description>
        <inlineHelpText>Scheduled hours times cost rate for a related resource request or assignment (if applicable), and month</inlineHelpText>
        <label>Scheduled Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSA_Scheduled_Days__c</fullName>
        <description>Summarized Estimated Days value from Est vs Actuals records for related assignments or resource requests. Used in calculating forecast billings of Expenses as Flat Amount per Day.</description>
        <inlineHelpText>Summarized Estimated Days value from Est vs Actuals records for related assignments or resource requests. Used in calculating forecast billings of Expenses as Flat Amount per Day.</inlineHelpText>
        <label>Scheduled Days</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PSA_Scheduled_Hours_Seasonal__c</fullName>
        <description>Scheduled Hours * related Seasonality Factor, to provide hours adjusted by seasonal availability</description>
        <formula>IF(NOT(IsBlank(PSA_Seasonality_Factor__c)), PSA_Scheduled_Hours__c * PSA_Seasonality_Factor__c, PSA_Scheduled_Hours__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Scheduled Hours * related Seasonality Factor, to provide hours adjusted by seasonal availability</inlineHelpText>
        <label>Scheduled Hours Seasonal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PSA_Scheduled_Hours__c</fullName>
        <description>Scheduled hours for a related resource request or assignment (if applicable), and month</description>
        <inlineHelpText>Scheduled hours for a related resource request or assignment (if applicable), and month</inlineHelpText>
        <label>Scheduled Hours</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PSA_Scheduled_Time_Billings__c</fullName>
        <description>Sum of expected Billings from scheduled Assignments and Resource Requests</description>
        <inlineHelpText>Sum of scheduled billings for the period from a scheduled Assignment or Resource Request</inlineHelpText>
        <label>Scheduled Time Billings</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSA_Seasonality_Factor__c</fullName>
        <description>Obtained from the monthly Time Period related to the record, a percentage supplied by Guidewire to the time period representing an adjustment factor for scheduled hours based on history of resource time off, etc., to produce forecasts based on expected (as opposed to scheduled) hours</description>
        <inlineHelpText>For calculating seasonally-adjusted hours, costs, and time-related billings based on resource availability</inlineHelpText>
        <label>Seasonality Factor</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>PSA Project Forecast Detail</label>
    <nameField>
        <displayFormat>PFD-{0000000}</displayFormat>
        <label>PSA Project Forecast Detail Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSA Project Forecast Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GenerateBillingsForecastDetails.cls
//--------------------
// REST API to send Billing Forecast Details.
// Date: 8/20/2015
// Author: Rohit Koul
//--------------------

@RestResource(urlMapping='/creatBillingForecastDetails/*')
global class GenerateBillingsForecastDetails {
 
  // Post request to get data specific to start and end date.	
  @HttpPost 
  global static List<BillingForecastDetails> getForecastDetails(String sDate,String eDate) {
  	 Date startdate = Date.valueof(sDate);
  	 Date endDate = Date.valueof(eDate);  
  	 List<PSA_Project_Forecast_Detail__c> forecastDetailList = [Select PSA_Project_Forecast__r.PSA_Project__c,PSA_Project_Forecast__r.PSA_Project__r.PSA_Empire_Project_ID__c,PSA_Project_Forecast__r.PSA_For_Month_Ending__c,PSA_Project_Forecast__r.PSA_Project__r.pse__Account__r.Name,PSA_Project_Forecast__r.PSA_Project__r.pse__Account__r.Participant_id__c,PSA_Project_Forecast__r.PSA_Project__r.pse__End_Date__c,
			  	 PSA_Project_Forecast__r.PSA_Project__r.pse__Start_Date__c,PSA_Forecast_Billings__c,PSA_Forecast_Category__c,PSA_Forecast_Category_Percent__c,PSA_Forecast_Source__c,PSA_Forecast_Type__c,PSA_Scheduled_Days__c,PSA_Scheduled_Hours__c,PSA_Seasonality_Factor__c,CurrencyIsoCode, 
			  	 PSA_Item_Key__c,PSA_Project_Forecast__r.PSA_Project__r.pse__Practice__r.Name,PSA_Project_Forecast__r.PSA_Project__r.Name,PSA_Project_Forecast__r.PSA_Project__r.pse__Project_ID__c,PSA_Project_Forecast__r.PSA_Project__r.pse__Region__r.Name,PSA_Scheduled_Cost__c,PSA_Scheduled_Hours_Seasonal__c,PSA_Scheduled_Time_Billings__c,PSA_Project_Forecast__r.PSA_Project__r.pse__Billing_Type__c,PSA_Project_Forecast__r.PSA_Time_Period__r.Name,
			  	 PSA_Project_Forecast__c, p.Id From PSA_Project_Forecast_Detail__c p where PSA_Project_Forecast__r.PSA_Project__c != null and PSA_Project_Forecast__c != null and PSA_Project_Forecast__r.PSA_Include_in_Forecast__c = true and PSA_Project_Forecast__r.PSA_For_Month_Ending__c >=: startdate and PSA_Project_Forecast__r.PSA_For_Month_Ending__c <=: endDate];
     
     List<BillingForecastDetails> forecastList = new List<BillingForecastDetails>();
     
     Map<String,Decimal> currencyCodeConversionRateMap = GWUtilities.currencyISOcodeconversionRateMap();  
     
     for(PSA_Project_Forecast_Detail__c forecastDetailVar: forecastDetailList){
     
	   	BillingForecastDetails forecast = new BillingForecastDetails();
	    forecast.Account_Participant_ID = forecastDetailVar.PSA_Project_Forecast__r.PSA_Project__r.pse__Account__r.Participant_id__c;
	    forecast.Account_Name = forecastDetailVar.PSA_Project_Forecast__r.PSA_Project__r.pse__Account__r.Name;
	    forecast.End_Date = forecastDetailVar.PSA_Project_Forecast__r.PSA_Project__r.pse__End_Date__c;        
	    forecast.Forecast_Billings = forecastDetailVar.PSA_Forecast_Billings__c;
	    forecast.Forecast_Category = forecastDetailVar.PSA_Forecast_Category__c; 
	    forecast.Forecast_Category_Percent = forecastDetailVar.PSA_Forecast_Category_Percent__c;
	    forecast.Forecast_Source = forecastDetailVar.PSA_Forecast_Source__c;
	    forecast.Forecast_Type = forecastDetailVar.PSA_Forecast_Type__c;
	    forecast.For_Month_Ending = forecastDetailVar.PSA_Project_Forecast__r.PSA_For_Month_Ending__c;
	    forecast.Item_Key = forecastDetailVar.PSA_Item_Key__c;
	    forecast.Practice_Name = forecastDetailVar.PSA_Project_Forecast__r.PSA_Project__r.pse__Practice__r.Name; 
	    forecast.Project_Name = forecastDetailVar.PSA_Project_Forecast__r.PSA_Project__r.Name;
	    forecast.Project_ID = forecastDetailVar.PSA_Project_Forecast__r.PSA_Project__r.pse__Project_ID__c;
	    forecast.Region_Name = forecastDetailVar.PSA_Project_Forecast__r.PSA_Project__r.pse__Region__r.Name;
	    forecast.Scheduled_Cost = forecastDetailVar.PSA_Scheduled_Cost__c;
	    forecast.Scheduled_Days= forecastDetailVar.PSA_Scheduled_Days__c;
	    forecast.Scheduled_Hours=forecastDetailVar.PSA_Scheduled_Hours__c; 
	    forecast.Scheduled_Hours_Seasonal= forecastDetailVar.PSA_Scheduled_Hours_Seasonal__c;
	    forecast.Scheduled_Time_Billings = forecastDetailVar.PSA_Scheduled_Time_Billings__c;
	    if(forecastDetailVar.CurrencyIsoCode != null && currencyCodeConversionRateMap.get(forecastDetailVar.CurrencyIsoCode) != null && currencyCodeConversionRateMap.get(forecastDetailVar.CurrencyIsoCode) != 0){
	      forecast.Forecast_Billings_converted = (forecastDetailVar.PSA_Forecast_Billings__c/currencyCodeConversionRateMap.get(forecastDetailVar.CurrencyIsoCode)).setScale(2);
	      forecast.Scheduled_Cost_converted= (forecastDetailVar.PSA_Scheduled_Cost__c/currencyCodeConversionRateMap.get(forecastDetailVar.CurrencyIsoCode)).setScale(2);
	      forecast.Scheduled_Time_Billings_converted = (forecastDetailVar.PSA_Scheduled_Time_Billings__c/currencyCodeConversionRateMap.get(forecastDetailVar.CurrencyIsoCode)).setScale(2);
	      forecast.Conversion_Rate = currencyCodeConversionRateMap.get(forecastDetailVar.CurrencyIsoCode);
	    }
	    forecast.Seasonality_Factor = forecastDetailVar.PSA_Seasonality_Factor__c;
	    forecast.Services_Billing_Type = forecastDetailVar.PSA_Project_Forecast__r.PSA_Project__r.pse__Billing_Type__c;
	    forecast.Start_Date = forecastDetailVar.PSA_Project_Forecast__r.PSA_Project__r.pse__Start_Date__c;
	    forecast.Time_Period_Name = forecastDetailVar.PSA_Project_Forecast__r.PSA_Time_Period__r.Name;
	    forecast.Empire_Project_Id = forecastDetailVar.PSA_Project_Forecast__r.PSA_Project__r.PSA_Empire_Project_ID__c;
	    forecastList.add(forecast);
     }
	  return forecastList;
  }

  
  global class BillingForecastDetails{
    public string Account_Name{get; set;}
    public string Account_Participant_ID{get; set;}
    public date End_Date{get; set;}
    public decimal Forecast_Billings{get; set;}
    public decimal Forecast_Billings_converted{get; set;}
    public string Forecast_Category{get; set;}
    public decimal Forecast_Category_Percent{get; set;}
    public string Forecast_Source{get; set;}
    public string Forecast_Type{get; set;}
    public date For_Month_Ending{get; set;}
    public string Item_Key{get; set;}
    public string Practice_Name{get; set;}
    public string Project_Name{get; set;}
    public string Project_ID{get; set;}
    public string Region_Name{get; set;}
    public decimal Scheduled_Cost{get; set;}
    public decimal Scheduled_Cost_converted{get; set;}
    public decimal Scheduled_Days{get; set;}
    public decimal Scheduled_Hours{get; set;}
    public decimal Scheduled_Hours_Seasonal{get; set;}
    public decimal Scheduled_Time_Billings{get; set;}
    public decimal Scheduled_Time_Billings_converted{get; set;}
    public decimal Seasonality_Factor{get; set;}
    public string Services_Billing_Type{get; set;}
    public date Start_Date{get; set;}
    public string Time_Period_Name{get; set;}
    public string Empire_Project_Id{get; set;}
    public Decimal Conversion_Rate{get; set;}  
  }

}