src/objects/PSA_Card_Transaction__c.object
<CustomObject>
    <description>This object will contain the results of the BoA integration with Guidewire for handoff of corporate card transaction data.  The table below describes each data element:</description>
    <fields>
        <fullName>PSA_Amount_in_Billing_Currency__c</fullName>
        <description>Copied from same field in PSA Card Transaction Stage.  This represents the amount Bank of America expects to be repaid for the given transaction.</description>
        <inlineHelpText>Copied from same field in PSA Card Transaction Stage.  This represents the amount Bank of America expects to be repaid for the given transaction.</inlineHelpText>
        <label>Amount in Billing Currency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSA_Amount_in_Original_Currency__c</fullName>
        <description>The amount of the transaction, in terms of the OriginalCurrencyCode. This will be used to set the expense amount.

Note: If the transaction is brought in by the integration as a debit, this will be a negative value.</description>
        <label>Amount in Original Currency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSA_Charge_Type__c</fullName>
        <label>Charge Type</label>
        <picklist>
            <picklistValues>
                <fullName>Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSA_Expense_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When a transaction is converted to one or more PSA expenses, this will be updated to refer to the expense report to which the expense(s) were added.  

A single transaction may result in multiple expense lines, so there is no lookup on this object to Expense.</description>
        <label>Expense Report</label>
        <referenceTo>pse__Expense_Report__c</referenceTo>
        <relationshipLabel>PSA Card Transactions</relationshipLabel>
        <relationshipName>PSA_Card_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Merchant_Name__c</fullName>
        <description>For setting the expense description</description>
        <label>Merchant Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Previously_Entered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Note, by selecting this box you are stating you have already processed this transaction.</description>
        <inlineHelpText>Note, by selecting this box you are stating you have already processed this transaction.</inlineHelpText>
        <label>Previously Entered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSA_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PSA Card Transactions</relationshipLabel>
        <relationshipName>PSA_Card_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Salesforce user associated with the EmployeeId value.  For mapping of the transaction to a PSA user. Each PSA Card Transaction record will be given ownership to this user, so that with private sharing enabled, users won’t be able to see each others’ card transaction info.</description>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PSA_Card_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Transaction_Date__c</fullName>
        <description>Represents the date that the transaction took place. This will be used to set the incurred date for any expenses created from the transaction.</description>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <label>PSA Card Transaction</label>
    <nameField>
        <label>PSA Card Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSA Card Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CreditCardTransUnassigned.cls
// Unassigned transactions with User Ids.

Global class CreditCardTransUnassigned Implements Schedulable
{
  global void Execute(SchedulableContext sc)
  {
     CardTransactions();      
  }
    
  public static void CardTransactions()
  {

    Map<id, List<PSA_Card_Transaction__c>> ResourceTransMap = new Map<id, List<PSA_Card_Transaction__c>>();
    
    List<PSA_Card_Transaction__c> CardTransLst = [Select id,PSA_Expense_Report__c,PSA_Expense_Report__r.pse__Status__c, PSA_Salesforce_User__c,PSA_Salesforce_User__r.email,PSA_Resource__c,PSA_Resource__r.email,PSA_Resource__r.name, PSA_Merchant_Name__c, 
                                              PSA_Amount_in_Billing_Currency__c,PSA_Amount_in_Original_Currency__c,PSA_Transaction_Date__c
                                              from PSA_Card_Transaction__c where PSA_Salesforce_User__c != Null and (PSA_Expense_Report__c = Null or PSA_Expense_Report__r.pse__Status__c ='Draft') and PSA_Charge_Type__c != 'Personal' and PSA_Previously_Entered__c != true ];
    
    for(PSA_Card_Transaction__c card : CardTransLst)
    {
        if(ResourceTransMap.containsKey(card.PSA_Salesforce_User__c))
        {
           List<PSA_Card_Transaction__c> newTransLst = ResourceTransMap.get(card.PSA_Salesforce_User__c);
           newTransLst.add(card);
           ResourceTransMap.put(card.PSA_Salesforce_User__c, newTransLst);
        }
        else
        {
            ResourceTransMap.put(card.PSA_Salesforce_User__c, new List<PSA_Card_Transaction__c> {card}); 
        } 
    }
      
  Messaging.SingleEmailMessage[] emailMessageList = new Messaging.SingleEmailMessage[]{};
    
  for(Id UserId : ResourceTransMap.keySet())
  {
     Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
     
     integer length = ResourceTransMap.get(UserId).size();
      
      mail.setTargetObjectId(UserId);
      
      mail.setSaveAsActivity(false);   
      
    /*  string[] toAdd = new String[]{};
      toAdd.add('hyarapathineni@guidewire.com');
      //toAdd.add('NMcGinn@guidewire.com');      
      
      mail.setCCAddresses(toAdd);
    */
      
      mail.setSubject('FinancialForce Expense Transactions to be Reviewed');
      
           
      String Table = 'This is to inform you that you either have not submitted expense reports or credit card transactions have not been assigned to an expense report. Transactions are listed below for your reference, and you may login to FinancialForce to see your outstanding expense reports.';
                            
                             table=table+'<br>';
                             table=table+'<br>';
                             table =table+ '<u>Company Card Transactions</u>';
                             table=table+'<br>';
                             table=table+'<br>';
                             table=table + '<table border="0" ><tr><td align="center"><b><u>Transaction Date</u></b></td><td align="center"><b><u>Vendor Name</u></b></td><td align="center"><b><u>Amount in Original Currency</u></b></td><td align="center"><b><u>Amount in Billing Currency</u></b></td><td align="center"><b><u>Resource Name</u></b></td>';                                                            
                             for(integer i=0; i< length; i++)
                             {  
                             table=table+'<tr>';
                             table=table + '<td align="Justify">' + ResourceTransMap.get(UserId)[i].PSA_Transaction_Date__c +' </td>';
                             table=table + '<td align="Justify">' + ResourceTransMap.get(UserId)[i].PSA_Merchant_Name__c + '</td>';  
                             table=table + '<td align="center">' + ResourceTransMap.get(UserId)[i].PSA_Amount_in_Original_Currency__c +' </td>';
                             table=table + '<td align="center">' + ResourceTransMap.get(UserId)[i].PSA_Amount_in_Billing_Currency__c + '</td>'; 
                             table=table + '<td align="justify">' + ResourceTransMap.get(UserId)[i].PSA_Resource__r.name +' </td>';
                             table=table+'</tr>';
                             } 
                             table=table+'</table>';
                                          
       mail.setHtmlBody(table);
      
       emailMessageList.add(mail);  
  }
 Messaging.sendEmail(emailMessageList);
 }
}





/*

// Unassigned transactions with Resource Email ids.

public class CreditCardTransUnassigned
{
  public void CardTransactions()
  {
  
    Map<string, List<PSA_Card_Transaction__c>> ResourceTransMap = new Map<string, List<PSA_Card_Transaction__c>>();
    
    List<PSA_Card_Transaction__c> CardTransLst = [Select id,PSA_Expense_Report__c,PSA_Expense_Report__r.pse__Status__c, PSA_Resource__c,PSA_Resource__r.email,PSA_Resource__r.name, PSA_Merchant_Name__c, 
                                              PSA_Amount_in_Billing_Currency__c,PSA_Amount_in_Original_Currency__c,PSA_Transaction_Date__c
                                              from PSA_Card_Transaction__c where (PSA_Expense_Report__c = Null or PSA_Expense_Report__r.pse__Status__c ='Draft') ];
    
    for(PSA_Card_Transaction__c card : CardTransLst)
    {
        if(ResourceTransMap.containsKey(card.PSA_Resource__r.email))
        {
           List<PSA_Card_Transaction__c> newTransLst = ResourceTransMap.get(card.PSA_Resource__r.email);
           newTransLst.add(card);
           ResourceTransMap.put(card.PSA_Resource__r.email, newTransLst);
        }
        else
        {
            ResourceTransMap.put(card.PSA_Resource__r.email, new List<PSA_Card_Transaction__c> {card}); 
        } 
    }
      
  Messaging.SingleEmailMessage[] emailMessageList = new Messaging.SingleEmailMessage[]{};
    
  for(String ResEmail : ResourceTransMap.keySet())
  {
     Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
     
     integer length = ResourceTransMap.get(ResEmail).size();
     string[] toAdd = new String[]{};
     toAdd.add(ResEmail);      
      
      mail.setToAddresses(toAdd);
                      
      mail.setSubject('Unassigned Transactions');
      
      String Table = 'This is to inform you that you either have not submitted expense reports or credit card transactions that have not been assigned to an expense report. Transactions are listed below for your reference, and you may login to FinancialForce to see your outstanding expense reports.';
                            
                             table=table+'<br>';
                             table=table+'<br>';
                             table =table+ '<u>Company Card Transactions</u>';
                             table=table+'<br>';
                             table=table+'<br>';
                             table=table + '<table border="0" ><tr><td align="center"><b><u>Transaction Date</u></b></td><td align="center"><b><u>Vendor Name</u></b></td><td align="center"><b><u>Amount in Original Currency</u></b></td><td align="center"><b><u>Amount in Billing Currency</u></b></td><td align="center"><b><u>Resource Name</u></b></td>';                                                            
                             for(integer i=0; i< length; i++)
                             {  
                             table=table+'<tr>';
                             table=table + '<td align="Justify">' + ResourceTransMap.get(ResEmail)[i].PSA_Transaction_Date__c +' </td>';
                             table=table + '<td align="Justify">' + ResourceTransMap.get(ResEmail)[i].PSA_Merchant_Name__c + '</td>';  
                             table=table + '<td align="center">' + ResourceTransMap.get(ResEmail)[i].PSA_Amount_in_Original_Currency__c +' </td>';
                             table=table + '<td align="center">' + ResourceTransMap.get(ResEmail)[i].PSA_Amount_in_Billing_Currency__c + '</td>'; 
                             table=table + '<td align="justify">' + ResourceTransMap.get(ResEmail)[i].PSA_Resource__r.name +' </td>';
                             table=table+'</tr>';
                             } 
                             table=table+'</table>';
                                          
       mail.setHtmlBody(table);
      
       emailMessageList.add(mail);  
  }
 Messaging.sendEmail(emailMessageList);

 }
}
*/