src/objects/PSA_Card_Transaction__c.object
<CustomObject>
    <description>This object will contain the results of the BoA integration with Guidewire for handoff of corporate card transaction data.  The table below describes each data element:</description>
    <fields>
        <fullName>PSA_Amount_in_Billing_Currency__c</fullName>
        <description>Copied from same field in PSA Card Transaction Stage.  This represents the amount Bank of America expects to be repaid for the given transaction.</description>
        <inlineHelpText>Copied from same field in PSA Card Transaction Stage.  This represents the amount Bank of America expects to be repaid for the given transaction.</inlineHelpText>
        <label>Amount in Billing Currency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSA_Amount_in_Original_Currency__c</fullName>
        <description>The amount of the transaction, in terms of the OriginalCurrencyCode. This will be used to set the expense amount.

Note: If the transaction is brought in by the integration as a debit, this will be a negative value.</description>
        <label>Amount in Original Currency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSA_Charge_Type__c</fullName>
        <label>Charge Type</label>
        <picklist>
            <picklistValues>
                <fullName>Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSA_EmployeeId__c</fullName>
        <description>Employee Id provided by Bank of America - for lookup of the corresponding PSA Resource / Salesforce User</description>
        <label>EmployeeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Expense_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When a transaction is converted to one or more PSA expenses, this will be updated to refer to the expense report to which the expense(s) were added.  

A single transaction may result in multiple expense lines, so there is no lookup on this object to Expense.</description>
        <label>Expense Report</label>
        <referenceTo>pse__Expense_Report__c</referenceTo>
        <relationshipLabel>PSA Card Transactions</relationshipLabel>
        <relationshipName>PSA_Card_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Expense_Type__c</fullName>
        <label>PSA Expense Type</label>
        <picklist>
            <picklistValues>
                <fullName>Airfare - Domestic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Airfare - International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visas/Passport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corp Apartment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taxi/Train/Public Transit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parking/Tolls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gas for Rental Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Mileage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meals - Self - Breakfast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meals - Self - Lunch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meals - Self - Dinner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meals - GW Emp Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meals - With 3rd Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meals - Per Diem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertain - GW Emp only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertain - With 3rd Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telecom - Mobile (Cell)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telecom - Non Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency exch/bank fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excess Baggage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc Expense - T &amp; E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Laundry/Dry Cleaning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office Supplies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postage/Courier Cost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relocation Exp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tax Prep Cost for Addtl State(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tips/Gratuities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dept/Co Meetings &amp; Events</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSA_FX__c</fullName>
        <description>The exchange rate between the incurred currency and billing (resource) currency.  This will be applied to the expense’s user-supplied exchange rate, to override the system-provided exchange rate, in order to match the transaction.

Note: This assumes that the “billing currency” from the B of A transaction, which represents the card customer’s currency, will always match the PSA Resource currency of the cardholder.</description>
        <label>FX Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PSA_Incurred_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incurred Country</label>
        <referenceTo>pw_cc__CountryObject__c</referenceTo>
        <relationshipLabel>PSA Card Transactions</relationshipLabel>
        <relationshipName>PSA_Card_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Incurred_State_Province__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incurred State / Province</label>
        <referenceTo>pw_cc__State__c</referenceTo>
        <relationshipLabel>PSA Card Transactions</relationshipLabel>
        <relationshipName>PSA_Card_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Invalid_Transaction__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to indicate the transaction is invalid.</description>
        <inlineHelpText>Check to indicate the transaction is invalid.</inlineHelpText>
        <label>Invalid Transaction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSA_Merchant_Country_Code__c</fullName>
        <description>For setting the expense description and incurred location info on the expense</description>
        <label>Merchant Country Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Merchant_Name__c</fullName>
        <description>For setting the expense description</description>
        <label>Merchant Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Merchant_Postal_Code__c</fullName>
        <label>Merchant Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Merchant_State_Province__c</fullName>
        <description>For setting the expense description and incurred location info on the expense</description>
        <label>Merchant State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Operations_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Operations Review</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSA_Posting_Date__c</fullName>
        <description>Needed for informational purposes, but not for expense creation/processing</description>
        <label>Posting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PSA_Previously_Entered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Note, by selecting this box you are stating you have already processed this transaction.</description>
        <inlineHelpText>Note, by selecting this box you are stating you have already processed this transaction.</inlineHelpText>
        <label>Previously Entered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSA_Processor_Transaction_Id__c</fullName>
        <description>External, unique transaction Id provided by Bank of America for each transaction</description>
        <externalId>true</externalId>
        <label>Processor Transaction Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Resource_Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Resource Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSA_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PSA Card Transactions</relationshipLabel>
        <relationshipName>PSA_Card_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Salesforce user associated with the EmployeeId value.  For mapping of the transaction to a PSA user. Each PSA Card Transaction record will be given ownership to this user, so that with private sharing enabled, users won’t be able to see each others’ card transaction info.</description>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PSA_Card_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSA_Status__c</fullName>
        <description>The status of the transaction record regarding how it will be used.  Options include:
Unassigned (default)
Assigned
Discarded</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unassigned (default)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSA_Transaction_Date__c</fullName>
        <description>Represents the date that the transaction took place. This will be used to set the incurred date for any expenses created from the transaction.</description>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <label>PSA Card Transaction</label>
    <nameField>
        <label>PSA Card Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSA Card Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PSA_Card_Transaction_Item__c.object
<CustomObject>
    <fields>
        <fullName>PSA_Amount_in_Original_Currency__c</fullName>
        <label>Amount in Original Currency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PSA_Card_Transaction__c</fullName>
        <label>PSA Card Transaction</label>
        <referenceTo>PSA_Card_Transaction__c</referenceTo>
        <relationshipLabel>PSA Card Transaction Items</relationshipLabel>
        <relationshipName>PSA_Card_Transaction_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PSA_Charge_Type__c</fullName>
        <label>Charge Type</label>
        <picklist>
            <picklistValues>
                <fullName>Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSA_Expense_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Expense report this card transaction itemization is associated with</description>
        <inlineHelpText>Expense report this card transaction itemization is associated with</inlineHelpText>
        <label>Expense Report</label>
        <referenceTo>pse__Expense_Report__c</referenceTo>
        <relationshipLabel>PSA Card Transaction Items</relationshipLabel>
        <relationshipName>PSA_Card_Transaction_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PSA Card Transaction Item</label>
    <nameField>
        <displayFormat>PCT-{00000}</displayFormat>
        <label>PSA Card Transaction Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSA Card Transaction Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/psaExpenseMatchCardTransactionController.cls
/*********************************************************************************************** x
Name            : psaExpenseMatchCardTransactionController
Author          : CLD
Created Date    : July 2016

Usage           : Controller for the psaExpenseMatchCardTransaction page.
                : Allows for matching card transaction with specific expense report expenses
***********************************************************************************************/
public with sharing class psaExpenseMatchCardTransactionController
{
    // ----------------------------------------------------
    // - constructor
    // ----------------------------------------------------
    public psaExpenseMatchCardTransactionController(){}

    // ----------------------------------------------------
    // - standard controller constructor
    // ----------------------------------------------------
    public psaExpenseMatchCardTransactionController(ApexPages.StandardController stdController){}


    // ----------------------------------------------------
    // # Retrieves expense report, the pending expens report items, and pending card transactions for expense report resource.
    // # expenseReportId - String value of the expense report details to load
    // # returns mapped values for:
    // #                     expense report     - expenseReport with pending expense items ,
    // #                     card transactions  - pending cardTransactions for the resource
    // #
    // # Map<String, Object> rslt =  psaExpenseMatchCardTransactionController.initializeExpenseReportCardTransactions(expRptId);
    // ----------------------------------------------------
    @RemoteAction public static Map<String, Object> initializeExpenseReportCardTransactions(String expenseReportId)
    {
        if (String.isEmpty(expenseReportId))
        {
            return makeError('Please match transactions from an expesne report', 'initializeExpenseReportCardTransactions');
        }

        Map<String, Object> result = new Map<String, Object>();

        try
        {
            // load expense report and expense information

            // lookup exp report
            pse__Expense_Report__c[] ersById = [
                select Id,
                       Name,
                       pse__Billable__c,
                       pse__Resource__c,
                       pse__Resource__r.Name,
                       pse__First_Expense_Date__c,
                       pse__Resource__r.PSA_Home_Country__c,
                       pse__Status__c,
                       pse__Description__c
                  from pse__Expense_Report__c
                 where id = :expenseReportId
            ];

            if (ersById != null && ersById.size() > 0)
            {
               // verify report status is allowed
                Set<String> allowedStatuses = new Set<String>{
                    'Draft',
                    'Rejected'
                };

                // when not allowed, render error mesage
                if (!allowedStatuses.contains(ersById[0].pse__status__c))
                {
                    return makeError('Only Draft or Rejected expense reports can be matched!', 'expenseReportStatus');
                }
            }

            // lookup expenses and attachments
            // expenses (associated to non-previously entered card transactions)
            // and non-itemized expenses
            pse__Expense__c[] expenseLines = [
                select Id,
                        Name,

                        PSA_Card_Transaction__c,

                        PSA_Card_Transaction__r.PSA_Merchant_Name__c,
                        PSA_Card_Transaction__r.PSA_Merchant_State_Province__c,
                        PSA_Card_Transaction__r.PSA_Merchant_Country_Code__c,
                        PSA_Card_Transaction__r.CurrencyIsoCode,
                        PSA_Card_Transaction__r.PSA_Amount_in_Original_Currency__c,
                        PSA_Card_Transaction__r.PSA_Transaction_Date__c,
                        PSA_Card_Transaction__r.PSA_Posting_Date__c,

                        PSA_Card_Transaction__r.PSA_Previously_Entered__c,

                        PSA_Card_Transaction_Item__c,


                        pse__Expense_Report__c,
                        pse__Notes__c,
                        pse__Expense_Report__r.Name,
                        pse__Amount__c,

                        CurrencyIsoCode,
                        pse__Description__c,
                        pse__Expense_Date__c,
                        pse__Resource__c,
                        pse__Type__c,
                        pse__Billable__c,
                        pse__Status__c,
                        PSA_Receipt_Type__c,
                        PSA_Pre_Match_Amount__c,
                        OwnerId,

                        ( SELECT Id,  Name, BodyLength, ParentId FROM Attachments )

                   from pse__Expense__c
                  where pse__Expense_Report__c = :expenseReportId
                    and PSA_Card_Transaction__r.PSA_Previously_Entered__c <> true
                    and PSA_Card_Transaction_Item__c = null
            ];


            if (ersById != null && ersById.size() > 0)
            {
                pse__Expense_Report__c exrpt = ersById[0];
                result.put('expenseReport', exrpt);
                result.put('expenseLines', (expenseLines != null) ? expenseLines : new pse__Expense__c[]{});


                // lookup card transactions for resource associated to expense report
                String resourceId = exrpt.pse__Resource__c;
                Map<String, Object> transPayload = new Map<String, Object>();

                Map<String, Object> transResponse = lookupCardTransactions(exrpt.pse__Resource__c, JSON.serialize(transPayload));
                if (transResponse.containsKey('errorCode'))
                {
                    return transResponse;
                }
                else
                {
                    result.put('cardTransactions', transResponse);
                }

            }
            else
            {
                return makeError('Please match transactions from an expesne report', 'initializeExpenseReportCardTransactions');
            }

        }
        catch(Exception e)
        {
            return makeError(e.getMessage(), 'lookup-card-trans');
        }

        return result;

    }



    // store expense report info / resource in state....
    // then pass to the remote actions from page.....


    // ------------------------------------------------------------------------
    // # Retrieves card transactions for the user based on from/to date range
    // # jsonFilterFields : JSON serialized string of transaction fields to filter:
    // # psaResourceId - required string value for the expense report resource id
    //      - (example from Javascript:)
    //          var filterFields = {
    //                filterStartDate: '2016-01-01',
    //                  filterEndDate: '2017-01-01'
    //          }
    //
    //
    // Map<String, Object> rslt =  lookupCardTransactions.initializeExpenseReportCardTransactions(psaResourceId, JSON.serialize(new Map<String, Object>()));
    // ------------------------------------------------------------------------
    @RemoteAction public static Map<String, Object> lookupCardTransactions(String psaResourceId, String jsonFilterFields)
    {
        Map<String, Object> result = new Map<String, Object>();

        Map<String, Object> incomingJsonFilterFields = null;
        try {
            incomingJsonFilterFields = (Map<String, Object>)JSON.deserializeUntyped(jsonFilterFields);
        } catch (JSONException je) {
            return makeError(je.getMessage(), 'JSON_PARSER_ERROR');
        }
        try
        {
            String filterStartDate = null;
            if (incomingJsonFilterFields.containsKey('filterStartDate')) {
                filterStartDate = String.valueOf(incomingJsonFilterFields.get('filterStartDate'));
            }

            String filterEndDate = null;
            if (incomingJsonFilterFields.containsKey('filterEndDate')) {
                filterEndDate = String.valueOf(incomingJsonFilterFields.get('filterEndDate'));
            }


            // These are the columns were going to retrieve from the PSA_CARD_TRANSACTION
            // using the cusomized WHERE clause based on our filter
            String[] psaCardTransactionColumns = new String[]{
                  'Id',
                  'CurrencyIsoCode',
                  'Name',
                  'OwnerId',
                  'PSA_Amount_in_Original_Currency__c',
                  'PSA_Amount_in_Billing_Currency__c',
                  'PSA_EmployeeId__c',
                  'PSA_Expense_Type__c',
                  'PSA_FX__c',
                  'PSA_Expense_Report__c',
                  'PSA_Merchant_Country_Code__c',
                  'PSA_Merchant_Name__c',
                  'PSA_Merchant_Postal_Code__c',
                  'PSA_Merchant_State_Province__c',
                  'PSA_Posting_Date__c',
                  'PSA_Processor_Transaction_Id__c',
                  'PSA_Salesforce_User__c',
                  'PSA_Status__c',
                  'PSA_Incurred_Country__c',
                  'PSA_Incurred_State_Province__c',
                  'PSA_Charge_Type__c',
                  'PSA_Resource__c',
                  'PSA_Resource_Inactive__c',
                  'PSA_Previously_Entered__c',
                  'PSA_Invalid_Transaction__c',
                  'PSA_Operations_Review__c',
                  'PSA_Operations_Review_Reason__c',
                  'PSA_Operations_Review_Comments__c',
                  'PSA_Discard__c',
                  'PSA_Transaction_Date__c',
                  'PSA_Remaining_Transaction_Amount__c',
                  'PSA_Assigned_Itemized_Amount__c',
                  'PSA_Transaction_Id__c '
            };

            // generate the soql for retrieving card transactions
            String soql = '';
            soql += ' SELECT ' + String.join(psaCardTransactionColumns, ',') + ' ';

            //soql += ',   ( SELECT Id, ';
            //soql += '            Name, ';
            //soql += '            BodyLength, ';
            //soql += '            ParentId ';
            //soql += '       FROM Attachments ) ';

            soql += '   FROM PSA_Card_Transaction__c ';
            soql += '  WHERE PSA_Resource__c = \'' + psaResourceId + '\'';
            soql += '    AND PSA_Status__c <> \'Assigned\' ';
            soql += '    AND PSA_Operations_Review__c <> true ';
            soql += '    AND PSA_Previously_Entered__c <> true ';
            soql += '    AND PSA_Invalid_Transaction__c <> true ';
            soql += '    AND PSA_Discard__c <> true ';

// filter out itemized transactions....
            soql += '    AND PSA_Assigned_Itemized_Amount__c = 0 ';

            soql += '    AND PSA_Discard__c <> true ';
            soql += '    AND PSA_Charge_Type__c <> \'Personal\' ';


            if (String.isNotEmpty(filterStartDate) && filterStartDate.length() == 10)
            {
                soql += ' AND PSA_Transaction_Date__c >= ' + filterStartDate;
            }
            if (String.isNotEmpty(filterEndDate) && filterEndDate.length() == 10)
            {
                soql += ' AND PSA_Transaction_Date__c <= ' + filterEndDate;
            }

            // retrieve card transactions
            PSA_Card_Transaction__c[] userCardTransactions = Database.query(soql);

            result.put('records', userCardTransactions);
            result.put('size', userCardTransactions.size());

            return result;

        }
        catch(Exception e)
        {
            return makeError(e.getMessage(), 'lookup-card-trans');
        }
    }

    // ------------------------------------------------------------------------
    // # Matches expense items to card transactions
    // # jsonExpCardMatchFields : JSON serialized list of expense ids to card transactions ids to match
    //      - (example from Javascript:)
    //          var filterFields = [{
    //              { expenseId: 'abc123', cardTransactionId: '123abc' },
    //              { expenseId: 'def456', cardTransactionId: '456def' }
    //           ];

    // # jsonExpIdMatchToRemove : List of expense ids to remove.....

    // Map<String, Object> rslt =  lookupCardTransactions.matchExpenseCardTransactions(expRptId, JSON.serialize(new list<object>()));
    // ------------------------------------------------------------------------
    @RemoteAction public static Map<String, Object> matchExpenseCardTransactions(String expenseReportId,
                                                                                 String jsonExpCardMatchFields,
                                                                                 String jsonExpIdMatchToRemove)
    {
        Map<String, Object> result = new Map<String, Object>();


        // -----
        // PARSE expense ids for mappings to remove (clear card transaction expense lookup, set card trans status back to unassigned)
        Set<String> expIdsToRemove = new Set<String>();
        try {
            List<Object> expidObjList = (List<Object>) JSON.deserializeUntyped(jsonExpIdMatchToRemove);
            if (expidObjList != null && expidObjList.size() > 0)
            {
                for (Object objItem : expidObjList)
                {
                    String eid = String.valueOf(objItem);
                    expIdsToRemove.add(eid);
                }

                // now need to load expenses and card transactions to 'remove...'

            }
        } catch (JSONException je) {
            return makeError(je.getMessage(), 'JSON_PARSER_ERROR');
        }


        // PARSE New Mappings to create!

        // parsed mapping of expense id to card transaction id to "match"
        Set<String> expenseIds = new Set<String>();
        Set<String> cardTransIds = new Set<String>();

        // maintain mapping of card transaction to expense and expens to card transactions....
        Map<String, String> parsedExpenseIdToCardTrans = new Map<String, String>();
        Map<String, String> parsedCardTransToExpenseId = new Map<String, String>();
        try {
            List<Object> objList = (List<Object>)JSON.deserializeUntyped(jsonExpCardMatchFields);
            if (objList != null && objList.size() > 0)
            {
                for (Object obj : objList)
                {
                    Map<String, Object> objMap = (Map<String, Object>)obj;
                    if (objMap != null && objMap.containsKey('expenseId') && objMap.containsKey('cardTransactionId'))
                    {
                        String expenseId = String.valueOf(objMap.get('expenseId'));
                        String cardTransactionId = String.valueOf(objMap.get('cardTransactionId'));

                        if (String.isNotEmpty(expenseId) && String.isNotEmpty(cardTransactionId))
                        {
                            expenseIds.add(expenseId);
                            cardTransIds.add(cardTransactionId);

                            parsedExpenseIdToCardTrans.put(expenseId, cardTransactionId);

                            parsedCardTransToExpenseId.put(cardTransactionId, expenseId);
                        }
                    }
                }
            }

        } catch (JSONException je) {
            return makeError(je.getMessage(), 'JSON_PARSER_ERROR');
        }

        //
        Savepoint savePoint = Database.setSavepoint();

        try
        {
            // HANDLE REMOVING ANY EXISTING ASSOCIATIONS
            if (expIdsToRemove.size() > 0)
            {
                disassociateExpenseAndCardTrans(expIdsToRemove);
            }

            // Does matching...
            if (parsedExpenseIdToCardTrans != null && parsedExpenseIdToCardTrans.size() > 0 &&
                 expenseIds != null && expenseIds.size() > 0 &&
                 cardTransIds != null && cardTransIds.size() > 0)
            {

                //LOAD NEW ORIGINAL EXPENSE AMOUNT FIELD
                // --- PSA_Pre_Match_Amount__c ??
                // load expenses....
                Map<Id, pse__Expense__c> expenseItems = new Map<Id, pse__Expense__c>(
                    [
                    select id,
                           CurrencyIsoCode,
                           PSA_Card_Transaction__c,
                           psa_card_transaction_item__c,
                           pse__Amount__c,
                           pse__Expense_Date__c,
                           GW_Card_Reimbursement_Amount__c,
                           PSA_GW_Card__c,
                           PSA_Pre_Match_Amount__c
                    from pse__Expense__c
                    where id in :expenseIds]);

                // load card transactions...need to handle partial itemizations..
                Map<Id, PSA_Card_Transaction__c> cardTransactions = new Map<Id, PSA_Card_Transaction__c>();


                for (PSA_Card_Transaction__c ct : [
                        select Id,
                               CurrencyIsoCode,
                               PSA_Assigned_Itemized_Amount__c,
                               PSA_Transaction_Date__c,
                               PSA_Expense_Report__c,
                               PSA_Remaining_Transaction_Amount__c,
                               PSA_Amount_in_Original_Currency__c,
                               PSA_Amount_in_Billing_Currency__c,
                               PSA_Merchant_Name__c,
                               PSA_Merchant_State_Province__c,
                               PSA_Merchant_Country_Code__c,
                               PSA_Status__c
                        from PSA_Card_Transaction__c
                        where id = :cardTransIds
                    ])
                {
                    String expId = parsedCardTransToExpenseId.get(ct.id);

                    ct.PSA_Status__c = 'Assigned';

                    cardTransactions.put(ct.id, ct);
                }

                // create transaction items for partially itemized transactions!!!!

                // match em.....
                Map<Id, pse__Expense__c> expensesToUpdate =new Map<Id, pse__Expense__c>();
                PSA_Card_Transaction__c[] cardTransToUpdate = new PSA_Card_Transaction__c[]{};


                // ------------------------------------------------------------
                // ------------------------------------------------------------
                // !!!!! workaround vr rule forcing us to make 2 updates
                //        - one that updates the amounts
                //        - next update associates our card trans!

                Map<Id, String> expenseIdToCardTransactionId = new Map<Id, String>();

                Map<Id, pse__Expense__c> expenseIdToExpense = new Map<Id, pse__Expense__c>();


                for (String expId : expenseIds)
                {
                    pse__Expense__c expItem = expenseItems.get(expId);
                    if (expItem != null)
                    {
                        String cardTransId = parsedExpenseIdToCardTrans.get(expId);
                        if (cardTransId != null && cardTransactions.containsKey(cardTransId))
                        {
                            PSA_Card_Transaction__c cardTrans = cardTransactions.get(cardTransId);
                            cardTrans.PSA_Status__c = 'Assigned';

                            cardTransToUpdate.add(cardTrans); // collect for update

                            // collect for the 2nd expense item update
                            // for working around vr rule!
                            expenseIdToCardTransactionId.put(expItem.id, cardTransId);
                            // expItem.PSA_Card_Transaction__c = cardTrans.id;

                            // TODO: include more items that are needed to be set on the expense
                            expItem.GW_Card_Reimbursement_Amount__c = cardTrans.PSA_Amount_in_Billing_Currency__c;
                            expItem.PSA_GW_Card__c                  = true; // maybe this is needed???
                            expItem.CurrencyIsoCode                 = cardTrans.CurrencyIsoCode;
                            expItem.PSA_Card_Transaction__c         = null; // clear so we can update amounts...and get around validation rule!
                            expItem.pse__Amount__c                  = cardTrans.PSA_Amount_in_Billing_Currency__c;   // default (not itemized)
                            expItem.pse__Expense_Date__c            = cardTrans.PSA_Transaction_Date__c;
                            expItem.pse__Non_Reimbursible__c        = true; //  force the non-reimbursable checkbox to true if a Credit Card transaction is matched?

                            if (String.isEmpty(expItem.pse__Description__c)) {
                                expItem.pse__Description__c  = psaExpenseMatchCardTransactionController.buildCardTransactionDescription(cardTrans);
                            }

                            // collect for updating...
                            expensesToUpdate.put(expItem.id, expItem);
                        }
                    }
                }

                if (expensesToUpdate != null && expensesToUpdate.size() > 0)
                {
                    update expensesToUpdate.values();

                    // now we need update the expenses again, setting the card transaction!
                    for (pse__Expense__c exp : expensesToUpdate.values())
                    {
                        String cardId = expenseIdToCardTransactionId.get(exp.Id);
                        if (String.isNotEmpty(cardId))
                        {
                            exp.PSA_Card_Transaction__c = cardId;
                        }
                    }

                    update expensesToUpdate.values();

                }
                if (cardTransToUpdate != null && cardTransToUpdate.size() > 0)
                {
                    update cardTransToUpdate;
                }
            }

        }
        catch(Exception e)
        {
            if (savePoint != null)
            {
                Database.rollback(savePoint);
            }

            return makeError(e.getMessage(), 'DML_ERR');
        }


        return initializeExpenseReportCardTransactions(expenseReportId);
    }



    // --
    // - appends the cc description into the expense
    public static String buildCardTransactionDescription( PSA_Card_Transaction__c cardTransaction)
    {
        String rtn = '';
        if (cardTransaction != null)
        {
            //String expDescription = expense.pse__Description__c;
            //expDescription = expDescription == null ? '' : expDescription + '  ';
            if (String.isNotEmpty(cardTransaction.PSA_Merchant_Name__c))
            {
                rtn += cardTransaction.PSA_Merchant_Name__c + ' ';
            }
            if (String.isNotEmpty(cardTransaction.PSA_Merchant_State_Province__c))
            {
                rtn += cardTransaction.PSA_Merchant_State_Province__c  + ', ';
            }
            if (String.isNotEmpty(cardTransaction.PSA_Merchant_Country_Code__c))
            {
                rtn += cardTransaction.PSA_Merchant_Country_Code__c;
            }

            rtn = rtn.length() > 255 ? rtn.substring(0, 250) : rtn;


        }
        return rtn;

    }



    // ******8
    public static void disassociateExpenseAndCardTrans(Set<String> expenseIds)
    {
        if (expenseIds != null && expenseIds.size() > 0)
        {
// TODO... PULLBACK NEW ORIGINAL AMOUNT FIELD then evaluate and use it to revert EXPENSE AMOUNT....

            // load expenses, and gather card transactions to unassign
            Set<Id> cardTransIdsToUnassign = new Set<Id>();
            pse__Expense__c[] expsToDisassociate = new pse__Expense__c[]{};
            for (pse__Expense__c e : [
                select id,
                       PSA_Card_Transaction__c,
                       psa_card_transaction_item__c,
                       pse__Amount__c,
                       pse__Expense_Date__c,
                       GW_Card_Reimbursement_Amount__c,
                       PSA_GW_Card__c,
                       PSA_Pre_Match_Amount__c
                  from pse__Expense__c
                 where id in :expenseIds ])
            {
                cardTransIdsToUnassign.add(e.PSA_Card_Transaction__c);
                expsToDisassociate.add(e);

            }

            // load card transactions
            if (cardTransIdsToUnassign != null && cardTransIdsToUnassign.size() > 0)
            {
                PSA_Card_Transaction__c[] unassignCardTrans = new PSA_Card_Transaction__c[]{};
                for (PSA_Card_Transaction__c pct : [
                    select id, PSA_Status__c
                    from PSA_Card_Transaction__c
                    where id in :cardTransIdsToUnassign])
                {
                    if (pct != null)
                    {
                        pct.PSA_Status__c = 'Unassigned';
                        unassignCardTrans.add(pct);
                    }
                }

                if (expsToDisassociate != null && expsToDisassociate.size() > 0)
                {

                    for (pse__Expense__c exp : expsToDisassociate)
                    {
                        // clear card transaction association
                        exp.PSA_Card_Transaction__c = null;

                        // reset amounts and indicators
                        exp.GW_Card_Reimbursement_Amount__c = null;
                        exp.PSA_GW_Card__c = false;
                        if (exp.PSA_Pre_Match_Amount__c != null) {
                            exp.pse__Amount__c = exp.PSA_Pre_Match_Amount__c;
                            exp.PSA_Pre_Match_Amount__c = null;
                        }
                    }

                    update expsToDisassociate;

                }

                if (unassignCardTrans != null && unassignCardTrans.size() > 0)
                {
                    update unassignCardTrans;
                }
            }
        }
    }

    // convenient method to make an error for returning to the ui!
    private static Map<String, Object> makeError(String errMsg, String errCode)
    {
        //gen.writeStringField('message', String.isNotEmpty(message) ? message : '') ;
        //gen.writeStringField('errorCode', String.isNotEmpty(errorCode) ? errorCode : 'ERR') ;
        return new Map<String, Object>{
            'errorCode' => errCode,
            'message' => errMsg
        };
    }


}