src/objects/PSA_Expense_Policy__c.object
<CustomObject>
    <description>Guidewire’s internal, customer-specific, and project specific expense policy information that will facilitate expense entry and approval review processes will be stored in the PSA Expense Policy custom object.</description>
    <fields>
        <fullName>PSA_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For project-specific policies. (Optional). This should be used for internal expense policies in addition to customer project policies.  If specified, no Account should be specified.</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>PSA Expense Policies</relationshipLabel>
        <relationshipName>PSA_Expense_Policies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PSA Expense Policy</label>
    <nameField>
        <label>PSA Expense Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSA Expense Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSA_Rate_Set__c.object
<CustomObject>
    <description>Custom - A PSA Rate Set, composed of multiple separate PSA Rates, determines which bill rates are applied to a project or an opportunity.</description>
    <fields>
        <fullName>PSA_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PSA Project</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipName>PSA_Bill_Rate_Sets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PSA Rate Set</label>
    <nameField>
        <label>Rate Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSA Rate Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/psaProjectSearchController.cls
public class psaProjectSearchController {
    public list <pse__Proj__c> proj {get;set;}  
    public string searchstring {get;set;}  
    
    public boolean isRateRendered {get;set;}
    public boolean isPolicyRendered {get;set;}
    public String accountId;
    public String currentProject;
    public psaProjectSearchController(ApexPages.StandardController controller) {
   
        accountId = apexpages.currentpage().getparameters().get('accountId');
        
        currentProject = apexpages.currentpage().getparameters().get('projectId');
        String typeOfSearch = apexpages.currentpage().getparameters().get('type');
        if(typeOfSearch == 'rate'){
            isPolicyRendered = false;
            search();
        }
        else if(typeOfSearch == 'policy'){
            isRateRendered = false;
            searchPolicy();
        }

   } 
   
   public void search(){  
   
     List<id> potentialProjects = new List<Id>();
     List<psa_Rate_Set__c> sets = [SELECT Id, psa_project__c from PSA_Rate_Set__c];
     for(PSA_Rate_Set__c next : sets){
         if(currentProject != '' && next.psa_Project__c != currentProject){
             potentialProjects.add(next.psa_Project__c);
         }
     
     }
     string searchquery='select name,id from pse__proj__c where id in :potentialProjects and pse__Account__c = :accountId';  
     proj = Database.query(searchquery);
     if(proj == null || proj.size() == 0){  
         isRateRendered = true;
     }
   }  
   
   public void searchPolicy(){  
   
     List<id> potentialProjects = new List<Id>();
     List<psa_Expense_Policy__c> sets = [SELECT Id, psa_project__c from PSA_Expense_Policy__c];
     for(PSA_Expense_Policy__c next : sets){
         if(currentProject != '' && next.psa_Project__c != currentProject){
             potentialProjects.add(next.psa_Project__c);
         }
     
     }
     string searchquery='select name,id from pse__proj__c where id in :potentialProjects and pse__Account__c = :accountId';  
     proj = Database.query(searchquery);  
     if(proj == null || proj.size() == 0){  
         isPolicyRendered = true;
     }
   }  
   
   public void clear(){  
       if(proj != null){
           proj.clear();
       }  
   }  
}