src/objects/Resource_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resource_Request__c</fullName>
        <label>Resource Request</label>
        <referenceTo>ResourceRequest__c</referenceTo>
        <relationshipLabel>Resource Assignments</relationshipLabel>
        <relationshipName>Resource_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Resource_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Resource Role</label>
        <referenceTo>Resource_Role__c</referenceTo>
        <relationshipLabel>Resource Assignments</relationshipLabel>
        <relationshipName>Resource_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Filled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Resource_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource Assignment</label>
    <nameField>
        <label>Resource Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Resource_Role__c.object
<CustomObject>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Resource_Request__c</fullName>
        <label>Resource Request</label>
        <referenceTo>ResourceRequest__c</referenceTo>
        <relationshipLabel>Resource Roles</relationshipLabel>
        <relationshipName>Resource_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>BillingCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Intelligence for InsuranceSuite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ClaimCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Data Managment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Portals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISO Templates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PolicyCenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Predictive Analytics for Claims</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Predictive Analytics for Profitability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Predictive Analytics Model Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Predictive Analytics Scoring Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reinsurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Required</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Potentially Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Filled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Resource Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Resource ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ResourceRequest__c.object
<CustomObject>
    <description>A request for resources to staff an event.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fully Staffed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revoked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Resource Request</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ResourceRequestAssignmentController.cls
public with sharing class ResourceRequestAssignmentController {

    public Resource_Assignment__c resourceAssignment { get; set;}
    public ResourceRequest__c resourceRequest { get; set;}


    public ResourceRequestAssignmentController(ApexPages.StandardController controller) {

        //let's set the resource request on the object here
        //let's see if it is already set...if not, let's pull it from the request

        String requestID = ApexPages.currentPage().getParameters().get('ResReqID');
        if(requestID != null)
        {  //it is a new role, so let's set it up accordingly
            resourceAssignment = new Resource_Assignment__c();
                
            resourceRequest = [SELECT Id from ResourceRequest__c
                                    WHERE Id = :requestID  LIMIT 1];
                
            resourceAssignment.Resource_Request__c = resourceRequest.Id ;
        }
        else
        { // it is an existing role, so just look it up from the ID
             resourceAssignment = [SELECT Resource_Role__r.Role__c, Note__c, Status__c, User__c, Resource_Request__c, Resource_Role__c FROM Resource_Assignment__c
                   WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
              
           resourceRequest = [SELECT Id from ResourceRequest__c
                                    WHERE Id = :resourceAssignment.Resource_Request__c LIMIT 1];
        }
    }
    
   public PageReference save() {
        upsert resourceAssignment ;
        //return to page for resource request
                
        PageReference reqPage = new ApexPages.StandardController(resourceRequest).view();
        reqPage.setRedirect(true);
        return reqPage ;
    }
    
    public Boolean getIsPresalesManager() {
      return (GWUserProfileHelper.isPresalesManager());
    }


}