src/objects/ResourceRequest__c.object
<CustomObject>
    <description>A request for resources to staff an event.</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Please provide details that are specific to the demo such as the goal of the meeting, description of the audience, line of business, states, etc.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Goals__c</fullName>
        <label>Event Goals</label>
        <length>1500</length>
        <type>Html</type>
    </fields>
    <label>Resource Request</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EditResourceRequestCon.cls
public with sharing class EditResourceRequestCon
{
    public ResourceRequest__c ResourceRequest {get; set;}
    
    public EditResourceRequestCon(ApexPages.StandardController controller)
    {
        ResourceRequest = (ResourceRequest__c)controller.getRecord();
        ResourceRequest.Event_Goals__c = Label.EVENT_GOALS_TEXT;
        ResourceRequest.Description__c = Label.ResourceRequest_Description_Text;
    }
    
    public PageReference saveMe()
    {
        insert ResourceRequest;
        PageReference page = new ApexPages.StandardController(ResourceRequest).view();
        return page;
    }
    

}