src/objects/Sales_Support_Request__c.object
<CustomObject>
    <description>Represents requests for support for things such as documents, strategy discussions, and other internal or non-staffing requests.</description>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <summarizedField>Support_Request_Preparation__c.Hours__c</summarizedField>
        <summaryForeignKey>Support_Request_Preparation__c.Sales_Support_Request__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Sales Support Request</label>
    <nameField>
        <displayFormat>SSR-{00000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Support Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Support_Request_Preparation__c.object
<CustomObject>
    <fields>
        <fullName>End__c</fullName>
        <label>End</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Support_Request__c</fullName>
        <label>Sales Support Request</label>
        <referenceTo>Sales_Support_Request__c</referenceTo>
        <relationshipLabel>Preparations</relationshipLabel>
        <relationshipName>Preparations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Who__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Support_Preparations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Preparation</label>
    <nameField>
        <label>Preparation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preparations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SupportRequestPreparationController.cls
public with sharing class SupportRequestPreparationController {

    public Support_Request_Preparation__c preparation {get;set;}
    public Support_Request_Preparation__c preparationOriginal {get;set;}
    public Sales_Support_Request__c salesSupportRequest {get;set;}


    public SupportRequestPreparationController(ApexPages.StandardController controller) {
        //let's see if it is already set...if not, let's pull it from the event

        String requestID= ApexPages.currentPage().getParameters().get('RequestID');
        if(requestID!= null)
        {//it is a new commitment, so let's set it up accordingly
            preparation = new Support_Request_Preparation__c();
                
            salesSupportRequest = [SELECT Id from Sales_Support_Request__c
                                        WHERE Id = : requestID LIMIT 1];
                    
            preparation.Sales_Support_Request__c = salesSupportRequest.Id ;
            //let's default it the current user
            preparation.Who__c = UserInfo.getUserId();
        
        }
        else
        { //it already exists, so look it up from the ID
              preparation = [SELECT Id, Who__c, Hours__c, Start__c, End__c, Note__c, Sales_Support_Request__c
                                     FROM Support_Request_Preparation__c
                                     WHERE Id=:ApexPages.currentPage().getParameters().get('id')];

            salesSupportRequest = [SELECT Id from Sales_Support_Request__c
                                        WHERE Id = : preparation.Sales_Support_Request__c LIMIT 1];
        }
        preparationOriginal = preparation.clone(); // Copy


    }
    
     public PageReference save() {
        upsert preparation;
    
        //return to page for the event
       PageReference reqPage = new ApexPages.StandardController(salesSupportRequest).view();
        reqPage.setRedirect(true);
        return reqPage ;
   }
    

}