src/objects/Sales_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Goals__c</fullName>
        <label>Event Goals</label>
        <length>1500</length>
        <type>Html</type>
    </fields>
    <label>Sales Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EditSalesEventCon.cls
public with sharing class EditSalesEventCon {
    public Sales_Event__c SalesEvent {get; set;}
    
    public EditSalesEventCon(ApexPages.StandardController controller)
    {
        SalesEvent = (Sales_Event__c)controller.getRecord();
        SalesEvent.Event_Goals__c = Label.EVENT_GOALS_TEXT;
    }
    
    public pageReference saveMe()
    {
        insert SalesEvent;
        PageReference page = new ApexPages.StandardController(SalesEvent).view();
        return page;
    }
}